"""Generate scratchpad/iter54_cmixpow/run_iter54.cmd from iter 45's champion runner.

Iter 54 makes the channel mixer's squared-ReLU exponent LEARNABLE (RWKV_CMIX_POW=1). Full WS +
decay: the exponent is a weight, so it acts from step 1 and cannot warm-start from the champion's
WS-final the way iter 52 does.

Generated by textual substitution so the env block and every existing guard are inherited verbatim.
The asserts check what a diff would not show -- and one of them exists because the first generated
version inherited iter 53's HEADER PROSE while carrying iter 54's lever, i.e. a runner that would
have executed correctly while describing the wrong experiment to whoever read it next.
"""
import io
import re

BS = chr(92)
SRC = "scratchpad/iter45_kddecay/run_iter45.cmd"
DST = "scratchpad/iter54_cmixpow/run_iter54.cmd"

s = io.open(SRC, encoding="utf-8", newline="").read().replace("\r\n", "\n")

# --- retarget: run dir, prefixes, tags ---
s = s.replace("scratchpad/iter45_kddecay", "scratchpad/iter54_cmixpow")
s = s.replace("scratchpad" + BS + "iter45_kddecay", "scratchpad" + BS + "iter54_cmixpow")
s = s.replace("i45_ws", "i54_ws").replace("i45_d", "i54_d")
s = s.replace("i45_decay.toml", "i54_decay.toml").replace("i45_eval.toml", "i54_eval.toml")
s = s.replace("RWKV-iter45_kddecay", "RWKV-iter54_cmixpow")
s = s.replace("RWKV-P-iter45_kddecay", "RWKV-P-iter54_cmixpow")
s = s.replace("iter45.log", "iter54.log")

# --- the lever: one env var, set beside the other Muon settings so it reads as one block ---
assert s.count("set RWKV_MUON_MOMENTUM=0.95\n") == 1
s = s.replace(
    "set RWKV_MUON_MOMENTUM=0.95\n",
    "set RWKV_MUON_MOMENTUM=0.95\n"
    "REM ---- THE LEVER: the channel mixer exponent becomes learnable, 13 scalars ----\n"
    "set RWKV_CMIX_POW=1\n",
)

# --- the guard that makes a silent no-op impossible ---
# NOT a log banner. A banner proves a value was PARSED, never that it was USED -- the lesson from
# the QAT env that was silently inert under RWKV_ARCH_MODULE while printing a truthful "[QAT-LOWRANK]
# set:" line. The param COUNT is consumed state: 558,225 can only happen if all 13 cmix_pow
# Parameters actually exist in the built model (the champion is 558,212).
GUARD = [
    "",
    "REM PHASE 0: the lever must reach the BUILT MODEL. A banner would only prove the env var was",
    "REM read; the param count is consumed state and can only be 558,225 if all 13 cmix_pow",
    "REM Parameters exist. The champion is 558,212.",
    ".venv" + BS + "Scripts" + BS + "python.exe scratchpad" + BS + "parity3" + BS
    + 'assert_param_count.py 558225 >> "%LOG%" 2>&1',
    "if not %ERRORLEVEL%==0 (",
    '  echo ITER54 WRONG_PARAM_COUNT %DATE% %TIME% >> "%LOG%"',
    '  echo DONE_EXIT_37 >> "%LOG%"',
    "  exit /b 37",
    ")",
]
anchor = 'echo === WS %TIME% === >> "%LOG%"'
assert s.count(anchor) == 1
s = s.replace(anchor, chr(10).join(GUARD) + chr(10) + chr(10) + anchor)

# --- header ---
HEADER = [
    "@echo off",
    "REM ===========================================================================================",
    "REM ITER 54: LEARNABLE EXPONENT IN THE CHANNEL MIXER (RWKV_CMIX_POW=1).",
    "REM Family: EXPRESSIVENESS -- a new family, opened by Andrew on 2026-08-17: 'No changes to",
    "REM architecture that improve expressiveness? Stuff like activation functions with learnable",
    "REM params.'",
    "REM",
    "REM WHY THIS ONE. rwkv_model.py:633 is W_v(square(relu(k))) -- RWKV-7's squared-ReLU FFN, the",
    "REM exponent a hardcoded 2. Making it learnable is 13 params, one per block, and it is the only",
    "REM candidate of its class that survived the REDUNDANCY TEST: relu(c*k) to the p equals c to the p times relu(k) to the p, so",
    "REM rescaling the input only rescales the output and the CURVATURE is set by p alone. No",
    "REM adjacent free linear can reproduce it. That same test killed learnable slopes on tanh and",
    "REM sigmoid (all sandwiched between free linears, hence pure reparameterizations) and cross-head",
    "REM mixing (W_o already mixes the full H*K dimension).",
    "REM",
    "REM ** EXPRESSIVENESS IS NOT CAPACITY, which is why the 0/3 capacity record does not cover this.",
    "REM Those three rejects added MORE OF THE SAME functional form (extra channel mixers,",
    "REM num_curves 64 to 128, a wider mixer). None tested a RICHER form at fixed parameter count.",
    "REM What p controls is the FFN's degree of homogeneity: relu(k) to the p is a pure power law, so p is a",
    "REM gain exponent -- higher is sharper and more selective, lower is smoother.",
    "REM",
    "REM THREE THINGS A NAIVE VERSION GETS WRONG, all handled in rwkv_model.py:",
    "REM   1. the p-gradient of x to the p is x to the p times log(x), which diverges as x nears 0,",
    "REM      and relu produces exact zeros on about half the units. The +1e-6 floor keeps it",
    "REM      finite; without it the run NaNs inside a hundred steps and looks like iter 51.",
    "REM   2. cmix_pow_on must be a TorchScript CONSTANT. TorchScript compiles BOTH branches of a",
    "REM      runtime if, so with the flag off it tried to resolve a Parameter that deliberately",
    "REM      does not exist, and the whole model failed to script.",
    "REM   3. rwkv_rnn_model.py carried its OWN hardcoded square(relu(k)). Changing only the training",
    "REM      path would have been a silent three-way parity break: train and eval on relu(k) to the p, CPU",
    "REM      inference on relu(k) squared, each self-consistent alone. Mirrored, plus a parity case.",
    "REM",
    "REM GATE: PLAIN basis vs iter 45 == 0.297697 ahead / 0.265375 imm on the VAL half, both-modes",
    "REM rule. Params 558,225 (558,212 plus 13) -- phase 0 asserts exactly that, because the param",
    "REM count is CONSUMED state whereas a log banner would only prove the env var was parsed.",
    "REM DEPLOY DEBT: forward-pass change, so it needs the Rust channel mixer plus a fresh parity",
    "REM trace before anything ships. First such candidate in a while.",
    "REM",
    "REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not a",
    "REM safe undo, because line endings shift the byte offset cmd.exe resumes from).",
    "REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.",
    "REM ===========================================================================================",
]
body = s[s.index("setlocal"):]
out = "\n".join(HEADER) + "\n" + body

low = out.lower()
assert "iter45" not in low and "i45_" not in low, "iter 45 reference leaked"
for _stale in ("iter 53", "iter53", "i53_", "muon_include_lora", "lora projections"):
    assert _stale not in low, "stale iter-53 text leaked: " + _stale
assert out.count("set RWKV_CMIX_POW=1") == 1
assert "assert_param_count.py 558225" in out, "param-count guard missing"
assert "set RWKV_AUGMENT_SEED=4321" in out and "architecture_d80_lora4_cnd.py" in out
assert out.count("set RWKV_KD_ALPHA=0.9") == 1 and out.count("set RWKV_KD_ALPHA=0.5") == 1, (
    "the champion's KD schedule (0.9 in WS, 0.5 in decay) must be preserved verbatim"
)
for ln in out.split("\n"):
    if ln.strip().upper().startswith("REM"):
        bad = [c for c in "<>&|^" if c in ln]
        assert not bad, "redirection char " + str(bad) + " in REM line: " + ln
io.open(DST, "w", encoding="ascii", newline="\r\n").write(out)
print("wrote", DST, len(out), "bytes,", out.count(chr(10)), "lines")
