"""Generate run_iter54_resume.cmd -- resume iter 54's WS from step 8000 after the power outage.

THE OUTAGE (2026-08-18): the box lost power mid-WS. iter 54 had reached step 8110 of 10,935 with a
clean checkpoint pair at step 8000 (verified loadable: 434 keys, 558,225 params), and its ws log has
ZERO NUL bytes, so nothing is corrupt. Resuming costs ~110 lost steps against ~2.4 h of salvaged
training.

MECHANISM (CLAUDE.md "MID-EPOCH RESUME"): `make_resume.py` wrote `i54_ws_resume.toml`
(LOAD_MODEL=true, LOAD_MODEL_NAME=i54_ws_8000, STEP_OFFSET=8001) and copied the optimizer file to
the loader's expected name. The resume RUN must additionally set **RWKV_RESUME_SKIP_GROUPS=1**, or
train_rwkv re-trains the early data and drops the tail.

⚠ DOCUMENTED CAVEAT, carried into the verdict: the resumed tail's DROPOUT DRAWS differ from an
uninterrupted run (weights and optimizer state are exact). Statistically equivalent, not
bit-identical -- so iter 54's number is a fair measurement but the run is not bit-reproducible.

WHAT CHANGES vs run_iter54.cmd, and nothing else:
  1. the WS phase points at i54_ws_resume.toml instead of i54_ws.toml
  2. RWKV_RESUME_SKIP_GROUPS=1 is set for the WS phase and CLEARED before decay
  3. a fresh STAMP, so the resumed WS writes a NEW log rather than clobbering the 8,110 steps
     already on disk (the trace is reconstructed from BOTH logs at verdict time)
Decay, eval and every guard are untouched.

Output guards mirror mk55/mk57 (the mk53/mk54 deletion incident) PLUS the endlocal check that iter
53's stranded chain earned.
"""
import io
import re

SRC = "scratchpad/iter54_cmixpow/run_iter54.cmd"
DST = "scratchpad/iter54_cmixpow/run_iter54_resume.cmd"

s = io.open(SRC, encoding="ascii", newline="").read()

# --- 1 + 2: the WS phase resumes ---
OLD_WS = ('echo === WS %TIME% === >> "%LOG%"\r\n'
          '.venv\\Scripts\\python.exe -u -m rwkv.train_rwkv --config '
          'scratchpad/iter54_cmixpow/i54_ws.toml > "%DIR%\\ws_%STAMP%.log" 2>&1\r\n')
NEW_WS = ('REM RESUMED from step 8000 after the 2026-08-18 power outage. SKIP_GROUPS is mandatory:\r\n'
          'REM without it train_rwkv re-trains the already-seen prefix and silently drops the tail.\r\n'
          'set RWKV_RESUME_SKIP_GROUPS=1\r\n'
          'echo === WS RESUME from step 8000 %TIME% === >> "%LOG%"\r\n'
          '.venv\\Scripts\\python.exe -u -m rwkv.train_rwkv --config '
          'scratchpad/iter54_cmixpow/i54_ws_resume.toml > "%DIR%\\ws_%STAMP%.log" 2>&1\r\n')
assert OLD_WS in s, "WS phase not found verbatim"
s = s.replace(OLD_WS, NEW_WS, 1)

# --- ARTIFACT GUARD: exit code 0 does NOT mean the WS ran ---
# The first resume attempt died instantly on a missing LOAD_MODEL_FOLDER, train_rwkv SWALLOWED the
# AttributeError and exited 0, and the runner logged "WS OK" after 8 seconds then proceeded to
# decay from a half-trained checkpoint. CLAUDE.md already warns "train_rwkv can swallow fatal
# errors to exit 0"; the only reliable test is whether the ARTIFACT exists.
OLD_DEC0 = 'echo === DECAY SETUP %TIME% === >> "%LOG%"\r\n'
GUARD = ('REM Exit code 0 is not evidence the WS ran -- train_rwkv can swallow a fatal error and\r\n'
         'REM still exit 0. The final checkpoint is the only reliable witness.\r\n'
         'if not exist "%DIR%\\i54_ws_10935.pth" (\r\n'
         '  echo WS produced no i54_ws_10935.pth -- refusing to decay a half-trained model %TIME% >> "%LOG%"\r\n'
         '  echo DONE_EXIT_WSNOFINAL %DATE% %TIME% >> "%LOG%"\r\n'
         '  exit /b 22\r\n'
         ')\r\n')
assert OLD_DEC0 in s
s = s.replace(OLD_DEC0, GUARD + OLD_DEC0, 1)

# clear the resume flag before the decay phase, like every other training-only var
OLD_DEC = 'echo === DECAY SETUP %TIME% === >> "%LOG%"\r\n'
assert OLD_DEC in s, "decay-setup marker not found"
s = s.replace(OLD_DEC, 'set RWKV_RESUME_SKIP_GROUPS=\r\n' + OLD_DEC, 1)

# --- 3: fresh STAMP so the resumed WS does not clobber the pre-outage log ---
s = re.sub(r'^set STAMP=.*$', 'set STAMP=resume8000', s, count=1, flags=re.M)

HEADER = [
    "@echo off",
    "REM =========================================================================================",
    "REM ITER 54 RESUME -- WS continues from step 8000 after the 2026-08-18 power outage.",
    "REM Generated by mk54_resume.py from run_iter54.cmd; see that file's docstring for the",
    "REM mechanism and the dropout-draw caveat. Reached step 8110/10935 before the outage; the",
    "REM step-8000 checkpoint pair was verified loadable and the old ws log has zero NUL bytes.",
    "REM",
    "REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not",
    "REM a safe undo, because line endings shift the byte offset cmd.exe resumes from).",
    "REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.",
    "REM =========================================================================================",
]
body = s[s.index("setlocal"):]
out = "\n".join(HEADER) + "\n" + body.replace("\r\n", "\n")
out = out.replace("\n", "\r\n")

# ---------------- OUTPUT GUARDS ----------------
lines = out.split("\r\n")
assert re.search(r"^cd /d ", out, re.M), "cd /d was deleted by the slice"
setpos, usepos = {}, {}
for n, ln in enumerate(lines):
    m = re.match(r"\s*set\s+([A-Za-z_][A-Za-z0-9_]*)=", ln)
    if m and m.group(1).upper() not in setpos:
        setpos[m.group(1).upper()] = n
    for v in re.findall(r"%([A-Za-z_][A-Za-z0-9_]*)%", ln):
        usepos.setdefault(v.upper(), n)
for v, un in usepos.items():
    if v in {"DATE", "TIME", "ERRORLEVEL", "RANDOM", "CD"}:
        continue
    assert v in setpos, f"%{v}% used at line {un + 1} but never set"
    assert setpos[v] < un, f"%{v}% used at line {un + 1} before being set at line {setpos[v] + 1}"

# the endlocal lesson from iter 53's stranded chain
_el = [n for n, ln in enumerate(lines) if ln.strip().lower() == "endlocal"]
_de = [n for n, ln in enumerate(lines) if ln.strip().startswith("echo DONE_EXIT_0")]
assert _el and _de and min(_el) > max(_de), "endlocal must come AFTER the DONE_EXIT_0 echo"

assert out.count("i54_ws_resume.toml") == 1, "WS must use the resume toml exactly once"
assert "i54_ws.toml" not in out, "the original WS toml must not survive anywhere"
assert out.count("set RWKV_RESUME_SKIP_GROUPS=1") == 1
assert out.count("set RWKV_RESUME_SKIP_GROUPS=") == 2, "the flag must also be CLEARED before decay"
assert out.count("DONE_EXIT_0") == 1
assert "STAMP=resume8000" in out, "fresh STAMP missing -- the pre-outage ws log would be clobbered"
for ln in lines:
    if ln.strip().upper().startswith("REM"):
        bad = [c for c in "<>&|^" if c in ln]
        assert not bad, "redirection char " + str(bad) + " in REM line: " + ln

io.open(DST, "w", encoding="ascii", newline="").write(out)
print("wrote", DST, len(out), "bytes")
