@echo off
REM =========================================================================================
REM ITER 54 RESUME -- WS continues from step 8000 after the 2026-08-18 power outage.
REM Generated by mk54_resume.py from run_iter54.cmd; see that file's docstring for the
REM mechanism and the dropout-draw caveat. Reached step 8110/10935 before the outage; the
REM step-8000 checkpoint pair was verified loadable and the old ws log has zero NUL bytes.
REM
REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not
REM a safe undo, because line endings shift the byte offset cmd.exe resumes from).
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter54_cmixpow
set LOG=%DIR%\iter54.log
set STAMP=resume8000
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935
REM BUDGET: 0 = full budget
set MAXSTEPS=0
echo ===== ITER 54 (learnable channel-mixer exponent) START %DATE% %TIME% ===== >> "%LOG%"
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
REM ---- THE LEVER: the channel mixer exponent becomes learnable, 13 scalars ----
set RWKV_CMIX_POW=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_GRAD_STATS=%DIR%\grad_stats.json
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.9
if not "%MAXSTEPS%"=="0" set RWKV_MAX_STEPS=%MAXSTEPS%
if not "%MAXSTEPS%"=="0" set RWKV_BENCH_WARMUP=100000


REM PHASE 0: the lever must reach the BUILT MODEL. A banner would only prove the env var was
REM read; the param count is consumed state and can only be 558,225 if all 13 cmix_pow
REM Parameters exist. The champion is 558,212.
.venv\Scripts\python.exe scratchpad\parity3\assert_param_count.py 558225 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER54 WRONG_PARAM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_37 >> "%LOG%"
  exit /b 37
)

REM RESUMED from step 8000 after the 2026-08-18 power outage. SKIP_GROUPS is mandatory:
REM without it train_rwkv re-trains the already-seen prefix and silently drops the tail.
set RWKV_RESUME_SKIP_GROUPS=1
echo === WS RESUME from step 8000 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/iter54_cmixpow/i54_ws_resume.toml > "%DIR%\ws_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WSFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 21
)
findstr /C:"[interleave] round-robin layer schedule ON" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOILV %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
findstr /C:"placement = front-loaded" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGPLACEMENT %DATE% %TIME% >> "%LOG%"
  exit /b 33
)
echo WS OK %TIME% >> "%LOG%"

REM ---- THE LEVER: KD is NOT cleared. Only the alpha changes for the decay phase. ----
set RWKV_KD_ALPHA=0.5
set RWKV_GRAD_STATS=
set RWKV_MAX_STEPS=

REM Exit code 0 is not evidence the WS ran -- train_rwkv can swallow a fatal error and
REM still exit 0. The final checkpoint is the only reliable witness.
if not exist "%DIR%\i54_ws_10935.pth" (
  echo WS produced no i54_ws_10935.pth -- refusing to decay a half-trained model %TIME% >> "%LOG%"
  echo DONE_EXIT_WSNOFINAL %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
set RWKV_RESUME_SKIP_GROUPS=
echo === DECAY SETUP %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/iter54_cmixpow i54_ws i54_d scratchpad/iter54_cmixpow/i54_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/iter54_cmixpow/i54_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
REM THE experiment's own guard: KD must actually have been ON during decay. Without this the run
REM silently reduces to the champion and would be recorded as a null.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOKD_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 35
)
findstr /C:"alpha FIXED at 0.5" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGALPHA_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 36
)
echo DECAY OK (KD ON, alpha 0.5) %TIME% >> "%LOG%"

echo === EVAL TOML rect %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/iter54_cmixpow i54_d scratchpad/iter54_cmixpow/i54_eval.toml RWKV-iter54_cmixpow RWKV-P-iter54_cmixpow 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
set RWKV_MUON_BATCHED=
set RWKV_NO_JIT=
set RWKV_QAT_COMPILE=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_EVAL_PAVA=1
echo === EVAL 5001-7500 RECTIFIED attempt 1 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/iter54_cmixpow/i54_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo EVAL rect attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/iter54_cmixpow/i54_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo EVAL rect OK %TIME% >> "%LOG%"
REM The terminal marker must be written BEFORE endlocal. endlocal restores the
REM pre-setlocal environment, so LOG expands to EMPTY after it and the append
REM target becomes an empty string -- nothing is written and every downstream
REM waiter is stranded forever. Cost iter 53 a 45-minute idle GPU on 2026-08-18
REM after a run that had already finished cleanly with exit 0.
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal
exit /b 0
