@echo off
REM ===========================================================================================
REM ITER 54: LEARNABLE EXPONENT IN THE CHANNEL MIXER (RWKV_CMIX_POW=1).
REM Family: EXPRESSIVENESS -- a new family, opened by Andrew on 2026-08-17: 'No changes to
REM architecture that improve expressiveness? Stuff like activation functions with learnable
REM params.'
REM
REM WHY THIS ONE. rwkv_model.py:633 is W_v(square(relu(k))) -- RWKV-7's squared-ReLU FFN, the
REM exponent a hardcoded 2. Making it learnable is 13 params, one per block, and it is the only
REM candidate of its class that survived the REDUNDANCY TEST: relu(c*k) to the p equals c to the p times relu(k) to the p, so
REM rescaling the input only rescales the output and the CURVATURE is set by p alone. No
REM adjacent free linear can reproduce it. That same test killed learnable slopes on tanh and
REM sigmoid (all sandwiched between free linears, hence pure reparameterizations) and cross-head
REM mixing (W_o already mixes the full H*K dimension).
REM
REM ** EXPRESSIVENESS IS NOT CAPACITY, which is why the 0/3 capacity record does not cover this.
REM Those three rejects added MORE OF THE SAME functional form (extra channel mixers,
REM num_curves 64 to 128, a wider mixer). None tested a RICHER form at fixed parameter count.
REM What p controls is the FFN's degree of homogeneity: relu(k) to the p is a pure power law, so p is a
REM gain exponent -- higher is sharper and more selective, lower is smoother.
REM
REM THREE THINGS A NAIVE VERSION GETS WRONG, all handled in rwkv_model.py:
REM   1. the p-gradient of x to the p is x to the p times log(x), which diverges as x nears 0,
REM      and relu produces exact zeros on about half the units. The +1e-6 floor keeps it
REM      finite; without it the run NaNs inside a hundred steps and looks like iter 51.
REM   2. cmix_pow_on must be a TorchScript CONSTANT. TorchScript compiles BOTH branches of a
REM      runtime if, so with the flag off it tried to resolve a Parameter that deliberately
REM      does not exist, and the whole model failed to script.
REM   3. rwkv_rnn_model.py carried its OWN hardcoded square(relu(k)). Changing only the training
REM      path would have been a silent three-way parity break: train and eval on relu(k) to the p, CPU
REM      inference on relu(k) squared, each self-consistent alone. Mirrored, plus a parity case.
REM
REM GATE: PLAIN basis vs iter 45 == 0.297697 ahead / 0.265375 imm on the VAL half, both-modes
REM rule. Params 558,225 (558,212 plus 13) -- phase 0 asserts exactly that, because the param
REM count is CONSUMED state whereas a log banner would only prove the env var was parsed.
REM DEPLOY DEBT: forward-pass change, so it needs the Rust channel mixer plus a fresh parity
REM trace before anything ships. First such candidate in a while.
REM
REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not a
REM safe undo, because line endings shift the byte offset cmd.exe resumes from).
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
REM ---- THE LEVER: the channel mixer exponent becomes learnable, 13 scalars ----
set RWKV_CMIX_POW=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_GRAD_STATS=%DIR%\grad_stats.json
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.9
if not "%MAXSTEPS%"=="0" set RWKV_MAX_STEPS=%MAXSTEPS%
if not "%MAXSTEPS%"=="0" set RWKV_BENCH_WARMUP=100000


REM PHASE 0: the lever must reach the BUILT MODEL. A banner would only prove the env var was
REM read; the param count is consumed state and can only be 558,225 if all 13 cmix_pow
REM Parameters exist. The champion is 558,212.
.venv\Scripts\python.exe scratchpad\parity3\assert_param_count.py 558225 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER54 WRONG_PARAM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_37 >> "%LOG%"
  exit /b 37
)

echo === WS %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/iter54_cmixpow/i54_ws.toml > "%DIR%\ws_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WSFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 21
)
findstr /C:"[interleave] round-robin layer schedule ON" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOILV %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
findstr /C:"placement = front-loaded" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGPLACEMENT %DATE% %TIME% >> "%LOG%"
  exit /b 33
)
echo WS OK %TIME% >> "%LOG%"

REM ---- THE LEVER: KD is NOT cleared. Only the alpha changes for the decay phase. ----
set RWKV_KD_ALPHA=0.5
set RWKV_GRAD_STATS=
set RWKV_MAX_STEPS=

echo === DECAY SETUP %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/iter54_cmixpow i54_ws i54_d scratchpad/iter54_cmixpow/i54_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/iter54_cmixpow/i54_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
REM THE experiment's own guard: KD must actually have been ON during decay. Without this the run
REM silently reduces to the champion and would be recorded as a null.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOKD_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 35
)
findstr /C:"alpha FIXED at 0.5" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGALPHA_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 36
)
echo DECAY OK (KD ON, alpha 0.5) %TIME% >> "%LOG%"

echo === EVAL TOML rect %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/iter54_cmixpow i54_d scratchpad/iter54_cmixpow/i54_eval.toml RWKV-iter54_cmixpow RWKV-P-iter54_cmixpow 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
set RWKV_MUON_BATCHED=
set RWKV_NO_JIT=
set RWKV_QAT_COMPILE=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_EVAL_PAVA=1
echo === EVAL 5001-7500 RECTIFIED attempt 1 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/iter54_cmixpow/i54_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo EVAL rect attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/iter54_cmixpow/i54_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo EVAL rect OK %TIME% >> "%LOG%"
endlocal

echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
exit /b 0
