@echo off
REM w10qatkd -- ARM 2 + DISTILLATION FROM THE FULL-PRECISION TWIN. Generated by
REM scratchpad/w10qatkddry/mk_w10qatkd.py from run_w10qat.cmd (the decay) and run_w10qat_eval.cmd
REM (the eval with the LEARNED catalogs). Control = arm 2 exactly; the ONLY change is
REM RWKV_QAT_KD=1.0 with RWKV_QAT_KD_TEACHER = arm 1's decayed final. Andrew 2026-09-10: "Yep, do KD".
REM The live-teacher target was fixed and proven first: scratchpad/qatkd/smoke_qatkd.py.
REM PREREG: scratchpad/w10qatkddry/PREREG.md. Budget: ~27 h decay (a teacher forward per step on top
REM of arm 2's ~0.24 steps/s) + ~10.5 h probe and quant-aware eval.
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\w10qatkddry
set SRC=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\ws10
set LOG=%DIR%\w10qatkddry.log
set STAMP=%RANDOM%%RANDOM%
set DECAYLOG=%DIR%\decay_%STAMP%.log
set TAG=w10qatkddry
set STEPS=546
set WSSTEPS=109350

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
REM The decay saves a checkpoint only on a validate step, and write_decay_setup hardcoded
REM 100000 -- so a 21,870-step decay checkpointed at step 50 and at the END and nowhere else.
REM A PC restart already killed one decay at 10,681/10,935. 2000 gives ~11 resume points for
REM ~4 percent of the phase, and it is trajectory-FREE: validation runs under model.eval()
REM inside no_grad and draws no main-process RNG (proven with a non-vacuity control by
REM scratchpad/ws10/rng_neutrality.py). Every endgame branch sets the SAME value, so they
REM stay mutually comparable.
set RWKV_DECAY_VALIDATE_EVERY=2000
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_MUON_INCLUDE_LORA=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1

REM ---- what distinguishes this arm: the -id layout AND the real-time cycles ----
set RWKV_ID_FEATURES=1
set RWKV_REAL_CYCLES=1
set RWKV_ZERO_FEATURES=
REM db overrides consumed by write_decay_setup.py / write_eval_toml.py, which used to
REM hardcode the 92-dim paths -- the trap the idfeat diagnostic caught.
set RWKV_VAL_DB=F:/rwkv_lmdb/test_db_5k_id5
set RWKV_EVAL_DB=F:/rwkv_lmdb/test_db_5k_id5
set RWKV_LABEL_FILTER_DB=F:/rwkv_lmdb/label_filter_db_id_e2s
REM KD explicitly CLEARED, never merely unset, so an inherited value cannot turn the
REM control into a treatment -- the false-green shape that bit the rgate smoke.
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=



REM ---- QAT: the ONLY difference from arm 1. Decay-only and warm-started, which is how QAT is
REM deployed here and what iter 40 (+0.0118 from scratch) says it must be.
set RWKV_QAT_LOWRANK_SCOPE=card:1:int4,note:1:int4
set RWKV_QAT_PQ=reference/pq_cb_wkv_ws10_b10.txt
set RWKV_QAT_SHIFT_PQ=reference/pq_cb_shift_ws10_m2b12.txt
set RWKV_QAT_SHIFT_SCOPE=card:int3,note:int3
set RWKV_QAT_NORM_BITS=1
set RWKV_QAT_FUSED=1
set RWKV_QAT_PQ_LEARN=1
set RWKV_QAT_SHIFT_PQ_LEARN=1

REM ---- THE LEVER: distil from the full-precision twin during the QAT decay ----
set RWKV_QAT_KD=1.0
set RWKV_QAT_KD_TEACHER=scratchpad/ws10/w10p_d_21870.pth

if not exist "%DIR%" mkdir "%DIR%"
echo ===== w10qatkddry START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE 0a: a C++ COMPILER MUST BE ON PATH, and this arm is the first run that needs one.
REM The 04:00 launch was HOLLOW: 255 of 288 batches raised
REM   torch._inductor.exc.InductorError: RuntimeError: Compiler: cl is not found.
REM and train_rwkv's per-batch except swallowed each one ("Exception caught ... Skipping batch"),
REM so it stepped at 3.7 steps/min on ~11% of the data while looking alive.
REM WHY IT IS NEW: RWKV_QAT_COMPILE=1 has been in the standard env since 2026-07-30 and every
REM plain run (ws10, arm 1) compiles to pure Triton, which needs no host compiler. The QAT graph
REM graph-breaks differently and asks inductor for a C++ kernel. No earlier QAT run hit this
REM because scratchpad/qat_tax/run_arm.cmd never set RWKV_QAT_COMPILE at all -- so QAT + compile
REM is a combination that has never run here.
REM The fix must NOT be RWKV_QAT_COMPILE=0: that would make arm 2 differ from arm 1 in two ways
REM and this A/B exists to isolate exactly one.
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
where cl.exe >nul 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% NO_CL_ON_PATH %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_50 %DATE% %TIME% >> "%LOG%"
  exit /b 50
)
echo %TAG% CL_OK %TIME% >> "%LOG%"


REM ---- PHASE 0: the catalogs must EXIST and be the ws10-fitted ones, and the QAT env must reach
REM the FINAL config. A banner proves a value was computed, never that it was used: on 2026-08-12
REM the whole QAT env was parsed and then discarded by RWKV_ARCH_MODULE for an entire track-2
REM phase, symptomless except for a quantization cost of zero.
if not exist "reference\pq_cb_wkv_ws10_b10.txt" (
  echo %TAG% MISSING ws10 WKV catalog -- fit it from the ws10 WS-final first %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_51 %DATE% %TIME% >> "%LOG%"
  exit /b 51
)
if not exist "reference\pq_cb_shift_ws10_m2b12.txt" (
  echo %TAG% MISSING ws10 shift catalog %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_52 %DATE% %TIME% >> "%LOG%"
  exit /b 52
)
.venv\Scripts\python.exe scratchpad/qat_tax/assert_qat_live.py >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% QAT env is INERT in the final config %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_53 %DATE% %TIME% >> "%LOG%"
  exit /b 53
)

REM ---- PHASE 0k: the teacher must EXIST before a ~27 h decay depends on it ----
if not exist "scratchpad\ws10\w10p_d_21870.pth" (
  echo %TAG% NO_TEACHER_CHECKPOINT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_80 %DATE% %TIME% >> "%LOG%"
  exit /b 80
)

REM ---- PHASE B: the 2-EPOCH decay from the shared 10-epoch WS checkpoint ----
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/ws10 w10_ws w10qkdry_d %DIR%\decay.toml F:/rwkv_lmdb/train_db_5k_h1_id5 1 5000 0.05 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% DSETUP_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_22 %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
findstr /C:"w10_ws_%WSSTEPS%" "%DIR%\dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% WRONGCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_32 %DATE% %TIME% >> "%LOG%"
  exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% DECAY_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_23 %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
REM The lever must have REACHED the loop: the trainer prints this line only when it built the
REM teacher from THIS path. Without it the run is arm 2 again under another name.
findstr /C:"[KD] teacher = scratchpad/ws10/w10p_d_21870.pth" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% KD_NOT_ENGAGED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_81 %DATE% %TIME% >> "%LOG%"
  exit /b 81
)
REM The DUMP-based KD (RWKV_KD_MIX) must still be absent -- only the live teacher is the lever.
REM KD must be ABSENT here -- the opposite of every recent runner's guard.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if %ERRORLEVEL%==0 (
  echo %TAG% KD_LEAKED_IN %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_43 %DATE% %TIME% >> "%LOG%"
  exit /b 43
)
if not exist "C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\ws10\w10qkdry_d_%STEPS%.pth" (
  echo %TAG% DECAY_SHORT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_28 %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
echo %TAG% DECAY_OK %TIME% >> "%LOG%"

REM ---- PHASE 0: the decay artifacts, tested WHERE A DECAY-ONLY RUN WRITES THEM (the SOURCE folder) ----
if not exist "%SRC%\w10qkdry_d_%STEPS%.pth" (
  echo %TAG% NO_DECAY_CKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_60 %DATE% %TIME% >> "%LOG%"
  exit /b 60
)
if not exist "%SRC%\w10qkdry_d_wkvcb_%STEPS%.txt" (
  echo %TAG% NO_LEARNED_WKV_CATALOG %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_61 %DATE% %TIME% >> "%LOG%"
  exit /b 61
)
if not exist "%SRC%\w10qkdry_d_shiftcb_%STEPS%.txt" (
  echo %TAG% NO_LEARNED_SHIFT_CATALOG %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_62 %DATE% %TIME% >> "%LOG%"
  exit /b 62
)

REM ---- PHASE 0b: the decay that produced them. The stopped runner would have checked KD here. ----
findstr /C:"[kd-mix] KD ON" "%DECAYLOG%" >nul
if not errorlevel 1 (
  echo %TAG% KD_WAS_ON_IN_THE_DECAY %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_63 %DATE% %TIME% >> "%LOG%"
  exit /b 63
)
findstr /C:"[wkv-pq] codebook LEARNABLE" "%DECAYLOG%" >nul
if errorlevel 1 (
  echo %TAG% WKV_CATALOG_WAS_NOT_LEARNABLE %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_64 %DATE% %TIME% >> "%LOG%"
  exit /b 64
)
findstr /C:"[shift-pq] codebook LEARNABLE" "%DECAYLOG%" >nul
if errorlevel 1 (
  echo %TAG% SHIFT_CATALOG_WAS_NOT_LEARNABLE %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_65 %DATE% %TIME% >> "%LOG%"
  exit /b 65
)
REM A HOLLOW decay swallows every step's exception and still exits 0 -- the first arm-2 launch.
findstr /C:"Traceback" /C:"InductorError" "%DECAYLOG%" >nul
if not errorlevel 1 (
  echo %TAG% DECAY_LOG_HAS_A_TRACEBACK %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_66 %DATE% %TIME% >> "%LOG%"
  exit /b 66
)
echo %TAG% DECAY_VERIFIED %TIME% >> "%LOG%"

REM ---- EVAL ENV: the LEARNED catalogs, learning OFF -- run_cblearn.cmd's recipe, verbatim ----
set RWKV_QAT_PQ=scratchpad/ws10/w10qkdry_d_wkvcb_%STEPS%.txt
set RWKV_QAT_SHIFT_PQ=scratchpad/ws10/w10qkdry_d_shiftcb_%STEPS%.txt
set RWKV_QAT_PQ_LEARN=
set RWKV_QAT_SHIFT_PQ_LEARN=
set RWKV_QAT_KD=
set RWKV_QAT_KD_TEACHER=
set RWKV_EVAL_PAVA=1

REM Quantization must be ON in the CONSUMED config (the 2026-08-12 inert-env class). Seconds.
.venv\Scripts\python.exe scratchpad/qat_tax/assert_qat_live.py >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% EVAL_WOULD_NOT_BE_QUANT_AWARE %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_67 %DATE% %TIME% >> "%LOG%"
  exit /b 67
)

REM ---- PHASE P: 10-user PROBE, minutes. It must LOAD the learned catalogs, with learning off, and
REM give a sane cost against arm 1 -- all proven before ~10 h of GPU is spent on the full eval. ----
if exist "result\RWKV-%TAG%p.jsonl" del /q "result\RWKV-%TAG%p.jsonl"
if exist "result\RWKV-P-%TAG%p.jsonl" del /q "result\RWKV-P-%TAG%p.jsonl"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/w10qatkddry w10qkdry_d %DIR%\probe.toml RWKV-%TAG%p RWKV-P-%TAG%p 5001 5020 > "%DIR%\ptoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% PROBE_TOML_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_68 %DATE% %TIME% >> "%LOG%"
  exit /b 68
)
findstr /C:"w10qkdry_d_%STEPS%.pth" "%DIR%\probe.toml" >nul
if errorlevel 1 (
  echo %TAG% PROBE_TOML_WRONG_CHECKPOINT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_69 %DATE% %TIME% >> "%LOG%"
  exit /b 69
)
findstr /C:"F:/rwkv_lmdb/test_db_5k_id5" "%DIR%\probe.toml" >nul
if errorlevel 1 (
  echo %TAG% PROBE_DB_MISMATCH %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_70 %DATE% %TIME% >> "%LOG%"
  exit /b 70
)
.venv\Scripts\python.exe -u -m rwkv.get_result --config %DIR%\probe.toml > "%DIR%\probe_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% PROBE_EVAL_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_71 %DATE% %TIME% >> "%LOG%"
  exit /b 71
)
findstr /C:"[QAT-PQ] uploaded rank-1 codebook scratchpad/ws10/w10qkdry_d_wkvcb_%STEPS%.txt" "%DIR%\probe_%STAMP%.log" >nul
if errorlevel 1 (
  echo %TAG% PROBE_DID_NOT_LOAD_THE_LEARNED_WKV_CATALOG %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_72 %DATE% %TIME% >> "%LOG%"
  exit /b 72
)
findstr /C:"[QAT-SHIFT-PQ] loaded scratchpad/ws10/w10qkdry_d_shiftcb_%STEPS%.txt" "%DIR%\probe_%STAMP%.log" >nul
if errorlevel 1 (
  echo %TAG% PROBE_DID_NOT_LOAD_THE_LEARNED_SHIFT_CATALOG %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_73 %DATE% %TIME% >> "%LOG%"
  exit /b 73
)
findstr /C:"learnable=True" "%DIR%\probe_%STAMP%.log" >nul
if not errorlevel 1 (
  echo %TAG% PROBE_RAN_WITH_LEARNING_ON %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_74 %DATE% %TIME% >> "%LOG%"
  exit /b 74
)
.venv\Scripts\python.exe scratchpad/qat_tax/sanity_probe_gate.py %TAG%p --base w10plain >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% PROBE_OUT_OF_BAND %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_75 %DATE% %TIME% >> "%LOG%"
  exit /b 75
)
echo %TAG% PROBE_OK %TIME% >> "%LOG%"

REM ---- PHASE C: rectified VAL-half eval, users 5001-7500, quant-aware with the learned catalogs ----
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/w10qatkddry w10qkdry_d %DIR%\eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 5020 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% ETOML_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_76 %DATE% %TIME% >> "%LOG%"
  exit /b 76
)
findstr /C:"F:/rwkv_lmdb/test_db_5k_id5" "%DIR%\eval.toml" >nul
if errorlevel 1 (
  echo %TAG% EVAL_DB_MISMATCH %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_77 %DATE% %TIME% >> "%LOG%"
  exit /b 77
)
if exist "result\RWKV-%TAG%.jsonl" del /q "result\RWKV-%TAG%.jsonl"
if exist "result\RWKV-P-%TAG%.jsonl" del /q "result\RWKV-P-%TAG%.jsonl"
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\eval.toml --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% EVAL_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_78 %DATE% %TIME% >> "%LOG%"
  exit /b 78
)
REM Post-check on the SHARD logs, DELIBERATELY NON-FATAL: the probe above is the authoritative
REM check, and a guard that can destroy a finished 10 h eval on a string mismatch is worse than
REM the failure it guards against.
findstr /C:"w10qkdry_d_wkvcb_%STEPS%.txt" scratchpad\eval_shards\shard_*.log >nul 2>&1
if errorlevel 1 (
  echo %TAG% NOTE the shard logs do not name the learned WKV catalog -- verify before trusting the number %DATE% %TIME% >> "%LOG%"
)
echo %TAG% EVAL_OK %TIME% >> "%LOG%"

REM Terminal marker BEFORE endlocal: endlocal restores the pre-setlocal environment,
REM so %LOG% would expand to empty and the marker would go to "".
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
