"""Build one UPWARD-sweep toml from the e2s WS config: a new MAX, and a SAFE save location.

WHY THIS EXISTS RATHER THAN REUSING write_max_toml.py. Two reasons, and the second is a live
hazard:

  1. The old sweep tomls (scratchpad/dispatch/ws_max*.toml) point at `train_db_5k_h1`, which was
     deleted on 2026-08-30. They would fail loudly, which is safe, but they cannot be re-run.

  2. ⚠ `scratchpad/e2s_rebase/ws.toml` writes to SAVE_MODEL_FOLDER=scratchpad/e2s_rebase with
     SAVE_MODEL_PREFIX=e2sc_ws -- the CHAMPION RE-BASE's own checkpoints. A benchmark cloned from
     it would silently overwrite `e2sc_ws_<step>.pth` mid-run and destroy the re-base. A bench is
     a throwaway; its outputs must never share a namespace with a real run. The assert below is
     the point of the file.

The sweep goes UPWARD (81920, 98304, 114688) because the paging premise turned out to be wrong:
real training peaks at 8.2 GB on a 12.28 GB card, so there is roughly 4 GB of headroom and MAX may
have been left low for a reason that never applied. Downward MAX is already closed -- 65536 beat
every smaller value on reviews/s.

⚠ MAX is not a pure speed lever: it sets the group count and so the optimizer steps per epoch,
which is why iter 34's move to 65536 cost 0.0003 at the old LR. A sweep result is a SPEED number;
adopting a MAX needs the LR retuned with it, which is phase 5.

Usage: write_sweep_toml.py <max_len> <out_toml>
"""
import io
import os
import re
import sys

SRC = "scratchpad/e2s_rebase/ws.toml"
SAFE_FOLDER = "scratchpad/dispatch/benchout"


def main():
    max_len, out = int(sys.argv[1]), sys.argv[2]
    s = io.open(SRC, encoding="utf-8").read()

    def sub1(pat, rep, text):
        text2, n = re.subn(pat, rep, text, count=1, flags=re.M)
        assert n == 1, "no match: " + pat
        return text2

    s = sub1(r"^MAX_TRAIN_GLOBAL_LEN[ \t]*=[ \t]*\d+[ \t]*$",
             "MAX_TRAIN_GLOBAL_LEN = %d" % max_len, s)
    s = sub1(r'^SAVE_MODEL_FOLDER[ \t]*=[ \t]*".*"$',
             'SAVE_MODEL_FOLDER = "%s"' % SAFE_FOLDER, s)
    s = sub1(r'^SAVE_MODEL_PREFIX[ \t]*=[ \t]*".*"$',
             'SAVE_MODEL_PREFIX = "swup%d"' % max_len, s)

    header = ("# UPWARD MAX SWEEP, throwaway benchmark toml. Generated by write_sweep_toml.py.\n"
              "# Saves into %s so it CANNOT touch the re-base's checkpoints.\n" % SAFE_FOLDER)
    io.open(out, "w", encoding="utf-8", newline="\n").write(header + s)

    # ---- assert on the OUTPUT ----
    chk = io.open(out, encoding="utf-8").read()
    assert 'SAVE_MODEL_FOLDER = "%s"' % SAFE_FOLDER in chk
    assert "e2sc_ws" not in chk, "the bench would overwrite the re-base's checkpoints"
    assert "e2s_rebase" not in chk.replace(header, ""), "bench still writes into the run's dir"
    m = re.search(r"^MAX_TRAIN_GLOBAL_LEN[ \t]*=[ \t]*(\d+)", chk, re.M)
    assert m and int(m.group(1)) == max_len
    # the db must still be the real one, or the bench measures nothing
    assert "F:/rwkv_lmdb/train_db_5k_h1_e2s" in chk
    os.makedirs(SAFE_FOLDER, exist_ok=True)
    print("wrote %s   MAX=%d   saves to %s" % (out, max_len, SAFE_FOLDER))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
