@echo off
REM ===========================================================================================
REM QAT-TAX ARM RUNNER.  call run_arm.cmd <TAG> <SHIFT_CB> <MODE:ptq|qat>
REM
REM   ptq : evaluate iter 45's PLAIN final UNDER the QAT env, no training. 500 users (5001-5500).
REM         = "quantize a model that was never trained for it" -> the PTQ cost.
REM   qat : re-run iter 45's DECAY from the SAME WS-final with the QAT env added and nothing else
REM         changed (KD stays alpha 0.5), then eval rectified on the full VAL half.
REM         = the deploy procedure -> the TAX.  TAX = this - iter 45 (0.297697 / 0.265375).
REM
REM WHY THE SHIFT CODEBOOK IS A PARAMETER. The shipped q72u shift catalog is C=32-shaped
REM (header `2 12 16 32 4096`) and HARD-FAILS on this C=80 model -- verified 2026-08-12:
REM   RuntimeError: The size of tensor a (32) must match the size of tensor b (80)
REM So it must be refitted, and the refit has a free choice of capacity. Andrew: do both.
REM   m=2 b=12 -> 24 b/shift-vector, the SAME bits as q72u    -> ~23 B card. "tax at today's budget"
REM   m=5 b=12 -> 60 b/shift-vector, the same bits PER DIM     -> ~37 B card. "tax when the
REM               quantizer is not starved" (q72u spent 24 b on 32 dims; this model has 80)
REM The pair separates "quantization costs X" from "our catalog is too small for this model".
REM The WKV catalog is NOT refitted here: its header is `1 10 32 16 1024`, i.e. joint-uv over
REM k=16, and K=16 is unchanged between d=32 and d=80, so it is dimensionally valid. It is still
REM a d=32-FITTED catalog, which inflates BOTH arms equally and so cannot distort their contrast.
REM
REM ⚠ train_rwkv can swallow fatal errors and exit 0 -> every phase is gated on BANNERS+ARTIFACTS.
REM ⚠ Do NOT edit this file while it runs (cmd.exe resumes from a saved byte offset).
REM ===========================================================================================
setlocal
set TAG=%~1
set SHIFT_CB=%~2
set MODE=%~3
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\qat_tax
set SRC=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter45_kddecay
set LOG=%DIR%\qat_tax.log
set STAMP=%RANDOM%%RANDOM%
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935

echo === ARM %TAG% (%MODE%, cb=%SHIFT_CB%) START %DATE% %TIME% === >> "%LOG%"

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5

REM ---- the q72u QAT recipe, with the shift catalog swapped for a C=80 refit ----
set RWKV_QAT_LOWRANK_SCOPE=card:1:int4,note:1:int4
set RWKV_QAT_PQ=reference/pq_cb_wkv_q72u.txt
set RWKV_QAT_SHIFT_PQ=%SHIFT_CB%
set RWKV_QAT_SHIFT_SCOPE=card:int3,note:int3
set RWKV_QAT_NORM_BITS=1
set RWKV_QAT_FUSED=1
set RWKV_NO_JIT=1
set RWKV_EVAL_PAVA=1

REM ---- PHASE 0: prove the QAT env is NOT inert before spending any GPU (2026-08-12 bug) ----
.venv\Scripts\python.exe -u scratchpad/qat_tax/assert_qat_live.py > "%DIR%\%TAG%_qatassert_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% QATINERT %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 44
)

if "%MODE%"=="ptq" goto :ptq
goto :qat

REM ================= PTQ: no training, 500 users =================
:ptq
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %SRC% i45_d %DIR%\%TAG%_eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 5500 > "%DIR%\%TAG%_etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 24
)
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\%TAG%_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\%TAG%_eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 25
)
REM ⚠ the banner lands in the SHARD log, not eval_sharded's parent log -- grep both (cost: one
REM spurious rc 41 on 2026-08-12, after which the arms had already run).
findstr /C:"[QAT-SHIFT-PQ] loaded" "%DIR%\%TAG%_eval_%STAMP%.log" scratchpad\eval_shards\shard_*.log >nul
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% NOQAT %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 41
)
echo ARM %TAG% PTQ OK %TIME% >> "%LOG%"
endlocal & exit /b 0

REM ================= QAT: warm-started decay from iter 45's WS-final =================
:qat
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.5
.venv\Scripts\python.exe scratchpad/write_decay_setup.py %SRC% i45_ws %TAG%_d %DIR%\%TAG%_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\%TAG%_dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 22
)
findstr /C:"i45_ws_%WSSTEPS%" "%DIR%\%TAG%_dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% WRONGCKPT %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\%TAG%_decay.toml > "%DIR%\%TAG%_decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 23
)
findstr /C:"[QAT-SHIFT-PQ] loaded" "%DIR%\%TAG%_decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% NOQAT_DECAY %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 42
)
findstr /C:"[kd-mix] KD ON" "%DIR%\%TAG%_decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% NOKD_DECAY %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 43
)
if not exist "%SRC%\%TAG%_d_%WSSTEPS%.pth" (
  echo ARM %TAG% NOCKPT %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 31
)
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %SRC% %TAG%_d %DIR%\%TAG%_eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 7500 > "%DIR%\%TAG%_etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 24
)
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\%TAG%_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\%TAG%_eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\%TAG%_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\%TAG%_eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo ARM %TAG% EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  endlocal & exit /b 25
)
echo ARM %TAG% QAT OK %TIME% >> "%LOG%"
endlocal & exit /b 0
