@echo off
REM ===========================================================================================
REM QAT TAX ON THE CURRENT d=80 TRUNK (2026-08-12, Andrew: "Let's re-measure the QAT tax and work
REM on reducing it").
REM
REM WHY RE-MEASURE. The only clean plain-vs-QAT pair on record is champ5k_plain vs champ5k_b1:
REM +0.00290 ahead / +0.00445 imm (matched recipe, n=5000, p=0.0). But that was the d=32 /
REM 193,724-param trunk, and the current model has 5x the card state (2,880 vs 576 floats). That
REM number is now the largest and least trustworthy term in the stopping-point balance sheet
REM (research_5k_notes.md), and imm BINDS because of it.
REM
REM ⚠ AND champ5k_b1 ran QAT THROUGHOUT WS+decay, which is NOT how QAT is deployed here. The
REM qat_log's decay-only rows say the difference matters enormously: #39 (decay-only QAT
REM warm-started from a WS-final) cost -0.000127 ahead / +0.000018 imm -- essentially FREE --
REM while #40 (QAT from scratch) cost +0.00534/+0.00446. So a large part of the "tax" may be WHEN
REM QAT is applied, not the quantization itself. This run measures the deploy procedure.
REM
REM DESIGN -- a true single-variable A/B against iter 45, reusing its WS phase unchanged:
REM   ARM A (PTQ, no training): evaluate iter 45's PLAIN final (i45_d_10935.pth) WITH the QAT env
REM       on. That is "quantize a model that was never trained for it" = the PTQ cost. 500 users
REM       (5001-5500) because it is a diagnostic and the effect is ~30x the noise floor.
REM   ARM B (deploy procedure): re-run iter 45's DECAY from the SAME WS-final (i45_ws_10935) with
REM       the q72u QAT env added and nothing else changed -- same KD alpha 0.5, same LR, same MAX,
REM       same 1.0 epochs. Eval rectified on the full VAL half.
REM   TAX      = ARM B - iter 45  (0.297697 / 0.265375)   <- the number for the balance sheet
REM   PTQ cost = ARM A - iter 45  (restricted to the same 500 users)
REM   what the QAT fine-tune recovers = ARM A - ARM B on the same users
REM
REM The q72u codebooks are FIXED and were learned on the d=32 state distribution. If ARM A is bad
REM and ARM B recovers most of it, the fine-tune is doing the work; if ARM A is bad and ARM B
REM stays bad, stale codebooks are the suspect and RWKV_QAT_PQ_LEARN (implemented, but its
REM export->eval wiring is not) is the lever.
REM
REM ⚠ Python maps QAT scopes BY NAME (architecture.py _QAT_NAME -> the config's own (name,cfg)
REM pairs), so card/note are the right streams under the reordered _cnd arch. The positional bug
REM found 2026-08-11 was Rust-only.
REM ⚠ train_rwkv can swallow fatal errors and exit 0, so every phase is gated on BANNERS and
REM ARTIFACTS, not just exit codes.
REM ⚠ Do NOT edit this file while it runs (cmd.exe resumes from a saved byte offset).
REM ===========================================================================================
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\qat_tax
set SRC=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter45_kddecay
set LOG=%DIR%\qat_tax.log
set STAMP=%RANDOM%%RANDOM%
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935

echo ===== QAT TAX (d=80 trunk, warm-started decay-QAT) START %DATE% %TIME% ===== > "%LOG%"

setlocal
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5

REM ---- THE q72u QAT RECIPE (CLAUDE.md 5k methodology (a)) ----
set RWKV_QAT_LOWRANK_SCOPE=card:1:int4,note:1:int4
set RWKV_QAT_PQ=reference/pq_cb_wkv_q72u.txt
set RWKV_QAT_SHIFT_PQ=reference/pq_cb_shift_q72u.txt
set RWKV_QAT_SHIFT_SCOPE=card:int3,note:int3
set RWKV_QAT_NORM_BITS=1
set RWKV_QAT_FUSED=1
set RWKV_NO_JIT=1
set RWKV_EVAL_PAVA=1

REM ================= ARM A: PTQ only (no training), 500 users =================
echo === ARM A: PTQ eval of the PLAIN champion under the QAT env %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %SRC% i45_d %DIR%\qtaxA_eval.toml RWKV-qtaxA RWKV-P-qtaxA 5001 5500 > "%DIR%\etomlA_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_TOMLAFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\qtaxA_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\evalA_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_EVALAFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
REM The QAT env must actually have been active -- otherwise ARM A silently re-measures the plain
REM champion and the "PTQ cost" comes out as zero for the wrong reason.
findstr /C:"[QAT-LOWRANK] set:" "%DIR%\evalA_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOQAT_ARMA %DATE% %TIME% >> "%LOG%"
  exit /b 41
)
echo ARM A OK %TIME% >> "%LOG%"

REM ================= ARM B: warm-started decay-QAT from iter 45's WS-final =================
REM KD stays ON at the champion's decay alpha 0.5 -- iter 45's decay had it, so leaving it on is
REM what makes this a SINGLE-variable A/B (QAT vs no QAT) rather than two changes.
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.5

echo === ARM B: decay-QAT setup from i45_ws_%WSSTEPS% %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_decay_setup.py %SRC% i45_ws qtax_d %DIR%\qtaxB_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetupB_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
findstr /C:"i45_ws_%WSSTEPS%" "%DIR%\dsetupB_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGCKPT %DATE% %TIME% >> "%LOG%"
  exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\qtaxB_decay.toml > "%DIR%\decayB_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
findstr /C:"[QAT-LOWRANK] set:" "%DIR%\decayB_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOQAT_ARMB %DATE% %TIME% >> "%LOG%"
  exit /b 42
)
findstr /C:"[kd-mix] KD ON" "%DIR%\decayB_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOKD_ARMB %DATE% %TIME% >> "%LOG%"
  exit /b 43
)
if not exist "%SRC%\qtax_d_%WSSTEPS%.pth" (
  echo DONE_EXIT_NOCKPT_ARMB %DATE% %TIME% >> "%LOG%"
  exit /b 31
)
echo ARM B decay OK %TIME% >> "%LOG%"

set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %SRC% qtax_d %DIR%\qtaxB_eval.toml RWKV-qtaxB RWKV-P-qtaxB 5001 7500 > "%DIR%\etomlB_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_TOMLBFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
echo === ARM B eval 5001-7500 RECTIFIED attempt 1 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\qtaxB_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\evalB1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\qtaxB_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\evalB2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_EVALBFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo ARM B eval OK %TIME% >> "%LOG%"
endlocal

echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
