@echo off
REM ===========================================================================================
REM QAT IMPROVEMENT #2: 2-BIT NORM.  Single-variable vs qtaxd_cblearn (learnable catalogs).
REM
REM Identical to the qtaxc_m2b12 chain in every respect -- same WS-final, same KD alpha 0.5, same
REM refit starting catalogs, same LR/schedule -- EXCEPT the two catalogs are trainable Parameters
REM (RWKV_QAT_PQ_LEARN=1 + RWKV_QAT_SHIFT_PQ_LEARN=1, wd=0 groups at PEAK_LR x RWKV_CB_LR_MULT=1).
REM So (this - qtaxc cell 2) is attributable to codebook learning alone.
REM
REM Deploy size is UNCHANGED: learning moves catalog VALUES, not structure; the engine ships the
REM exported text catalogs either way. Baseline to beat: 0.301882 / 0.271594 (VAL half).
REM
REM Two lessons from this week are baked in:
REM   - phase 0 asserts the QAT env reached the FINAL config (the architecture.py bug);
REM   - a 10-USER VALIDITY PROBE gates the 7-h eval (the cell-3 lesson: probe for VALIDITY, not
REM     just cost). It uses the EXPORTED catalogs, so it also proves the export->eval wiring.
REM
REM NO CELL 3: an fp32 eval of a structurally-quantized model is meaningless (2026-08-13 finding).
REM ⚠ Do NOT edit this file while it runs.
REM ===========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set TAG=qtaxe_norm2
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\qat_tax
set SRCREL=scratchpad/iter45_kddecay
set SRC=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter45_kddecay
REM own log file: sharing cblearn.log would mix two runs' terminal tokens, which is exactly the
REM append-across-runs trap that fired a false "finished" on 2026-08-13.
set LOG=%DIR%\norm2.log
set STAMP=%RANDOM%%RANDOM%
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935

echo ===== NORM2 CHAIN START %DATE% %TIME% ===== >> "%LOG%"

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_EVAL_PAVA=1
set RWKV_GRAD_STATS=%DIR%\%TAG%_grad_stats.json

REM ---- the frozen quantizer (refit catalogs) + THE ONE CHANGE: both catalogs LEARNABLE ----
set RWKV_QAT_LOWRANK_SCOPE=card:1:int4,note:1:int4
set RWKV_QAT_PQ=reference/pq_cb_wkv_c80_b10.txt
set RWKV_QAT_PQ_LEARN=1
set RWKV_QAT_SHIFT_PQ=reference/pq_cb_shift_c80_m2b12.txt
set RWKV_QAT_SHIFT_PQ_LEARN=1
set RWKV_QAT_SHIFT_SCOPE=card:int3,note:int3
set RWKV_QAT_NORM_BITS=2
set RWKV_QAT_FUSED=1
set RWKV_NO_JIT=1

REM ================= PHASE 0: the QAT env must reach the FINAL config =================
.venv\Scripts\python.exe -u scratchpad/qat_tax/assert_qat_live.py > "%DIR%\%TAG%_qatassert_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo NORM2 QATINERT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_44 >> "%LOG%"
  endlocal & exit /b 44
)

REM ================= PHASE A: decay-QAT with learnable catalogs =================
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.5
.venv\Scripts\python.exe scratchpad/write_decay_setup.py %SRCREL% i45_ws %TAG%_d %DIR%\%TAG%_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\%TAG%_dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo NORM2 DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_22 >> "%LOG%"
  endlocal & exit /b 22
)
findstr /C:"i45_ws_%WSSTEPS%" "%DIR%\%TAG%_dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo NORM2 WRONGCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_32 >> "%LOG%"
  endlocal & exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\%TAG%_decay.toml > "%DIR%\%TAG%_decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo NORM2 DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_23 >> "%LOG%"
  endlocal & exit /b 23
)
REM gates: QAT banners + BOTH learnable-group registrations + KD + artifacts (ckpt AND both
REM exported catalogs -- the whole point of the run).
findstr /C:"[QAT-SHIFT-PQ] loaded" "%DIR%\%TAG%_decay_%STAMP%.log" >nul || (echo NORM2 NOQAT %DATE% %TIME% >> "%LOG%" & echo DONE_EXIT_42 >> "%LOG%" & endlocal & exit /b 42)
findstr /C:"[shift-pq] codebook LEARNABLE" "%DIR%\%TAG%_decay_%STAMP%.log" >nul || (echo NORM2 NOLEARN_SHIFT %DATE% %TIME% >> "%LOG%" & echo DONE_EXIT_47 >> "%LOG%" & endlocal & exit /b 47)
findstr /C:"[wkv-pq] codebook LEARNABLE" "%DIR%\%TAG%_decay_%STAMP%.log" >nul || (echo NORM2 NOLEARN_WKV %DATE% %TIME% >> "%LOG%" & echo DONE_EXIT_48 >> "%LOG%" & endlocal & exit /b 48)
findstr /C:"[kd-mix] KD ON" "%DIR%\%TAG%_decay_%STAMP%.log" >nul || (echo NORM2 NOKD %DATE% %TIME% >> "%LOG%" & echo DONE_EXIT_43 >> "%LOG%" & endlocal & exit /b 43)
if not exist "%SRC%\%TAG%_d_%WSSTEPS%.pth" (echo NORM2 NOCKPT %DATE% %TIME% >> "%LOG%" & echo DONE_EXIT_31 >> "%LOG%" & endlocal & exit /b 31)
if not exist "%SRC%\%TAG%_d_wkvcb_%WSSTEPS%.txt" (echo NORM2 NOWKVCB %DATE% %TIME% >> "%LOG%" & echo DONE_EXIT_49 >> "%LOG%" & endlocal & exit /b 49)
if not exist "%SRC%\%TAG%_d_shiftcb_%WSSTEPS%.txt" (echo NORM2 NOSHIFTCB %DATE% %TIME% >> "%LOG%" & echo DONE_EXIT_50 >> "%LOG%" & endlocal & exit /b 50)
echo NORM2 PHASE_A_OK %TIME% >> "%LOG%"
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_GRAD_STATS=

REM ================= EVAL ENV: point at the LEARNED catalogs, learning OFF =================
set RWKV_QAT_PQ=%SRCREL%/%TAG%_d_wkvcb_%WSSTEPS%.txt
set RWKV_QAT_SHIFT_PQ=%SRCREL%/%TAG%_d_shiftcb_%WSSTEPS%.txt
set RWKV_QAT_PQ_LEARN=
set RWKV_QAT_SHIFT_PQ_LEARN=

REM ================= PHASE B0: 10-user VALIDITY PROBE (the cell-3 lesson) =================
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %SRCREL% %TAG%_d %DIR%\%TAG%_probe.toml RWKV-%TAG%p RWKV-P-%TAG%p 5001 5010 > "%DIR%\%TAG%_ptoml_%STAMP%.log" 2>&1
.venv\Scripts\python.exe -u -m rwkv.get_result --config %DIR%\%TAG%_probe.toml > "%DIR%\%TAG%_probe_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo NORM2 PROBEFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_51 >> "%LOG%"
  endlocal & exit /b 51
)
.venv\Scripts\python.exe -u scratchpad/qat_tax/sanity_probe_gate.py %TAG%p >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo NORM2 PROBE_INSANE %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 >> "%LOG%"
  endlocal & exit /b 46
)
echo NORM2 PROBE_OK %TIME% >> "%LOG%"

REM ================= PHASE B: full VAL-half eval, quantized with the learned catalogs =========
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %SRCREL% %TAG%_d %DIR%\%TAG%_eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 7500 > "%DIR%\%TAG%_etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo NORM2 TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_24 >> "%LOG%"
  endlocal & exit /b 24
)
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\%TAG%_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\%TAG%_eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\%TAG%_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\%TAG%_eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo NORM2 EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 >> "%LOG%"
  endlocal & exit /b 25
)
findstr /C:"[QAT-SHIFT-PQ] loaded" "%DIR%\%TAG%_eval1_%STAMP%.log" "%DIR%\%TAG%_eval2_%STAMP%.log" scratchpad\eval_shards\shard_*.log >nul
if not %ERRORLEVEL%==0 (
  echo NORM2 EVAL_NOT_QUANTIZED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_41 >> "%LOG%"
  endlocal & exit /b 41
)
echo NORM2 EVAL_OK %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
