"""Generate wait_budget_then_decaylen.cmd: the DECAY-LENGTH pair behind the budget curve.

WHY. The chain ends with the budget curve (~09-14 17:00); without a next link the GPU idles until a
human arms one. Decay length (1 and 3 epochs off ws10, control = arm 1's 2) is next on the plan and
built. This waiter is a placeholder that keeps the GPU busy: anything more urgent that the week's
verdicts produce displaces it by stopping THIS waiter while it still loops in gate 0 (stop its cmd
FIRST, then its children -- 2026-09-10).

GATE 0 polls the budget WAITER's log, which already holds one SPURIOUS `DONE_EXIT_100` (13:15, a
children-first stop; see the NOTE line there). So it fires only once a SECOND terminal line exists,
and it reads the LAST one: `DONE_EXIT_100` again means arm 2's eval failed upstream and the GPU is
kept for its resume (refuse, 120); anything else means the GPU is free.
Then both dry runs (0.05 epochs, 20 users), then w10d3 (~12 h), then w10d1 (~6 h).

Usage: python scratchpad/w10d3/mk_wait_decaylen.py
"""
import io

B = chr(92)
R = "C:" + B + "Users" + B + "Andrew" + B + "rwkv-anki-autoresearch"
OUT = "scratchpad/w10d3/wait_budget_then_decaylen.cmd"

T = r"""@echo off
REM Decay-length pair behind the budget curve: dry w10d3, dry w10d1, then w10d3, then w10d1.
REM Generated by scratchpad/w10d3/mk_wait_decaylen.py -- read its docstring for the gate logic.
REM Displace it by stopping THIS waiter's cmd FIRST, then its children, while it loops in gate 0.
setlocal
cd /d {R}
set WLOG={R}{B}scratchpad{B}w10d3{B}wait_decaylen.log
set PREV={R}{B}scratchpad{B}w10b2{B}wait_budget.log
set R={R}
set NDONE=0
set LAST=none
echo ===== decay-length waiter armed on the budget waiter %DATE% %TIME% ===== >> "%WLOG%"

:waitprev
if not exist "%PREV%" goto sleepprev
set NDONE=0
for /f %%N in ('findstr /B /C:"DONE_EXIT_" "%PREV%" ^| find /c /v ""') do set NDONE=%%N
if %NDONE% LSS 2 goto sleepprev
goto gotprev
:sleepprev
ping -n 61 127.0.0.1 >nul
goto waitprev

:gotprev
for /f "delims=" %%L in ('findstr /B /C:"DONE_EXIT_" "%PREV%"') do set LAST=%%L
echo budget waiter ended: %LAST% >> "%WLOG%"
echo %LAST% | findstr /B /C:"DONE_EXIT_100 " >nul
if not errorlevel 1 (
  echo arm 2 eval FAILED upstream -- the GPU is kept for its resume, not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_120 %DATE% %TIME% >> "%WLOG%"
  exit /b 120
)
echo budget chain done -- 120 s for its workers, then the two dry runs %DATE% %TIME% >> "%WLOG%"
ping -n 121 127.0.0.1 >nul

call %R%{B}scratchpad{B}w10d3dry{B}run_w10d3dry.cmd
findstr /B /C:"DONE_EXIT_0 " "%R%{B}scratchpad{B}w10d3dry{B}w10d3dry.log" >nul 2>&1
if errorlevel 1 (
  echo w10d3 dry run ended WITHOUT success -- not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_121 %DATE% %TIME% >> "%WLOG%"
  exit /b 121
)
findstr /C:"Traceback" /C:"Exception caught" "%R%{B}scratchpad{B}w10d3dry{B}decay_*.log" >nul 2>&1
if not errorlevel 1 (
  echo w10d3 dry decay swallowed an exception -- a HOLLOW run, not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_122 %DATE% %TIME% >> "%WLOG%"
  exit /b 122
)
if not exist "%R%{B}result{B}RWKV-P-w10d3dry.jsonl" (
  echo w10d3 dry eval produced no result file %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_123 %DATE% %TIME% >> "%WLOG%"
  exit /b 123
)

call %R%{B}scratchpad{B}w10d1dry{B}run_w10d1dry.cmd
findstr /B /C:"DONE_EXIT_0 " "%R%{B}scratchpad{B}w10d1dry{B}w10d1dry.log" >nul 2>&1
if errorlevel 1 (
  echo w10d1 dry run ended WITHOUT success -- not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_124 %DATE% %TIME% >> "%WLOG%"
  exit /b 124
)
findstr /C:"Traceback" /C:"Exception caught" "%R%{B}scratchpad{B}w10d1dry{B}decay_*.log" >nul 2>&1
if not errorlevel 1 (
  echo w10d1 dry decay swallowed an exception -- a HOLLOW run, not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_125 %DATE% %TIME% >> "%WLOG%"
  exit /b 125
)
if not exist "%R%{B}result{B}RWKV-P-w10d1dry.jsonl" (
  echo w10d1 dry eval produced no result file %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_126 %DATE% %TIME% >> "%WLOG%"
  exit /b 126
)

echo both dry runs clean -- launching w10d3 %DATE% %TIME% >> "%WLOG%"
call %R%{B}scratchpad{B}w10d3{B}run_w10d3.cmd
echo run_w10d3.cmd returned %ERRORLEVEL% -- launching w10d1 %DATE% %TIME% >> "%WLOG%"
call %R%{B}scratchpad{B}w10d1{B}run_w10d1.cmd
echo run_w10d1.cmd returned %ERRORLEVEL% %DATE% %TIME% >> "%WLOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%WLOG%"
endlocal & exit /b 0
"""
out = T.replace("{R}", R).replace("{B}", B)
assert "{" not in out
io.open(OUT, "w", encoding="ascii", newline="\r\n").write(out)
raw = open(OUT, "rb").read()
print(f"wrote {OUT}: {raw.count(b'\n')} lines, {raw.count(b'\r\n')} CRLF")
