"""Generate the muongates runner (Muon coverage of the 13 rkvdag_lerp token-shift gates) from a reference.
    python scratchpad/muongates/mk_muongates.py realcyc
    python scratchpad/muongates/mk_muongates.py eqw        (if eqw promotes: its runner carries the weighting)
One variable on top of the base recipe: `set RWKV_MUON_INCLUDE_GATES=1` (own Muon group, wd 0.0). No new
parameters. WS-log guard: the [muon] banner must name the gate-matrix group. Both-direction guards as in
mk_muonscale.py (no stale token survives outside REM; every mentioning line visited).
"""
import os
import re
import sys
args = [a for a in sys.argv[1:] if not a.startswith("--")]
base = args[0] if args else "realcyc"
cfg = {"realcyc": dict(src_dir="realcyc", src_tag="realcyc", params="563652", keep=()),
       # eqw's own WS-log guard quotes its "[eqw] scored-set loss weighting ON: ..." banner. That line
       # MUST survive verbatim (muongates inherits eqw's recipe, so it must inherit eqw's guard), and
       # it legitimately contains the base's tag -- so it is exempted from the stale-token scan below
       # by exact substring, not by relaxing the scan.
       "eqw": dict(src_dir="eqw", src_tag="eqw", params="563652",
                   keep=("[eqw] scored-set loss weighting",))}[base]
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(REPO)
src_cmd = open(f"scratchpad/{cfg['src_dir']}/run_{cfg['src_tag']}.cmd", newline="").read()
src_ws = open(f"scratchpad/{cfg['src_dir']}/ws.toml", newline="").read()
assert "\r\n" not in src_cmd[:300] and "\r\n" not in src_ws[:300]
m = re.search(r"%DIR%\\(\w+)_ws_%STEPS%\.pth", src_cmd)
assert m
cfg["src_prefix"] = m.group(1)
TAG, PREFIX, DIRN = "muongates", "mg", "muongates"
visited = 0
out = []
for line in src_cmd.split("\n"):
    orig = line
    if line.startswith("REM ") and ("PHASE 2" in line or "restart" in line or "generated by scratchpad/" in line):
        continue
    line = line.replace(f"\\scratchpad\\{cfg['src_dir']}", f"\\scratchpad\\{DIRN}")
    line = line.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}")
    line = line.replace(f"set TAG={cfg['src_tag']}", f"set TAG={TAG}")
    line = line.replace(f"{cfg['src_tag']}.log", f"{TAG}.log")
    line = line.replace(f"{cfg['src_prefix']}_ws", f"{PREFIX}_ws").replace(f"{cfg['src_prefix']}_d", f"{PREFIX}_d")
    line = line.replace(f"===== {cfg['src_tag']} START", f"===== {TAG} START").replace("===== REALCYC START", f"===== {TAG} START")
    if line != orig:
        visited += 1
    out.append(line)
s = "\n".join(out)
anchor = "set RWKV_KD_ALPHA=\n"
assert s.count(anchor) == 1
s = s.replace(anchor, anchor +
    "REM ---- THE LEVER (muongates, ADOPTED: Muon's rule is every 2-D weight -- Jordan 2024, Moonlight 2502.16982):\n"
    "REM the 13 rkvdag_lerp (8,1,1,80) token-shift mixing gates, 8,320 params, the last NON-degenerate\n"
    "REM squeeze-2-D tensors on AdamW. Screen 2026-09-07: 2.0 pct of update energy, anisotropy 0.543 vs a\n"
    "REM 0.449 white-noise floor. `bonus` is excluded: it reshapes to (1,80), where Newton-Schulz is a\n"
    "REM normalisation, not an orthogonalisation. Motivated by iter 67 (gates pay out of proportion to mass).\n"
    "set RWKV_MUON_INCLUDE_GATES=1\n", 1)
guard_anchor = 'echo %TAG% WS_OK %TIME% >> "%LOG%"'
assert s.count(guard_anchor) == 1
s = s.replace(guard_anchor,
    'REM The optimizer must have CONSUMED the flag: the [muon] banner names the gate-matrix group.\n'
    'findstr /C:"gate-matrix params in a wd=0.0 group" "%DIR%\\ws_%STAMP%.log" >nul\n'
    'if not %ERRORLEVEL%==0 (\n'
    '  echo %TAG% GATE_GROUP_NOT_CONSUMED %DATE% %TIME% >> "%LOG%"\n'
    '  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"\n'
    '  exit /b 44\n'
    ')\n' + guard_anchor, 1)
s = s.replace("@echo off\n", f"@echo off\nREM muongates -- generated by scratchpad/muongates/mk_muongates.py from the {base} runner. DO NOT HAND-EDIT.\n", 1)
if " --exclude 6701 " not in s:
    s = s.replace(" --shards 1 --solo-threshold 0 --fetch-per-shard 2", " --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2", 1)
assert s.count(" --exclude 6701 ") == 1
body = "\n".join(l for l in s.split("\n")
                 if not l.startswith("REM") and not any(k in l for k in cfg["keep"]))
assert all(any(k in l for l in s.split("\n")) for k in cfg["keep"]), \
    "the base's own lever guard was exempted from the scan but is MISSING from the output"
for tok in (cfg["src_tag"], f"{cfg['src_prefix']}_", f"scratchpad/{cfg['src_dir']}", f"\\{cfg['src_dir']}\\"):
    assert tok not in body, f"stale token survived outside REM: {tok!r}"
n_mentions = sum(1 for l in src_cmd.split("\n")
                 if not l.startswith("REM") and not any(k in l for k in cfg["keep"])
                 and (cfg["src_tag"] in l or cfg["src_prefix"] + "_" in l or cfg["src_dir"] in l))
assert visited >= n_mentions, (visited, n_mentions)
assert s.count("set RWKV_MUON_INCLUDE_GATES=1") == 1 and s.count("DONE_EXIT_0") == 1
assert f"Trainable parameters: {cfg['params']}" in s
assert "set RWKV_DUR_DROP=" not in s and "set RWKV_ORD_LAMBDA=" not in s and "set RWKV_RESUME_SKIP_GROUPS" not in s
assert "set RWKV_MUON_INCLUDE_SCALE=1" not in s, "muonscale was rejected -- it must not ride along"
assert ("set RWKV_EQUALIZE_LOSS_W=" in s) == (base == "eqw")
ws = src_ws.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}").replace(f'"{cfg["src_prefix"]}_ws"', f'"{PREFIX}_ws"')
assert f'SAVE_MODEL_PREFIX = "{PREFIX}_ws"' in ws and f'SAVE_MODEL_FOLDER = "scratchpad/{DIRN}"' in ws
ws = ws.replace(ws.split("\n")[0], f"# muongates WS phase -- {base}'s recipe + RWKV_MUON_INCLUDE_GATES=1 (set in the runner env, not here).", 1)
os.makedirs(f"scratchpad/{DIRN}", exist_ok=True)
open(f"scratchpad/{DIRN}/run_{TAG}.cmd", "w", newline="\n").write(s)
open(f"scratchpad/{DIRN}/ws.toml", "w", newline="\n").write(ws)
open(f"scratchpad/{DIRN}/CONTROL.txt", "w").write(f"base={base}\ncontrol={base}\n")
print(f"wrote run_{TAG}.cmd + ws.toml from {base}: visited {visited} lines (>= {n_mentions}); guard params {cfg['params']}")
