"""Generate the muonscale runner (Muon coverage of the 26 k/v scale matrices) from a reference runner.
    python scratchpad/muonscale/mk_muonscale.py realcyc [--sam]
    python scratchpad/muonscale/mk_muonscale.py hord    [--sam]     (if hord promotes: its recipe carries
                                                                   the hinge; --sam if the decay carries SAM)
One variable on top of the base recipe: `set RWKV_MUON_INCLUDE_SCALE=1` (own Muon group, wd 0.0). No new
parameters. WS-log guard: the [muon] banner must carry `scale-matrix params in a wd=0.0 group`. With
--sam the SAM env is set after the WS phase and before the decay setup (as in mk_hord.py). Both-direction
guards as in mk_hord.py.
"""
import os
import re
import sys
args = [a for a in sys.argv[1:] if not a.startswith("--")]
base = args[0] if args else "realcyc"
WITH_SAM = "--sam" in sys.argv
cfg = {"realcyc": dict(src_dir="realcyc", src_tag="realcyc", params="563652"),
       "hord": dict(src_dir="hord", src_tag="hord", params="563652")}[base]
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(REPO)
src_cmd = open(f"scratchpad/{cfg['src_dir']}/run_{cfg['src_tag']}.cmd", newline="").read()
src_ws = open(f"scratchpad/{cfg['src_dir']}/ws.toml", newline="").read()
assert "\r\n" not in src_cmd[:300] and "\r\n" not in src_ws[:300]
m = re.search(r"%DIR%\\(\w+)_ws_%STEPS%\.pth", src_cmd)
assert m
cfg["src_prefix"] = m.group(1)
TAG, PREFIX, DIRN = "muonscale", "ms", "muonscale"
src_has_sam = "set RWKV_SAM_RHO=0.05" in src_cmd
visited = 0
out = []
for line in src_cmd.split("\n"):
    orig = line
    if line.startswith("REM ") and ("PHASE 2" in line or "restart" in line or "generated by scratchpad/" in line):
        continue
    line = line.replace(f"\\scratchpad\\{cfg['src_dir']}", f"\\scratchpad\\{DIRN}")
    line = line.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}")
    line = line.replace(f"set TAG={cfg['src_tag']}", f"set TAG={TAG}")
    line = line.replace(f"{cfg['src_tag']}.log", f"{TAG}.log")
    line = line.replace(f"{cfg['src_prefix']}_ws", f"{PREFIX}_ws").replace(f"{cfg['src_prefix']}_d", f"{PREFIX}_d")
    line = line.replace(f"===== {cfg['src_tag']} START", f"===== {TAG} START").replace("===== REALCYC START", f"===== {TAG} START")
    if line != orig:
        visited += 1
    out.append(line)
s = "\n".join(out)
anchor = "set RWKV_KD_ALPHA=\n"
assert s.count(anchor) == 1
s = s.replace(anchor, anchor +
    "REM ---- THE LEVER (muonscale, ADOPTED: Muon on every 2-D weight, Moonlight arXiv 2502.16982 / Jordan 2024):\n"
    "REM the 26 k/v scale (5,80) projections -- the last 2-D weights on AdamW after iter 53 -- move to Muon in\n"
    "REM their own wd=0.0 group. Screen 2026-09-05: update anisotropy 0.653 (LoRAs 0.649), 1 pct of update energy.\n"
    "set RWKV_MUON_INCLUDE_SCALE=1\n", 1)
guard_anchor = 'echo %TAG% WS_OK %TIME% >> "%LOG%"'
assert s.count(guard_anchor) == 1
s = s.replace(guard_anchor,
    'REM The optimizer must have CONSUMED the flag: the [muon] banner names the scale-matrix group.\n'
    'findstr /C:"scale-matrix params in a wd=0.0 group" "%DIR%\\ws_%STAMP%.log" >nul\n'
    'if not %ERRORLEVEL%==0 (\n'
    '  echo %TAG% SCALE_GROUP_NOT_CONSUMED %DATE% %TIME% >> "%LOG%"\n'
    '  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"\n'
    '  exit /b 44\n'
    ')\n' + guard_anchor, 1)
if WITH_SAM and not src_has_sam:
    b = "REM ---- PHASE B: decay, ratio 1.0 ----\n"
    assert s.count(b) == 1
    s = s.replace(b, "REM the reference recipe carries SAM in its DECAY: apply it here, after WS\nset RWKV_SAM_RHO=0.05\nset RWKV_SAM_EVERY=1\n" + b, 1)
    g = 'echo %TAG% DECAY_OK %TIME% >> "%LOG%"'
    assert s.count(g) == 1
    s = s.replace(g, 'findstr /C:"[sam] first pass: weights restored bit-exactly" "%DIR%\\decay_%STAMP%.log" >nul\n'
                     'if not %ERRORLEVEL%==0 (\n  echo %TAG% SAM_NEVER_RAN %DATE% %TIME% >> "%LOG%"\n  echo DONE_EXIT_45 %DATE% %TIME% >> "%LOG%"\n  exit /b 45\n)\n' + g, 1)
s = s.replace("@echo off\n", f"@echo off\nREM muonscale -- generated by scratchpad/muonscale/mk_muonscale.py from the {base} runner{' WITH SAM in the decay' if (WITH_SAM or src_has_sam) else ''}. DO NOT HAND-EDIT.\n", 1)
if " --exclude 6701 " not in s:
    s = s.replace(" --shards 1 --solo-threshold 0 --fetch-per-shard 2", " --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2", 1)
assert s.count(" --exclude 6701 ") == 1
body = "\n".join(l for l in s.split("\n") if not l.startswith("REM"))
for tok in (cfg["src_tag"], f"{cfg['src_prefix']}_", f"scratchpad/{cfg['src_dir']}", f"\\{cfg['src_dir']}\\"):
    assert tok not in body, f"stale token survived outside REM: {tok!r}"
n_mentions = sum(1 for l in src_cmd.split("\n") if not l.startswith("REM") and (cfg["src_tag"] in l or cfg["src_prefix"] + "_" in l or cfg["src_dir"] in l))
assert visited >= n_mentions, (visited, n_mentions)
assert s.count("set RWKV_MUON_INCLUDE_SCALE=1") == 1 and s.count("DONE_EXIT_0") == 1
assert f"Trainable parameters: {cfg['params']}" in s
assert "set RWKV_DUR_DROP=" not in s and "set RWKV_ORD_LAMBDA=" not in s and "set RWKV_RESUME_SKIP_GROUPS" not in s
assert (s.count("set RWKV_SAM_RHO=0.05") == 1) == (WITH_SAM or src_has_sam)
assert ("set RWKV_PAVA_HORIZON_LAMBDA=" in s) == (base == "hord")
ws = src_ws.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}").replace(f'"{cfg["src_prefix"]}_ws"', f'"{PREFIX}_ws"')
assert f'SAVE_MODEL_PREFIX = "{PREFIX}_ws"' in ws and f'SAVE_MODEL_FOLDER = "scratchpad/{DIRN}"' in ws
ws = ws.replace(ws.split("\n")[0], f"# muonscale WS phase -- {base}'s recipe + RWKV_MUON_INCLUDE_SCALE=1 (set in the runner env, not here).", 1)
os.makedirs(f"scratchpad/{DIRN}", exist_ok=True)
open(f"scratchpad/{DIRN}/run_{TAG}.cmd", "w", newline="\n").write(s)
open(f"scratchpad/{DIRN}/ws.toml", "w", newline="\n").write(ws)
open(f"scratchpad/{DIRN}/CONTROL.txt", "w").write(f"base={base}\nwith_sam={WITH_SAM or src_has_sam}\ncontrol={base}\n")
print(f"wrote run_{TAG}.cmd + ws.toml from {base}{' with SAM in the decay' if (WITH_SAM or src_has_sam) else ''}: visited {visited} lines (>= {n_mentions}); guard params {cfg['params']}")
