"""Generate scratchpad/leak/run_leak_cf.cmd: the query-row clock-leak counterfactual on arm 1.

Env copied VERBATIM from scratchpad/w10plain/run_w10plain_eval.cmd (arm 1's own eval), every QAT/KD
variable cleared explicitly (the caller may be a QAT runner), RWKV_EVAL_PAVA=1. Three evals of
arm 1's decayed checkpoint on users 5001-5300 through scratchpad/leak/get_result_cf.py:
LEAK_CF_T = 0 (control), 1800, 10800. Never fatal: every failure logs and moves on, and the runner
always returns 0, because it is called from inside arm 2's eval chain.
Usage: python scratchpad/leak/mk_leak_cf.py
"""
import io
import re
import sys

B = chr(92)
R = "C:" + B + "Users" + B + "Andrew" + B + "rwkv-anki-autoresearch"
SRC = "scratchpad/w10plain/run_w10plain_eval.cmd"
OUT = "scratchpad/leak/run_leak_cf.cmd"

src = io.open(SRC, encoding="ascii", newline="").read().replace("\r\n", "\n")
a = src.index("set PYTHONUNBUFFERED=1")
b = src.index("set RWKV_KD_ALPHA=") + len("set RWKV_KD_ALPHA=")
env = src[a:b]
if re.search(r"^\s*(if|call|echo|findstr|goto)\b", env, re.M | re.I):
    sys.exit("REFUSING: the copied env block contains control flow")
for need in ("RWKV_ID_FEATURES=1", "RWKV_REAL_CYCLES=1", "RWKV_EVAL_DB=F:/rwkv_lmdb/test_db_5k_id5",
             "RWKV_NO_AHEAD_RESIDUAL=1", "RWKV_PROBE_DUR=0.0"):
    if need not in env:
        sys.exit(f"REFUSING: arm 1's env lacks {need}")
if "RWKV_QAT_LOWRANK_SCOPE" in env:
    sys.exit("REFUSING: arm 1's env carries a QAT scope -- it must be plain")

HEAD = r"""@echo off
REM QUERY-ROW CLOCK LEAK, eval-only counterfactual on arm 1 (w10p_d_21870). Generated by
REM scratchpad/leak/mk_leak_cf.py -- edit that. PREREG: scratchpad/leak/PREREG.md.
REM Never fatal: logs to scratchpad/leak/leak_cf.log and always returns 0.
setlocal
cd /d {R}
set DIR={R}{B}scratchpad{B}leak
set LOG=%DIR%{B}leak_cf.log
set STAMP=%RANDOM%%RANDOM%
set CKPT={R}{B}scratchpad{B}ws10{B}w10p_d_21870.pth
echo ===== LEAK-CF START %DATE% %TIME% ===== > "%LOG%"

"""
CLEAR = """
REM every QAT and KD variable cleared: this is arm 1's PLAIN eval, whoever calls it
set RWKV_QAT_LOWRANK_SCOPE=
set RWKV_QAT_PQ=
set RWKV_QAT_SHIFT_PQ=
set RWKV_QAT_SHIFT_SCOPE=
set RWKV_QAT_NORM_BITS=
set RWKV_QAT_FUSED=
set RWKV_QAT_PQ_LEARN=
set RWKV_QAT_SHIFT_PQ_LEARN=
set RWKV_QAT_KD=
set RWKV_QAT_KD_TEACHER=
set RWKV_EVAL_PAVA=1

if not exist "%CKPT%" (
  echo LEAK-CF arm 1 checkpoint missing -- nothing run >> "%LOG%"
  goto lkdone
)
"""
ARM = r"""
set ARM={arm}
set LEAK_CF_T={t}
echo LEAK-CF arm %ARM% T=%LEAK_CF_T% start %TIME% >> "%LOG%"
if exist "result{B}RWKV-%ARM%.jsonl" del /q "result{B}RWKV-%ARM%.jsonl"
if exist "result{B}RWKV-P-%ARM%.jsonl" del /q "result{B}RWKV-P-%ARM%.jsonl"
.venv{B}Scripts{B}python.exe scratchpad/write_eval_toml.py scratchpad/w10plain w10p_d %DIR%{B}%ARM%.toml RWKV-%ARM% RWKV-P-%ARM% 5001 5300 > "%DIR%{B}%ARM%_toml.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LEAK-CF arm %ARM% TOML_FAILED -- skipped >> "%LOG%"
  goto {nxt}
)
findstr /C:"w10p_d_21870.pth" "%DIR%{B}%ARM%.toml" >nul
if errorlevel 1 (
  echo LEAK-CF arm %ARM% TOML_WRONG_CHECKPOINT -- skipped >> "%LOG%"
  goto {nxt}
)
findstr /C:"F:/rwkv_lmdb/test_db_5k_id5" "%DIR%{B}%ARM%.toml" >nul
if errorlevel 1 (
  echo LEAK-CF arm %ARM% TOML_WRONG_DB -- skipped >> "%LOG%"
  goto {nxt}
)
.venv{B}Scripts{B}python.exe -u scratchpad/leak/get_result_cf.py --config %DIR%{B}%ARM%.toml > "%DIR%{B}%ARM%_eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LEAK-CF arm %ARM% EVAL_FAILED -- see %ARM%_eval_%STAMP%.log >> "%LOG%"
  goto {nxt}
)
findstr /C:"[leak-cf] counterfactual ON: T={t} s" "%DIR%{B}%ARM%_eval_%STAMP%.log" >nul
if errorlevel 1 echo LEAK-CF arm %ARM% NOTE the wrapper banner is missing -- do not trust this arm >> "%LOG%"
findstr /C:"[leak-cf pid" "%DIR%{B}%ARM%_eval_%STAMP%.log" >nul
if errorlevel 1 echo LEAK-CF arm %ARM% NOTE no worker reported the patch -- do not trust this arm >> "%LOG%"
echo LEAK-CF arm %ARM% OK %TIME% >> "%LOG%"
"""
TAIL = r"""
:lkdone
.venv{B}Scripts{B}python.exe scratchpad/leak/leak_report.py > "%DIR%{B}leak_report.txt" 2>&1
echo LEAK-CF report rc %ERRORLEVEL% -- see scratchpad/leak/leak_report.txt %DATE% %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
"""
arms = [("lkc0", "0"), ("lkc30m", "1800"), ("lkc3h", "10800")]
body = ""
for i, (arm, t) in enumerate(arms):
    nxt = "lk_" + arms[i + 1][0] if i + 1 < len(arms) else "lkdone"
    body += (("" if i == 0 else ":lk_" + arm + "\n") + ARM.format(arm=arm, t=t, nxt=nxt, B="{B}"))
out = (HEAD + env + "\n" + CLEAR + body + TAIL).replace("{R}", R).replace("{B}", B)
assert "{" not in out
io.open(OUT, "w", encoding="ascii", newline="\r\n").write(out)
raw = open(OUT, "rb").read()
print(f"wrote {OUT}: {raw.count(b'\n')} lines, {raw.count(b'\r\n')} CRLF")
