@echo off
REM QUERY-ROW CLOCK LEAK, eval-only counterfactual on arm 1 (w10p_d_21870). Generated by
REM scratchpad/leak/mk_leak_cf.py -- edit that. PREREG: scratchpad/leak/PREREG.md.
REM Never fatal: logs to scratchpad/leak/leak_cf.log and always returns 0.
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\leak
set LOG=%DIR%\leak_cf.log
set STAMP=%RANDOM%%RANDOM%
set CKPT=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\ws10\w10p_d_21870.pth
echo ===== LEAK-CF START %DATE% %TIME% ===== > "%LOG%"

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_DECAY_VALIDATE_EVERY=2000
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_MUON_INCLUDE_LORA=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1

set RWKV_ID_FEATURES=1
set RWKV_REAL_CYCLES=1
set RWKV_ZERO_FEATURES=
set RWKV_VAL_DB=F:/rwkv_lmdb/test_db_5k_id5
set RWKV_EVAL_DB=F:/rwkv_lmdb/test_db_5k_id5
set RWKV_LABEL_FILTER_DB=F:/rwkv_lmdb/label_filter_db_id_e2s
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=

REM every QAT and KD variable cleared: this is arm 1's PLAIN eval, whoever calls it
set RWKV_QAT_LOWRANK_SCOPE=
set RWKV_QAT_PQ=
set RWKV_QAT_SHIFT_PQ=
set RWKV_QAT_SHIFT_SCOPE=
set RWKV_QAT_NORM_BITS=
set RWKV_QAT_FUSED=
set RWKV_QAT_PQ_LEARN=
set RWKV_QAT_SHIFT_PQ_LEARN=
set RWKV_QAT_KD=
set RWKV_QAT_KD_TEACHER=
set RWKV_EVAL_PAVA=1

if not exist "%CKPT%" (
  echo LEAK-CF arm 1 checkpoint missing -- nothing run >> "%LOG%"
  goto lkdone
)

set ARM=lkc0
set LEAK_CF_T=0
echo LEAK-CF arm %ARM% T=%LEAK_CF_T% start %TIME% >> "%LOG%"
if exist "result\RWKV-%ARM%.jsonl" del /q "result\RWKV-%ARM%.jsonl"
if exist "result\RWKV-P-%ARM%.jsonl" del /q "result\RWKV-P-%ARM%.jsonl"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/w10plain w10p_d %DIR%\%ARM%.toml RWKV-%ARM% RWKV-P-%ARM% 5001 5300 > "%DIR%\%ARM%_toml.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LEAK-CF arm %ARM% TOML_FAILED -- skipped >> "%LOG%"
  goto lk_lkc30m
)
findstr /C:"w10p_d_21870.pth" "%DIR%\%ARM%.toml" >nul
if errorlevel 1 (
  echo LEAK-CF arm %ARM% TOML_WRONG_CHECKPOINT -- skipped >> "%LOG%"
  goto lk_lkc30m
)
findstr /C:"F:/rwkv_lmdb/test_db_5k_id5" "%DIR%\%ARM%.toml" >nul
if errorlevel 1 (
  echo LEAK-CF arm %ARM% TOML_WRONG_DB -- skipped >> "%LOG%"
  goto lk_lkc30m
)
.venv\Scripts\python.exe -u scratchpad/leak/get_result_cf.py --config %DIR%\%ARM%.toml > "%DIR%\%ARM%_eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LEAK-CF arm %ARM% EVAL_FAILED -- see %ARM%_eval_%STAMP%.log >> "%LOG%"
  goto lk_lkc30m
)
findstr /C:"[leak-cf] counterfactual ON: T=0 s" "%DIR%\%ARM%_eval_%STAMP%.log" >nul
if errorlevel 1 echo LEAK-CF arm %ARM% NOTE the wrapper banner is missing -- do not trust this arm >> "%LOG%"
findstr /C:"[leak-cf pid" "%DIR%\%ARM%_eval_%STAMP%.log" >nul
if errorlevel 1 echo LEAK-CF arm %ARM% NOTE no worker reported the patch -- do not trust this arm >> "%LOG%"
echo LEAK-CF arm %ARM% OK %TIME% >> "%LOG%"
:lk_lkc30m

set ARM=lkc30m
set LEAK_CF_T=1800
echo LEAK-CF arm %ARM% T=%LEAK_CF_T% start %TIME% >> "%LOG%"
if exist "result\RWKV-%ARM%.jsonl" del /q "result\RWKV-%ARM%.jsonl"
if exist "result\RWKV-P-%ARM%.jsonl" del /q "result\RWKV-P-%ARM%.jsonl"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/w10plain w10p_d %DIR%\%ARM%.toml RWKV-%ARM% RWKV-P-%ARM% 5001 5300 > "%DIR%\%ARM%_toml.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LEAK-CF arm %ARM% TOML_FAILED -- skipped >> "%LOG%"
  goto lk_lkc3h
)
findstr /C:"w10p_d_21870.pth" "%DIR%\%ARM%.toml" >nul
if errorlevel 1 (
  echo LEAK-CF arm %ARM% TOML_WRONG_CHECKPOINT -- skipped >> "%LOG%"
  goto lk_lkc3h
)
findstr /C:"F:/rwkv_lmdb/test_db_5k_id5" "%DIR%\%ARM%.toml" >nul
if errorlevel 1 (
  echo LEAK-CF arm %ARM% TOML_WRONG_DB -- skipped >> "%LOG%"
  goto lk_lkc3h
)
.venv\Scripts\python.exe -u scratchpad/leak/get_result_cf.py --config %DIR%\%ARM%.toml > "%DIR%\%ARM%_eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LEAK-CF arm %ARM% EVAL_FAILED -- see %ARM%_eval_%STAMP%.log >> "%LOG%"
  goto lk_lkc3h
)
findstr /C:"[leak-cf] counterfactual ON: T=1800 s" "%DIR%\%ARM%_eval_%STAMP%.log" >nul
if errorlevel 1 echo LEAK-CF arm %ARM% NOTE the wrapper banner is missing -- do not trust this arm >> "%LOG%"
findstr /C:"[leak-cf pid" "%DIR%\%ARM%_eval_%STAMP%.log" >nul
if errorlevel 1 echo LEAK-CF arm %ARM% NOTE no worker reported the patch -- do not trust this arm >> "%LOG%"
echo LEAK-CF arm %ARM% OK %TIME% >> "%LOG%"
:lk_lkc3h

set ARM=lkc3h
set LEAK_CF_T=10800
echo LEAK-CF arm %ARM% T=%LEAK_CF_T% start %TIME% >> "%LOG%"
if exist "result\RWKV-%ARM%.jsonl" del /q "result\RWKV-%ARM%.jsonl"
if exist "result\RWKV-P-%ARM%.jsonl" del /q "result\RWKV-P-%ARM%.jsonl"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/w10plain w10p_d %DIR%\%ARM%.toml RWKV-%ARM% RWKV-P-%ARM% 5001 5300 > "%DIR%\%ARM%_toml.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LEAK-CF arm %ARM% TOML_FAILED -- skipped >> "%LOG%"
  goto lkdone
)
findstr /C:"w10p_d_21870.pth" "%DIR%\%ARM%.toml" >nul
if errorlevel 1 (
  echo LEAK-CF arm %ARM% TOML_WRONG_CHECKPOINT -- skipped >> "%LOG%"
  goto lkdone
)
findstr /C:"F:/rwkv_lmdb/test_db_5k_id5" "%DIR%\%ARM%.toml" >nul
if errorlevel 1 (
  echo LEAK-CF arm %ARM% TOML_WRONG_DB -- skipped >> "%LOG%"
  goto lkdone
)
.venv\Scripts\python.exe -u scratchpad/leak/get_result_cf.py --config %DIR%\%ARM%.toml > "%DIR%\%ARM%_eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LEAK-CF arm %ARM% EVAL_FAILED -- see %ARM%_eval_%STAMP%.log >> "%LOG%"
  goto lkdone
)
findstr /C:"[leak-cf] counterfactual ON: T=10800 s" "%DIR%\%ARM%_eval_%STAMP%.log" >nul
if errorlevel 1 echo LEAK-CF arm %ARM% NOTE the wrapper banner is missing -- do not trust this arm >> "%LOG%"
findstr /C:"[leak-cf pid" "%DIR%\%ARM%_eval_%STAMP%.log" >nul
if errorlevel 1 echo LEAK-CF arm %ARM% NOTE no worker reported the patch -- do not trust this arm >> "%LOG%"
echo LEAK-CF arm %ARM% OK %TIME% >> "%LOG%"

:lkdone
.venv\Scripts\python.exe scratchpad/leak/leak_report.py > "%DIR%\leak_report.txt" 2>&1
echo LEAK-CF report rc %ERRORLEVEL% -- see scratchpad/leak/leak_report.txt %DATE% %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
