@echo off
REM Auto-generated by optimization/hp_tuner_5k.py -- do NOT edit while running (cmd.exe re-reads
REM a running .cmd at a saved byte offset).
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\tuner65k\t65_muon_momentum_0p9
set LOG=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\tuner65k\t65_muon_momentum_0p9.log
set STAMP=%RANDOM%%RANDOM%

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=1234
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4.py
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.1
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_MOMENTUM=0.95
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
REM ---- this trial's HPs ----
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.9
set RWKV_ADAMW_BETA2=0.999
set RWKV_WEIGHT_DECAY=0.01
set RWKV_CLIP=0.25
REM ---- the adopted speed stack (cleared again before eval) ----
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1

echo ===== TRIAL t65_muon_momentum_0p9 (param=muon_momentum=0.9) cfg={"lr_mult": 1.0, "warmup_steps": 400, "muon_lr_mult": 0.125, "weight_decay": 0.01, "clip": 0.25, "decay_ratio": 1.0, "muon_momentum": 0.9, "adamw_beta2": 0.999} peak_lr=0.001 muon_lr=0.0025 START %DATE% %TIME% ===== > "%LOG%"

echo === SANITY 40 steps (VRAM + speed-flag proof) %TIME% === >> "%LOG%"
set RWKV_MAX_STEPS=40
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_ws.toml > "%DIR%\sanity_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_SANITYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
set RWKV_MAX_STEPS=
REM An env typo that silently disables a speed flag would cost ~2 extra hours PER TRIAL, so prove
REM both engaged before committing to the run.
findstr /C:"BATCHED Newton-Schulz" "%DIR%\sanity_%STAMP%.log" >nul 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_MUONNOTBATCHED %DATE% %TIME% >> "%LOG%"
  exit /b 16
)
findstr /C:"[compile] torch.compile" "%DIR%\sanity_%STAMP%.log" >nul 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOCOMPILE %DATE% %TIME% >> "%LOG%"
  exit /b 17
)
echo SANITY OK %TIME% >> "%LOG%"

set RWKV_STEP_TRACE=scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_ws_trace.jsonl
set RWKV_VPRUNE_REF=optimization/tuner65k_vprune_ref.json
set RWKV_VPRUNE_MIN_STEP=1000
echo === WS 1 epoch (1-5000, MAX=65536 -^> ~10935 steps) %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_ws.toml > "%DIR%\ws_%STAMP%.log" 2>&1
if %ERRORLEVEL%==42 (
  echo === VAL-PRUNED - recording estimated logloss %TIME% === >> "%LOG%"
  .venv\Scripts\python.exe optimization/hp_tuner_5k.py record-pruned t65_muon_momentum_0p9 >> "%LOG%" 2>&1
  echo DONE_EXIT_PRUNED %DATE% %TIME% >> "%LOG%"
  exit /b 0
)
REM A crashed WS must NOT cascade into decay/eval -- write_decay_setup takes the LATEST ckpt, so
REM a half-trained one would be silently decayed and evaluated as if it were the real trial.
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WSFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 4
)
echo WS OK %TIME% >> "%LOG%"
set RWKV_STEP_TRACE=
set RWKV_VPRUNE_REF=

echo === DECAY SETUP (1 ep, ratio 1) %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/tuner65k/t65_muon_momentum_0p9 t65_muon_momentum_0p9ws t65_muon_momentum_0p9d scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_decay.toml train_db_5k_h1 1 5000 1 0.001 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DSETUPFAIL %DATE% %TIME% >> "%LOG%"
  exit /b 5
)
echo === DECAY %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 6
)
echo DECAY OK %TIME% >> "%LOG%"

echo === WRITE EVAL TOML %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/tuner65k/t65_muon_momentum_0p9 t65_muon_momentum_0p9d scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_eval.toml RWKV-t65_muon_momentum_0p9 RWKV-P-t65_muon_momentum_0p9 5001 6000 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 7
)
REM Eval runs WITHOUT the training speed flags, exactly as run_maxval.cmd does.
set RWKV_MUON_BATCHED=
set RWKV_QAT_COMPILE=
set RWKV_NO_JIT=
set RWKV_EVAL_PAVA=1
REM Users 5002/5905/5995 (266k-367k reviews) OOM the 12 GB card iff the desktop is holding
REM several GB of VRAM. eval_sharded SKIPS users already banked, so a retry costs only the
REM remainder -- hence three attempts and NO del between them (the 2026-07-30 ops rule).
echo === EVAL 5001-6000 RECTIFIED, attempt 1 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo EVAL attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo EVAL attempt 2 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/tuner65k/t65_muon_momentum_0p9/t65_muon_momentum_0p9_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval3_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 8
)
echo EVAL OK %TIME% >> "%LOG%"

echo === RECORD t65_muon_momentum_0p9 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe optimization/hp_tuner_5k.py record t65_muon_momentum_0p9 >> "%LOG%" 2>&1
echo DONE_EXIT_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
