"""Generate run_kdalpha025.cmd -- KD `alpha_decay` 0.5 -> 0.25, the other bracket point.

WHY THIS, AND WHY NOW. iter 55 (`iter52_kdalpha`) raised `alpha_decay` 0.5 -> 0.9 and REGRESSED
(ahead -0.000043, a tie; imm -0.000116, a real loss). That is an asymmetry, because alpha=0.9 WINS
in the WS phase (iter 39, accepted, on a dose curve monotone up through 0.5/0.75/0.9). Two facts now
bracket the decay optimum:

    iter 45:  alpha_decay 0.5  BEATS  no KD in decay      -> some teacher in decay helps
    iter 55:  alpha_decay 0.9  LOSES  to alpha_decay 0.5  -> too much teacher in decay hurts

=> the decay optimum is INTERIOR and near 0.5. 0.25 is the untested side of it.

THE MECHANISM PREDICTS THE DIRECTION, and it was registered before iter 55 ran. `srs_model.py`
overwrites the target with `label_y = alpha*teacher + (1-alpha)*hard`, so the curve head inherits the
TEACHER's calibration instead of fitting the outcome. The champion is overconfident by -0.00292 over
83,478 predictions, and a one-parameter logit shift recovers +0.000115 held out. Reading: KD pays
through target-VARIANCE reduction, which is worth most EARLY when gradients are noisy; CALIBRATION
matters LATE, when the LR anneals and the weights settle into what ships. Lowering alpha in decay
should therefore improve calibration at the moment it counts.
**Prediction: improves. A null bounds the effect and closes the lever from the other side.**

NAMED FOR ITS LEVER, WITH NO NUMBER IN THE PATH -- this is the first run under the 2026-08-18
convention. The number is assigned when the verdict is recorded, so baking one into the directory or
the checkpoint prefix is exactly what made `iter54_cmixpow` and `iter55_rgate` end up with slugs that
lie about their numbers.

Single variable vs iter 45: same WS-final, same dump, same schedule, only the decay alpha differs.
Decay-only, so the lever cannot touch WS by construction. ~6.1 h.
"""
import io
import re

SRC = "scratchpad/iter52_kdalpha/run_iter52.cmd"
DST = "scratchpad/kdalpha025/run_kdalpha025.cmd"

s = io.open(SRC, encoding="ascii", newline="").read()

s = s.replace(r"scratchpad\iter52_kdalpha", r"scratchpad\kdalpha025")
s = s.replace("scratchpad/iter52_kdalpha", "scratchpad/kdalpha025")
s = s.replace("i52_d", "kda025_d")
s = s.replace("i52_decay.toml", "kda025_decay.toml").replace("i52_eval.toml", "kda025_eval.toml")
s = s.replace("iter52.log", "kdalpha025.log")
# TAG names the result jsonls (RWKV-%TAG%.jsonl). It MUST be unique, or this run would
# overwrite iter 55's banked results -- and eval_sharded RESUMES from existing files, so a
# collision would silently mix two models' users into one score.
s = s.replace("set TAG=iter52_kdalpha", "set TAG=kdalpha025")
s = s.replace("ITER52", "KDA025").replace("ITER 52", "KDALPHA025")

# --- THE LEVER: 0.9 -> 0.25, and the guard that proves it took effect ---
assert "set RWKV_KD_ALPHA=0.9\n" in s or "set RWKV_KD_ALPHA=0.9\r\n" in s
s = s.replace("set RWKV_KD_ALPHA=0.9", "set RWKV_KD_ALPHA=0.25", 1)
assert 'findstr /C:"alpha FIXED at 0.9"' in s, "the KD-alpha guard is missing"
s = s.replace('findstr /C:"alpha FIXED at 0.9"', 'findstr /C:"alpha FIXED at 0.25"', 1)

# --- AND THE PROSE MUST NOT LIE ABOUT THE LEVER ---
# Cloning a runner means updating every string that DEPENDS on the lever, not just the lever
# itself. iter 52's header and its DECAY_OK echo name ITS alpha (0.9). Left alone they write
# "alpha 0.9" into THIS run's log for a run whose alpha is 0.25 -- and the log is what a verdict
# gets read from months later. The guard was already correct, so the run was never at risk; the
# RECORD was. Same family as iter 57, whose START banner still announces iter 52's lever.
s = s.replace("(KD alpha_decay 0.5 to 0.9)", "(KD alpha_decay 0.5 to 0.25)")
s = s.replace("KD alpha 0.9 ====", "KD alpha 0.25 ====")
s = s.replace("DECAY_OK KD ON alpha 0.9", "DECAY_OK KD ON alpha 0.25")

HEADER = [
    "@echo off",
    "REM =========================================================================================",
    "REM KD alpha_decay 0.5 to 0.25 -- the other bracket point. Decay-only, ~6.1 h, zero code.",
    "REM Generated by mk_kdalpha025.py; see that docstring for the full argument.",
    "REM",
    "REM WHY: iter 45 showed alpha_decay 0.5 BEATS no-KD-in-decay. iter 55 showed alpha_decay 0.9",
    "REM LOSES to 0.5. So the decay optimum is INTERIOR and near 0.5, and 0.25 is the untested",
    "REM side. Note alpha=0.9 WINS in WS (iter 39) and LOSES in decay -- that asymmetry is the",
    "REM finding this run follows up.",
    "REM",
    "REM MECHANISM, registered before iter 55 ran: label_y is overwritten with",
    "REM alpha times teacher plus one-minus-alpha times hard, so the curve head inherits the",
    "REM TEACHER's calibration rather than fitting the outcome. The champion is overconfident by",
    "REM -0.00292 and a one-parameter logit shift recovers +0.000115 held out. Variance reduction",
    "REM is an EARLY good; calibration is a LATE one. PREDICTION: this improves.",
    "REM",
    "REM NAMED FOR ITS LEVER, NO NUMBER IN THE PATH -- first run under the 2026-08-18 convention.",
    "REM The number is assigned at verdict time.",
    "REM",
    "REM Do NOT edit this file while it runs (iters 43 and 46 died that way).",
    "REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.",
    "REM =========================================================================================",
]
out = "\n".join(HEADER) + "\n" + s[s.index("setlocal"):].replace("\r\n", "\n")
out = out.replace("\n", "\r\n")

# ---------------- OUTPUT GUARDS ----------------
lines = out.split("\r\n")
assert re.search(r"^cd /d ", out, re.M), "cd /d was lost by the slice"
setpos, usepos = {}, {}
for n, ln in enumerate(lines):
    m = re.match(r"\s*set\s+([A-Za-z_][A-Za-z0-9_]*)=", ln)
    if m and m.group(1).upper() not in setpos:
        setpos[m.group(1).upper()] = n
    for v in re.findall(r"%([A-Za-z_][A-Za-z0-9_]*)%", ln):
        usepos.setdefault(v.upper(), n)
for v, un in usepos.items():
    if v in {"DATE", "TIME", "ERRORLEVEL", "RANDOM", "CD"}:
        continue
    assert v in setpos, f"%{v}% used at line {un + 1} but never set"
    assert setpos[v] < un, f"%{v}% used at line {un + 1} before being set at line {setpos[v] + 1}"

_el = [n for n, ln in enumerate(lines) if ln.strip().lower() == "endlocal"]
_de = [n for n, ln in enumerate(lines) if ln.strip().startswith("echo DONE_EXIT_0")]
assert _de, "no terminal marker"
if _el:
    assert min(_el) > max(_de), "endlocal must come AFTER the DONE_EXIT_0 echo"

assert out.count("set RWKV_KD_ALPHA=0.25") == 1, "the lever must be set exactly once"
assert "set RWKV_KD_ALPHA=0.9" not in out, "the old alpha survived somewhere"
assert 'findstr /C:"alpha FIXED at 0.25"' in out, "the guard must check the NEW alpha"
# Every ECHOED line that names an alpha must name THIS run's alpha. A REM may legitimately
# discuss 0.9 (the WHY paragraph compares against iter 55); a line written to the log may not.
# Match a NUMBER after the word "alpha", not the word itself -- the error labels
# (WRONGALPHA_DECAY) contain "alpha" and name no value. A guard that fires on the wrong thing
# is the failure it exists to prevent.
for ln in lines:
    st = ln.strip()
    if st.lower().startswith("echo"):
        vals = re.findall("alpha[^0-9]{0,12}([0-9]+[.][0-9]+)", st, re.I)
        # A line may legitimately name the value moved FROM ("0.5 to 0.25"); it may never
        # name alphas WITHOUT naming this run's own.
        assert not vals or "0.25" in st, "echoed line names " + str(vals) + " but not 0.25: " + st
assert out.count("DONE_EXIT_0") == 1
for stale in ("iter52", "i52_", "iter 52"):
    body = "\n".join(l for l in lines if not l.strip().upper().startswith("REM")).lower()
    assert stale not in body, f"stale iter-52 text in an EXECUTED line: {stale}"
assert "%SRCREL% i45_ws kda025_d" in out, "must decay from the champion's own WS-final"
assert "set TAG=kdalpha025" in out, "TAG must be unique or results collide"
for ln in lines:
    if ln.strip().upper().startswith("REM"):
        bad = [c for c in "<>&|^" if c in ln]
        assert not bad, "redirection char " + str(bad) + " in REM line: " + ln

io.open(DST, "w", encoding="ascii", newline="").write(out)
print("wrote", DST, len(out), "bytes")
