@echo off
REM QAT-TAX DECOMPOSITION. Generated by scratchpad/qat_decomp/mk_decomp.py -- edit that, not this.
REM Evaluates the SAME QAT checkpoint twice more on users 5001-5300, each arm the deploy env MINUS
REM exactly one component, so deploy minus arm IS that component's cost:
REM   noshift  shift quantization off (scope and catalog cleared)
REM   nowcb    WKV codebook and WKV norm quant off (rank-1 kept, factors at int8, near exact)
REM The whole-QAT-off arm is deliberately ABSENT: rank-1 truncation is STRUCTURAL, and a model trained
REM through it scores garbage at full precision (research_5k_notes.md, cell 3). Each arm first runs a
REM 10-user probe that must load the right quantizers and must not be far WORSE than deploy -- a model
REM that is worse without a quantizer depends on it, and its difference is not a cost.
REM Never fatal to the caller. PREREG: scratchpad/qat_decomp/PREREG.md.
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DTAG=%~1
set DSTEPS=%~2
set DPREFIX=%~3
set DFOLDER=%~4
set DDIR=%~5
set DWKVCB=%~6
set DSHIFTCB=%~7
set LOG=%DDIR%\decomp.log
echo ===== %DTAG% DECOMP START %DATE% %TIME% ===== > "%LOG%"
echo args tag=%DTAG% steps=%DSTEPS% prefix=%DPREFIX% folder=%DFOLDER% wkvcb=%DWKVCB% shiftcb=%DSHIFTCB% >> "%LOG%"
REM Keep the caller's full-eval shard log -- its banners are the evidence the full eval loaded the
REM learned catalogs, and each arm below deletes the shard logs before it runs.
type scratchpad\eval_shards\shard_*.log > "%DDIR%\eval_full_shard.log" 2>nul

REM The inherited env must BE the deploy env, or neither arm differs from deploy by one component.
.venv\Scripts\python.exe scratchpad/qat_decomp/assert_arm.py deploy %DSTEPS% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP inherited env is not the deploy env -- no arms run >> "%LOG%"
  goto dcreport
)

set ARM=noshift
set RWKV_QAT_LOWRANK_SCOPE=card:1:int4,note:1:int4
set RWKV_QAT_PQ=%DWKVCB%
set RWKV_QAT_SHIFT_SCOPE=
set RWKV_QAT_SHIFT_PQ=
call :runarm

set ARM=nowcb
set RWKV_QAT_LOWRANK_SCOPE=card:1:int8,note:1:int8
set RWKV_QAT_PQ=
set RWKV_QAT_SHIFT_SCOPE=card:int3,note:int3
set RWKV_QAT_SHIFT_PQ=%DSHIFTCB%
call :runarm

:dcreport
.venv\Scripts\python.exe scratchpad/qat_decomp/decomp_report.py %DTAG% %DDIR% > "%DDIR%\decomp_report.txt" 2>&1
echo %DTAG% DECOMP report rc %ERRORLEVEL% -- see %DDIR%\decomp_report.txt %DATE% %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0

REM ---- one arm: env assert, 10-user validity probe, banner check, probe gate, 300-user eval ----
:runarm
echo %DTAG% DECOMP arm %ARM% start %TIME% >> "%LOG%"
.venv\Scripts\python.exe scratchpad/qat_decomp/assert_arm.py %ARM% %DSTEPS% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP arm %ARM% ENV_WRONG -- skipped >> "%LOG%"
  goto :eof
)
if exist "result\RWKV-%DTAG%d%ARM%p.jsonl" del /q "result\RWKV-%DTAG%d%ARM%p.jsonl"
if exist "result\RWKV-P-%DTAG%d%ARM%p.jsonl" del /q "result\RWKV-P-%DTAG%d%ARM%p.jsonl"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %DFOLDER% %DPREFIX% %DDIR%\d%ARM%p.toml RWKV-%DTAG%d%ARM%p RWKV-P-%DTAG%d%ARM%p 5001 5010 > "%DDIR%\d%ARM%p_toml.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP arm %ARM% PROBE_TOML_FAILED -- skipped >> "%LOG%"
  goto :eof
)
findstr /C:"%DPREFIX%_%DSTEPS%.pth" "%DDIR%\d%ARM%p.toml" >nul
if errorlevel 1 (
  echo %DTAG% DECOMP arm %ARM% PROBE_TOML_WRONG_CHECKPOINT -- skipped >> "%LOG%"
  goto :eof
)
.venv\Scripts\python.exe -u -m rwkv.get_result --config %DDIR%\d%ARM%p.toml > "%DDIR%\d%ARM%p.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP arm %ARM% PROBE_EVAL_FAILED -- skipped >> "%LOG%"
  goto :eof
)
.venv\Scripts\python.exe scratchpad/qat_decomp/check_banners.py %ARM% "%DDIR%\d%ARM%p.log" %DWKVCB% %DSHIFTCB% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP arm %ARM% PROBE_BANNERS_WRONG -- skipped >> "%LOG%"
  goto :eof
)
.venv\Scripts\python.exe scratchpad/qat_decomp/probe_gate.py %DTAG% %ARM% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP arm %ARM% OFF_DISTRIBUTION per the 10-user probe -- skipped >> "%LOG%"
  goto :eof
)
if exist "result\RWKV-%DTAG%d%ARM%.jsonl" del /q "result\RWKV-%DTAG%d%ARM%.jsonl"
if exist "result\RWKV-P-%DTAG%d%ARM%.jsonl" del /q "result\RWKV-P-%DTAG%d%ARM%.jsonl"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %DFOLDER% %DPREFIX% %DDIR%\d%ARM%.toml RWKV-%DTAG%d%ARM% RWKV-P-%DTAG%d%ARM% 5001 5300 > "%DDIR%\d%ARM%_toml.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP arm %ARM% TOML_FAILED -- skipped >> "%LOG%"
  goto :eof
)
findstr /C:"%DPREFIX%_%DSTEPS%.pth" "%DDIR%\d%ARM%.toml" >nul
if errorlevel 1 (
  echo %DTAG% DECOMP arm %ARM% TOML_WRONG_CHECKPOINT -- skipped >> "%LOG%"
  goto :eof
)
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DDIR%\d%ARM%.toml --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2 --threads-per-shard 7 > "%DDIR%\d%ARM%_eval.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP arm %ARM% EVAL_FAILED >> "%LOG%"
  goto :eof
)
type scratchpad\eval_shards\shard_*.log > "%DDIR%\d%ARM%_shard.log" 2>nul
.venv\Scripts\python.exe scratchpad/qat_decomp/check_banners.py %ARM% "%DDIR%\d%ARM%_shard.log" %DWKVCB% %DSHIFTCB% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo %DTAG% DECOMP arm %ARM% NOTE the shard log banners are wrong -- the report must not use this arm >> "%LOG%"
  echo BANNERS_WRONG > "%DDIR%\d%ARM%_BANNERS_WRONG.txt"
  goto :eof
)
echo %DTAG% DECOMP arm %ARM% OK %TIME% >> "%LOG%"
goto :eof
