"""Regenerate the leave-one-out sweep: run_loo.cmd + one eval toml per arm + arms.json.
Arms = one per FEATURE of featB's 23 new columns (sin/cos pairs ablated together => 19 arms), 300 users
(5001-5300) each, paired against featB's own results by loo_verdict.py. Env block is cloned from
run_ablate.cmd so the eval env is featB's exactly. No backslash literals in this file on purpose
(the shell heredoc that first wrote it collapses them): paths are built with chr(92).
"""
import json, os
B = chr(92); NL = chr(10)
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
cols_struct = "scaled_user_tenure,scaled_creation_to_first_review,scaled_deck_age_at_review,card_predates_deck,is_default_deck,scaled_deck_depth,scaled_creation_batch_1min,scaled_creation_batch_1h,scaled_creation_batch_1d,scaled_creation_batch_pos_1h,is_default_preset,scaled_sibling_gap,card_predates_first_review".split(",")
groups = [("tod", ["tod_sin", "tod_cos"]), ("tod_dev", ["tod_dev_sin", "tod_dev_cos"]), ("dow", ["dow_sin", "dow_cos"]),
          ("doy", ["doy_sin", "doy_cos"]), ("is_weekend", ["is_weekend"]), ("t_since_any", ["scaled_t_since_any_review"])]
groups += [(c.replace("scaled_", ""), [c]) for c in cols_struct]
assert sum(len(g[1]) for g in groups) == 23
tmpl = open("scratchpad/feat_ablate/eval_abl_struct.toml", newline="").read()
head = open("scratchpad/feat_ablate/run_ablate.cmd", newline="").read()
env = head[head.index("setlocal"):head.index("set CLOCK=")]
env = env.replace(B + "feat_ablate", B + "feat_loo").replace("ablate.log", "loo.log")
assert "feat_loo" in env and "loo.log" in env
lines = ["@echo off",
 "REM =========================================================================================",
 "REM LEAVE-ONE-OUT feature ablation on featB's checkpoint: 19 arms, one per feature (sin/cos",
 "REM pairs count as one), 300 users each (5001-5300, paired against featB's own results).",
 "REM Andrew 2026-09-03: 'ideally we should try ablating everything, but that is time-consuming.'",
 "REM At ~25 min per arm it is ~8 h of GPU, parked behind lorawd. Inference-time ablation measures",
 "REM RELIANCE, not value: a retrained model recovers part of any loss. But a column whose removal",
 "REM costs ~0 here cannot be worth more than ~0 retrained-without either, so ~0 == droppable.",
 "REM Generated by mk_loo.py. DO NOT HAND-EDIT. No angle brackets or arrows in REM lines.",
 "REM =========================================================================================",
 env.rstrip(NL), 'if not exist "%DIR%" mkdir "%DIR%"', 'echo ===== LOO ABLATION START %DATE% %TIME% ===== > "%LOG%"', ""]
for i, (tag, cs) in enumerate(groups, 1):
    t = tmpl.replace("abl_struct", "loo_" + tag).replace("# FEATURE-ABLATION arm loo_" + tag + ".", "# LOO arm loo_" + tag + ": " + ",".join(cs) + ".")
    open("scratchpad/feat_loo/eval_loo_%s.toml" % tag, "w", newline=NL).write(t)
    lines += ["REM ---- ARM %d: loo_%s (%s) ----" % (i, tag, ",".join(cs)),
     "set RWKV_ABLATE_FEATURES=%s" % ",".join(cs),
     'if exist "result%sRWKV-loo_%s.jsonl" del /q "result%sRWKV-loo_%s.jsonl"' % (B, tag, B, tag),
     'if exist "result%sRWKV-P-loo_%s.jsonl" del /q "result%sRWKV-P-loo_%s.jsonl"' % (B, tag, B, tag),
     '%%PY%% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_%s.toml > "%%DIR%%%sloo_%s_%%STAMP%%.log" 2>&1' % (tag, B, tag),
     "if not %ERRORLEVEL%==0 (", '  echo LOO loo_%s_FAILED_%%ERRORLEVEL%% %%DATE%% %%TIME%% >> "%%LOG%%"' % tag,
     '  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"', "  exit /b 13", ")",
     '%%PY%% scratchpad/feat_ablate/check_mask_count.py "%%DIR%%%sloo_%s_%%STAMP%%.log" %d >> "%%LOG%%" 2>&1' % (B, tag, len(cs)),
     "if not %ERRORLEVEL%==0 (", '  echo LOO loo_%s_WRONG_DIM_COUNT %%DATE%% %%TIME%% >> "%%LOG%%"' % tag,
     '  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"', "  exit /b 46", ")",
     'echo LOO loo_%s_OK %%TIME%% >> "%%LOG%%"' % tag, ""]
lines += ["REM ---- the verdict ----", '%PY% scratchpad/feat_loo/loo_verdict.py >> "%LOG%" 2>&1',
 "REM Terminal marker BEFORE endlocal.", 'echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"', "endlocal & exit /b 0", ""]
out = NL.join(lines)
open("scratchpad/feat_loo/run_loo.cmd", "w", newline=NL).write(out)
json.dump(groups, open("scratchpad/feat_loo/arms.json", "w"))
print("wrote run_loo.cmd with %d arms" % len(groups))
