@echo off
REM =========================================================================================
REM LEAVE-ONE-OUT feature ablation on featB's checkpoint: 19 arms, one per feature (sin/cos
REM pairs count as one), 300 users each (5001-5300, paired against featB's own results).
REM Andrew 2026-09-03: 'ideally we should try ablating everything, but that is time-consuming.'
REM At ~25 min per arm it is ~8 h of GPU, parked behind lorawd. Inference-time ablation measures
REM RELIANCE, not value: a retrained model recovers part of any loss. But a column whose removal
REM costs ~0 here cannot be worth more than ~0 retrained-without either, so ~0 == droppable.
REM Generated by mk_loo.py. DO NOT HAND-EDIT. No angle brackets or arrows in REM lines.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\feat_loo
set LOG=%DIR%\loo_p2.log
set STAMP=%RANDOM%%RANDOM%
set PY=.venv\Scripts\python.exe
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=6

REM featB's eval env, reproduced exactly -- anything that differs would confound the ablation.
set RWKV_ID_FEATURES=1
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_EVAL_PAVA=1
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ZERO_FEATURES=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
if not exist "%DIR%" mkdir "%DIR%"
echo ===== LOO ABLATION PHASE 2 (arms 8-19 after the arm-8 CUDA fault) START %DATE% %TIME% ===== > "%LOG%"
REM ---- ARM 8: loo_creation_to_first_review (scaled_creation_to_first_review) ----
set RWKV_ABLATE_FEATURES=scaled_creation_to_first_review
if exist "result\RWKV-loo_creation_to_first_review.jsonl" del /q "result\RWKV-loo_creation_to_first_review.jsonl"
if exist "result\RWKV-P-loo_creation_to_first_review.jsonl" del /q "result\RWKV-P-loo_creation_to_first_review.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_creation_to_first_review.toml > "%DIR%\loo_creation_to_first_review_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_to_first_review_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_creation_to_first_review_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_to_first_review_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_creation_to_first_review_OK %TIME% >> "%LOG%"

REM ---- ARM 9: loo_deck_age_at_review (scaled_deck_age_at_review) ----
set RWKV_ABLATE_FEATURES=scaled_deck_age_at_review
if exist "result\RWKV-loo_deck_age_at_review.jsonl" del /q "result\RWKV-loo_deck_age_at_review.jsonl"
if exist "result\RWKV-P-loo_deck_age_at_review.jsonl" del /q "result\RWKV-P-loo_deck_age_at_review.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_deck_age_at_review.toml > "%DIR%\loo_deck_age_at_review_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_deck_age_at_review_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_deck_age_at_review_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_deck_age_at_review_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_deck_age_at_review_OK %TIME% >> "%LOG%"

REM ---- ARM 10: loo_card_predates_deck (card_predates_deck) ----
set RWKV_ABLATE_FEATURES=card_predates_deck
if exist "result\RWKV-loo_card_predates_deck.jsonl" del /q "result\RWKV-loo_card_predates_deck.jsonl"
if exist "result\RWKV-P-loo_card_predates_deck.jsonl" del /q "result\RWKV-P-loo_card_predates_deck.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_card_predates_deck.toml > "%DIR%\loo_card_predates_deck_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_card_predates_deck_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_card_predates_deck_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_card_predates_deck_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_card_predates_deck_OK %TIME% >> "%LOG%"

REM ---- ARM 11: loo_is_default_deck (is_default_deck) ----
set RWKV_ABLATE_FEATURES=is_default_deck
if exist "result\RWKV-loo_is_default_deck.jsonl" del /q "result\RWKV-loo_is_default_deck.jsonl"
if exist "result\RWKV-P-loo_is_default_deck.jsonl" del /q "result\RWKV-P-loo_is_default_deck.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_is_default_deck.toml > "%DIR%\loo_is_default_deck_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_is_default_deck_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_is_default_deck_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_is_default_deck_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_is_default_deck_OK %TIME% >> "%LOG%"

REM ---- ARM 12: loo_deck_depth (scaled_deck_depth) ----
set RWKV_ABLATE_FEATURES=scaled_deck_depth
if exist "result\RWKV-loo_deck_depth.jsonl" del /q "result\RWKV-loo_deck_depth.jsonl"
if exist "result\RWKV-P-loo_deck_depth.jsonl" del /q "result\RWKV-P-loo_deck_depth.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_deck_depth.toml > "%DIR%\loo_deck_depth_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_deck_depth_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_deck_depth_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_deck_depth_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_deck_depth_OK %TIME% >> "%LOG%"

REM ---- ARM 13: loo_creation_batch_1min (scaled_creation_batch_1min) ----
set RWKV_ABLATE_FEATURES=scaled_creation_batch_1min
if exist "result\RWKV-loo_creation_batch_1min.jsonl" del /q "result\RWKV-loo_creation_batch_1min.jsonl"
if exist "result\RWKV-P-loo_creation_batch_1min.jsonl" del /q "result\RWKV-P-loo_creation_batch_1min.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_creation_batch_1min.toml > "%DIR%\loo_creation_batch_1min_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_batch_1min_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_creation_batch_1min_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_batch_1min_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_creation_batch_1min_OK %TIME% >> "%LOG%"

REM ---- ARM 14: loo_creation_batch_1h (scaled_creation_batch_1h) ----
set RWKV_ABLATE_FEATURES=scaled_creation_batch_1h
if exist "result\RWKV-loo_creation_batch_1h.jsonl" del /q "result\RWKV-loo_creation_batch_1h.jsonl"
if exist "result\RWKV-P-loo_creation_batch_1h.jsonl" del /q "result\RWKV-P-loo_creation_batch_1h.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_creation_batch_1h.toml > "%DIR%\loo_creation_batch_1h_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_batch_1h_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_creation_batch_1h_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_batch_1h_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_creation_batch_1h_OK %TIME% >> "%LOG%"

REM ---- ARM 15: loo_creation_batch_1d (scaled_creation_batch_1d) ----
set RWKV_ABLATE_FEATURES=scaled_creation_batch_1d
if exist "result\RWKV-loo_creation_batch_1d.jsonl" del /q "result\RWKV-loo_creation_batch_1d.jsonl"
if exist "result\RWKV-P-loo_creation_batch_1d.jsonl" del /q "result\RWKV-P-loo_creation_batch_1d.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_creation_batch_1d.toml > "%DIR%\loo_creation_batch_1d_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_batch_1d_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_creation_batch_1d_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_batch_1d_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_creation_batch_1d_OK %TIME% >> "%LOG%"

REM ---- ARM 16: loo_creation_batch_pos_1h (scaled_creation_batch_pos_1h) ----
set RWKV_ABLATE_FEATURES=scaled_creation_batch_pos_1h
if exist "result\RWKV-loo_creation_batch_pos_1h.jsonl" del /q "result\RWKV-loo_creation_batch_pos_1h.jsonl"
if exist "result\RWKV-P-loo_creation_batch_pos_1h.jsonl" del /q "result\RWKV-P-loo_creation_batch_pos_1h.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_creation_batch_pos_1h.toml > "%DIR%\loo_creation_batch_pos_1h_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_batch_pos_1h_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_creation_batch_pos_1h_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_creation_batch_pos_1h_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_creation_batch_pos_1h_OK %TIME% >> "%LOG%"

REM ---- ARM 17: loo_is_default_preset (is_default_preset) ----
set RWKV_ABLATE_FEATURES=is_default_preset
if exist "result\RWKV-loo_is_default_preset.jsonl" del /q "result\RWKV-loo_is_default_preset.jsonl"
if exist "result\RWKV-P-loo_is_default_preset.jsonl" del /q "result\RWKV-P-loo_is_default_preset.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_is_default_preset.toml > "%DIR%\loo_is_default_preset_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_is_default_preset_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_is_default_preset_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_is_default_preset_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_is_default_preset_OK %TIME% >> "%LOG%"

REM ---- ARM 18: loo_sibling_gap (scaled_sibling_gap) ----
set RWKV_ABLATE_FEATURES=scaled_sibling_gap
if exist "result\RWKV-loo_sibling_gap.jsonl" del /q "result\RWKV-loo_sibling_gap.jsonl"
if exist "result\RWKV-P-loo_sibling_gap.jsonl" del /q "result\RWKV-P-loo_sibling_gap.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_sibling_gap.toml > "%DIR%\loo_sibling_gap_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_sibling_gap_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_sibling_gap_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_sibling_gap_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_sibling_gap_OK %TIME% >> "%LOG%"

REM ---- ARM 19: loo_card_predates_first_review (card_predates_first_review) ----
set RWKV_ABLATE_FEATURES=card_predates_first_review
if exist "result\RWKV-loo_card_predates_first_review.jsonl" del /q "result\RWKV-loo_card_predates_first_review.jsonl"
if exist "result\RWKV-P-loo_card_predates_first_review.jsonl" del /q "result\RWKV-P-loo_card_predates_first_review.jsonl"
%PY% -u -m rwkv.get_result --config scratchpad/feat_loo/eval_loo_card_predates_first_review.toml > "%DIR%\loo_card_predates_first_review_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_card_predates_first_review_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
%PY% scratchpad/feat_ablate/check_mask_count.py "%DIR%\loo_card_predates_first_review_%STAMP%.log" 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo LOO loo_card_predates_first_review_WRONG_DIM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 %DATE% %TIME% >> "%LOG%"
  exit /b 46
)
echo LOO loo_card_predates_first_review_OK %TIME% >> "%LOG%"

REM ---- the verdict ----
%PY% scratchpad/feat_loo/loo_verdict.py >> "%LOG%" 2>&1
REM Terminal marker BEFORE endlocal.
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
