@echo off
REM =========================================================================================
REM Rebuild the PUBLISHED eval db with the int64 id fix, then measure the UNCHAMPION-CHANGED
REM champion against it.
REM
REM WHAT THIS ANSWERS, and it needs no decision from Andrew: eval groups rows by the ids STORED
REM in the test db, while DEPLOY keys its states on the RAW full-precision id. Those disagreed.
REM On the published test db, user 5010 had note n_unique == 1 across ALL 171,933 scored rows,
REM and user 5002 had 451,782 of 565,262 rows carrying a saturated note id. So the champion's
REM recorded 0.297523 / 0.265191 is NOT what it would do in Anki.
REM
REM Scoring the SAME checkpoint against a fixed db measures its true deploy accuracy. Nothing is
REM retrained, no champion is re-based, and test_db_5k is left untouched beside it.
REM
REM Do NOT edit this file while it runs. No angle brackets or arrows in REM lines.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\features_rebuild
set LOG=%DIR%\testfix.log
set STAMP=%RANDOM%%RANDOM%
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=6

echo ===== TESTFIX START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE 0: the id fix must actually be in the code we are about to run with ----
.venv\Scripts\python.exe scratchpad/parity3/smoke_id_identity.py >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo TESTFIX IDENTITY_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_40 %DATE% %TIME% >> "%LOG%"
  exit /b 40
)
echo TESTFIX SMOKE_OK %TIME% >> "%LOG%"

REM ---- PHASE 1: build the fixed eval db (published dataset, id fix only) ----
set RWKV_ID_FEATURES=
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_test_5k_h2_fix.toml > "%DIR%\testfix_build_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo TESTFIX BUILD_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/test_db_5k_fix 2000 24 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo TESTFIX DB_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_14 %DATE% %TIME% >> "%LOG%"
  exit /b 14
)
echo TESTFIX BUILD_OK %TIME% >> "%LOG%"

echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
