@echo off
REM =========================================================================================
REM THE FEATURES REBUILD -- authorized by Andrew 2026-08-19. Three phases, all CPU-only.
REM
REM   0. label_filter_db_id   users 1-10000   (dataset-dependent, feature-INDEPENDENT)
REM   1. train_db_5k_h1_id    users 1-5000    ~372.5 GB
REM   2. test_db_5k_id        users 5001-10000 ~116 GB (eval half only; the swap half has no
REM                                             live reader, which saves ~116 GB)
REM
REM CPU ONLY, so it runs beside live GPU training. That is why the features phase can start
REM now rather than after the chain drains.
REM
REM BUILT ON F: BESIDE THE ORIGINALS -- nothing is deleted. 605 GB budgeted against 885 GB
REM free, so a bad rebuild is an rm of the new dirs, not a 2-4 day re-run of the old ones.
REM Every path is NEW, so no live run can read a half-built db by accident.
REM
REM RESUMABLE, AND THAT IS A TRAP AS WELL AS A FEATURE: data_processing skips users already
REM present, so a pre-existing db reports success in seconds having done nothing. That is
REM exactly what the de-risk build did at 17:27 today (its dbs were left over from 2026-08-16).
REM Hence the phase guards below check ENTRY COUNTS, not merely that a file exists.
REM
REM Do NOT edit this file while it runs. No angle brackets or arrows in REM lines.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\features_rebuild
set LOG=%DIR%\rebuild.log
set STAMP=%RANDOM%%RANDOM%
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=6

if not exist "%DIR%" mkdir "%DIR%"
echo ===== FEATURES REBUILD START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE 0: label_filter for -id. No feature flag: it selects WHICH reviews count. ----
set RWKV_ID_FEATURES=
if exist "%DIR%\lf_%STAMP%.log" del /q "%DIR%\lf_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.find_equalize_test_reviews --config rwkv/find_equalize_id.toml > "%DIR%\lf_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD LF_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_11 %DATE% %TIME% >> "%LOG%"
  exit /b 11
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/label_filter_db_id 5000 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD LF_TOO_SMALL %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_12 %DATE% %TIME% >> "%LOG%"
  exit /b 12
)
echo REBUILD LF_OK %TIME% >> "%LOG%"

REM ---- PHASE 1: the TRAIN db, with the new columns ON ----
set RWKV_ID_FEATURES=1
if exist "%DIR%\train_%STAMP%.log" del /q "%DIR%\train_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_train_5k_h1_id.toml > "%DIR%\train_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD TRAIN_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/train_db_5k_h1_id 100000 44 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD TRAIN_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_14 %DATE% %TIME% >> "%LOG%"
  exit /b 14
)
echo REBUILD TRAIN_OK %TIME% >> "%LOG%"

REM ---- PHASE 2: the EVAL db, same flag ----
if exist "%DIR%\test_%STAMP%.log" del /q "%DIR%\test_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_test_5k_h2_id.toml > "%DIR%\test_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD TEST_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_15 %DATE% %TIME% >> "%LOG%"
  exit /b 15
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/test_db_5k_id 2000 44 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD TEST_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_16 %DATE% %TIME% >> "%LOG%"
  exit /b 16
)
echo REBUILD TEST_OK %TIME% >> "%LOG%"

echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
