@echo off
REM =========================================================================================
REM FEATURES REBUILD -- DE-RISK STEP. 100 users from anki-revlogs-10k-id, both arms.
REM Andrew authorized the rebuild 2026-08-19. This is step 0: prove the pipeline on ~1% of
REM the cost before committing 2-4 days.
REM
REM CPU ONLY. It does not touch the GPU, so it runs beside the live rgate training. That is
REM the whole reason the features phase can start now.
REM
REM THE COMPARISON IS -id-vs--id, ARM OFF vs ARM ON. Comparing against the PUBLISHED db is
REM INVALID: `size` moves for ~30 percent of users from the dataset swap alone, so that check
REM would false-alarm on a third of them. ON-vs-OFF isolates the new derivations.
REM
REM Do NOT edit this file while it runs: cmd.exe re-reads a batch file from a saved byte
REM offset after every command returns.
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\features_rebuild
set LOG=%DIR%\derisk.log
set STAMP=%RANDOM%%RANDOM%
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=6

if not exist "%DIR%" mkdir "%DIR%"
echo ===== DERISK START %DATE% %TIME% ===== > "%LOG%"

REM ---- ARM OFF: the -id dataset with the new columns NOT emitted ----
REM RWKV_ID_FEATURES is explicitly CLEARED rather than merely left unset, so an inherited
REM value cannot silently make the control arm a treatment arm. That is exactly how the
REM rgate smoke produced a false green on 2026-08-18.
set RWKV_ID_FEATURES=
if exist "%DIR%\off_%STAMP%.log" del /q "%DIR%\off_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_derisk_off.toml > "%DIR%\off_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DERISK OFF_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_11 %DATE% %TIME% >> "%LOG%"
  exit /b 11
)
if not exist "F:\rwkv_lmdb\derisk_id_off\data.mdb" (
  echo DERISK OFF_NOARTIFACT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_12 %DATE% %TIME% >> "%LOG%"
  exit /b 12
)
echo DERISK OFF_OK %TIME% >> "%LOG%"

REM ---- ARM ON: the same dataset with the 21 real-timestamp columns emitted ----
set RWKV_ID_FEATURES=1
if exist "%DIR%\on_%STAMP%.log" del /q "%DIR%\on_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_derisk_on.toml > "%DIR%\on_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DERISK ON_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
if not exist "F:\rwkv_lmdb\derisk_id_on\data.mdb" (
  echo DERISK ON_NOARTIFACT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_14 %DATE% %TIME% >> "%LOG%"
  exit /b 14
)
REM The ON arm must actually have widened the vector. Without this the run could silently
REM produce a byte-identical db and the whole de-risk would pass vacuously.
findstr /C:"112" "%DIR%\on_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DERISK ON_WIDTH_NOT_112 %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_15 %DATE% %TIME% >> "%LOG%"
  exit /b 15
)
echo DERISK ON_OK %TIME% >> "%LOG%"

echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
