@echo off
REM =========================================================================================
REM Rebuild the PUBLISHED train db with the int64 id fix -- the FIXED CONTROL for the features
REM A/B. Andrew 2026-08-21: "Sure, re-run featA".
REM
REM Waits for the eval-db build to finish first, so the two CPU builds do not contend.
REM PROCESSES stays 6 (chunked format, bounded per-worker memory) but the champion deploy eval
REM runs on the GPU beside it, so nice_rebuild.ps1 should be running to keep this at BelowNormal.
REM
REM Do NOT edit this file while it runs. No angle brackets or arrows in REM lines.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\features_rebuild
set LOG=%DIR%\trainfix.log
set STAMP=%RANDOM%%RANDOM%
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=6
set RWKV_ID_FEATURES=

echo ===== TRAINFIX START %DATE% %TIME% ===== > "%LOG%"

:wait
findstr /B /C:"DONE_EXIT_0" "%DIR%\testfix.log" >nul 2>&1
if %ERRORLEVEL%==0 goto go
timeout /t 60 /nobreak >nul
goto wait

:go
echo eval-db build finished, starting train build %DATE% %TIME% >> "%LOG%"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_train_5k_h1_fix.toml > "%DIR%\trainfix_build_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo TRAINFIX BUILD_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py train_db_5k_h1_fix 100000 24 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo TRAINFIX DB_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_14 %DATE% %TIME% >> "%LOG%"
  exit /b 14
)
echo TRAINFIX BUILD_OK %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
