@echo off
REM =========================================================================================
REM THE FEATURES REBUILD, GENERATION 2 -- Andrew 2026-08-20: "we still have to do another
REM LMDB rebuild". Adds the two columns his coverage audit found designed-but-never-implemented:
REM   scaled_sibling_gap          his sibling feature, in the non-leaking PRECEDING-sibling form
REM   card_predates_first_review  his "probably not important, but we can try"
REM card_features 44 -- 46, model input 112 -- 114.
REM
REM   1. train_db_5k_h1_id3   users 1-5000
REM   2. test_db_5k_id3       users 5001-10000
REM
REM PHASE 0 IS DELIBERATELY ABSENT. label_filter_db_id selects WHICH reviews count, not what
REM they contain, so it is feature-INDEPENDENT and generation 1's copy is reused as-is. That is
REM stated in find_equalize_id.toml's own header. Rebuilding it would cost an hour for a
REM byte-identical result.
REM
REM CPU ONLY, so it runs beside the live featA training. That is the whole reason this fits:
REM featA reads the OLD 92-dim dbs and finishes around 01:45, and the _id dbs have no reader.
REM
REM DISK -- the gen-1 plan's "605 GB" was LOGICAL and overstated the real cost 2.5x. Measured
REM with GetCompressedFileSize, gen 1 actually allocates 115.8 GiB (train) + 115.9 (test). Gen 2
REM is built BESIDE gen 1 against 650.8 GiB free; gen 1 is deleted only after this verifies.
REM
REM RESUMABLE, AND THAT IS A TRAP AS WELL AS A FEATURE: data_processing skips users already
REM present, so a pre-existing db reports success in seconds having done nothing. Both phase
REM guards therefore check ENTRY COUNTS and COLUMN WIDTH, not that a file exists.
REM
REM Do NOT edit this file while it runs. No angle brackets or arrows in REM lines.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\features_rebuild
set LOG=%DIR%\rebuild3.log
set STAMP=%RANDOM%%RANDOM%
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=6
set WIDTH=46

if not exist "%DIR%" mkdir "%DIR%"
echo ===== FEATURES REBUILD GEN3 START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE 0: prove the flag really produces WIDTH columns before spending 4 hours ----
set RWKV_ID_FEATURES=1
.venv\Scripts\python.exe -c "import os,sys; sys.path.insert(0,os.getcwd()); import rwkv.id_features as f; w=f.card_feature_width(); print('card_feature_width', w, 'input_width', f.input_width()); sys.exit(0 if w==%WIDTH% else 44)" >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD3 WIDTH_MISMATCH %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"
  exit /b 44
)
echo REBUILD3 WIDTH_OK %TIME% >> "%LOG%"

REM ---- PHASE 1: the TRAIN db ----
if exist "%DIR%\train3_%STAMP%.log" del /q "%DIR%\train3_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_train_5k_h1_id3.toml > "%DIR%\train3_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD3 TRAIN_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/train_db_5k_h1_id3 100000 %WIDTH% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD3 TRAIN_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_14 %DATE% %TIME% >> "%LOG%"
  exit /b 14
)
echo REBUILD3 TRAIN_OK %TIME% >> "%LOG%"

REM ---- PHASE 2: the EVAL db ----
if exist "%DIR%\test3_%STAMP%.log" del /q "%DIR%\test3_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_test_5k_h2_id3.toml > "%DIR%\test3_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD3 TEST_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_15 %DATE% %TIME% >> "%LOG%"
  exit /b 15
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/test_db_5k_id3 2000 %WIDTH% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD3 TEST_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_16 %DATE% %TIME% >> "%LOG%"
  exit /b 16
)
echo REBUILD3 TEST_OK %TIME% >> "%LOG%"

echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
