@echo off
REM =========================================================================================
REM THE FEATURES REBUILD, GENERATION 4 -- Andrew 2026-09-01: "since we will almost certainly
REM adopt timestamp features, we need the fixes".
REM
REM Gen 3 was built 2026-08-24, two days BEFORE the nan_id_fill fix, so it still writes
REM ID_PLACEHOLDER + card_id through a float64 column and loses 37.2% of note identity on the
REM cards with missing metadata (measured on gen 3 itself: 39,599 cards, 24,707 placeholders).
REM Gen 4 is gen 3 plus that single fix.
REM
REM   1. train_db_5k_h1_id4   users 1-5000
REM   2. test_db_5k_id4       users 5001-10000
REM
REM PHASE 0 IS THREE GUARDS, NOT ONE, AND THE SECOND IS THE POINT OF THE BUILD:
REM   0a WIDTH   the flag really produces 46 columns before spending 4 hours
REM   0b BUG C   nan_id_fill is exact AND the guard can prove it would detect the bug
REM   0c TARGET  the configs really point at _id4, so a stale clone cannot overwrite gen 3
REM Bug C destroys VALUES, not shapes, so every banner and width check passes while it is
REM active. A build for a fix must assert the fix, or it cannot tell success from failure.
REM
REM AND THE ARTIFACT IS CHECKED, NOT JUST THE CODE. check_db_idfill.py reads the finished db
REM back. "The fix is live in code" and "this database was built with it" are different claims;
REM conflating them is what produced the featA2 number retracted on 2026-09-01.
REM
REM LABEL FILTER REUSED, not rebuilt -- it selects WHICH reviews count, not what they contain.
REM
REM ⚠ BUILT BESIDE GEN 3, NEVER OVER IT. train_db_5k_h1_id3 is featB's live database. Nothing
REM here deletes anything; gen 3 goes only on Andrew's say-so.
REM
REM Do NOT edit this file while it runs -- cmd.exe re-reads batch files from a byte offset.
REM No angle brackets or arrows in REM lines: cmd parses redirection before it honours REM.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\features_rebuild
set LOG=%DIR%\rebuild4.log
set STAMP=%RANDOM%%RANDOM%
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=6
set WIDTH=46
set RWKV_ID_FEATURES=1
REM Must stay CLEARED: the published end-to-start formula subtracts the wrong review's duration
REM on an -id frame. data_processing asserts against it, but clear it rather than rely on that.
set RWKV_E2S_PUBLISHED=

if not exist "%DIR%" mkdir "%DIR%"
echo ===== FEATURES REBUILD GEN4 START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE 0: everything the chain ASSUMES, checked before spending ~7 hours ----
REM Targets must not already exist (data_processing and find_equalize SKIP users already
REM present, so a pre-existing store reports success in seconds having done nothing); gen 3 must
REM still be there for phase 3 and because featB is scored against it; the -id dataset must be
REM readable; and F: must have the space, measured by FREE SPACE because these stores are sparse
REM and file length reports the map_size reservation instead of the allocation.
.venv\Scripts\python.exe scratchpad/features_rebuild/preflight_gen4.py >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 PREFLIGHT_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_50 %DATE% %TIME% >> "%LOG%"
  exit /b 50
)
echo REBUILD4 PREFLIGHT_OK %TIME% >> "%LOG%"

REM ---- PHASE 0a: the flag really produces WIDTH columns ----
.venv\Scripts\python.exe -c "import os,sys; sys.path.insert(0,os.getcwd()); import rwkv.id_features as f; w=f.card_feature_width(); print('card_feature_width', w, 'input_width', f.input_width()); sys.exit(0 if w==%WIDTH% else 44)" >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 WIDTH_MISMATCH %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"
  exit /b 44
)
echo REBUILD4 WIDTH_OK %TIME% >> "%LOG%"

REM ---- PHASE 0b: the Bug C fix is LIVE, and the guard could tell if it were not ----
.venv\Scripts\python.exe scratchpad/features_rebuild/assert_bugc_fixed.py >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 BUGC_NOT_LIVE %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_45 %DATE% %TIME% >> "%LOG%"
  exit /b 45
)
echo REBUILD4 BUGC_GUARD_OK %TIME% >> "%LOG%"

REM ---- PHASE 0c: the configs point at _id4, so a stale clone cannot overwrite featB's gen 3 ----
findstr /C:"train_db_5k_h1_id4" rwkv\data_processing_train_5k_h1_id4.toml >nul
if not %ERRORLEVEL%==0 (
  echo REBUILD4 TRAIN_TARGET_WRONG %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_49 %DATE% %TIME% >> "%LOG%"
  exit /b 49
)
findstr /C:"test_db_5k_id4" rwkv\data_processing_test_5k_h2_id4.toml >nul
if not %ERRORLEVEL%==0 (
  echo REBUILD4 TEST_TARGET_WRONG %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_49 %DATE% %TIME% >> "%LOG%"
  exit /b 49
)
echo REBUILD4 TARGETS_OK %TIME% >> "%LOG%"

REM ---- PHASE 0d: the END-TO-START LABEL FILTER, which gen 4 is built against ----
REM Andrew 2026-09-01: "We should have delta_t > 0 though, to make our methodology closer to
REM that of srs-benchmark." We already HAD delta_t 0 -- it comes from create_features. What was
REM missing is that find_equalize read the parquet directly and never applied the interval
REM correction, so the filter was evaluated on END-TO-END gaps while training and eval use
REM end-to-start. With SECS=true that filter is not interval-independent.
REM
REM It must run BEFORE the dbs, because label_is_equalize is BAKED INTO the LMDB at build time.
REM Adopting it later would cost a second 4 h rebuild, which is the whole reason it is here.
REM Resumable: find_equalize skips users already present, so a re-run is cheap.
if exist "%DIR%\lf4_%STAMP%.log" del /q "%DIR%\lf4_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.find_equalize_test_reviews --config rwkv/find_equalize_id_e2s.toml > "%DIR%\lf4_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 LABELFILTER_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_17 %DATE% %TIME% >> "%LOG%"
  exit /b 17
)
echo REBUILD4 LABELFILTER_OK %TIME% >> "%LOG%"

REM ---- PHASE 1: the TRAIN db ----
if exist "%DIR%\train4_%STAMP%.log" del /q "%DIR%\train4_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_train_5k_h1_id4.toml > "%DIR%\train4_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 TRAIN_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_13 %DATE% %TIME% >> "%LOG%"
  exit /b 13
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/train_db_5k_h1_id4 100000 %WIDTH% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 TRAIN_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_14 %DATE% %TIME% >> "%LOG%"
  exit /b 14
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db_idfill.py F:/rwkv_lmdb/train_db_5k_h1_id4 400000000000 1 20 53 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 TRAIN_BUGC_IN_ARTIFACT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_47 %DATE% %TIME% >> "%LOG%"
  exit /b 47
)
echo REBUILD4 TRAIN_OK %TIME% >> "%LOG%"

REM ---- PHASE 2: the EVAL db ----
if exist "%DIR%\test4_%STAMP%.log" del /q "%DIR%\test4_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.data_processing --config rwkv/data_processing_test_5k_h2_id4.toml > "%DIR%\test4_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 TEST_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_15 %DATE% %TIME% >> "%LOG%"
  exit /b 15
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/test_db_5k_id4 2000 %WIDTH% >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 TEST_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_16 %DATE% %TIME% >> "%LOG%"
  exit /b 16
)
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db_idfill.py F:/rwkv_lmdb/test_db_5k_id4 250000000000 5001 20 53 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo REBUILD4 TEST_BUGC_IN_ARTIFACT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_47 %DATE% %TIME% >> "%LOG%"
  exit /b 47
)
echo REBUILD4 TEST_OK %TIME% >> "%LOG%"

REM ---- PHASE 3: gen 4 must score a DIFFERENT set from gen 3, and that expectation is INVERTED ----
REM ⚠ THIS CHECK MEANT THE OPPOSITE ONE HOUR AGO. When gen 4 was going to reuse
REM label_filter_db_id, identical counts were REQUIRED and a difference was a build bug. Adding
REM phase 0d flipped it: gen 4 now scores an end-to-start-selected set, so it MUST differ from
REM gen 3 by roughly 0.19%. A guard whose meaning depends on a config decision has to be revisited
REM whenever that decision moves -- exactly the stale-guard failure that rejected iter 54's decay
REM and nearly rejected decayshape's.
REM
REM So the informative outcome here is exit 1 (they differ). Exit 0 would mean the NEW label
REM filter did not take effect and the point of phase 0d was silently missed.
.venv\Scripts\python.exe scratchpad/features_rebuild/compare_equalize.py F:/rwkv_lmdb/test_db_5k_id3 250000000000 F:/rwkv_lmdb/test_db_5k_id4 250000000000 5001 20 53 >> "%LOG%" 2>&1
if %ERRORLEVEL%==1 (
  echo REBUILD4 EQUALIZE_DIFFERS_FROM_GEN3 -- EXPECTED, the e2s label filter took effect %TIME% >> "%LOG%"
) else (
  echo REBUILD4 EQUALIZE_IDENTICAL_TO_GEN3 -- SUSPICIOUS, did phase 0d take effect? %DATE% %TIME% >> "%LOG%"
)

REM Terminal marker BEFORE endlocal: endlocal restores the pre-setlocal environment, so %LOG%
REM would expand to empty and the marker would be appended to "" instead.
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
