"""Generate scratchpad/iter52_kdalpha/run_iter52.cmd from iter 45's runner.

Generated rather than hand-written so the ~30-line env block is copied byte-for-byte from the
champion's own runner: iter 52 is a SINGLE-VARIABLE change (decay KD alpha 0.5 -> 0.9) and a
transcription slip in the env would silently make it something else. The asserts at the bottom
check the things that would be invisible in a diff -- no QAT env leaking into a plain iteration,
exactly one alpha setting, the d=128 teacher dump, and no redirection characters in REM lines
(cmd.exe parses those BEFORE it honours REM, which cost a dead launch on 2026-08-14).
"""
import io
import re

BS = chr(92)
SRC = "scratchpad/iter45_kddecay/run_iter45.cmd"
DST = "scratchpad/iter52_kdalpha/run_iter52.cmd"

s = io.open(SRC, encoding="utf-8", newline="").read()
env = s[s.index("cd /d C:"): s.index("set RWKV_MUON_BATCHED=1")]
env = re.sub(r"^set (LOG|DIR|STAMP|SRCREL|SRC)=.*\r?\n", "", env, flags=re.M)
env = re.sub(r"^echo =====.*\r?\n", "", env, flags=re.M)
env = re.sub(r"^set RWKV_GRAD_STATS=.*\r?\n", "", env, flags=re.M)
# iter 45's block opens its OWN `setlocal` and defines a WS-phase budget knob. HEADER already
# opens one, and this run has no WS phase -- two levels would leave the outer popped only at
# process exit, and a live-looking MAXSTEPS would read as a lever this runner does not have.
# Normalise line endings first: the source is read with newline="" so it carries \r\n, and a
# regex written for \n silently matches nothing (which is exactly what happened first try).
env = env.replace("\r\n", "\n")
env = re.sub(r"^setlocal\n", "", env, flags=re.M)
env = re.sub(r"^REM ---- BUDGET.*\n", "", env, flags=re.M)
env = re.sub(r"^set MAXSTEPS=.*\n", "", env, flags=re.M)

HEADER = [
 "@echo off",
 "REM ===========================================================================================",
 "REM ITER 52: KD ALPHA IN THE DECAY PHASE, 0.5 to 0.9.  Family: distillation (4/5, the only",
 "REM family with a real hit rate). First of the 10 algorithmic iterations Andrew asked for",
 "REM on 2026-08-17.",
 "REM",
 "REM THE LEVER IS ONE NUMBER AND ZERO CODE. Iter 45 became champion because its runner did not",
 "REM clear RWKV_KD_ALPHA before decay, leaving decay at 0.5 while WS ran the tuned 0.9. That",
 "REM value was never CHOSEN -- iter 45's own notes flag alpha_decay 0.9 and 0.25 as open",
 "REM in-family and cheap. Iter 45's finding points at 0.9: teacher signal paid in BOTH phases,",
 "REM so the anneal-onto-the-true-objective intuition is wrong here and matching WS is the",
 "REM simpler hypothesis.",
 "REM",
 "REM DECAY-ONLY, SO WS IS SKIPPED AND THIS COSTS ABOUT 3.5 h NOT 5.5 h. The lever cannot touch",
 "REM WS, so warm-starting from the champion's own i45_ws_10935 is EXACT rather than an",
 "REM approximation -- the same checkpoint the QAT arms warm-start from. Outputs land beside it,",
 "REM following that precedent.",
 "REM",
 "REM GATE: PLAIN basis vs iter 45 == 0.297697 ahead / 0.265375 imm on the VAL half. Both-modes",
 "REM rule: KD alpha feeds the curve AND the rating targets, so the curve-side exception does NOT",
 "REM apply. Params unchanged at 558,212 -- a training-only change ships nothing to Rust.",
 "REM",
 "REM PHASE 0 IS THE ITER-48 GUARD. srs_model.py and srs_model_rnn.py were touched on 2026-08-16",
 "REM (card_features_dim derived instead of hardcoded twice), and a PLAIN eval is the only path",
 "REM that SCRIPTS the model -- so a TorchScript runtime break is invisible to training and to",
 "REM QAT evals, and would surface only after the decay phase. 90 s to rule out.",
 "REM",
 "REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not a",
 "REM safe undo, because line endings shift the byte offset cmd.exe resumes from).",
 "REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.",
 "REM ===========================================================================================",
 "setlocal",
]

BODY = [
 "",
 "set TAG=iter52_kdalpha",
 "set DIR=C:" + BS + "Users" + BS + "Andrew" + BS + "rwkv-anki-autoresearch" + BS + "scratchpad" + BS + "iter52_kdalpha",
 "set SRCREL=scratchpad/iter45_kddecay",
 "set SRC=C:" + BS + "Users" + BS + "Andrew" + BS + "rwkv-anki-autoresearch" + BS + "scratchpad" + BS + "iter45_kddecay",
 "set LOG=%DIR%" + BS + "iter52.log",
 "set STAMP=%RANDOM%%RANDOM%",
 "set WSSTEPS=10935",
 "set RWKV_GRAD_STATS=%DIR%" + BS + "grad_stats.json",
 # Cleared EXPLICITLY, not assumed: the runner inherits the launching environment, and the
 # features flag changes the model input width 92 -> 112. Leaking in would make the model
 # disagree with the LMDB rather than fail loudly. Same discipline as the speed-stack vars.
 "set RWKV_ID_FEATURES=",
 # Likewise: a WS-phase step cap inherited from the environment would silently truncate the
 # decay phase, and the run would still exit 0.
 "set RWKV_MAX_STEPS=",
 "",
 'echo ===== ITER 52 (KD alpha_decay 0.5 to 0.9) START %DATE% %TIME% ===== >> "%LOG%"',
 "",
 "REM ================= PHASE 0: the scripted-eval guard (iter 48's lesson) =================",
 # ABSOLUTE path to bash: a WMI-detached cmd.exe gets the SYSTEM environment, whose PATH need
 # not contain Git's bash even though an interactive shell's does.
 '"C:' + BS + 'Program Files' + BS + 'Git' + BS + 'usr' + BS + 'bin' + BS + 'bash.exe" '
 'scratchpad/parity3/smoke_scripted_eval.sh > "%DIR%' + BS + 'smoke_%STAMP%.log" 2>&1',
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 SCRIPTED_EVAL_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_45 >> "%LOG%"',
 "  endlocal & exit /b 45",
 ")",
 'echo ITER52 SMOKE_OK %TIME% >> "%LOG%"',
 "",
 "REM ============ PHASE A: decay from the champion's WS-final, KD alpha 0.9 ============",
 "set RWKV_MUON_BATCHED=1",
 "set RWKV_NO_JIT=1",
 "set RWKV_QAT_COMPILE=1",
 "set RWKV_KD_MIX=%DUMP%:%WSSTEPS%",
 "set RWKV_KD_ALPHA=0.9",
 ".venv" + BS + "Scripts" + BS + "python.exe scratchpad/write_decay_setup.py %SRCREL% i45_ws i52_d "
 '%DIR%' + BS + 'i52_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%' + BS + 'dsetup_%STAMP%.log" 2>&1',
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_22 >> "%LOG%"',
 "  endlocal & exit /b 22",
 ")",
 'findstr /C:"i45_ws_%WSSTEPS%" "%DIR%' + BS + 'dsetup_%STAMP%.log" >nul',
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 WRONGCKPT %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_32 >> "%LOG%"',
 "  endlocal & exit /b 32",
 ")",
 ".venv" + BS + "Scripts" + BS + "python.exe -u -m rwkv.train_rwkv --config %DIR%" + BS
 + 'i52_decay.toml > "%DIR%' + BS + 'decay_%STAMP%.log" 2>&1',
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_23 >> "%LOG%"',
 "  endlocal & exit /b 23",
 ")",
 "REM The experiment's own guards: KD must be ON and at the RIGHT alpha. Without these the run",
 "REM silently reduces to iter 45 and would be recorded as a null.",
 'findstr /C:"[kd-mix] KD ON" "%DIR%' + BS + 'decay_%STAMP%.log" >nul',
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 NOKD_DECAY %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_35 >> "%LOG%"',
 "  endlocal & exit /b 35",
 ")",
 'findstr /C:"alpha FIXED at 0.9" "%DIR%' + BS + 'decay_%STAMP%.log" >nul',
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 WRONGALPHA_DECAY %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_36 >> "%LOG%"',
 "  endlocal & exit /b 36",
 ")",
 'if not exist "%SRC%' + BS + 'i52_d_%WSSTEPS%.pth" (',
 '  echo ITER52 NOCKPT %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_31 >> "%LOG%"',
 "  endlocal & exit /b 31",
 ")",
 'echo ITER52 DECAY_OK KD ON alpha 0.9 %TIME% >> "%LOG%"',
 "",
 "REM ================= PHASE B: rectified VAL-half eval =================",
 ".venv" + BS + "Scripts" + BS + "python.exe scratchpad/write_eval_toml.py %SRCREL% i52_d "
 "%DIR%" + BS + 'i52_eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 7500 > "%DIR%' + BS + 'etoml_%STAMP%.log" 2>&1',
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_24 >> "%LOG%"',
 "  endlocal & exit /b 24",
 ")",
 "set RWKV_MUON_BATCHED=",
 "set RWKV_NO_JIT=",
 "set RWKV_QAT_COMPILE=",
 "set RWKV_KD_MIX=",
 "set RWKV_KD_ALPHA=",
 "set RWKV_GRAD_STATS=",
 "set RWKV_EVAL_PAVA=1",
 "del /q scratchpad" + BS + "eval_shards" + BS + "shard_*.log 2>nul",
 ".venv" + BS + "Scripts" + BS + "python.exe -u optimization/eval_sharded.py --config %DIR%" + BS
 + 'i52_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%'
 + BS + 'eval1_%STAMP%.log" 2>&1',
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 EVAL attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"',
 "  .venv" + BS + "Scripts" + BS + "python.exe -u optimization/eval_sharded.py --config %DIR%" + BS
 + 'i52_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%'
 + BS + 'eval2_%STAMP%.log" 2>&1',
 ")",
 "if not %ERRORLEVEL%==0 (",
 '  echo ITER52 EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
 '  echo DONE_EXIT_25 >> "%LOG%"',
 "  endlocal & exit /b 25",
 ")",
 'echo ITER52 EVAL_OK %TIME% >> "%LOG%"',
 'echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"',
 "endlocal & exit /b 0",
]

out = "\n".join(HEADER) + "\n" + env.rstrip() + "\n" + "\n".join(BODY) + "\n"

low = out.lower()
assert "rwkv_qat_lowrank_scope" not in low, "QAT env leaked into a PLAIN iteration"
assert "rwkv_qat_pq" not in low, "QAT env leaked into a PLAIN iteration"
assert out.count("set RWKV_KD_ALPHA=0.9") == 1, "alpha not set exactly once"
assert "set DUMP=C:" + BS + "rwkv_kd_dump" + BS + "t128_seedpair_65k" in out, "d=128 dump missing"
assert "set RWKV_AUGMENT_SEED=4321" in out, "champion seed missing"
assert "architecture_d80_lora4_cnd.py" in out, "champion arch missing"
assert "set RWKV_INTERLEAVE=1" in out, "interleave missing"
assert "set RWKV_ID_FEATURES=" + chr(10) in out, "features flag not explicitly cleared"
assert "bash.exe" in out, "absolute bash path missing"
assert out.count("setlocal" + chr(10)) == 1, "more than one setlocal"
assert "set RWKV_MAX_STEPS=" + chr(10) in out, "step cap not cleared"
assert "MAXSTEPS" not in out, "dead WS budget knob left in"
for ln in out.split("\n"):
    if ln.strip().upper().startswith("REM"):
        bad = [c for c in "<>&|^" if c in ln]
        assert not bad, "redirection char " + str(bad) + " in REM line: " + ln
io.open(DST, "w", encoding="ascii", newline="\r\n").write(out)
print("wrote", DST, len(out), "bytes,", out.count(chr(10)), "lines")
