@echo off
REM ===========================================================================================
REM ITER 52: KD ALPHA IN THE DECAY PHASE, 0.5 to 0.9.  Family: distillation (4/5, the only
REM family with a real hit rate). First of the 10 algorithmic iterations Andrew asked for
REM on 2026-08-17.
REM
REM THE LEVER IS ONE NUMBER AND ZERO CODE. Iter 45 became champion because its runner did not
REM clear RWKV_KD_ALPHA before decay, leaving decay at 0.5 while WS ran the tuned 0.9. That
REM value was never CHOSEN -- iter 45's own notes flag alpha_decay 0.9 and 0.25 as open
REM in-family and cheap. Iter 45's finding points at 0.9: teacher signal paid in BOTH phases,
REM so the anneal-onto-the-true-objective intuition is wrong here and matching WS is the
REM simpler hypothesis.
REM
REM DECAY-ONLY, SO WS IS SKIPPED AND THIS COSTS ABOUT 3.5 h NOT 5.5 h. The lever cannot touch
REM WS, so warm-starting from the champion's own i45_ws_10935 is EXACT rather than an
REM approximation -- the same checkpoint the QAT arms warm-start from. Outputs land beside it,
REM following that precedent.
REM
REM GATE: PLAIN basis vs iter 45 == 0.297697 ahead / 0.265375 imm on the VAL half. Both-modes
REM rule: KD alpha feeds the curve AND the rating targets, so the curve-side exception does NOT
REM apply. Params unchanged at 558,212 -- a training-only change ships nothing to Rust.
REM
REM PHASE 0 IS THE ITER-48 GUARD. srs_model.py and srs_model_rnn.py were touched on 2026-08-16
REM (card_features_dim derived instead of hardcoded twice), and a PLAIN eval is the only path
REM that SCRIPTS the model -- so a TorchScript runtime break is invisible to training and to
REM QAT evals, and would surface only after the decay phase. 90 s to rule out.
REM
REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not a
REM safe undo, because line endings shift the byte offset cmd.exe resumes from).
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935


set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5

set TAG=iter52_kdalpha
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter52_kdalpha
set SRCREL=scratchpad/iter45_kddecay
set SRC=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter45_kddecay
set LOG=%DIR%\iter52.log
set STAMP=%RANDOM%%RANDOM%
set WSSTEPS=10935
set RWKV_GRAD_STATS=%DIR%\grad_stats.json
set RWKV_ID_FEATURES=
set RWKV_MAX_STEPS=

echo ===== ITER 52 (KD alpha_decay 0.5 to 0.9) START %DATE% %TIME% ===== >> "%LOG%"

REM ================= PHASE 0: the scripted-eval guard (iter 48's lesson) =================
"C:\Program Files\Git\bin\bash.exe" scratchpad/parity3/smoke_scripted_eval.sh scratchpad/iter45_kddecay/i45_eval.toml > "%DIR%\smoke_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER52 SCRIPTED_EVAL_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_45 >> "%LOG%"
  endlocal & exit /b 45
)
echo ITER52 SMOKE_OK %TIME% >> "%LOG%"

REM ============ PHASE A: decay from the champion's WS-final, KD alpha 0.9 ============
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.9
.venv\Scripts\python.exe scratchpad/write_decay_setup.py %SRCREL% i45_ws i52_d %DIR%\i52_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER52 DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_22 >> "%LOG%"
  endlocal & exit /b 22
)
findstr /C:"i45_ws_%WSSTEPS%" "%DIR%\dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ITER52 WRONGCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_32 >> "%LOG%"
  endlocal & exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\i52_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER52 DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_23 >> "%LOG%"
  endlocal & exit /b 23
)
REM The experiment's own guards: KD must be ON and at the RIGHT alpha. Without these the run
REM silently reduces to iter 45 and would be recorded as a null.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ITER52 NOKD_DECAY %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_35 >> "%LOG%"
  endlocal & exit /b 35
)
findstr /C:"alpha FIXED at 0.9" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ITER52 WRONGALPHA_DECAY %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_36 >> "%LOG%"
  endlocal & exit /b 36
)
if not exist "%SRC%\i52_d_%WSSTEPS%.pth" (
  echo ITER52 NOCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_31 >> "%LOG%"
  endlocal & exit /b 31
)
echo ITER52 DECAY_OK KD ON alpha 0.9 %TIME% >> "%LOG%"

REM ================= PHASE B: rectified VAL-half eval =================
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %SRCREL% i52_d %DIR%\i52_eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER52 TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_24 >> "%LOG%"
  endlocal & exit /b 24
)
set RWKV_MUON_BATCHED=
set RWKV_NO_JIT=
set RWKV_QAT_COMPILE=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_GRAD_STATS=
set RWKV_EVAL_PAVA=1
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\i52_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER52 EVAL attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\i52_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo ITER52 EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 >> "%LOG%"
  endlocal & exit /b 25
)
echo ITER52 EVAL_OK %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
