@echo off
REM sam -- DECAY-ONLY runner generated by scratchpad/sam/mk_sam.py from the realcyc runner. DO NOT HAND-EDIT.
REM ======================================================================================
REM REALCYC -- TREATMENT: gen4base's recipe, byte-identical except the db paths and one flag,
REM on the GENERATION 5 dbs. RWKV_REAL_CYCLES=1 replaces the 28 pseudo day-offset cycle dims
REM with 24 real-time cycle columns and drops the pseudo day_of_week column (input 114 to 109,
REM params 565,252 to 563,652). Andrew 2026-09-02: "use real features for 3 days/week/month/
REM year/decade/century, so that every pseudo feature is replaced with its real counterpart";
REM "11 is also a pseudo-calendar feature, so make sure it also gets replaced."
REM
REM CONTROL = gen4base. Same label filter (label_filter_db_id_e2s), so the pair is SIZE-GATED
REM and single-variable. KD OFF in both -- the d=128 teacher cannot forward the -id layouts
REM (teacher-114 screen). realcyc minus gen4base is the number that means something.
REM
REM THE PARAM GUARD IS THE FLAG GUARD: 563,652 is what train_rwkv reports when RWKV_REAL_CYCLES
REM reached the workers; 565,252 means it did not and the run is gen4base under another name.
REM
REM Generated from run_gen4base.cmd by transform with output assertions; the cloned FEATB
REM strings in that file were NOT carried over. Do NOT edit while running.
REM ======================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\sam
set LOG=%DIR%\sam.log
set STAMP=%RANDOM%%RANDOM%
set TAG=sam
set STEPS=10935

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_MUON_INCLUDE_LORA=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1

REM ---- what distinguishes this arm: the -id layout AND the real-time cycles ----
set RWKV_ID_FEATURES=1
set RWKV_REAL_CYCLES=1
set RWKV_ZERO_FEATURES=
REM db overrides consumed by write_decay_setup.py / write_eval_toml.py, which used to
REM hardcode the 92-dim paths -- the trap the idfeat diagnostic caught.
set RWKV_VAL_DB=F:/rwkv_lmdb/test_db_5k_id5
set RWKV_EVAL_DB=F:/rwkv_lmdb/test_db_5k_id5
set RWKV_LABEL_FILTER_DB=F:/rwkv_lmdb/label_filter_db_id_e2s
REM KD explicitly CLEARED, never merely unset, so an inherited value cannot turn the
REM control into a treatment -- the false-green shape that bit the rgate smoke.
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
REM ---- THE LEVER (sam, ADOPTED: Foret et al. 2021, arXiv 2010.01412): Sharpness-Aware Minimization on
REM the DECAY phase only, rho 0.05 every step. Screen 2026-09-04: L(w+rho g/||g||)-L(w) median +0.023 on
REM realcyc (sharp). The optimizer is untouched; only the gradient it consumes changes. 2x decay cost.
set RWKV_SAM_RHO=0.05
set RWKV_SAM_EVERY=1

if not exist "%DIR%" mkdir "%DIR%"
echo ===== sam START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE A: NONE. Decay-only SAM: warm-start from the base's WS-final checkpoint ----
if not exist "scratchpad\realcyc\rc_ws_%STEPS%.pth" (
  echo %TAG% BASE_WS_MISSING %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_21 %DATE% %TIME% >> "%LOG%"
  exit /b 21
)

REM ---- PHASE B: decay, ratio 1.0 ----
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/realcyc rc_ws sam_d %DIR%\decay.toml F:/rwkv_lmdb/train_db_5k_h1_id5 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% DSETUP_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_22 %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
findstr /C:"rc_ws_%STEPS%" "%DIR%\dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% WRONGCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_32 %DATE% %TIME% >> "%LOG%"
  exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% DECAY_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_23 %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
REM KD must be ABSENT here -- the opposite of every recent runner's guard.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if %ERRORLEVEL%==0 (
  echo %TAG% KD_LEAKED_IN %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_43 %DATE% %TIME% >> "%LOG%"
  exit /b 43
)
if not exist "scratchpad\realcyc\sam_d_%STEPS%.pth" (
  echo %TAG% DECAY_SHORT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_28 %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
REM SAM must have RUN, not merely been configured: both banners are written by the training process.
findstr /C:"[sam] Sharpness-Aware Minimization ON: rho=0.05" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% SAM_NOT_ON %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"
  exit /b 44
)
findstr /C:"[sam] first pass: weights restored bit-exactly" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% SAM_NEVER_RAN %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_45 %DATE% %TIME% >> "%LOG%"
  exit /b 45
)
echo %TAG% DECAY_OK %TIME% >> "%LOG%"

REM ---- PHASE C: rectified VAL-half eval, users 5001-7500 ----
set RWKV_EVAL_PAVA=1
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/realcyc sam_d %DIR%\eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% ETOML_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_24 %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
REM The eval toml must point at THIS arm's db, or the arm silently scores on the
REM other arm's feature width. This is trap #2 made into a guard.
findstr /C:"F:/rwkv_lmdb/test_db_5k_id5" "%DIR%\eval.toml" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% EVAL_DB_MISMATCH %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_34 %DATE% %TIME% >> "%LOG%"
  exit /b 34
)
if exist "result\RWKV-%TAG%.jsonl" del /q "result\RWKV-%TAG%.jsonl"
if exist "result\RWKV-P-%TAG%.jsonl" del /q "result\RWKV-P-%TAG%.jsonl"
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\eval.toml --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% EVAL_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo %TAG% EVAL_OK %TIME% >> "%LOG%"

REM Terminal marker BEFORE endlocal: endlocal restores the pre-setlocal environment,
REM so %LOG% would expand to empty and the marker would go to "".
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0