@echo off
REM Leak-free decay-length pair behind w10lf: dry lfd3, dry lfd1, then lfd3, then lfd1.
REM Generated by scratchpad/w10lf/mk_wait_lf_decaylen.py -- read its docstring for the gate logic.
REM Displace it by stopping THIS waiter's cmd FIRST, then its children, while it loops in gate 0.
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set R=C:\Users\Andrew\rwkv-anki-autoresearch
set WLOG=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\lfd3\wait_lfdecay.log
set PREV=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\w10lf\wait_lf2.log
echo ===== leak-free decay-length waiter armed on the w10lf waiter %DATE% %TIME% ===== >> "%WLOG%"

:waitprev
if not exist "%PREV%" goto sleepprev
findstr /B /C:"DONE_EXIT_" "%PREV%" >nul 2>&1
if errorlevel 1 goto sleepprev
goto gotprev
:sleepprev
ping -n 61 127.0.0.1 >nul
goto waitprev

:gotprev
findstr /B /C:"DONE_EXIT_150 " "%PREV%" >nul 2>&1
if not errorlevel 1 (
  echo arm 2 eval FAILED upstream per the w10lf waiter -- the GPU is kept for its resume %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_160 %DATE% %TIME% >> "%WLOG%"
  exit /b 160
)
findstr /B /C:"DONE_EXIT_0 " "%PREV%" >nul 2>&1
if errorlevel 1 (
  echo w10lf never ran -- its waiter refused; this pair has no base, a human must look %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_161 %DATE% %TIME% >> "%WLOG%"
  exit /b 161
)
findstr /B /C:"DONE_EXIT_0 " "%R%\scratchpad\w10lf\w10lf.log" >nul 2>&1
if errorlevel 1 goto nobase
if not exist "%R%\scratchpad\w10lf\w10lf_ws_109350.pth" goto nobase
if not exist "%R%\scratchpad\w10lf\w10lf_d_21870.pth" goto nobase
goto preflight
:nobase
echo w10lf did not finish cleanly -- no success line or a final checkpoint missing; a human must look %DATE% %TIME% >> "%WLOG%"
echo DONE_EXIT_162 %DATE% %TIME% >> "%WLOG%"
exit /b 162

:preflight
.venv\Scripts\python.exe scratchpad/preflight_runner.py scratchpad/lfd3/run_lfd3.cmd scratchpad/lfd1/run_lfd1.cmd scratchpad/lfd3dry/run_lfd3dry.cmd scratchpad/lfd1dry/run_lfd1dry.cmd >> "%WLOG%" 2>&1
if errorlevel 1 (
  echo preflight FAILED on the decay-length runners -- not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_163 %DATE% %TIME% >> "%WLOG%"
  exit /b 163
)
echo w10lf done and preflight clean -- 120 s for its workers, then the two dry runs %DATE% %TIME% >> "%WLOG%"
ping -n 121 127.0.0.1 >nul

call %R%\scratchpad\lfd3dry\run_lfd3dry.cmd
findstr /B /C:"DONE_EXIT_0 " "%R%\scratchpad\lfd3dry\lfd3dry.log" >nul 2>&1
if errorlevel 1 (
  echo lfd3 dry run ended WITHOUT success -- not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_164 %DATE% %TIME% >> "%WLOG%"
  exit /b 164
)
findstr /C:"Traceback" /C:"Exception caught" "%R%\scratchpad\lfd3dry\decay_*.log" >nul 2>&1
if not errorlevel 1 (
  echo lfd3 dry decay swallowed an exception -- a HOLLOW run, not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_165 %DATE% %TIME% >> "%WLOG%"
  exit /b 165
)
if not exist "%R%\result\RWKV-P-lfd3dry.jsonl" (
  echo lfd3 dry eval produced no result file %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_166 %DATE% %TIME% >> "%WLOG%"
  exit /b 166
)

call %R%\scratchpad\lfd1dry\run_lfd1dry.cmd
findstr /B /C:"DONE_EXIT_0 " "%R%\scratchpad\lfd1dry\lfd1dry.log" >nul 2>&1
if errorlevel 1 (
  echo lfd1 dry run ended WITHOUT success -- not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_167 %DATE% %TIME% >> "%WLOG%"
  exit /b 167
)
findstr /C:"Traceback" /C:"Exception caught" "%R%\scratchpad\lfd1dry\decay_*.log" >nul 2>&1
if not errorlevel 1 (
  echo lfd1 dry decay swallowed an exception -- a HOLLOW run, not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_168 %DATE% %TIME% >> "%WLOG%"
  exit /b 168
)
if not exist "%R%\result\RWKV-P-lfd1dry.jsonl" (
  echo lfd1 dry eval produced no result file %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_169 %DATE% %TIME% >> "%WLOG%"
  exit /b 169
)

echo both dry runs clean -- launching lfd3 %DATE% %TIME% >> "%WLOG%"
call %R%\scratchpad\lfd3\run_lfd3.cmd
echo run_lfd3.cmd returned %ERRORLEVEL% -- launching lfd1 %DATE% %TIME% >> "%WLOG%"
call %R%\scratchpad\lfd1\run_lfd1.cmd
echo run_lfd1.cmd returned %ERRORLEVEL% %DATE% %TIME% >> "%WLOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%WLOG%"
endlocal & exit /b 0
