"""Generate run_w10qatkd.cmd: ARM 2 + DISTILLATION FROM THE FULL-PRECISION TWIN (Andrew 2026-09-10).

Andrew, asked whether to put QAT-with-distillation on the list: "Yep, do KD".

THE ARM. Exactly arm 2 (ws10's WS-final -> the same 2-epoch QAT decay, both catalogs learnable,
evaluated quant-aware with the LEARNED catalogs) plus ONE change: RWKV_QAT_KD=1.0 with the teacher
RWKV_QAT_KD_TEACHER = arm 1's decayed final (scratchpad/ws10/w10p_d_21870.pth) -- the same model,
same WS, same decay batches, full precision. So w10qatkd - w10qat is what KD does to the QAT tax,
single variable, and the teacher is the model the quantized student is trying to be.

WHY THE LIVE TEACHER (RWKV_QAT_KD) AND NOT A DUMP (RWKV_KD_MIX). The live teacher forwards the SAME
prepared batch in the same step, so batch alignment holds by construction; a dump is aligned only
by a labels checksum, which this repo has twice watched pass on misaligned inputs. Cost: one bf16
no-grad forward per step, ~10% on a QAT step.
lambda = 1.0: the term is ADDITIVE (hard + lambda*soft), which for CE/BCE (linear in the target) is
the target mix alpha = lambda/(1+lambda) = 0.5 at an overall loss scale of 2 -- the established decay
KD strength (iter 45), and the loss scale is immaterial to Muon's normalised steps and Adam's.

⚠ THE LIVE PATH HAD A BUG AND IT IS FIXED FIRST (rwkv/train_rwkv.py, qat_kd_targets). It predates the
GRU head and built the teacher's CURVE target with the plain forgetting_curve(w, t), while the
student's own curve is gru_forgetting_curve(w, s, d, t). scratchpad/qatkd/smoke_qatkd.py proves the
fix: with teacher == student the KD gradient is 2.9e-07 of the hard-loss gradient (it vanishes, as it
must), and the old formula's is 0.79 -- the old code would have pulled the curve head toward a curve
no model computes, with ~79% of the whole task gradient's strength. It also proves the teacher is
full precision: the stripped QAT-env teacher gives targets IDENTICAL (0.0e+00) to the plain model,
while the unstripped one differs by up to 1.08.

Usage: python scratchpad/w10qatkd/mk_w10qatkd.py
"""
import io
import os
import re
import sys

os.chdir(r"C:\Users\Andrew\rwkv-anki-autoresearch")

DECAY_SRC = "scratchpad/w10qat/run_w10qat.cmd"
EVAL_SRC = "scratchpad/w10qat/run_w10qat_eval.cmd"
OUT = "scratchpad/w10qatkd/run_w10qatkd.cmd"
TEACHER = "scratchpad/ws10/w10p_d_21870.pth"
LAMBDA = "1.0"

HEADER = r"""@echo off
REM w10qatkd -- ARM 2 + DISTILLATION FROM THE FULL-PRECISION TWIN. Generated by
REM scratchpad/w10qatkd/mk_w10qatkd.py from run_w10qat.cmd (the decay) and run_w10qat_eval.cmd
REM (the eval with the LEARNED catalogs). Control = arm 2 exactly; the ONLY change is
REM RWKV_QAT_KD=1.0 with RWKV_QAT_KD_TEACHER = arm 1's decayed final. Andrew 2026-09-10: "Yep, do KD".
REM The live-teacher target was fixed and proven first: scratchpad/qatkd/smoke_qatkd.py.
REM PREREG: scratchpad/w10qatkd/PREREG.md. Budget: ~27 h decay (a teacher forward per step on top
REM of arm 2's ~0.24 steps/s) + ~10.5 h probe and quant-aware eval.
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\w10qatkd
set SRC=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\ws10
set LOG=%DIR%\w10qatkd.log
set STAMP=%RANDOM%%RANDOM%
set DECAYLOG=%DIR%\decay_%STAMP%.log
set TAG=w10qatkd
set STEPS=21870
set WSSTEPS=109350

"""

KD_ENV = """
REM ---- THE LEVER: distil from the full-precision twin during the QAT decay ----
set RWKV_QAT_KD=%s
set RWKV_QAT_KD_TEACHER=%s
""" % (LAMBDA, TEACHER)

TEACHER_GUARD = r"""REM ---- PHASE 0k: the teacher must EXIST before a ~27 h decay depends on it ----
if not exist "scratchpad\ws10\w10p_d_21870.pth" (
  echo %TAG% NO_TEACHER_CHECKPOINT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_80 %DATE% %TIME% >> "%LOG%"
  exit /b 80
)

"""

KD_ENGAGED_GUARD = r"""REM The lever must have REACHED the loop: the trainer prints this line only when it built the
REM teacher from THIS path. Without it the run is arm 2 again under another name.
findstr /C:"[KD] teacher = scratchpad/ws10/w10p_d_21870.pth" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% KD_NOT_ENGAGED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_81 %DATE% %TIME% >> "%LOG%"
  exit /b 81
)
"""


def main():
    d = io.open(DECAY_SRC, encoding="utf-8", newline="").read().replace("\r\n", "\n")
    e = io.open(EVAL_SRC, encoding="utf-8", newline="").read().replace("\r\n", "\n")

    a = d.index("set PYTHONUNBUFFERED=1")
    b = d.index("set RWKV_QAT_SHIFT_PQ_LEARN=1") + len("set RWKV_QAT_SHIFT_PQ_LEARN=1")
    env = d[a:b]
    c0 = d.index('if not exist "%DIR%" mkdir "%DIR%"')
    c1 = d.index('echo %TAG% DECAY_OK %TIME% >> "%LOG%"') + len('echo %TAG% DECAY_OK %TIME% >> "%LOG%"')
    decay = d[c0:c1]
    ev = e[e.index("REM ---- PHASE 0: the decay artifacts"):]

    subs = [
        ("echo ===== w10qat START", "echo ===== w10qatkd START"),
        ("scratchpad/write_decay_setup.py scratchpad/ws10 w10_ws w10q_d",
         "scratchpad/write_decay_setup.py scratchpad/ws10 w10_ws w10qk_d"),
        (r"scratchpad\ws10\w10q_d_%STEPS%.pth", r"scratchpad\ws10\w10qk_d_%STEPS%.pth"),
    ]
    for x, y in subs:
        if decay.count(x) != 1:
            sys.exit(f"REFUSING: decay substitution did not fire exactly once: {x}")
        decay = decay.replace(x, y)
    anchor_b = "REM ---- PHASE B: the 2-EPOCH decay"
    if decay.count(anchor_b) != 1:
        sys.exit("REFUSING: phase-B anchor missing")
    decay = decay.replace(anchor_b, TEACHER_GUARD + anchor_b)
    anchor_kd = "REM KD must be ABSENT here"
    if decay.count(anchor_kd) != 1:
        sys.exit("REFUSING: KD-absent anchor missing")
    decay = decay.replace(anchor_kd, KD_ENGAGED_GUARD + "REM The DUMP-based KD (RWKV_KD_MIX) must still be absent -- only the live teacher is the lever.\n" + anchor_kd)

    n_ev = ev.count("w10q_d")
    if n_ev < 5:
        sys.exit(f"REFUSING: expected the eval phase to name w10q_d several times, found {n_ev}")
    ev = ev.replace("w10q_d", "w10qk_d")
    # write_eval_toml's FOLDER argument names arm 2's run dir (forward slashes). The first version of
    # this generator missed it -- its stale list held only the BACKSLASH forms -- and preflight's
    # decay-writes-here-vs-eval-looks-there check caught it. Both slash forms are now in the list.
    n_dir = ev.count("scratchpad/w10qat ")
    if n_dir != 2:
        sys.exit(f"REFUSING: expected write_eval_toml to name scratchpad/w10qat twice, found {n_dir}")
    ev = ev.replace("scratchpad/w10qat ", "scratchpad/w10qatkd ")
    clear = "set RWKV_QAT_SHIFT_PQ_LEARN=\n"
    if ev.count(clear) != 1:
        sys.exit("REFUSING: the eval-env LEARN clear is missing")
    ev = ev.replace(clear, clear + "set RWKV_QAT_KD=\nset RWKV_QAT_KD_TEACHER=\n")

    out = HEADER + env + "\n" + KD_ENV + "\n" + decay + "\n\n" + ev

    # ---- assertions on the OUTPUT, both directions ----
    code = "\n".join(l for l in out.split("\n") if not l.strip().upper().startswith("REM"))
    stale = ["w10q_d", "\\w10qat\\", "\\w10qat\n", "/w10qat ", "/w10qat\n", "/w10qat/", "w10qat.log",
             "w10qat_eval.log", "w10qat START", "w10qat EVAL"]
    for t in stale:
        if t in code:
            sys.exit(f"REFUSING: arm 2's identity {t!r} survives on a non-REM line")
    if "set TAG=w10qat\n" in code:
        sys.exit("REFUSING: arm 2's TAG line survives")
    if code.count("set RWKV_QAT_KD=%s\n" % LAMBDA) != 1 or code.count("set RWKV_QAT_KD_TEACHER=%s\n" % TEACHER) != 1:
        sys.exit("REFUSING: the KD lines are not present exactly once")
    i_set, i_clear, i_eval = (code.index("set RWKV_QAT_KD=%s" % LAMBDA), code.index("set RWKV_QAT_KD=\n"),
                              code.index("optimization/eval_sharded.py"))
    if not (i_set < code.index("rwkv.train_rwkv") < i_clear < i_eval):
        sys.exit("REFUSING: KD must be set for the decay and cleared before the eval")
    if len(re.findall(r'(?<!>)> "%LOG%"', code)) != 1:
        sys.exit("REFUSING: expected exactly one TRUNCATING write to the log (the START line)")
    codes = re.findall(r"echo DONE_EXIT_(\d+) ", out)
    if len(codes) != len(set(codes)):
        sys.exit(f"REFUSING: duplicate exit codes {sorted(int(c) for c in codes)}")
    if out.index("echo DONE_EXIT_0 ") > out.rindex("endlocal"):
        sys.exit("REFUSING: the terminal marker follows endlocal")
    if code.index("set DECAYLOG=") < code.index("set STAMP="):
        sys.exit("REFUSING: DECAYLOG is set before STAMP")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, "w", encoding="ascii", newline="\r\n").write(out)
    raw = open(OUT, "rb").read()
    print(f"wrote {OUT}  ({raw.count(b'\n')} lines, {raw.count(b'\r\n')} CRLF)")
    print(f"  exit codes {sorted(int(c) for c in codes)}")
    print(f"  decay prefix w10qk_d, teacher {TEACHER}, lambda {LAMBDA}")


if __name__ == "__main__":
    main()
