"""Generate the eqw runner ("train on what is scored": RWKV_EQUALIZE_LOSS_W=0.25) from a reference runner.
    python scratchpad/eqw/mk_eqw.py realcyc | hord | muonscale
One variable on top of the base recipe: `set RWKV_EQUALIZE_LOSS_W=0.25` (unscored rows weighted 0.25 in the
ahead and imm objectives; train-only; no new parameters). WS-log guard: the [eqw] banner must carry the
value. Both-direction guards as in mk_muonscale.py. The base's own levers (hord's hinge, muonscale's flag,
SAM) survive verbatim because only the reference's identity tokens are rewritten.
"""
import os
import re
import sys
args = [a for a in sys.argv[1:] if not a.startswith("--")]
base = args[0] if args else "realcyc"
cfg = {"realcyc": dict(src_dir="realcyc", src_tag="realcyc", params="563652"),
       "hord": dict(src_dir="hord", src_tag="hord", params="563652"),
       "muonscale": dict(src_dir="muonscale", src_tag="muonscale", params="563652")}[base]
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(REPO)
src_cmd = open(f"scratchpad/{cfg['src_dir']}/run_{cfg['src_tag']}.cmd", newline="").read()
src_ws = open(f"scratchpad/{cfg['src_dir']}/ws.toml", newline="").read()
assert "\r\n" not in src_cmd[:300] and "\r\n" not in src_ws[:300]
m = re.search(r"%DIR%\\(\w+)_ws_%STEPS%\.pth", src_cmd)
assert m
cfg["src_prefix"] = m.group(1)
TAG, PREFIX, DIRN, W = "eqw", "eq", "eqw", "0.25"
visited = 0
out = []
for line in src_cmd.split("\n"):
    orig = line
    if line.startswith("REM ") and ("PHASE 2" in line or "restart" in line or "generated by scratchpad/" in line):
        continue
    line = line.replace(f"\\scratchpad\\{cfg['src_dir']}", f"\\scratchpad\\{DIRN}")
    line = line.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}")
    line = line.replace(f"set TAG={cfg['src_tag']}", f"set TAG={TAG}")
    line = line.replace(f"{cfg['src_tag']}.log", f"{TAG}.log")
    line = line.replace(f"{cfg['src_prefix']}_ws", f"{PREFIX}_ws").replace(f"{cfg['src_prefix']}_d", f"{PREFIX}_d")
    line = line.replace(f"===== {cfg['src_tag']} START", f"===== {TAG} START").replace("===== REALCYC START", f"===== {TAG} START")
    if line != orig:
        visited += 1
    out.append(line)
s = "\n".join(out)
anchor = "set RWKV_KD_ALPHA=\n"
assert s.count(anchor) == 1
s = s.replace(anchor, anchor +
    "REM ---- THE LEVER (eqw, INVENTED, 2026-09-06 round rank 1): the benchmark never scores the first sixth of a\n"
    "REM user's history (TimeSeriesSplit(5)) and those rows are EASIER (realcyc train users: by-user ahead BCE 0.189\n"
    "REM vs 0.279). Unscored rows (label_is_equalize=0) are weighted 0.25 in the ahead and imm objectives; scored 1.\n"
    f"set RWKV_EQUALIZE_LOSS_W={W}\n", 1)
guard_anchor = 'echo %TAG% WS_OK %TIME% >> "%LOG%"'
assert s.count(guard_anchor) == 1
s = s.replace(guard_anchor,
    'REM The model must have CONSUMED the flag: the [eqw] banner carries the weight it was constructed with.\n'
    f'findstr /C:"[eqw] scored-set loss weighting ON: unscored (label_is_equalize=0) rows weighted {W}" "%DIR%\\ws_%STAMP%.log" >nul\n'
    'if not %ERRORLEVEL%==0 (\n'
    '  echo %TAG% EQW_NOT_CONSUMED %DATE% %TIME% >> "%LOG%"\n'
    '  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"\n'
    '  exit /b 44\n'
    ')\n' + guard_anchor, 1)
s = s.replace("@echo off\n", f"@echo off\nREM eqw -- generated by scratchpad/eqw/mk_eqw.py from the {base} runner. DO NOT HAND-EDIT.\n", 1)
if " --exclude 6701 " not in s:
    s = s.replace(" --shards 1 --solo-threshold 0 --fetch-per-shard 2", " --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2", 1)
assert s.count(" --exclude 6701 ") == 1
body = "\n".join(l for l in s.split("\n") if not l.startswith("REM"))
for tok in (cfg["src_tag"], f"{cfg['src_prefix']}_", f"scratchpad/{cfg['src_dir']}", f"\\{cfg['src_dir']}\\"):
    assert tok not in body, f"stale token survived outside REM: {tok!r}"
n_mentions = sum(1 for l in src_cmd.split("\n") if not l.startswith("REM") and (cfg["src_tag"] in l or cfg["src_prefix"] + "_" in l or cfg["src_dir"] in l))
assert visited >= n_mentions, (visited, n_mentions)
assert s.count(f"set RWKV_EQUALIZE_LOSS_W={W}") == 1 and s.count("DONE_EXIT_0") == 1
assert f"Trainable parameters: {cfg['params']}" in s
assert "set RWKV_DUR_DROP=" not in s and "set RWKV_ORD_LAMBDA=" not in s and "set RWKV_RESUME_SKIP_GROUPS" not in s
assert ("set RWKV_PAVA_HORIZON_LAMBDA=" in s) == (base == "hord")
assert ("set RWKV_MUON_INCLUDE_SCALE=1" in s) == (base == "muonscale")
ws = src_ws.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}").replace(f'"{cfg["src_prefix"]}_ws"', f'"{PREFIX}_ws"')
assert f'SAVE_MODEL_PREFIX = "{PREFIX}_ws"' in ws and f'SAVE_MODEL_FOLDER = "scratchpad/{DIRN}"' in ws
ws = ws.replace(ws.split("\n")[0], f"# eqw WS phase -- {base}'s recipe + RWKV_EQUALIZE_LOSS_W={W} (set in the runner env, not here).", 1)
os.makedirs(f"scratchpad/{DIRN}", exist_ok=True)
open(f"scratchpad/{DIRN}/run_{TAG}.cmd", "w", newline="\n").write(s)
open(f"scratchpad/{DIRN}/ws.toml", "w", newline="\n").write(ws)
open(f"scratchpad/{DIRN}/CONTROL.txt", "w").write(f"base={base}\ncontrol={base}\n")
print(f"wrote run_{TAG}.cmd + ws.toml from {base}: visited {visited} lines (>= {n_mentions}); guard params {cfg['params']}")
