# HP5k trial hp5k_cb_lr_mult_0p1: param=cb_lr_mult -> 0.1.  Full config: {"peak_lr": 0.001, "warmup_steps": 200, "weight_decay": 0.2, "clip": 0.25, "decay_ratio": 0.25, "adamw_beta2": 0.999, "dropout_scale": 0.5, "cb_lr_mult": 0.1}
TRAIN_USERS_START = 1
TRAIN_USERS_END = 5000
VALIDATE_USERS_START = 5001
VALIDATE_USERS_END = 5010

TRAIN_DATASET_LMDB_PATH = "train_db_5k_h1"
TRAIN_DATASET_LMDB_SIZE = 400_000_000_000
VALIDATE_DATASET_LMDB_PATH = "F:/rwkv_lmdb/test_db_5k"
VALIDATE_DATASET_LMDB_SIZE = 250_000_000_000
LABEL_FILTER_LMDB_PATH = "label_filter_db"
LABEL_FILTER_LMDB_SIZE = 40_000_000_000

NUM_FETCH_PROCESSES = 4
MAX_TRAIN_GLOBAL_LEN = 110000

TRAIN_MODE = "WS"
STEP_OFFSET = 1
WARMUP_STEPS = 200
EPOCHS = 1
VALIDATE_EVERY = 500
PEAK_LR = 0.001

LOAD_MODEL = false
SAVE_MODEL_FOLDER = "scratchpad/tuner5k/hp5k_cb_lr_mult_0p1"
SAVE_MODEL_PREFIX = "hp5k_cb_lr_mult_0p1ws"
DEVICE = "cuda"
DTYPE = "bfloat16"

USE_WANDB = false
WANDB_PROJECT_NAME = "rwkv"
WANDB_RESUME = false
WANDB_RESUME_ID = ""
