FILE_AHEAD = "RWKV-lad_deck1"
FILE_IMM = "RWKV-P-lad_deck1"
MODEL_PATH = "scratchpad/lad_deck1/laddeck1d_1638.pth"
DEVICE = "cuda"
DTYPE = "bfloat16"
DATASET_LMDB_PATH = "F:/rwkv_lmdb/test_db_5k"
DATASET_LMDB_SIZE = 250_000_000_000
LABEL_FILTER_LMDB_PATH = "label_filter_db"
LABEL_FILTER_LMDB_SIZE = 40_000_000_000
RAW = false
RAW_DB_PATH = "raw/result_db"
RAW_DB_SIZE = 1_000_000_000
USER_START = 5001
USER_END = 10000
NUM_FETCH_PROCESSES = 4
