FILE_AHEAD = "RWKV-evalspeed-shd-s0"
FILE_IMM = "RWKV-P-evalspeed-shd-s0"
MODEL_PATH = "scratchpad/muongates/mg_d_10935.pth"
DEVICE = "cuda"
DTYPE = "bfloat16"
DATASET_LMDB_PATH = "F:/rwkv_lmdb/test_db_5k_id5"
DATASET_LMDB_SIZE = 250_000_000_000
LABEL_FILTER_LMDB_PATH = "F:/rwkv_lmdb/label_filter_db_id_e2s"
LABEL_FILTER_LMDB_SIZE = 40_000_000_000
RAW = false
RAW_DB_PATH = "raw/result_db"
RAW_DB_SIZE = 1_000_000_000
USER_START = 5001
USER_END = 5400
NUM_FETCH_PROCESSES = 2
USERS_FILE = "C:/Users/Andrew/rwkv-anki-autoresearch/scratchpad/evalspeed/shards/users_s0.json"
