DEVICE = "cpu"
DTYPE = "bfloat16"
DATA_PATH = "../anki-revlogs-10k-id"
LMDB_PATH = "F:/rwkv_lmdb/timing_db2"
LMDB_SIZE = 8_000_000_000
LABEL_FILTER_LMDB_PATH = "label_filter_db"
LABEL_FILTER_LMDB_SIZE = 40_000_000_000
USER_START = 1
USER_END = 20
MAX_BATCH_SIZE = 16384
PROCESSES = 6
RWKV_SUBMODULES = ["card_id", "note_id", "deck_id", "preset_id", "user_id"]
