@echo off
REM ===========================================================================================
REM DE-RISK BUILD for the -id features rebuild. CPU ONLY -- no GPU, safe beside a training run.
REM FUTURE_FEATURES.md "De-risk before committing anything": build a 100-user LMDB first and
REM check the pipeline end to end for about 1 percent of the 23 h rebuild's cost.
REM
REM TWO ARMS, and the control is the point. The published-vs-id dataset swap alone moves `size`
REM for about 30 percent of users, so comparing against the existing DB would be unattributable.
REM Both arms here read the SAME -id dataset with the SAME users, batch size and label filter;
REM the only difference is RWKV_ID_FEATURES, i.e. 24 columns vs 44.
REM
REM WHAT THIS ACTUALLY DE-RISKS, beyond what the CPU smokes already cover:
REM   the multiprocessing path (6 workers), the LMDB writer, MAX_BATCH_SIZE chunking and the
REM   per-user max_size logic -- none of which create_sample alone exercises. Plus a real
REM   reviews/s number for the new derivations, so the 23 h projection stops being an estimate
REM   that predates the features existing.
REM
REM Writes throwaway DBs to F: (888 GB free). Reads the read-only -id set. Touches nothing live.
REM Do NOT edit this file while it runs. No angle brackets or arrows in REM lines.
REM ===========================================================================================
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=scratchpad\id_features
set PY=.venv\Scripts\python.exe
set OMP_NUM_THREADS=2
set RWKV_ID_FEATURES=

echo ===== DE-RISK BUILD START %DATE% %TIME% =====

echo --- ARM OFF (control, 24 columns) ---
if exist F:\rwkv_lmdb\derisk_id_off rmdir /s /q F:\rwkv_lmdb\derisk_id_off
%PY% -m rwkv.data_processing --config %DIR%\dp_derisk_off.toml > %DIR%\derisk_off.log 2>&1
if errorlevel 1 (
  echo ARM OFF FAILED
  echo DONE_EXIT_OFFFAIL
  exit /b 1
)

echo --- ARM ON (44 columns) ---
set RWKV_ID_FEATURES=1
if exist F:\rwkv_lmdb\derisk_id_on rmdir /s /q F:\rwkv_lmdb\derisk_id_on
%PY% -m rwkv.data_processing --config %DIR%\dp_derisk_on.toml > %DIR%\derisk_on.log 2>&1
if errorlevel 1 (
  echo ARM ON FAILED
  echo DONE_EXIT_ONFAIL
  exit /b 1
)

echo --- COMPARE ---
set RWKV_ID_FEATURES=
%PY% %DIR%\compare_derisk.py > %DIR%\derisk_compare.log 2>&1
if errorlevel 1 (
  echo COMPARE FAILED
  echo DONE_EXIT_CMPFAIL
  exit /b 1
)
type %DIR%\derisk_compare.log

echo ===== DE-RISK BUILD END %DATE% %TIME% =====
echo DONE_EXIT_%ERRORLEVEL%
