"""Generate run_fit_catalogs.cmd -- the ws10 PQ-catalog refit that arm 2's phase 0 demands.

WHY IT IS A CHAIN STEP AND NOT A NOTE. Both deployed catalogs were measured STALE on the gen-5
trunk (scratchpad/qat_gen5/FINDING.md): the WKV one scored 0.9416 against a random control of
0.9582, and the shift one 1.0352 / 1.0811, i.e. WORSE than encoding everything to zero. A stale
catalog passes every shape assert, so nothing downstream would have complained. Arm 2 exists to
price quantization, so it must not start from a broken catalog -- and the fix is ~10 min of CPU
that can run while arm 1 has the GPU.

WHY IT IS CHEAP. The corpus dump is Rust (seconds); what is slow is producing a parity TRACE, at
~25 rows/s in the Python deploy RNN. It is not needed: trace files are model-independent INPUTS,
so reference_realcyc's three users drive any gen-5 checkpoint, and only the WEIGHTS have to be
converted -- export_weights_only.py does that in seconds.

FREE MEASUREMENT ON THE WAY PAST. Phase 4 scores the realcyc-fitted catalogs on ws10's states.
Same architecture, same features, 8x the budget -- so it answers whether a catalog transfers
across a budget change, which nothing in the record has ever asked.

Usage: python scratchpad/w10qat/mk_fit_catalogs.py
"""
import io
import os

B = chr(92)
os.chdir(r"C:\Users\Andrew\rwkv-anki-autoresearch")

ENV = [
    "set PYTHONPATH=C:" + B + "Users" + B + "Andrew" + B + "rwkv-anki-autoresearch",
    "set PYTHONIOENCODING=utf-8",
    "set OMP_NUM_THREADS=4",
    "set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py",
    "set RWKV_INTERLEAVE=1",
    "set RWKV_GRU_HEAD=3",
    "set RWKV_PAVA_LAMBDA=0.2",
    "set RWKV_NO_AHEAD_RESIDUAL=1",
    "set RWKV_STRIP_L0_VLORA=1",
    "set RWKV_STATE_CLAMP_TAU=300",
    "set RWKV_STATE_CLAMP_WINDOW=32768",
    "set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,"
    "deck_id:1,deck_id:2,card_id:1",
    "set RWKV_ID_FEATURES=1",
    "set RWKV_REAL_CYCLES=1",
    "set RWKV_ZERO_FEATURES=",
    "set RWKV_CHAMP_CKPT=scratchpad/ws10/w10_ws_109350.pth",
    "set RWKV_REF_DIR=scratchpad/w10qat/cb",
]

L = []
L += ["@echo off",
      "REM Refit the PQ catalogs on the ws10 WS-final. Generated by mk_fit_catalogs.py; read that",
      "REM file for why this is a chain step and why it costs minutes rather than hours.",
      "setlocal",
      "cd /d C:" + B + "Users" + B + "Andrew" + B + "rwkv-anki-autoresearch",
      "set DIR=C:" + B + "Users" + B + "Andrew" + B + "rwkv-anki-autoresearch"
      + B + "scratchpad" + B + "w10qat",
      "set LOG=%DIR%" + B + "fitcb.log",
      "set PY=.venv" + B + "Scripts" + B + "python.exe",
      "set BIN=rust" + B + "rwkv-infer" + B + "target" + B + "release" + B + "rwkv-infer.exe"]
L += ENV
L += ['echo ===== ws10 CATALOG REFIT START %DATE% %TIME% ===== > "%LOG%"',
      "",
      "REM ---- PHASE 0: the WS-final must exist. A refit on an intermediate checkpoint would be",
      "REM silently wrong: the catalog would be fitted for a model arm 2 does not start from.",
      'if not exist "scratchpad' + B + 'ws10' + B + 'w10_ws_109350.pth" (',
      '  echo missing w10_ws_109350.pth %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_61 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 61",
      ")",
      "",
      "REM ---- PHASE 1: weights to safetensors (seconds; NOT the slow trace export)",
      '"%PY%" -u scratchpad/w10qat/export_weights_only.py >> "%LOG%" 2>&1',
      "if not %ERRORLEVEL%==0 (",
      '  echo weights export FAILED %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_62 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 62",
      ")",
      "",
      "REM ---- PHASE 2: dump the corpus with the Rust engine, driven by the EXISTING gen-5 traces",
      "set RWKV_TRACE_DIR=reference_realcyc",
      "set RWKV_WEIGHTS=scratchpad/w10qat/cb/rwkv_ref_558.safetensors",
      'if not exist "%DIR%' + B + 'corpus" mkdir "%DIR%' + B + 'corpus"']
for u in (107, 136, 156):
    for s in ("card", "note"):
        base = '"%DIR%' + B + 'corpus' + B
        L += ['%BIN% --dump-corpus ' + str(u) + ' ' + s + ' 1 > ' + base +
              'wkv_' + str(u) + '_' + s + '.txt" 2>> "%LOG%"',
              '%BIN% --dump-shift-corpus ' + str(u) + ' ' + s + ' 1 > ' + base +
              'shift_' + str(u) + '_' + s + '.txt" 2>> "%LOG%"']
L += ["",
      "REM ---- PHASE 3: fit both catalogs. Headers stay byte-compatible with the deployed pair,",
      "REM so deploy state size is unchanged and only the centroids move.",
      '"%PY%" scratchpad/pq_train_juv.py reference/pq_cb_wkv_ws10_b10.txt '
      '"%DIR%' + B + 'corpus' + B + 'wkv_*_*.txt" --k 16 --h 5 --bits 10 >> "%LOG%" 2>&1',
      "if not %ERRORLEVEL%==0 (",
      '  echo WKV fit FAILED %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_63 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 63",
      ")",
      '"%PY%" scratchpad/pq_train_shift.py reference/pq_cb_shift_ws10_m2b12.txt '
      '"%DIR%' + B + 'corpus' + B + 'shift_*_*.txt" --c 80 --m 2 --bits 12 --minibatch 1 '
      '>> "%LOG%" 2>&1',
      "if not %ERRORLEVEL%==0 (",
      '  echo shift fit FAILED %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_64 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 64",
      ")",
      "",
      "REM ---- PHASE 4: report how the realcyc-fitted catalogs score on ws10 states. Free, and it",
      "REM answers a question the record has never asked: does a catalog survive a budget change?",
      "set WKV_CB=reference/pq_cb_wkv_gen5_b10.txt",
      '"%PY%" scratchpad/qat_tax/wkv_cb_staleness.py "%DIR%' + B + 'corpus' + B + 'wkv_*_*.txt" '
      '--holdout-user 156 >> "%LOG%" 2>&1',
      '"%PY%" scratchpad/qat_gen5/shift_cb_staleness.py reference/pq_cb_shift_gen5_m2b12.txt '
      '"%DIR%' + B + 'corpus' + B + 'shift_*_*.txt" --holdout-user 156 >> "%LOG%" 2>&1',
      "",
      'if not exist "reference' + B + 'pq_cb_wkv_ws10_b10.txt" (',
      '  echo WKV catalog was not written %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_65 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 65",
      ")",
      'if not exist "reference' + B + 'pq_cb_shift_ws10_m2b12.txt" (',
      '  echo shift catalog was not written %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_66 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 66",
      ")",
      'echo CATALOGS OK %DATE% %TIME% >> "%LOG%"',
      'echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"',
      "endlocal & exit /b 0",
      ""]

io.open("scratchpad/w10qat/run_fit_catalogs.cmd", "w", newline="\r\n").write("\n".join(L))
print("wrote scratchpad/w10qat/run_fit_catalogs.cmd")
