@echo off
REM Refit the PQ catalogs on the ws10 WS-final. Generated by mk_fit_catalogs.py; read that
REM file for why this is a chain step and why it costs minutes rather than hours.
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\w10qat
set LOG=%DIR%\fitcb.log
set PY=.venv\Scripts\python.exe
set BIN=rust\rwkv-infer\target\release\rwkv-infer.exe
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set PYTHONIOENCODING=utf-8
set OMP_NUM_THREADS=4
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_ID_FEATURES=1
set RWKV_REAL_CYCLES=1
set RWKV_ZERO_FEATURES=
set RWKV_CHAMP_CKPT=scratchpad/ws10/w10_ws_109350.pth
set RWKV_REF_DIR=scratchpad/w10qat/cb
echo ===== ws10 CATALOG REFIT START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE 0: the WS-final must exist. A refit on an intermediate checkpoint would be
REM silently wrong: the catalog would be fitted for a model arm 2 does not start from.
if not exist "scratchpad\ws10\w10_ws_109350.pth" (
  echo missing w10_ws_109350.pth %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_61 %DATE% %TIME% >> "%LOG%"
  exit /b 61
)

REM ---- PHASE 1: weights to safetensors (seconds; NOT the slow trace export)
"%PY%" -u scratchpad/w10qat/export_weights_only.py >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo weights export FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_62 %DATE% %TIME% >> "%LOG%"
  exit /b 62
)

REM ---- PHASE 2: dump the corpus with the Rust engine, driven by the EXISTING gen-5 traces
set RWKV_TRACE_DIR=reference_realcyc
set RWKV_WEIGHTS=scratchpad/w10qat/cb/rwkv_ref_558.safetensors
if not exist "%DIR%\corpus" mkdir "%DIR%\corpus"
%BIN% --dump-corpus 107 card 1 > "%DIR%\corpus\wkv_107_card.txt" 2>> "%LOG%"
%BIN% --dump-shift-corpus 107 card 1 > "%DIR%\corpus\shift_107_card.txt" 2>> "%LOG%"
%BIN% --dump-corpus 107 note 1 > "%DIR%\corpus\wkv_107_note.txt" 2>> "%LOG%"
%BIN% --dump-shift-corpus 107 note 1 > "%DIR%\corpus\shift_107_note.txt" 2>> "%LOG%"
%BIN% --dump-corpus 136 card 1 > "%DIR%\corpus\wkv_136_card.txt" 2>> "%LOG%"
%BIN% --dump-shift-corpus 136 card 1 > "%DIR%\corpus\shift_136_card.txt" 2>> "%LOG%"
%BIN% --dump-corpus 136 note 1 > "%DIR%\corpus\wkv_136_note.txt" 2>> "%LOG%"
%BIN% --dump-shift-corpus 136 note 1 > "%DIR%\corpus\shift_136_note.txt" 2>> "%LOG%"
%BIN% --dump-corpus 156 card 1 > "%DIR%\corpus\wkv_156_card.txt" 2>> "%LOG%"
%BIN% --dump-shift-corpus 156 card 1 > "%DIR%\corpus\shift_156_card.txt" 2>> "%LOG%"
%BIN% --dump-corpus 156 note 1 > "%DIR%\corpus\wkv_156_note.txt" 2>> "%LOG%"
%BIN% --dump-shift-corpus 156 note 1 > "%DIR%\corpus\shift_156_note.txt" 2>> "%LOG%"

REM ---- PHASE 3: fit both catalogs. Headers stay byte-compatible with the deployed pair,
REM so deploy state size is unchanged and only the centroids move.
"%PY%" scratchpad/pq_train_juv.py reference/pq_cb_wkv_ws10_b10.txt "%DIR%\corpus\wkv_*_*.txt" --k 16 --h 5 --bits 10 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo WKV fit FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_63 %DATE% %TIME% >> "%LOG%"
  exit /b 63
)
"%PY%" scratchpad/pq_train_shift.py reference/pq_cb_shift_ws10_m2b12.txt "%DIR%\corpus\shift_*_*.txt" --c 80 --m 2 --bits 12 --minibatch 1 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo shift fit FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_64 %DATE% %TIME% >> "%LOG%"
  exit /b 64
)

REM ---- PHASE 4: report how the realcyc-fitted catalogs score on ws10 states. Free, and it
REM answers a question the record has never asked: does a catalog survive a budget change?
set WKV_CB=reference/pq_cb_wkv_gen5_b10.txt
"%PY%" scratchpad/qat_tax/wkv_cb_staleness.py "%DIR%\corpus\wkv_*_*.txt" --holdout-user 156 >> "%LOG%" 2>&1
"%PY%" scratchpad/qat_gen5/shift_cb_staleness.py reference/pq_cb_shift_gen5_m2b12.txt "%DIR%\corpus\shift_*_*.txt" --holdout-user 156 >> "%LOG%" 2>&1

if not exist "reference\pq_cb_wkv_ws10_b10.txt" (
  echo WKV catalog was not written %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_65 %DATE% %TIME% >> "%LOG%"
  exit /b 65
)
if not exist "reference\pq_cb_shift_ws10_m2b12.txt" (
  echo shift catalog was not written %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_66 %DATE% %TIME% >> "%LOG%"
  exit /b 66
)
echo CATALOGS OK %DATE% %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
