"""THE FAST DIAGNOSTIC HARNESS -- a whole train -> decay -> eval cycle in ~25 min instead of 9.2 h.

Andrew, 2026-08-18: "Obviously not every bug will be caught just by staring at the code, so
temporarily reduce the number of epochs to 0.05 and the number of eval users to 20, and use that
for diagnostics."

THE POINT IS EXECUTION, NOT ACCURACY. Every failure of 2026-08-17/18 -- the `endlocal` marker, the
omitted LOAD_MODEL_FOLDER, the two alpha/guard mismatches, the smoke that inherited its own control
-- would have been caught by ONE cheap end-to-end run. None of them was visible by reading. A
diagnostic run's LOGLOSS IS MEANINGLESS and must never be recorded as a result; what it reports is
whether the path runs at all, and whether the thing you switched on actually took effect.

  EPOCHS 0.05 x 10,935 groups = 546 steps ~= 10 min per phase, plus a 20-user eval.

TWO SCALINGS THAT ARE NOT OPTIONAL, because without them the run is fast but hollow:

  * WARMUP_STEPS 400 -> 20. At 546 steps a 400-step warmup is 73% of the run, so the LR would
    never reach its plateau and the decay phase would start from a model that never trained at
    the production LR. Scaled by the same 0.05.
  * VALIDATE_EVERY 1000 -> 200. 1000 > 546 means validation NEVER FIRES -- the validation path,
    which has its own code and its own failure modes, would go completely unexercised while the
    run looked green. This is the same shape as the bugs being hunted: a phase that silently does
    not happen.

WHAT IS DELIBERATELY *NOT* REDUCED, and why: the db, the user range, MAX_TRAIN_GLOBAL_LEN and the
fetch-process count all stay at production values. KD replays its dump BY STEP INDEX and hard-exits
43 on a per-step `labels_sum` checksum mismatch, so changing any data-affecting field would break
the KD path -- which is one of the paths most worth exercising. Reducing the number of USERS would
also change `num_groups`, and with it the step count, silently.

Usage:
    .venv/Scripts/python.exe scratchpad/bughunt/mk_diag.py <tag> [KEY=VAL ...]

    mk_diag.py base                              # the champion path, nothing switched on
    mk_diag.py idfeat RWKV_ID_FEATURES=1         # the features code, never yet run on GPU
    mk_diag.py rgate  RWKV_RGATE=card

Each tag gets its own directory, log, checkpoints and result jsonls, so two diagnostics can never
collide -- eval_sharded RESUMES from existing result files, so a shared TAG would silently merge
two models' users into one score.
"""
import io
import os
import re
import sys

REPO = r"C:\Users\Andrew\rwkv-anki-autoresearch"
KD_DUMP = r"C:\rwkv_kd_dump\t128_seedpair_65k"

# 0.05 x 10,935 groups. VERIFY THIS BY EXECUTION on the first run and correct it here if the
# observed final step differs -- num_groups is data-dependent, and assuming it is exactly the
# habit this harness exists to break.
DIAG_STEPS = 546
EVAL_USERS = (5001, 5020)

# The champion recipe (iter 53). A diagnostic that does not run the real env tests nothing real.
CHAMPION_ENV = [
    ("PYTHONUNBUFFERED", "1"), ("PYTHONPATH", REPO), ("OMP_NUM_THREADS", "7"),
    ("RWKV_DETERMINISTIC", "1"), ("RWKV_AUGMENT_SEED", "4321"),
    ("RWKV_EMPTY_CACHE_EVERY", "1"), ("RWKV_EMPTY_CACHE_WINDOW", "0"),
    ("RWKV_ARCH_MODULE", "scratchpad/track2_a18/architecture_d80_lora4_cnd.py"),
    ("RWKV_INTERLEAVE", "1"), ("RWKV_GRU_HEAD", "3"), ("RWKV_PAVA_LAMBDA", "0.2"),
    ("RWKV_PROBE_DENSITY", "0.08"), ("RWKV_PROBE_DUR", "0.0"),
    ("RWKV_MUON", "1"), ("RWKV_MUON_LR", "0.0025"), ("RWKV_MUON_MOMENTUM", "0.95"),
    ("RWKV_MUON_INCLUDE_LORA", "1"),
    ("RWKV_NO_AHEAD_RESIDUAL", "1"), ("RWKV_STRIP_L0_VLORA", "1"), ("RWKV_ZERO_FEATURES", "22"),
    ("RWKV_STATE_CLAMP_TAU", "300"), ("RWKV_STATE_CLAMP_WINDOW", "32768"),
    ("RWKV_STRIP_CMIX", "user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,"
                        "preset_id:2,deck_id:1,deck_id:2,card_id:1"),
    ("RWKV_WEIGHT_DECAY", "0.01"), ("RWKV_WEIGHT_DECAY_HEAD", "0.01"),
    ("RWKV_CLIP", "0.25"), ("RWKV_ADAMW_BETA2", "0.999"), ("RWKV_DROPOUT_SCALE", "0.5"),
    ("RWKV_MUON_BATCHED", "1"), ("RWKV_NO_JIT", "1"), ("RWKV_QAT_COMPILE", "1"),
]

WS_TOML = '''# DIAGNOSTIC WS phase for `{tag}` -- generated by scratchpad/bughunt/mk_diag.py.
# EPOCHS 0.05 => ~{steps} steps. THIS RUN'S LOGLOSS IS MEANINGLESS; it exists to execute the path.
# Data-affecting fields are at PRODUCTION values on purpose: KD replays its dump by step index
# and hard-exits 43 on a per-step labels_sum mismatch, so shrinking the data breaks the KD path.
TRAIN_USERS_START = 1
TRAIN_USERS_END = 5000
VALIDATE_USERS_START = 5001
VALIDATE_USERS_END = 5010

TRAIN_DATASET_LMDB_PATH = "train_db_5k_h1"
TRAIN_DATASET_LMDB_SIZE = 400_000_000_000
VALIDATE_DATASET_LMDB_PATH = "F:/rwkv_lmdb/test_db_5k"
VALIDATE_DATASET_LMDB_SIZE = 250_000_000_000
LABEL_FILTER_LMDB_PATH = "label_filter_db"
LABEL_FILTER_LMDB_SIZE = 40_000_000_000

NUM_FETCH_PROCESSES = 2
MAX_TRAIN_GLOBAL_LEN = 65536

TRAIN_MODE = "WS"
STEP_OFFSET = 1
# scaled with EPOCHS: 400 of 546 steps would be 73% warmup, so the LR would never plateau
WARMUP_STEPS = 20
EPOCHS = 0.05
# MUST be < the step count or the validation path never executes and the run looks green anyway
VALIDATE_EVERY = 200
PEAK_LR = 1e-3

LOAD_MODEL = false
SAVE_MODEL_FOLDER = "scratchpad/bughunt/diag_{tag}"
SAVE_MODEL_PREFIX = "{tag}_ws"
DEVICE = "cuda"
DTYPE = "bfloat16"

USE_WANDB = false
WANDB_PROJECT_NAME = "rwkv"
WANDB_RESUME = false
WANDB_RESUME_ID = ""
'''


def rem(t):
    for b, g in (("<", "("), (">", ")"), ("&", "and"), ("|", "/"), ("^", "")):
        t = t.replace(b, g)
    return "REM " + t


def build(tag, lever):
    d = "%s\\scratchpad\\bughunt\\diag_%s" % (REPO, tag)
    L = ["@echo off",
         "REM " + "=" * 85,
         rem("DIAGNOSTIC RUN `%s` -- EPOCHS 0.05, %d-user eval. ~25 min." % (tag, EVAL_USERS[1] - EVAL_USERS[0] + 1)),
         rem("Generated by scratchpad/bughunt/mk_diag.py. DO NOT HAND-EDIT; regenerate."),
         "REM",
         rem("THIS RUN'S LOGLOSS IS MEANINGLESS and must never be recorded as a result. The"),
         rem("purpose is to EXECUTE the path -- reading code did not catch any of the failures"),
         rem("of 2026-08-17/18, and one cheap end-to-end run would have caught every one."),
         "REM",
         rem("Do NOT edit this file while it runs: cmd.exe re-reads a batch file from a saved"),
         rem("byte offset after every command returns (iters 43 and 46 died that way)."),
         "REM " + "=" * 85,
         "setlocal",
         "cd /d " + REPO,
         "",
         "set DIR=" + d,
         "set LOG=%DIR%\\diag_" + tag + ".log",
         "set STAMP=%RANDOM%%RANDOM%",
         "set TAG=diag_" + tag,
         "set STEPS=%d" % DIAG_STEPS,
         "set DUMP=" + KD_DUMP,
         ""]
    for k, v in CHAMPION_ENV:
        L.append("set %s=%s" % (k, v))
    if lever:
        L += ["", rem("---- THE LEVER UNDER TEST ----")]
        for k, v in lever.items():
            L.append("set %s=%s" % (k, v))
    L += ["", 'if not exist "%DIR%" mkdir "%DIR%"',
          'echo ===== DIAG ' + tag + ' START %DATE% %TIME% ===== > "%LOG%"']

    # ---- phase A: WS -------------------------------------------------------------------
    L += ["", rem("---- PHASE A: WS, 0.05 epochs ----"),
          "set RWKV_KD_MIX=%DUMP%:10935",
          "set RWKV_KD_ALPHA=0.9",
          'if exist "%DIR%\\ws_%STAMP%.log" del /q "%DIR%\\ws_%STAMP%.log"',
          '.venv\\Scripts\\python.exe -u -m rwkv.train_rwkv --config scratchpad/bughunt/diag_%s/ws.toml > "%%DIR%%\\ws_%%STAMP%%.log" 2>&1' % tag,
          "if not %ERRORLEVEL%==0 (",
          '  echo DIAG WS_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_21 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 21",
          ")",
          rem("Gate on the ARTIFACT AT THE EXPECTED STEP. Neither the exit code nor the mere"),
          rem("existence of a .pth is evidence: train_rwkv has exited 0 after a fatal error, and"),
          rem("an interrupted run leaves a checkpoint at the step it died on."),
          'if not exist "%DIR%\\' + tag + '_ws_%STEPS%.pth" (',
          '  echo DIAG WS_SHORT no ' + tag + '_ws_%STEPS%.pth %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_27 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 27",
          ")",
          rem("The validation path must actually have run -- VALIDATE_EVERY under the step count"),
          rem("is the whole reason it can."),
          'findstr /C:"val" "%DIR%\\ws_%STAMP%.log" >nul',
          "if not %ERRORLEVEL%==0 (",
          '  echo DIAG NOVALIDATION %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_29 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 29",
          ")",
          'echo DIAG WS_OK %TIME% >> "%LOG%"']

    # ---- phase B: decay ----------------------------------------------------------------
    L += ["", rem("---- PHASE B: decay, 0.05 epochs ----"),
          rem("alpha 0.5 in decay (iter 45); 0.9 is the WS value (iter 39). Setting this is what"),
          rem("iter 54 phase 2a omitted, and it decayed 3.3 h at the wrong value."),
          "set RWKV_KD_ALPHA=0.5",
          'if exist "%DIR%\\decay_%STAMP%.log" del /q "%DIR%\\decay_%STAMP%.log"',
          '.venv\\Scripts\\python.exe scratchpad/write_decay_setup.py scratchpad/bughunt/diag_%s %s_ws %s_d %%DIR%%\\decay.toml train_db_5k_h1 1 5000 0.05 1e-3 65536 > "%%DIR%%\\dsetup_%%STAMP%%.log" 2>&1' % (tag, tag, tag),
          "if not %ERRORLEVEL%==0 (",
          '  echo DIAG DSETUP_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_22 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 22",
          ")",
          rem("The decay must start from the step the WS phase actually reached."),
          'findstr /C:"' + tag + '_ws_%STEPS%" "%DIR%\\dsetup_%STAMP%.log" >nul',
          "if not %ERRORLEVEL%==0 (",
          '  echo DIAG WRONGCKPT %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_32 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 32",
          ")",
          '.venv\\Scripts\\python.exe -u -m rwkv.train_rwkv --config %DIR%\\decay.toml > "%DIR%\\decay_%STAMP%.log" 2>&1',
          "if not %ERRORLEVEL%==0 (",
          '  echo DIAG DECAY_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_23 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 23",
          ")",
          rem("Guards derived from the value set above, not typed independently: a guard that"),
          rem("names a different number than its env is how two runs went wrong in one day."),
          'findstr /C:"alpha FIXED at 0.5" "%DIR%\\decay_%STAMP%.log" >nul',
          "if not %ERRORLEVEL%==0 (",
          '  echo DIAG WRONGALPHA %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_36 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 36",
          ")",
          'if not exist "%DIR%\\' + tag + '_d_%STEPS%.pth" (',
          '  echo DIAG DECAY_SHORT %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_28 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 28",
          ")",
          'echo DIAG DECAY_OK alpha 0.5 %TIME% >> "%LOG%"']

    # ---- phase C: 20-user eval ---------------------------------------------------------
    L += ["", rem("---- PHASE C: %d-user rectified eval ----" % (EVAL_USERS[1] - EVAL_USERS[0] + 1)),
          "set RWKV_KD_MIX=",
          "set RWKV_KD_ALPHA=",
          "set RWKV_EVAL_PAVA=1",
          '.venv\\Scripts\\python.exe scratchpad/write_eval_toml.py scratchpad/bughunt/diag_%s %s_d %%DIR%%\\eval.toml RWKV-%%TAG%% RWKV-P-%%TAG%% %d %d > "%%DIR%%\\etoml_%%STAMP%%.log" 2>&1' % (tag, tag, EVAL_USERS[0], EVAL_USERS[1]),
          "if not %ERRORLEVEL%==0 (",
          '  echo DIAG ETOML_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_24 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 24",
          ")",
          rem("A stale result jsonl would be RESUMED from, not overwritten -- eval_sharded skips"),
          rem("users already present, so a rerun would silently mix two models' users."),
          'if exist "result\\RWKV-%TAG%.jsonl" del /q "result\\RWKV-%TAG%.jsonl"',
          'if exist "result\\RWKV-P-%TAG%.jsonl" del /q "result\\RWKV-P-%TAG%.jsonl"',
          '.venv\\Scripts\\python.exe -u optimization/eval_sharded.py --config %DIR%\\eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\\eval_%STAMP%.log" 2>&1',
          "if not %ERRORLEVEL%==0 (",
          '  echo DIAG EVAL_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_25 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 25",
          ")",
          'if not exist "result\\RWKV-P-%TAG%.jsonl" (',
          '  echo DIAG NORESULT %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_26 %DATE% %TIME% >> "%LOG%"',
          "  exit /b 26",
          ")",
          'echo DIAG EVAL_OK %TIME% >> "%LOG%"',
          "",
          rem("The terminal marker goes BEFORE endlocal. endlocal restores the pre-setlocal"),
          rem("environment, so %LOG% would expand to EMPTY and the marker would be written to"),
          rem('"" -- which stranded a four-job chain for 45 min on 2026-08-18.'),
          'echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"',
          "endlocal & exit /b 0"]
    return L


def validate(text):
    problems, lines = [], text.replace("\r\n", "\n").split("\n")
    if not re.search(r"^cd /d ", text, re.M):
        problems.append("no cd /d")
    setpos, usepos = {}, {}
    for n, l in enumerate(lines):
        m = re.match(r"\s*set\s+([A-Za-z_][A-Za-z0-9_]*)=", l)
        if m and m.group(1).upper() not in setpos:
            setpos[m.group(1).upper()] = n
        if l.strip().upper().startswith("REM"):
            continue
        for v in re.findall(r"%([A-Za-z_][A-Za-z0-9_]*)%", l):
            usepos.setdefault(v.upper(), n)
    for v, un in usepos.items():
        if v in {"DATE", "TIME", "ERRORLEVEL", "RANDOM", "CD"}:
            continue
        if v not in setpos:
            problems.append("%%%s%% used at line %d, never set" % (v, un + 1))
        elif setpos[v] > un:
            problems.append("%%%s%% used at line %d before set at %d" % (v, un + 1, setpos[v] + 1))
    el = [n for n, l in enumerate(lines) if l.strip().lower() == "endlocal"]
    de = [n for n, l in enumerate(lines) if l.strip().startswith("echo DONE_EXIT_")]
    if el and de and min(el) < max(de):
        problems.append("endlocal precedes a DONE_EXIT_ echo")
    if text.count("DONE_EXIT_0") != 1:
        problems.append("expected exactly one DONE_EXIT_0")
    for l in lines:
        if l.strip().upper().startswith("REM"):
            bad = [c for c in "<>&|^" if c in l]
            if bad:
                problems.append("redirection char %s in REM: %s" % (bad, l[:60]))
    # the guard must name the alpha the runner sets for the decay
    for n, l in enumerate(lines):
        m = re.search(r'findstr /C:"alpha FIXED at ([0-9.]+)"', l)
        if m:
            env = None
            for prev in lines[:n]:
                mm = re.match(r"\s*set\s+RWKV_KD_ALPHA=(.*)$", prev)
                if mm and mm.group(1).strip():
                    env = mm.group(1).strip()
            if env is None or abs(float(env) - float(m.group(1))) > 1e-9:
                problems.append("guard/value desync: guard %s, env %s" % (m.group(1), env))
    return problems


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    tag = sys.argv[1]
    lever = {}
    for a in sys.argv[2:]:
        k, _, v = a.partition("=")
        lever[k] = v
    d = os.path.join("scratchpad", "bughunt", "diag_" + tag)
    os.makedirs(d, exist_ok=True)
    io.open(os.path.join(d, "ws.toml"), "w", encoding="ascii", newline="\n").write(
        WS_TOML.format(tag=tag, steps=DIAG_STEPS))
    text = "\n".join(build(tag, lever)).replace("\n", "\r\n")
    problems = validate(text)
    if problems:
        print("REFUSING to write -- the runner fails its own guards:")
        for p in problems:
            print("   ! " + p)
        return 1
    out = os.path.join(d, "run_diag_%s.cmd" % tag)
    io.open(out, "w", encoding="ascii", newline="").write(text)
    print("wrote %s (%d bytes) + %s/ws.toml" % (out, len(text), d))
    print("lever: %s" % (lever or "none (champion path)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
