"""Generate run_realcyc_resume.cmd (+ a wrapper) -- resume realcyc's WS from its newest checkpoint
after the gen-5 train db is moved from F: (USB HDD) to C: (SSD).

WHY (2026-09-03 16:30): realcyc trains at 0.23-0.29 steps/s against gen4base's 0.69 from the same
drive. Mechanism, measured: F: is at its random-read ceiling (225 reads/s, ~11.5 MB/s, queue 3),
gen-5 rows are 1.5x wider (69 vs 46 card-feature columns), and the first 1,000 steps were fast only
because the rebuild's check scripts had left those pages in the file cache. Fragmentation is ruled
out (47,557 extents vs gen 4's 47,367); RAM is not the cause (workers' PRIVATE memory 2.7 GB each;
the 21 GB working sets are the LMDB file cache). The fix is the SSD, which needs C: space, which
needs a deletion -- Andrew's call. This generator makes the switch cost minutes once he decides.

PROCEDURE at switch time (in this order, or lorawd fires early):
  1. kill the v3 WAITER cmd FIRST (its `call` returning writes DONE_EXIT_0 to wait_realcyc3.log,
     which is lorawd's trigger), then the runner cmd, then the python tree.
  2. move_lmdb.py train_db_5k_h1_id5 ; finalize_lmdb.py train_db_5k_h1_id5  (F: path -> junction;
     no toml or guard string changes).
  3. python scratchpad/make_resume.py scratchpad/realcyc rc_ws scratchpad/realcyc/ws.toml
        scratchpad/realcyc/ws_resume.toml
  4. preflight both generated .cmd, then detach run_realcyc_resume_wrap.cmd (literal quoted path).

WHAT CHANGES vs run_realcyc.cmd, and nothing else (mk54_resume.py's shape):
  1. the WS phase points at ws_resume.toml and sets RWKV_RESUME_SKIP_GROUPS=1 (mandatory: without it
     train_rwkv re-trains the already-seen prefix and drops the tail); cleared before decay.
  2. (the runner already guards on the rc_ws_10935.pth ARTIFACT before decay -- kept as is.)
  3. STAMP=resume so the resumed WS writes a NEW log; the pre-switch ws log stays on disk.
  4. the wrapper appends the two lines the dead v3 waiter would have written to wait_realcyc3.log,
     so lorawd's waiter keeps its trigger.
CAVEAT carried into the verdict: the resumed tail's dropout draws differ (weights/optimizer exact);
statistically equivalent, not bit-reproducible.
"""
import io
import os
import re

os.chdir(r"C:\Users\Andrew\rwkv-anki-autoresearch")
SRC = "scratchpad/realcyc/run_realcyc.cmd"
DST = "scratchpad/realcyc/run_realcyc_resume.cmd"
WRAP = "scratchpad/realcyc/run_realcyc_resume_wrap.cmd"
s = io.open(SRC, encoding="ascii", newline="").read()
assert "\r\n" not in s, "runner is LF; generator assumes LF"

OLD_WS = ('.venv\\Scripts\\python.exe -u -m rwkv.train_rwkv --config scratchpad/realcyc/ws.toml '
          '> "%DIR%\\ws_%STAMP%.log" 2>&1\n')
NEW_WS = ('REM RESUMED from the newest rc_ws checkpoint after the gen-5 train db moved to the SSD.\n'
          'REM SKIP_GROUPS is mandatory: without it train_rwkv re-trains the seen prefix and drops the tail.\n'
          'set RWKV_RESUME_SKIP_GROUPS=1\n'
          'echo === WS RESUME %TIME% === >> "%LOG%"\n'
          '.venv\\Scripts\\python.exe -u -m rwkv.train_rwkv --config scratchpad/realcyc/ws_resume.toml '
          '> "%DIR%\\ws_%STAMP%.log" 2>&1\n')
assert s.count(OLD_WS) == 1, "WS line not found verbatim"
s = s.replace(OLD_WS, NEW_WS, 1)

OLD_B = "REM ---- PHASE B: decay, ratio 1.0 ----\n"
GUARD = "set RWKV_RESUME_SKIP_GROUPS=\n"  # the runner already carries the rc_ws_%STEPS%.pth artifact guard
assert s.count(OLD_B) == 1, "phase B marker not found"
s = s.replace(OLD_B, GUARD + OLD_B, 1)

assert s.count("set STAMP=%RANDOM%%RANDOM%\n") == 1
s = s.replace("set STAMP=%RANDOM%%RANDOM%\n", "set STAMP=resume\n", 1)

HEADER = ("@echo off\n"
          "REM ==== RESUME RUNNER generated by mk_realcyc_resume.py -- see its docstring. Do NOT edit while running.\n")
assert s.startswith("@echo off\n")
s = HEADER + s[len("@echo off\n"):]

# ---- output guards: what leaked IN and what SURVIVED ----
assert "scratchpad/realcyc/ws.toml " not in s and 'scratchpad/realcyc/ws.toml"' not in s, "old WS toml survived"
assert s.count("ws_resume.toml") == 1
assert s.count("set RWKV_RESUME_SKIP_GROUPS=1\n") == 1 and s.count("set RWKV_RESUME_SKIP_GROUPS=\n") == 1
assert s.index("set RWKV_RESUME_SKIP_GROUPS=1\n") < s.index("set RWKV_RESUME_SKIP_GROUPS=\n") < s.index(OLD_B)
assert s.count("STAMP=resume") == 1
for v in ("DIR", "LOG", "STAMP", "TAG", "STEPS"):
    assert s.index("set %s=" % v) < s.index("%%%s%%" % v), "%s used before set" % v
assert s.index('echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"') < s.index("endlocal & exit /b 0")
assert "cd /d C:\\Users\\Andrew\\rwkv-anki-autoresearch" in s
io.open(DST, "w", encoding="ascii", newline="").write(s)

wrap = ("@echo off\n"
        "REM Wrapper: call the resume runner, then write the two lines the (killed) v3 waiter would have\n"
        "REM written to wait_realcyc3.log -- lorawd's waiter polls that file for an anchored DONE_EXIT_.\n"
        "setlocal\n"
        "cd /d C:\\Users\\Andrew\\rwkv-anki-autoresearch\n"
        "set WLOG=C:\\Users\\Andrew\\rwkv-anki-autoresearch\\scratchpad\\realcyc\\wait_realcyc3.log\n"
        "echo resume wrapper start %DATE% %TIME% >> \"%WLOG%\"\n"
        "call C:\\Users\\Andrew\\rwkv-anki-autoresearch\\scratchpad\\realcyc\\run_realcyc_resume.cmd\n"
        "echo run_realcyc_resume returned %ERRORLEVEL% %DATE% %TIME% >> \"%WLOG%\"\n"
        "echo DONE_EXIT_0 %DATE% %TIME% >> \"%WLOG%\"\n"
        "endlocal & exit /b 0\n")
io.open(WRAP, "w", encoding="ascii", newline="").write(wrap)
print("wrote", DST, "and", WRAP)
