"""Generate scratchpad/iter55_rgate/run_iter55.cmd from the (repaired) iter-54 runner.

Iter 55 gates the delta rule's in-context learning rate `a` on an FSRS-form retrievability computed
from the ACTUAL elapsed time (RWKV_RGATE=card). Full WS + decay: the gate has weights, so it acts
from step 1 and cannot warm-start from the champion's WS-final the way iter 52 does.

Generated by textual substitution so the env block and every existing guard are inherited verbatim.

★ THIS GENERATOR HAS OUTPUT GUARDS, WHICH IS THE WHOLE POINT. mk53.py and mk54.py built the runner
as `HEADER + s[s.index("setlocal"):]` and thereby DELETED `cd /d` and the entire
DIR/LOG/STAMP/DUMP/WSSTEPS/MAXSTEPS block, because in the source runner those lines sit ABOVE
`setlocal`. Both would have died in seconds without writing a DONE_EXIT_ line, hanging the chain.
Every assert in those two files checked that stale text had not leaked IN; none checked that
required setup had SURVIVED. So this one asserts on the OUTPUT: `cd /d` present, every %VAR%
declared before first use, exactly one DONE_EXIT_0, and the WS toml actually on disk (they forgot
that too). scratchpad/preflight_runner.py re-checks all of it independently.
"""
import io
import os
import re

BS = chr(92)
SRC = "scratchpad/iter54_cmixpow/run_iter54.cmd"
DST = "scratchpad/iter55_rgate/run_iter55.cmd"

s = io.open(SRC, encoding="ascii", newline="").read().replace("\r\n", "\n")

# --- retarget: run dir, prefixes, tags ---
s = s.replace("scratchpad/iter54_cmixpow", "scratchpad/iter55_rgate")
s = s.replace("scratchpad" + BS + "iter54_cmixpow", "scratchpad" + BS + "iter55_rgate")
s = s.replace("i54_ws", "i55_ws").replace("i54_d", "i55_d")
s = s.replace("i54_decay.toml", "i55_decay.toml").replace("i54_eval.toml", "i55_eval.toml")
s = s.replace("RWKV-iter54_cmixpow", "RWKV-iter55_rgate")
s = s.replace("RWKV-P-iter54_cmixpow", "RWKV-P-iter55_rgate")
s = s.replace("iter54.log", "iter55.log")
s = s.replace("ITER 54 (learnable channel-mixer exponent)", "ITER 55 (retrievability-gated `a`)")
s = s.replace("ITER54 WRONG_PARAM_COUNT", "ITER55 WRONG_PARAM_COUNT")

# --- the lever ---
s = s.replace(
    "REM ---- THE LEVER: the channel mixer exponent becomes learnable, 13 scalars ----\n"
    "set RWKV_CMIX_POW=1",
    "REM ---- THE LEVER: FSRS-form retrievability gates the delta rule's rate `a` (card stream) ----\n"
    "set RWKV_RGATE=card",
)
# Only the SET line can be checked here -- iter 54's header prose still names its lever at this
# point and is replaced further down; the `stale` loop on the final output catches that.
assert "set RWKV_CMIX_POW" not in s, "iter 54's lever SET line survived the substitution"
assert s.count("set RWKV_RGATE=card") == 1

# --- the param guard: 558,212 champion + 324 (2 gated layers x [80+1 log_s, 80 d, 1 gain]) ---
s = s.replace("assert_param_count.py 558225", "assert_param_count.py 558536")
s = s.replace(
    "REM PHASE 0: the lever must reach the BUILT MODEL. A banner would only prove the env var was\n"
    "REM read; the param count is consumed state and can only be 558,225 if all 13 cmix_pow\n"
    "REM Parameters exist. The champion is 558,212.",
    "REM PHASE 0c: the lever must reach the BUILT MODEL. A banner would only prove the env var was\n"
    "REM read; the param count is CONSUMED state and can only be 558,536 if both gated layers built\n"
    "REM their three tensors. The champion is 558,212; the gate adds exactly 324.\n"
    "REM Verified 2026-08-17 under this exact env -- and the first attempt at it read 558,533,\n"
    "REM because the ad-hoc env omitted RWKV_PAVA_LAMBDA and lost its 3 learnable thetas. That is\n"
    "REM the guard doing its job on the person writing the guard.",
)
assert "558536" in s and "558225" not in s

# --- phase 0a/0b: the two CPU smokes, in front of the param guard ---
anchor = "REM PHASE 0c: the lever must reach the BUILT MODEL."
assert anchor in s
PHASE0 = "\n".join([
    "REM ================= PHASE 0a: the plumbing smoke (CPU, no GPU) =================",
    "REM log_dt is the first RAW INPUT FEATURE ever threaded into the recurrence, and under",
    "REM RWKV_INTERLEAVE it must be gathered with each split's own canonical indices. An off-by-one",
    "REM there is invisible: the model still trains and still evaluates, it just gates every review",
    "REM on some OTHER review's elapsed time. The smoke asserts ON-at-init equals OFF BIT-FOR-BIT",
    "REM (gain is zero-init), that a real gain moves the output, that all 8 tensors get finite",
    "REM non-zero grads, and that the recovered log_dt is physically log-seconds.",
    '.venv' + BS + 'Scripts' + BS + 'python.exe scratchpad' + BS + 'parity3' + BS + 'smoke_rgate.py >> "%LOG%" 2>&1',
    "if not %ERRORLEVEL%==0 (",
    '  echo ITER55 RGATE_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"',
    '  echo DONE_EXIT_46 >> "%LOG%"',
    "  exit /b 46",
    ")",
    "",
    "REM ============ PHASE 0b: the scripted-eval guard (iter 48's lesson) ============",
    "REM Training and QAT evals both run RWKV_NO_JIT=1, so a PLAIN eval is the ONLY path that",
    "REM scripts the model -- a TorchScript-runtime bug is invisible until then, i.e. after the full",
    "REM training spend. iter 48 lost its eval that way. load_state_dict is STRICT and no existing",
    "REM checkpoint has the rgate keys, so a throwaway random one is built first; the guard is about",
    "REM CODE PATHS, not weights, and its logloss is discarded.",
    'set RWKV_NO_JIT=',
    '.venv' + BS + 'Scripts' + BS + 'python.exe scratchpad/parity3/make_smoke_ckpt.py '
    'scratchpad/iter55_rgate/i55_smoke_1.pth >> "%LOG%" 2>&1',
    "if not %ERRORLEVEL%==0 (",
    '  echo ITER55 SMOKE_CKPT_FAILED %DATE% %TIME% >> "%LOG%"',
    '  echo DONE_EXIT_47 >> "%LOG%"',
    "  exit /b 47",
    ")",
    '.venv' + BS + 'Scripts' + BS + 'python.exe scratchpad/write_eval_toml.py scratchpad/iter55_rgate '
    'i55_smoke scratchpad/iter55_rgate/i55_smoke.toml RWKV-i55smoke RWKV-P-i55smoke 5001 5001 '
    '>> "%LOG%" 2>&1',
    "if not %ERRORLEVEL%==0 (",
    '  echo ITER55 SMOKE_TOML_FAILED %DATE% %TIME% >> "%LOG%"',
    '  echo DONE_EXIT_48 >> "%LOG%"',
    "  exit /b 48",
    ")",
    "REM Git" + BS + "bin" + BS + "bash.exe, NOT Git" + BS + "usr" + BS + "bin" + BS + "bash.exe: the raw MSYS binary has no MSYS",
    "REM PATH when cmd.exe starts it, so the script dies on 'dirname: command not found'. That plus a",
    "REM missing toml argument is exactly how iter 52's first launch died in 0.07 s.",
    '"C:' + BS + 'Program Files' + BS + 'Git' + BS + 'bin' + BS + 'bash.exe" scratchpad/parity3/smoke_scripted_eval.sh '
    'scratchpad/iter55_rgate/i55_smoke.toml > "%DIR%' + BS + 'smoke_%STAMP%.log" 2>&1',
    "if not %ERRORLEVEL%==0 (",
    '  echo ITER55 SCRIPTED_EVAL_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"',
    '  echo DONE_EXIT_45 >> "%LOG%"',
    "  exit /b 45",
    ")",
    'del /q scratchpad' + BS + 'iter55_rgate' + BS + 'i55_smoke_1.pth 2>nul',
    "REM ** RESTORE IT. The guard above has to clear RWKV_NO_JIT (a scripted eval is the whole",
    "REM point), but WS and decay must train with it SET: RWKV_QAT_COMPILE / torch.compile cannot",
    "REM trace a ScriptModule, and leaving it cleared would silently train a different",
    "REM configuration from the champion's. Caught by reading the generated file, then guarded in",
    "REM preflight_runner.py so the next runner cannot repeat it.",
    "set RWKV_NO_JIT=1",
    'echo ITER55 SMOKES_OK %TIME% >> "%LOG%"',
    "",
])
s = s.replace(anchor, PHASE0 + anchor, 1)

# --- header prose ---
HEADER = [
    "@echo off",
    "REM ===========================================================================================",
    "REM ITER 55: RETRIEVABILITY-GATED STATE UPDATE (RWKV_RGATE=card).",
    "REM Family: EXPRESSIVENESS / domain structure. Approved by Andrew 2026-08-17 after he asked for",
    "REM genuinely big architectural changes and pointed at FSRS.",
    "REM",
    "REM THE MECHANISM, read from FSRS's own code (srs-benchmark/models/fsrs_v7.py step()):",
    "REM   R     = forgetting_curve(dt, S, S_short, D)    time enters the READOUT",
    "REM   S_new = next_stability(S, D, R, rating)        and R then GATES the state update",
    "REM FSRS's state does NOT decay in real time; it is unchanged between reviews. What pays is that",
    "REM the SIZE of the update is scaled by predicted retrievability: recall something you were",
    "REM likely to have forgotten and stability jumps; recall something you would have remembered",
    "REM anyway and it barely moves. That is the spacing effect as STRUCTURE.",
    "REM",
    "REM WHY OUR MODEL IS THE RIGHT TARGET. RWKV-7 already HAS the matching mechanism: `a` is",
    "REM literally an in-context learning rate, with delta-direction eigenvalue w minus a times the",
    "REM squared kappa norm. And we MEASURED it sitting idle on this trunk: that product is about",
    "REM 0.13 against a reachable 0.95, moving the eigenvalue about 0.15 against a decay of 0.98. So",
    "REM the one RWKV-7 mechanism that structurally matches FSRS's core update is the one this trunk",
    "REM barely uses.",
    "REM",
    "REM ** THE CONSTRAINT THAT MAKES IT A LEVER AND NOT A CAPACITY ADD (capacity-at-5k is 0/3).",
    "REM A second learned function of the same x the a-LoRA already sees is ABSORBABLE by it and adds",
    "REM nothing. What survives the REDUNDANCY TEST is FSRS's FUNCTIONAL FORM -- an interaction",
    "REM between a learned scalar and the ACTUAL ELAPSED TIME, which no rank-4 LoRA over x can",
    "REM express:  rhat = (1 + dt/s) to the power -d,  then  a_logit += gain times (1 - rhat).",
    "REM Computed in log space as exp(-d times softplus(log_dt - log_s)), which is the same function",
    "REM for every real input: no clamp, no NaN branch.",
    "REM",
    "REM ** BOUNDED BY CONSTRUCTION, the check iter 51 lacked. rhat lies in (0,1] for EVERY input, so",
    "REM the added logit term lies in [0, abs(gain)] -- a WORST-CASE bound, not a typical-case",
    "REM statistic. A median cannot see a blow-up; only a max can. `a` then passes through sigmoid.",
    "REM",
    "REM gain is ZERO-INIT, so the model is bit-identical to the champion at init (measured at",
    "REM 0.000e+00, not asserted) and the lever must earn its way in. All three tensors land in",
    "REM other_params at wd=0 deliberately: weight decay on a zero-init gain would pin it at zero and",
    "REM make the null hypothesis unfalsifiable rather than a finding.",
    "REM",
    "REM GATE: PLAIN basis vs iter 45 == 0.297697 ahead / 0.265375 imm on the VAL half, BOTH-modes",
    "REM rule (this changes the shared trunk, so the curve-side exception does not apply).",
    "REM Params 558,536 == 558,212 plus 324. Per-entity state sizes UNCHANGED, so the frozen 9-byte",
    "REM card budget holds.",
    "REM PRE-REGISTERED counter-hypotheses (write the verdict against these, not after the fact):",
    "REM   1. gain trains to ~0     == surprise-gating adds nothing; the generic recurrence already",
    "REM      does what FSRS needs explicit structure for. Same shape as iter 48's learned-but-",
    "REM      negligible coupling.",
    "REM   2. gain moves, logloss does not == the trunk already had the information (iter 48/50).",
    "REM   3. it helps == the delta rule was idle because nothing pointed it at the right signal.",
    "REM REPORT the learned gain per gated layer, as iter 54 reports its 13 cmix_pow values.",
    "REM DEPLOY DEBT: forward-pass change, so it needs the Rust port plus a fresh parity trace before",
    "REM anything ships. The Python RNN mirror and a parity_train_vs_rnn case are already in.",
    "REM",
    "REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not a",
    "REM safe undo, because line endings shift the byte offset cmd.exe resumes from).",
    "REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.",
    "REM ===========================================================================================",
]
body = s[s.index("setlocal"):]
out = "\n".join(HEADER) + "\n" + body

# ---------------- OUTPUT GUARDS: what mk53/mk54 did not have ----------------
# Stale-identifier check applies to the EXECUTABLE BODY, not the header. A wrong path or prefix in
# a line cmd.exe runs is the dangerous thing; a prose cross-reference ("as iter 54 reports its 13
# cmix_pow values") is legitimate and a blanket ban on the string forbids it. The header gets its
# own, narrower check -- that its TITLE names this iteration -- which is the hazard mk54.py
# actually hit (a runner that executes correctly while describing the wrong experiment).
body_low = out[out.index("setlocal"):].lower()
for stale in ("iter54", "iter 54", "i54_", "cmix_pow", "cmixpow"):
    assert stale not in body_low, "stale iter-54 text leaked into the executable body: " + stale
header_low = out[:out.index("setlocal")].lower()
assert "rem iter 55:" in header_low, "the header does not announce ITER 55"
assert "rem iter 54:" not in header_low, "the header still announces ITER 54"

assert re.search(r"^cd /d ", out, re.M), "cd /d was DELETED -- the mk54 bug"
lines = out.split("\n")
setpos, usepos = {}, {}
for n, ln in enumerate(lines):
    m = re.match(r"\s*set\s+([A-Za-z_][A-Za-z0-9_]*)=", ln)
    if m and m.group(1).upper() not in setpos:
        setpos[m.group(1).upper()] = n
    for v in re.findall(r"%([A-Za-z_][A-Za-z0-9_]*)%", ln):
        usepos.setdefault(v.upper(), n)
BUILTIN = {"DATE", "TIME", "ERRORLEVEL", "RANDOM", "CD"}
for v, un in usepos.items():
    if v in BUILTIN:
        continue
    assert v in setpos, f"%{v}% used at line {un + 1} but never set"
    assert setpos[v] < un, f"%{v}% used at line {un + 1} before being set at {setpos[v] + 1}"

assert out.count("DONE_EXIT_0") == 1, "the waiter's success signal must appear exactly once"
assert os.path.isfile("scratchpad/iter55_rgate/i55_ws.toml"), (
    "i55_ws.toml is missing -- mk53/mk54 forgot exactly this and the WS phase died on --config")
assert "set RWKV_AUGMENT_SEED=4321" in out and "architecture_d80_lora4_cnd.py" in out
assert out.count("set RWKV_KD_ALPHA=0.9") == 1 and out.count("set RWKV_KD_ALPHA=0.5") == 1, (
    "the champion's KD schedule (0.9 in WS, 0.5 in decay) must be preserved verbatim")
for ln in lines:
    if ln.strip().upper().startswith("REM"):
        bad = [c for c in "<>&|^" if c in ln]
        assert not bad, "redirection char " + str(bad) + " in REM line: " + ln

io.open(DST, "w", encoding="ascii", newline="\r\n").write(out)
print("wrote", DST, len(out), "bytes,", out.count(chr(10)), "lines")
