@echo off
REM ===========================================================================================
REM ITER 55: RETRIEVABILITY-GATED STATE UPDATE (RWKV_RGATE=card).
REM Family: EXPRESSIVENESS / domain structure. Approved by Andrew 2026-08-17 after he asked for
REM genuinely big architectural changes and pointed at FSRS.
REM
REM THE MECHANISM, read from FSRS's own code (srs-benchmark/models/fsrs_v7.py step()):
REM   R     = forgetting_curve(dt, S, S_short, D)    time enters the READOUT
REM   S_new = next_stability(S, D, R, rating)        and R then GATES the state update
REM FSRS's state does NOT decay in real time; it is unchanged between reviews. What pays is that
REM the SIZE of the update is scaled by predicted retrievability: recall something you were
REM likely to have forgotten and stability jumps; recall something you would have remembered
REM anyway and it barely moves. That is the spacing effect as STRUCTURE.
REM
REM WHY OUR MODEL IS THE RIGHT TARGET. RWKV-7 already HAS the matching mechanism: `a` is
REM literally an in-context learning rate, with delta-direction eigenvalue w minus a times the
REM squared kappa norm. And we MEASURED it sitting idle on this trunk: that product is about
REM 0.13 against a reachable 0.95, moving the eigenvalue about 0.15 against a decay of 0.98. So
REM the one RWKV-7 mechanism that structurally matches FSRS's core update is the one this trunk
REM barely uses.
REM
REM ** THE CONSTRAINT THAT MAKES IT A LEVER AND NOT A CAPACITY ADD (capacity-at-5k is 0/3).
REM A second learned function of the same x the a-LoRA already sees is ABSORBABLE by it and adds
REM nothing. What survives the REDUNDANCY TEST is FSRS's FUNCTIONAL FORM -- an interaction
REM between a learned scalar and the ACTUAL ELAPSED TIME, which no rank-4 LoRA over x can
REM express:  rhat = (1 + dt/s) to the power -d,  then  a_logit += gain times (1 - rhat).
REM Computed in log space as exp(-d times softplus(log_dt - log_s)), which is the same function
REM for every real input: no clamp, no NaN branch.
REM
REM ** BOUNDED BY CONSTRUCTION, the check iter 51 lacked. rhat lies in (0,1] for EVERY input, so
REM the added logit term lies in [0, abs(gain)] -- a WORST-CASE bound, not a typical-case
REM statistic. A median cannot see a blow-up; only a max can. `a` then passes through sigmoid.
REM
REM gain is ZERO-INIT, so the model is bit-identical to the champion at init (measured at
REM 0.000e+00, not asserted) and the lever must earn its way in. All three tensors land in
REM other_params at wd=0 deliberately: weight decay on a zero-init gain would pin it at zero and
REM make the null hypothesis unfalsifiable rather than a finding.
REM
REM GATE: PLAIN basis vs iter 45 == 0.297697 ahead / 0.265375 imm on the VAL half, BOTH-modes
REM rule (this changes the shared trunk, so the curve-side exception does not apply).
REM Params 558,536 == 558,212 plus 324. Per-entity state sizes UNCHANGED, so the frozen 9-byte
REM card budget holds.
REM PRE-REGISTERED counter-hypotheses (write the verdict against these, not after the fact):
REM   1. gain trains to ~0     == surprise-gating adds nothing; the generic recurrence already
REM      does what FSRS needs explicit structure for. Same shape as iter 48's learned-but-
REM      negligible coupling.
REM   2. gain moves, logloss does not == the trunk already had the information (iter 48/50).
REM   3. it helps == the delta rule was idle because nothing pointed it at the right signal.
REM REPORT the learned gain per gated layer, as iter 54 reports its 13 cmix_pow values.
REM DEPLOY DEBT: forward-pass change, so it needs the Rust port plus a fresh parity trace before
REM anything ships. The Python RNN mirror and a parity_train_vs_rnn case are already in.
REM
REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not a
REM safe undo, because line endings shift the byte offset cmd.exe resumes from).
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter55_rgate
set LOG=%DIR%\iter55.log
set STAMP=%RANDOM%%RANDOM%
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935
REM BUDGET: 0 = full budget
set MAXSTEPS=0
echo ===== ITER 55 (retrievability-gated `a`) START %DATE% %TIME% ===== >> "%LOG%"
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
REM ---- THE LEVER: FSRS-form retrievability gates the delta rule's rate `a` (card stream) ----
set RWKV_RGATE=card
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_GRAD_STATS=%DIR%\grad_stats.json
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.9
if not "%MAXSTEPS%"=="0" set RWKV_MAX_STEPS=%MAXSTEPS%
if not "%MAXSTEPS%"=="0" set RWKV_BENCH_WARMUP=100000


REM ================= PHASE 0a: the plumbing smoke (CPU, no GPU) =================
REM log_dt is the first RAW INPUT FEATURE ever threaded into the recurrence, and under
REM RWKV_INTERLEAVE it must be gathered with each split's own canonical indices. An off-by-one
REM there is invisible: the model still trains and still evaluates, it just gates every review
REM on some OTHER review's elapsed time. The smoke asserts ON-at-init equals OFF BIT-FOR-BIT
REM (gain is zero-init), that a real gain moves the output, that all 8 tensors get finite
REM non-zero grads, and that the recovered log_dt is physically log-seconds.
.venv\Scripts\python.exe scratchpad\parity3\smoke_rgate.py >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER55 RGATE_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 >> "%LOG%"
  exit /b 46
)

REM ============ PHASE 0b: the scripted-eval guard (iter 48's lesson) ============
REM Training and QAT evals both run RWKV_NO_JIT=1, so a PLAIN eval is the ONLY path that
REM scripts the model -- a TorchScript-runtime bug is invisible until then, i.e. after the full
REM training spend. iter 48 lost its eval that way. load_state_dict is STRICT and no existing
REM checkpoint has the rgate keys, so a throwaway random one is built first; the guard is about
REM CODE PATHS, not weights, and its logloss is discarded.
set RWKV_NO_JIT=
.venv\Scripts\python.exe scratchpad/parity3/make_smoke_ckpt.py scratchpad/iter55_rgate/i55_smoke_1.pth >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER55 SMOKE_CKPT_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_47 >> "%LOG%"
  exit /b 47
)
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/iter55_rgate i55_smoke scratchpad/iter55_rgate/i55_smoke.toml RWKV-i55smoke RWKV-P-i55smoke 5001 5001 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER55 SMOKE_TOML_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_48 >> "%LOG%"
  exit /b 48
)
REM Git\bin\bash.exe, NOT Git\usr\bin\bash.exe: the raw MSYS binary has no MSYS
REM PATH when cmd.exe starts it, so the script dies on 'dirname: command not found'. That plus a
REM missing toml argument is exactly how iter 52's first launch died in 0.07 s.
"C:\Program Files\Git\bin\bash.exe" scratchpad/parity3/smoke_scripted_eval.sh scratchpad/iter55_rgate/i55_smoke.toml > "%DIR%\smoke_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER55 SCRIPTED_EVAL_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_45 >> "%LOG%"
  exit /b 45
)
del /q scratchpad\iter55_rgate\i55_smoke_1.pth 2>nul
REM ** RESTORE IT. The guard above has to clear RWKV_NO_JIT (a scripted eval is the whole
REM point), but WS and decay must train with it SET: RWKV_QAT_COMPILE / torch.compile cannot
REM trace a ScriptModule, and leaving it cleared would silently train a different
REM configuration from the champion's. Caught by reading the generated file, then guarded in
REM preflight_runner.py so the next runner cannot repeat it.
set RWKV_NO_JIT=1
echo ITER55 SMOKES_OK %TIME% >> "%LOG%"
REM PHASE 0c: the lever must reach the BUILT MODEL. A banner would only prove the env var was
REM read; the param count is CONSUMED state and can only be 558,536 if both gated layers built
REM their three tensors. The champion is 558,212; the gate adds exactly 324.
REM Verified 2026-08-17 under this exact env -- and the first attempt at it read 558,533,
REM because the ad-hoc env omitted RWKV_PAVA_LAMBDA and lost its 3 learnable thetas. That is
REM the guard doing its job on the person writing the guard.
.venv\Scripts\python.exe scratchpad\parity3\assert_param_count.py 558536 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER55 WRONG_PARAM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_37 >> "%LOG%"
  exit /b 37
)

echo === WS %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/iter55_rgate/i55_ws.toml > "%DIR%\ws_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WSFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 21
)
findstr /C:"[interleave] round-robin layer schedule ON" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOILV %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
findstr /C:"placement = front-loaded" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGPLACEMENT %DATE% %TIME% >> "%LOG%"
  exit /b 33
)
echo WS OK %TIME% >> "%LOG%"

REM ---- THE LEVER: KD is NOT cleared. Only the alpha changes for the decay phase. ----
set RWKV_KD_ALPHA=0.5
set RWKV_GRAD_STATS=
set RWKV_MAX_STEPS=

REM Exit code 0 is not evidence the phase ran: train_rwkv has swallowed a fatal error and
REM still exited 0 (2026-08-18). Nor is "a checkpoint exists" -- an INTERRUPTED run leaves
REM one at the step it died on, which is what made the outage recovery decay a half-trained
REM model. The gate has to name the expected FINAL step.
if not exist "%DIR%\i55_ws_%WSSTEPS%.pth" (
  echo ITER55 WS_SHORT no i55_ws_%WSSTEPS%.pth %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_WSSHORT %DATE% %TIME% >> "%LOG%"
  exit /b 27
)
echo === DECAY SETUP %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/iter55_rgate i55_ws i55_d scratchpad/iter55_rgate/i55_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/iter55_rgate/i55_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
REM THE experiment's own guard: KD must actually have been ON during decay. Without this the run
REM silently reduces to the champion and would be recorded as a null.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOKD_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 35
)
findstr /C:"alpha FIXED at 0.5" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGALPHA_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 36
)
echo DECAY OK (KD ON, alpha 0.5) %TIME% >> "%LOG%"

REM Same reasoning for the decay phase: name the step, do not merely test for a .pth.
if not exist "%DIR%\i55_d_%WSSTEPS%.pth" (
  echo ITER55 DECAY_SHORT no i55_d_%WSSTEPS%.pth %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_DECAYSHORT %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
echo === EVAL TOML rect %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/iter55_rgate i55_d scratchpad/iter55_rgate/i55_eval.toml RWKV-iter55_rgate RWKV-P-iter55_rgate 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
set RWKV_MUON_BATCHED=
set RWKV_NO_JIT=
set RWKV_QAT_COMPILE=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_EVAL_PAVA=1
echo === EVAL 5001-7500 RECTIFIED attempt 1 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/iter55_rgate/i55_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo EVAL rect attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/iter55_rgate/i55_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo EVAL rect OK %TIME% >> "%LOG%"
REM The terminal marker must be written BEFORE endlocal. endlocal restores the
REM pre-setlocal environment, so LOG expands to EMPTY after it and the append
REM target becomes an empty string -- nothing is written and every downstream
REM waiter is stranded forever. Cost iter 53 a 45-minute idle GPU on 2026-08-18
REM after a run that had already finished cleanly with exit 0.
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal
exit /b 0
