"""Arm A: pure shrink -- d=32, context depth 1/2/2/2, features_fc_mult=4

Generated by scratchpad/hybrid100k/mk_arch.py -- see optimization/HYBRID_100K.md.
Priced at 84007 parameters, card state 1152 floats.

MUST be run with this arm's own RWKV_STRIP_CMIX (below); the champion's list names layers
this arm does not have and would be silently half-ignored:
    RWKV_STRIP_CMIX=card_id:1,deck_id:1,preset_id:0,preset_id:1,user_id:0,user_id:1
"""
from dataclasses import dataclass
from rwkv.model.rwkv_model import RWKV7Config

HEAD_DIM = 16
N_HEADS = 2

import os

_DROPOUT_SCALE = float(os.environ.get("RWKV_DROPOUT_SCALE") or "1")
DROPOUT = 0.02 * _DROPOUT_SCALE
DROPOUT_LONG = 0.05 * _DROPOUT_SCALE
DROPOUT_LAYER = 0.01 * _DROPOUT_SCALE


@dataclass
class AnkiRWKVConfig:
    d_model: int
    modules: list
    dropout: float
    num_curves: int = 128
    num_points: int = 128
    head_fc_mult: int = 4
    features_fc_mult: int = 4


def _m(n_layers, cmf, dropout):
    return RWKV7Config(
        d_model=HEAD_DIM * N_HEADS, n_heads=N_HEADS, n_layers=n_layers,
        layer_offset=0, total_layers=n_layers, channel_mixer_factor=cmf,
        decay_lora=4, a_lora=4, v0_mix_amt_lora=2, gate_lora=4,
        dropout=dropout, dropout_layer=DROPOUT_LAYER,
    )


_layers = [
    ("card_id", _m(2, 1.0, DROPOUT)),
    ("note_id", _m(1, 1.0, DROPOUT)),
    ("deck_id", _m(2, 1.0, DROPOUT_LONG)),
    ("preset_id", _m(2, 1.0, DROPOUT_LONG)),
    ("user_id", _m(2, 1.0, DROPOUT_LONG)),
]

DEFAULT_ANKI_RWKV_CONFIG = AnkiRWKVConfig(
    d_model=HEAD_DIM * N_HEADS, modules=_layers, dropout=DROPOUT,
    num_curves=128, num_points=128,
    head_fc_mult=4, features_fc_mult=4,
)
