"""Price candidate <=100k-parameter architectures EXACTLY, by building them.

Andrew's target is "a hybrid FSRS-RWKV with <=100k parameters". Every estimate of what
fits is worthless unless the model is actually constructed: the champion's own headline
number is 558,212 only under its full env, and 782,710 without RWKV_STRIP_CMIX -- a 40%
error from one missing variable. So this generates a real arch module per candidate and
counts the constructed model, in a subprocess (old-style ScriptModule bakes the first
construction's env flags into the compiled class, so two configs must never share a
process).

Reports params AND per-card RNN state, because state -- not parameters -- is the binding
deploy budget: Anki persists the card stream's state for every card in the collection.

Usage: .venv/Scripts/python.exe scratchpad/hybrid100k/budget.py
"""
import json
import os
import subprocess
import sys
import tempfile

REPO = os.getcwd()

TEMPLATE = '''# generated by scratchpad/hybrid100k/budget.py -- throwaway sizing arch, not a run config
from dataclasses import dataclass
from rwkv.model.rwkv_model import RWKV7Config

HEAD_DIM = {head_dim}
N_HEADS = {n_heads}
DROPOUT = 0.02
DROPOUT_LONG = 0.05
DROPOUT_LAYER = 0.01


@dataclass
class AnkiRWKVConfig:
    d_model: int
    modules: list
    dropout: float
    num_curves: int = 128
    num_points: int = 128
    head_fc_mult: int = 4
    features_fc_mult: int = 4


def _m(n_layers, cmf, dropout):
    return RWKV7Config(
        d_model=HEAD_DIM * N_HEADS, n_heads=N_HEADS, n_layers=n_layers,
        layer_offset=0, total_layers=n_layers, channel_mixer_factor=cmf,
        decay_lora={lora}, a_lora={lora}, v0_mix_amt_lora={lora2}, gate_lora={lora},
        dropout=dropout, dropout_layer=DROPOUT_LAYER,
    )


_layers = [
    ("card_id", _m({L_card}, {cmf}, DROPOUT)),
    ("note_id", _m({L_note}, {cmf}, DROPOUT)),
    ("deck_id", _m({L_deck}, {cmf}, DROPOUT_LONG)),
    ("preset_id", _m({L_preset}, {cmf}, DROPOUT_LONG)),
    ("user_id", _m({L_user}, {cmf}, DROPOUT_LONG)),
]

DEFAULT_ANKI_RWKV_CONFIG = AnkiRWKVConfig(
    d_model=HEAD_DIM * N_HEADS, modules=_layers, dropout=DROPOUT,
    num_curves={curves}, num_points={points},
    head_fc_mult={head_mult}, features_fc_mult={feat_mult},
)
'''

COUNTER = r'''
import json, os, sys
sys.path.insert(0, os.getcwd())
import torch
torch.set_num_threads(1)
from rwkv.architecture import DEFAULT_ANKI_RWKV_CONFIG as CFG
from rwkv.model.srs_model_rnn import SrsRWKVRnn
m = SrsRWKVRnn(CFG)
IDX = {i: n for i, (n, _) in enumerate(CFG.modules)}
tot, by = 0, {}
for n, p in m.named_parameters():
    parts = n.split(".")
    s = IDX[int(parts[1])] if parts[0] == "rwkv_modules" else "(model)"
    by[s] = by.get(s, 0) + p.numel()
    tot += p.numel()
H = CFG.modules[0][1].n_heads
K = CFG.d_model // H
per_layer = H * K * K + 2 * CFG.d_model
card_l = dict(CFG.modules)["card_id"].n_layers
note_l = dict(CFG.modules)["note_id"].n_layers
print("@@" + json.dumps({"total": tot, "by": by,
                         "card_state": card_l * per_layer,
                         "note_state": note_l * per_layer}))
'''


def price(name, head_dim=16, n_heads=5, L=(2, 1, 4, 3, 3), cmf=1.0, lora=4, lora2=2,
          curves=128, points=128, head_mult=4, feat_mult=4, strip_cmix=None):
    src = TEMPLATE.format(head_dim=head_dim, n_heads=n_heads, cmf=cmf, lora=lora, lora2=lora2,
                          L_card=L[0], L_note=L[1], L_deck=L[2], L_preset=L[3], L_user=L[4],
                          curves=curves, points=points, head_mult=head_mult, feat_mult=feat_mult)
    fd, path = tempfile.mkstemp(suffix=".py", dir=os.path.join(REPO, "scratchpad", "hybrid100k"))
    with os.fdopen(fd, "w") as fh:
        fh.write(src)
    env = dict(os.environ)
    env.update({
        "RWKV_ARCH_MODULE": os.path.relpath(path, REPO).replace("\\", "/"),
        "RWKV_INTERLEAVE": "1", "RWKV_GRU_HEAD": "3", "RWKV_PAVA_LAMBDA": "0.2",
        "RWKV_NO_AHEAD_RESIDUAL": "1", "RWKV_STRIP_L0_VLORA": "1", "RWKV_ZERO_FEATURES": "22",
        "RWKV_STATE_CLAMP_TAU": "300", "RWKV_STATE_CLAMP_WINDOW": "32768",
        "RWKV_NO_JIT": "1", "OMP_NUM_THREADS": "1",
    })
    if strip_cmix:
        env["RWKV_STRIP_CMIX"] = strip_cmix
    else:
        env.pop("RWKV_STRIP_CMIX", None)
    try:
        r = subprocess.run([os.path.join(REPO, ".venv", "Scripts", "python.exe"), "-c", COUNTER],
                           cwd=REPO, env=env, capture_output=True, text=True, timeout=300)
    finally:
        os.unlink(path)
    line = [x for x in r.stdout.splitlines() if x.startswith("@@")]
    if not line:
        return {"name": name, "error": (r.stderr or r.stdout).strip().splitlines()[-1:][:1]}
    d = json.loads(line[0][2:])
    d["name"] = name
    return d


CHAMP_STRIP = ("user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,"
               "deck_id:1,deck_id:2,card_id:1")

# Candidates. Each isolates ONE structural idea so the table reads as a ladder, not a pile.
CANDS = [
    dict(name="champion (d=80, 13L)", strip_cmix=CHAMP_STRIP),
    # d=48 keeps the union d95=44 covered; can it fit under 100k on depth alone?
    dict(name="d=48 ctx 1/1/1/1 (6L)", n_heads=3, L=(2,1,1,1,1), strip_cmix=CHAMP_STRIP),
    dict(name="d=48 ctx 1/1/1/1 hm2", n_heads=3, L=(2,1,1,1,1), head_mult=2, strip_cmix=CHAMP_STRIP),
    dict(name="d=48 card1 ctx 1/1/1/1", n_heads=3, L=(1,1,1,1,1), strip_cmix=CHAMP_STRIP),
    dict(name="d=48 card1 ctx1/1/1/1 hm2", n_heads=3, L=(1,1,1,1,1), head_mult=2, strip_cmix=CHAMP_STRIP),
    dict(name="d=48 ctx 1/2/1/1 hm2", n_heads=3, L=(2,1,2,1,1), head_mult=2, strip_cmix=CHAMP_STRIP),
    # K=8 shrinks STATE quadratically while keeping d
    dict(name="d=48 (H6K8) ctx 1/1/1/1", head_dim=8, n_heads=6, L=(2,1,1,1,1), strip_cmix=CHAMP_STRIP),
    dict(name="d=48 (H6K8) ctx 1/2/2/2", head_dim=8, n_heads=6, L=(2,1,2,2,2), strip_cmix=CHAMP_STRIP),
    dict(name="d=48 (H6K8) ctx1/2/2/2 hm2", head_dim=8, n_heads=6, L=(2,1,2,2,2), head_mult=2,
         strip_cmix=CHAMP_STRIP),
    dict(name="d=32 ctx 1/2/2/2 fm4", head_dim=16, n_heads=2, L=(2,1,2,2,2), strip_cmix=CHAMP_STRIP),
]

rows = []
for c in CANDS:
    nm = c.pop("name")
    rows.append(price(nm, **c))

print("%-32s %9s %9s %9s %8s %8s" % ("design", "params", "card st", "note st", "card B", "vs 100k"))
print("-" * 82)
for d in rows:
    if "error" in d:
        print("%-32s  ERROR %s" % (d["name"], d["error"]))
        continue
    # deployed card bytes at the frozen recipe: the champion's 2,880 floats ship as 9 B,
    # i.e. the PQ index budget, which scales with H*n_layers rather than with floats.
    print("%-32s %9d %9d %9d %8s %8s"
          % (d["name"], d["total"], d["card_state"], d["note_state"], "-",
             "OK" if d["total"] <= 100_000 else "+%d" % (d["total"] - 100_000)))
print()
print("card st / note st are FLOATS of RNN state per entity (the deploy budget), not bytes.")
print("Champion reference: 558,212 params, card 2,880 floats, note 1,440 floats.")
