"""Write the arm A / B / C arch files, and PROVE each is the model that was priced.

WHY THIS ASSERTS INSTEAD OF JUST WRITING. `RWKV_STRIP_CMIX` matches on the exact string
"<stream>:<layer>" (rwkv_model.py:577). Entries naming a layer that does not exist at the new
depths are SILENTLY IGNORED -- no error, no warning. The champion's list names deck_id:2,
preset_id:2 and user_id:2, none of which exist once the context streams drop to 2 layers, so
carrying it verbatim would leave a half-inert config that looks deliberate and is not. Same
family as the QAT env that was parsed and then discarded: the setting was truthful, the object
it mutated was thrown away.

So each arm gets an EXPLICIT strip list containing only layers it actually has, and this script
verifies against the constructed model that (a) exactly the intended mixers are stripped and
(b) the parameter count equals the figure recorded in optimization/HYBRID_100K.md. A mismatch
is a hard failure, not a printed note.

Usage: .venv/Scripts/python.exe scratchpad/hybrid100k/mk_arch.py
"""
import json
import os
import subprocess
import sys

REPO = os.getcwd()
OUT = os.path.join(REPO, "scratchpad", "hybrid100k")

TEMPLATE = '''"""Arm {arm}: {desc}

Generated by scratchpad/hybrid100k/mk_arch.py -- see optimization/HYBRID_100K.md.
Priced at {params} parameters, card state {card_state} floats.

MUST be run with this arm's own RWKV_STRIP_CMIX (below); the champion's list names layers
this arm does not have and would be silently half-ignored:
    RWKV_STRIP_CMIX={strip}
"""
from dataclasses import dataclass
from rwkv.model.rwkv_model import RWKV7Config

HEAD_DIM = {head_dim}
N_HEADS = {n_heads}

import os

_DROPOUT_SCALE = float(os.environ.get("RWKV_DROPOUT_SCALE") or "1")
DROPOUT = 0.02 * _DROPOUT_SCALE
DROPOUT_LONG = 0.05 * _DROPOUT_SCALE
DROPOUT_LAYER = 0.01 * _DROPOUT_SCALE


@dataclass
class AnkiRWKVConfig:
    d_model: int
    modules: list
    dropout: float
    num_curves: int = 128
    num_points: int = 128
    head_fc_mult: int = 4
    features_fc_mult: int = 4


def _m(n_layers, cmf, dropout):
    return RWKV7Config(
        d_model=HEAD_DIM * N_HEADS, n_heads=N_HEADS, n_layers=n_layers,
        layer_offset=0, total_layers=n_layers, channel_mixer_factor=cmf,
        decay_lora=4, a_lora=4, v0_mix_amt_lora=2, gate_lora=4,
        dropout=dropout, dropout_layer=DROPOUT_LAYER,
    )


_layers = [
    ("card_id", _m({L_card}, 1.0, DROPOUT)),
    ("note_id", _m({L_note}, 1.0, DROPOUT)),
    ("deck_id", _m({L_deck}, 1.0, DROPOUT_LONG)),
    ("preset_id", _m({L_preset}, 1.0, DROPOUT_LONG)),
    ("user_id", _m({L_user}, 1.0, DROPOUT_LONG)),
]

DEFAULT_ANKI_RWKV_CONFIG = AnkiRWKVConfig(
    d_model=HEAD_DIM * N_HEADS, modules=_layers, dropout=DROPOUT,
    num_curves=128, num_points=128,
    head_fc_mult={head_mult}, features_fc_mult={feat_mult},
)
'''

VERIFY = r'''
import json, os, sys
sys.path.insert(0, os.getcwd())
import torch
torch.set_num_threads(1)
from rwkv.architecture import DEFAULT_ANKI_RWKV_CONFIG as CFG
from rwkv.model.srs_model_rnn import SrsRWKVRnn
m = SrsRWKVRnn(CFG)
IDX = {i: n for i, (n, _) in enumerate(CFG.modules)}
tot, by = 0, {}
for n, p in m.named_parameters():
    parts = n.split(".")
    s = IDX[int(parts[1])] if parts[0] == "rwkv_modules" else "(model)"
    by[s] = by.get(s, 0) + p.numel()
    tot += p.numel()
stripped, alive = [], []
for i, mod in enumerate(m.rwkv_modules):
    for j, blk in enumerate(mod.blocks):
        tag = "%s:%d" % (IDX[i], j)
        (stripped if getattr(blk, "cmix_stripped", False) else alive).append(tag)
H = CFG.modules[0][1].n_heads
K = CFG.d_model // H
per_layer = H * K * K + 2 * CFG.d_model
L = dict(CFG.modules)
print("@@" + json.dumps({"total": tot, "by": by, "stripped": stripped, "alive": alive,
                         "card_state": L["card_id"].n_layers * per_layer,
                         "note_state": L["note_id"].n_layers * per_layer,
                         "d_model": CFG.d_model}))
'''

# arm -> (desc, head_dim, n_heads, layers, head_mult, feat_mult, expected params, expected card state)
ARMS = {
    "A": ("pure shrink -- d=32, context depth 1/2/2/2, features_fc_mult=4",
          16, 2, (2, 1, 2, 2, 2), 4, 4, 84007, 1152),
    "B": ("d=32, context 1/2/2/2, features_fc_mult=8 -- feature MLP at 32% of budget",
          16, 2, (2, 1, 2, 2, 2), 4, 8, 100263, 1152),
    "C": ("d=32, context 1/1/1/1, features_fc_mult=12 -- feature MLP at 48% of budget",
          16, 2, (2, 1, 1, 1, 1), 4, 12, 99596, 1152),
}


def strip_for(L):
    """The champion's strip pattern, restricted to layers that EXIST at these depths.
    Champion: user_id:0,1,2  preset_id:0,1,2  deck_id:1,2  card_id:1."""
    card, note, deck, preset, user = L
    want = ([("card_id", 1)]
            + [("deck_id", j) for j in (1, 2)]
            + [("preset_id", j) for j in (0, 1, 2)]
            + [("user_id", j) for j in (0, 1, 2)])
    have = {"card_id": card, "note_id": note, "deck_id": deck, "preset_id": preset,
            "user_id": user}
    return ",".join("%s:%d" % (s, j) for s, j in want if j < have[s])


# ---------------------------------------------------------------------------------------
# The verification pass lives under main() so this file can also be IMPORTED. mk_runner.py
# needs ARMS and strip_for(), and duplicating them there produced two wrong strip lists on
# the first attempt -- the arms must have exactly one definition, and it is this one.
# ---------------------------------------------------------------------------------------


def main():
    fail = 0
    for arm, (desc, hd, nh, L, hm, fm, exp_p, exp_cs) in ARMS.items():
        strip = strip_for(L)
        path = os.path.join(OUT, "arch_%s.py" % arm)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(TEMPLATE.format(arm=arm, desc=desc, head_dim=hd, n_heads=nh,
                                     L_card=L[0], L_note=L[1], L_deck=L[2], L_preset=L[3],
                                     L_user=L[4], head_mult=hm, feat_mult=fm,
                                     params=exp_p, card_state=exp_cs, strip=strip))
        env = dict(os.environ)
        env.update({
            "RWKV_ARCH_MODULE": "scratchpad/hybrid100k/arch_%s.py" % arm,
            "RWKV_INTERLEAVE": "1", "RWKV_GRU_HEAD": "3", "RWKV_PAVA_LAMBDA": "0.2",
            "RWKV_NO_AHEAD_RESIDUAL": "1", "RWKV_STRIP_L0_VLORA": "1", "RWKV_ZERO_FEATURES": "22",
            "RWKV_STATE_CLAMP_TAU": "300", "RWKV_STATE_CLAMP_WINDOW": "32768",
            "RWKV_STRIP_CMIX": strip, "RWKV_NO_JIT": "1", "OMP_NUM_THREADS": "1",
        })
        r = subprocess.run([os.path.join(REPO, ".venv", "Scripts", "python.exe"), "-c", VERIFY],
                           cwd=REPO, env=env, capture_output=True, text=True, timeout=300)
        line = [x for x in r.stdout.splitlines() if x.startswith("@@")]
        if not line:
            print("ARM %s: BUILD FAILED\n%s" % (arm, (r.stderr or r.stdout)[-800:]))
            fail += 1
            continue
        d = json.loads(line[0][2:])
        ok_p = d["total"] == exp_p
        ok_s = d["card_state"] == exp_cs
        ok_strip = sorted(d["stripped"]) == sorted(strip.split(","))
        print("ARM %s  d=%d  params %d %s  card_state %d %s"
              % (arm, d["d_model"], d["total"], "OK" if ok_p else "*** EXPECTED %d" % exp_p,
                 d["card_state"], "OK" if ok_s else "*** EXPECTED %d" % exp_cs))
        print("   strip list : %s" % strip)
        print("   stripped   : %s  %s"
              % (",".join(sorted(d["stripped"])), "OK" if ok_strip else "*** MISMATCH"))
        print("   cmix alive : %s" % ",".join(sorted(d["alive"])))
        print("   by stream  : %s" % json.dumps(d["by"], sort_keys=True))
        if not (ok_p and ok_s and ok_strip):
            fail += 1
        print()

    print("RESULT: %s" % ("ALL ARMS VERIFIED" if not fail else "*** %d ARM(S) FAILED" % fail))
    return 1 if fail else 0



if __name__ == "__main__":
    raise SystemExit(main())
