"""Emit the three chain waiters: GPU-free -> arm A -> arm B -> arm C.

WHY A WAITER AND NOT A NUDGE CHECK. Andrew's instruction was "start the <100k arms once the GPU is
free", with "check on every nudge" as the mechanism. The nudge check works but only fires when a
nudge happens to coincide with the GPU freeing, which can waste hours overnight. A detached waiter
implements the same instruction with minutes of latency instead.

THE GPU GUARD IS TWO CONSECUTIVE FREE READINGS, NOT ONE. `gpu_free.py 120` already averages over
two minutes, but a benchmark BETWEEN phases can be genuinely idle for that long -- and starting a
co-tenant run on top of Andrew's benchmark is the thing CLAUDE.md forbids outright (two processes
deadlocked in WDDM paging for 2.7 h once). Two readings, four minutes apart, is the same
two-witness rule that the 08-20 false alarm and the midnight flight-recorder alarm both taught:
a decision built on a single witness reports the witness, not the system.

THE CHAIN GUARD IS AN ANCHORED MARKER SEARCH. `findstr /B /C:"DONE_EXIT_"` -- unanchored, the
pattern matches the waiter's own announcement line and the loop fires instantly. That cost one
wrongly-started eval on 2026-07-26.

THE DOUBLE-LAUNCH GUARD IS A LOCK FILE. The nudge path stays active as a fallback, so both could
in principle fire at once. The waiter writes `hyb<arm>.launched` BEFORE calling the runner and
re-checks it immediately before; the nudge path checks the same file. Belt and braces, because
two concurrent trainings on one 12 GB card is the documented deadlock.

⚠ NEVER EDIT A WAITER WHILE IT LOOPS. cmd.exe re-reads a batch file from a saved byte offset.
Patching an ARMED runner is safe only while its waiter is still looping (a `call`ed .cmd is not
open until the call); a LOOPING waiter is not.

Usage: python scratchpad/hybrid100k/mk_waiters.py
"""

import io
import os

DIRW = r"C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\hybrid100k"
REPO = r"C:\Users\Andrew\rwkv-anki-autoresearch"

GPU_WAITER = r'''@echo off
REM ===========================================================================================
REM Waits for the GPU to be genuinely free, then launches hybrid arm A.
REM
REM FREE means gpu_free.py exits 0 TWICE IN A ROW. Each call samples for 120 s, so the loop is
REM self-throttling and the two readings are four minutes apart. One reading is not enough: a
REM benchmark between phases is idle for longer than that, and starting on top of Andrew's
REM benchmark is what CLAUDE.md forbids (two trainings once deadlocked in WDDM paging for 2.7 h).
REM
REM Do NOT edit this file while it loops -- cmd.exe resumes from a saved byte offset.
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d {repo}
set DIR={dirw}
set WLOG=%DIR%\wait_gpu.log
set LOCK=%DIR%\hybA.launched
echo === GPU waiter armed %DATE% %TIME% (waits for two consecutive free readings) >> "%WLOG%"

:loop
if exist "%LOCK%" goto already
.venv\Scripts\python.exe scratchpad\gpu_free.py 120 > "%DIR%\gpucheck_a.log" 2>&1
if not %ERRORLEVEL%==0 goto loop
echo --- first free reading %DATE% %TIME%, confirming >> "%WLOG%"
.venv\Scripts\python.exe scratchpad\gpu_free.py 120 > "%DIR%\gpucheck_b.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo --- second reading was BUSY, back to waiting %DATE% %TIME% >> "%WLOG%"
  goto loop
)
if exist "%LOCK%" goto already
echo launched by wait_gpu_then_hybA %DATE% %TIME% > "%LOCK%"
echo === GPU FREE twice, launching arm A %DATE% %TIME% >> "%WLOG%"
call "%DIR%\run_hybA.cmd"
echo === arm A returned %ERRORLEVEL% at %DATE% %TIME% >> "%WLOG%"
goto done

:already
echo === arm A was already launched elsewhere, waiter exiting %DATE% %TIME% >> "%WLOG%"

:done
endlocal & exit /b 0
'''

CHAIN_WAITER = r'''@echo off
REM ===========================================================================================
REM Waits for hybrid arm {prev} to write its terminal marker, then launches arm {arm}.
REM
REM ANCHORED marker search. `findstr /B /C:"DONE_EXIT_"` matches only a line that STARTS with the
REM token. Unanchored it also matches this file's own announcement and any prose mentioning it,
REM which fires the loop instantly -- that cost a wrongly-started eval on 2026-07-26.
REM
REM It fires on ANY DONE_EXIT_, success or failure. A failed arm {prev} should not block arm
REM {arm}: they test different questions, and an ops failure repeats fast and cheap in phase 0.
REM The marker actually seen is echoed below, so the log says which happened.
REM
REM Do NOT edit this file while it loops -- cmd.exe resumes from a saved byte offset.
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d {repo}
set DIR={dirw}
set WLOG=%DIR%\wait_{lower}.log
set PREVLOG=%DIR%\hyb{prev}.log
set LOCK=%DIR%\hyb{arm}.launched
echo === arm {arm} waiter armed %DATE% %TIME%, polling hyb{prev}.log >> "%WLOG%"

:loop
if exist "%LOCK%" goto already
findstr /B /C:"DONE_EXIT_" "%PREVLOG%" >nul 2>&1
if %ERRORLEVEL%==0 goto go
REM cmd has no sleep; ping is the portable one and does not need a console (timeout /t does).
ping -n 61 127.0.0.1 >nul
goto loop

:go
if exist "%LOCK%" goto already
echo launched by wait_then_hyb{arm} %DATE% %TIME% > "%LOCK%"
findstr /B /C:"DONE_EXIT_" "%PREVLOG%" >> "%WLOG%"
echo === arm {prev} finished, launching arm {arm} %DATE% %TIME% >> "%WLOG%"
call "%DIR%\run_hyb{arm}.cmd"
echo === arm {arm} returned %ERRORLEVEL% at %DATE% %TIME% >> "%WLOG%"
goto done

:already
echo === arm {arm} was already launched elsewhere, waiter exiting %DATE% %TIME% >> "%WLOG%"

:done
endlocal & exit /b 0
'''


def check(text, name):
    """Same output-side asserts as mk_runner.py, for the same reason."""
    body = text.split("\n")
    assert "cd /d " + REPO in text, name + ": cd /d missing"
    import re
    declared, first_use = {}, {}
    for i, line in enumerate(body):
        m = re.match(r"\s*set (\w+)=", line)
        if m:
            declared.setdefault(m.group(1), i)
        for v in re.findall(r"%(\w+)%", line):
            first_use.setdefault(v, i)
    for v, use in sorted(first_use.items()):
        if v in {"ERRORLEVEL", "DATE", "TIME", "RANDOM"}:
            continue
        assert v in declared and declared[v] <= use, \
            "%s: %%%s%% used at line %d before it is set" % (name, v, use)
    for i, l in enumerate(body):
        if l.strip().upper().startswith("REM"):
            bad = sorted(set("<>&|^") & set(l))
            assert not bad, "%s: REM line %d contains %s" % (name, i, bad)
    # the marker search must be anchored wherever it is used as a trigger
    for i, l in enumerate(body):
        if "findstr" in l and "DONE_EXIT_" in l and ">nul" in l:
            assert "/B " in l, "%s: line %d searches DONE_EXIT_ UNANCHORED" % (name, i)
    # a waiter must never itself write a line starting with the token it polls for
    for l in body:
        s = l.strip()
        if s.lower().startswith("echo done_exit_"):
            raise AssertionError(name + ": a waiter must not emit a terminal marker")


def main():
    out = []

    t = GPU_WAITER.format(repo=REPO, dirw=DIRW)
    check(t, "wait_gpu_then_hybA.cmd")
    out.append(("wait_gpu_then_hybA.cmd", t))

    for arm, prev in (("B", "A"), ("C", "B")):
        t = CHAIN_WAITER.format(repo=REPO, dirw=DIRW, arm=arm, prev=prev,
                                lower="hyb" + arm.lower())
        check(t, "wait_then_hyb%s.cmd" % arm)
        out.append(("wait_then_hyb%s.cmd" % arm, t))

    for name, text in out:
        p = os.path.join(DIRW, name)
        io.open(p, "w", encoding="utf-8", newline="\r\n").write(text)
        print("wrote " + p)

    # A stale terminal marker in a polled log fires its waiter instantly -- the reason iter 52's
    # first log had to be renamed. Refuse to arm a chain whose target logs already exist.
    stale = [f for f in ("hybA.log", "hybB.log", "hybC.log", "hybA.launched",
                         "hybB.launched", "hybC.launched")
             if os.path.exists(os.path.join(DIRW, f))]
    if stale:
        print("\n*** WARNING: these already exist and will confuse the chain: %s" % stale)
        return 1
    print("\nno stale logs or locks: the chain is safe to arm")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
