@echo off
REM ===========================================================================================
REM HYBRID ARM A: pure shrink -- d=32, context depth 1/2/2/2, features_fc_mult=4
REM Priced at 84007 params vs the champion's 558,212. Design: optimization/HYBRID_100K.md.
REM

REM GATE (Andrew 2026-08-28): the track-2 RATIO rule, not the flat accept bar.
REM     ratio == 100,000 * (LL_cand - LL_champ) / (params_champ - params_cand)
REM must be at most 0.0001 in BOTH modes, and params must strictly decrease.
REM Champion iter 53 == 0.297523 ahead / 0.265191 imm on the VAL half, 558,212 params.
REM With 84007 params the budget is dparams == 474,205, so the largest tolerable
REM regression is about 0.000474 in each mode. For scale the A0-to-A18 ladder scored
REM 0.0000435 ahead / 0.0000240 imm, so this is winnable and not a formality.
REM
REM SINGLE VARIABLE: every training-recipe field matches the champion. The arm is exactly
REM RWKV_ARCH_MODULE plus this arm's own RWKV_STRIP_CMIX.
REM
REM PHASE 0 HAS TWO GUARDS.
REM   1. the scripted-eval smoke -- a PLAIN eval is the only path that TorchScript-compiles the
REM      model, so a runtime break is invisible to training and surfaces only after the decay.
REM      srs_model.py and srs_model_rnn.py were touched on 2026-08-29 (RWKV_ABLATE_FEATURES).
REM   2. assert_arch.py -- RWKV_STRIP_CMIX silently ignores a name that matches no layer, and
REM      every arm changes the per-stream depths, so a stale list yields a different model with
REM      no error at all. It asserts the exact param count and that every entry matched.
REM
REM Do NOT edit this file while it runs. cmd.exe resumes from a saved byte offset, and
REM git checkout is not a safe undo (line endings shift the offset). Iters 43 and 46 died so.
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\hybrid100k
set LOG=%DIR%\hybA.log
set STAMP=%RANDOM%%RANDOM%
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
REM ---- THE ARM: the architecture, and this arm's OWN strip list ----
set RWKV_ARCH_MODULE=scratchpad/hybrid100k/arch_A.py
set RWKV_STRIP_CMIX=card_id:1,deck_id:1,preset_id:0,preset_id:1,user_id:0,user_id:1
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_MUON_INCLUDE_LORA=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_GRAD_STATS=%DIR%\grad_stats_hya.json
set RWKV_ID_FEATURES=
set RWKV_ABLATE_FEATURES=
set RWKV_MAX_STEPS=

echo ===== HYBRID ARM A (84007 params) START %DATE% %TIME% ===== >> "%LOG%"

REM ================= PHASE 0a: the scripted-eval guard (iter 48's lesson) =================
REM RUNS UNDER THE CHAMPION'S ARCH, NOT THIS ARM'S, and that is load-bearing. The guard asks
REM "does the CURRENT CODE TorchScript-compile and run a plain eval", and it answers by
REM loading a REAL checkpoint: the champion's d=80 i45 one. Under this arm's d=32 arch that
REM checkpoint cannot load, and the first version of this runner died in 9 seconds on 200
REM size mismatches -- the very clone-inheritance failure this generator exists to prevent,
REM committed inside it. The arm's own values are restored explicitly below.
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
REM The smoke loads the CHAMPION checkpoint, which has no FSRS core -- the flag
REM must be OFF for it and restored below with the rest of the arm's env.
set RWKV_FSRS_CARD=
"C:\Program Files\Git\bin\bash.exe" scratchpad/parity3/smoke_scripted_eval.sh scratchpad/iter45_kddecay/i45_eval.toml > "%DIR%\smoke_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo hybA SCRIPTED_EVAL_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_45 >> "%LOG%"
  exit /b 45
)
REM Restore the arm's own values. Deliberately a plain set/restore rather than a nested
REM setlocal: preflight_runner.py's endlocal check is nesting-blind and would flag the inner
REM endlocal as the bug it was built for. Fewer mechanisms, same guarantee, and what is in
REM force at each line is readable without modelling cmd scoping.
set RWKV_ARCH_MODULE=scratchpad/hybrid100k/arch_A.py
set RWKV_STRIP_CMIX=card_id:1,deck_id:1,preset_id:0,preset_id:1,user_id:0,user_id:1
echo hybA SMOKE_OK %TIME% >> "%LOG%"

REM ================= PHASE 0b: is this the model we priced? =================
.venv\Scripts\python.exe scratchpad/hybrid100k/assert_arch.py 84007 > "%DIR%\arch_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo hybA ARCH_ASSERT_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_46 >> "%LOG%"
  exit /b 46
)
echo hybA ARCH_OK 84007 params %TIME% >> "%LOG%"

REM ================= PHASE A: WS, 1 epoch, KD alpha 0.9 =================
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.9
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/hybrid100k/hya_ws.toml > "%DIR%\ws_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo hybA WSFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_21 >> "%LOG%"
  exit /b 21
)
findstr /C:"[kd-mix] KD ON" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo hybA NOKD_WS %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_35 >> "%LOG%"
  exit /b 35
)
findstr /C:"alpha FIXED at 0.9" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo hybA WRONGALPHA_WS %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_36 >> "%LOG%"
  exit /b 36
)
REM Gate on the ARTIFACT, not the exit code: train_rwkv can swallow a fatal error and exit 0.
if not exist "%DIR%\hya_ws_%WSSTEPS%.pth" (
  echo hybA NO_WS_CKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_30 >> "%LOG%"
  exit /b 30
)
echo hybA WS_OK %TIME% >> "%LOG%"

REM ================= PHASE B: decay, ratio 1.0, KD alpha 0.5 =================
REM The champion runs KD alpha 0.9 in WS and 0.5 in DECAY (iters 39 and 45). The reset below
REM lives here on purpose: iter 45 became champion because its runner FORGOT it, and a
REM decay-only generator that slices this phase away would inherit 0.9 by accident.
set RWKV_KD_ALPHA=0.5
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/hybrid100k hya_ws hya_d %DIR%\hya_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo hybA DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_22 >> "%LOG%"
  exit /b 22
)
findstr /C:"hya_ws_%WSSTEPS%" "%DIR%\dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo hybA WRONGCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_32 >> "%LOG%"
  exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\hya_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo hybA DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_23 >> "%LOG%"
  exit /b 23
)
findstr /C:"alpha FIXED at 0.5" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo hybA WRONGALPHA_DECAY %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_36 >> "%LOG%"
  exit /b 36
)
if not exist "%DIR%\hya_d_%WSSTEPS%.pth" (
  echo hybA NO_DECAY_CKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_31 >> "%LOG%"
  exit /b 31
)
echo hybA DECAY_OK %TIME% >> "%LOG%"

REM ================= PHASE C: rectified VAL-half eval =================
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/hybrid100k hya_d %DIR%\hya_eval.toml RWKV-hybA RWKV-P-hybA 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo hybA TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_24 >> "%LOG%"
  exit /b 24
)
set RWKV_MUON_BATCHED=
set RWKV_NO_JIT=
set RWKV_QAT_COMPILE=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_GRAD_STATS=
set RWKV_EVAL_PAVA=1
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\hya_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo hybA EVAL attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\hya_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo hybA EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 >> "%LOG%"
  exit /b 25
)
echo hybA EVAL_OK %TIME% >> "%LOG%"
REM The terminal marker goes BEFORE endlocal: endlocal restores the pre-setlocal environment,
REM so %LOG% would expand to empty and the append would silently go nowhere. That is exactly
REM how iter 53 finished cleanly at 07:11 and stranded four waiters for 45 minutes.
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
