@echo off
REM ===========================================================================================
REM Waits for hybrid arm A to write its terminal marker, then launches arm B.
REM
REM ANCHORED marker search. `findstr /B /C:"DONE_EXIT_"` matches only a line that STARTS with the
REM token. Unanchored it also matches this file's own announcement and any prose mentioning it,
REM which fires the loop instantly -- that cost a wrongly-started eval on 2026-07-26.
REM
REM It fires on ANY DONE_EXIT_, success or failure. A failed arm A should not block arm
REM B: they test different questions, and an ops failure repeats fast and cheap in phase 0.
REM The marker actually seen is echoed below, so the log says which happened.
REM
REM Do NOT edit this file while it loops -- cmd.exe resumes from a saved byte offset.
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\hybrid100k
set WLOG=%DIR%\wait_hybb.log
set PREVLOG=%DIR%\hybA.log
set LOCK=%DIR%\hybB.launched
echo === arm B waiter armed %DATE% %TIME%, polling hybA.log >> "%WLOG%"

:loop
if exist "%LOCK%" goto already
findstr /B /C:"DONE_EXIT_" "%PREVLOG%" >nul 2>&1
if %ERRORLEVEL%==0 goto go
REM cmd has no sleep; ping is the portable one and does not need a console (timeout /t does).
ping -n 61 127.0.0.1 >nul
goto loop

:go
if exist "%LOCK%" goto already
echo launched by wait_then_hybB %DATE% %TIME% > "%LOCK%"
findstr /B /C:"DONE_EXIT_" "%PREVLOG%" >> "%WLOG%"
echo === arm A finished, launching arm B %DATE% %TIME% >> "%WLOG%"
call "%DIR%\run_hybB.cmd"
echo === arm B returned %ERRORLEVEL% at %DATE% %TIME% >> "%WLOG%"
goto done

:already
echo === arm B was already launched elsewhere, waiter exiting %DATE% %TIME% >> "%WLOG%"

:done
endlocal & exit /b 0
