@echo off
REM ===========================================================================================
REM Waits for the GPU to be genuinely free, then launches hybrid arm A.
REM
REM FREE means gpu_free.py exits 0 TWICE IN A ROW. Each call samples for 120 s, so the loop is
REM self-throttling and the two readings are four minutes apart. One reading is not enough: a
REM benchmark between phases is idle for longer than that, and starting on top of Andrew's
REM benchmark is what CLAUDE.md forbids (two trainings once deadlocked in WDDM paging for 2.7 h).
REM
REM Do NOT edit this file while it loops -- cmd.exe resumes from a saved byte offset.
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\hybrid100k
set WLOG=%DIR%\wait_gpu.log
set LOCK=%DIR%\hybA.launched
echo === GPU waiter armed %DATE% %TIME% (waits for two consecutive free readings) >> "%WLOG%"

:loop
if exist "%LOCK%" goto already
.venv\Scripts\python.exe scratchpad\gpu_free.py 120 > "%DIR%\gpucheck_a.log" 2>&1
if not %ERRORLEVEL%==0 goto loop
echo --- first free reading %DATE% %TIME%, confirming >> "%WLOG%"
.venv\Scripts\python.exe scratchpad\gpu_free.py 120 > "%DIR%\gpucheck_b.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo --- second reading was BUSY, back to waiting %DATE% %TIME% >> "%WLOG%"
  goto loop
)
if exist "%LOCK%" goto already
echo launched by wait_gpu_then_hybA %DATE% %TIME% > "%LOCK%"
echo === GPU FREE twice, launching arm A %DATE% %TIME% >> "%WLOG%"
call "%DIR%\run_hybA.cmd"
echo === arm A returned %ERRORLEVEL% at %DATE% %TIME% >> "%WLOG%"
goto done

:already
echo === arm A was already launched elsewhere, waiter exiting %DATE% %TIME% >> "%WLOG%"

:done
endlocal & exit /b 0
