@echo off
REM ===========================================================================================
REM ITER 57: THE DECAY PHASE'S LR SHAPE (RWKV_DECAY_SHAPE=linear). Decay-only, ~3.5 h.
REM Family: schedule. PROPOSALS.md rank 5, RE-SPECIFIED 2026-08-17 by a pure-arithmetic screen.
REM
REM WHAT THE SCREEN FOUND, and it corrects the proposal twice over:
REM   1. WE ARE NOT ON A COSINE. train_rwkv.py's `cosine_down` computes
REM      1 + cos(pi/2*(1+x)), which is IDENTICALLY 1 - sin(pi/2*x) (agreement 4.4e-16) --
REM      much more aggressive than a standard cosine. The NAME is what made it look like one.
REM   2. 1-sqrt(x) IS NOT AN ALTERNATIVE DIRECTION. Its integrated LR multiplier is 0.3333 vs
REM      the current 0.3634, and the two are IDENTICAL at the midpoint (0.293). It sits on top
REM      of where we already are.
REM   So the only informative direction is MORE LR mass: linear and standard cosine are both
REM   0.5000, i.e. 1.376x current.
REM
REM ** THE MOTIVATION IS THEREFORE NOT 'shape is unexplored'. iter 34 adopted decay_ratio
REM 0.25 to 1.0 -- 4x the decay steps -- and it was the phase's largest gain, i.e. evidence
REM that more decay-LR-mass helps. decay_ratio buys mass by spending WALL-CLOCK; the shape buys
REM 1.376x of it at an IDENTICAL step count, for free. That is the argument.
REM
REM ** PRE-REGISTERED COUNTER-HYPOTHESIS: linear and standard cosine have the SAME mass (0.5)
REM and different profiles, so a win here is a MASS result, not a SHAPE result, until those two
REM are compared. If this wins, the follow-up that separates them is cosine at matched mass.
REM Do NOT claim 'shape matters' from this run alone.
REM
REM PERFECTLY CONTROLLED BY CONSTRUCTION: decay-only, warm-started from the champion's own
REM i45_ws_10935, so WS is literally the champion's and the lever cannot touch it. KD alpha
REM stays at the champion's 0.5 (iter 52 is the run that moves it).
REM
REM GATE: PLAIN basis vs iter 45 == 0.297697 ahead / 0.265375 imm on the VAL half, BOTH-modes
REM rule. Params UNCHANGED at 558,212 -- a schedule has no weights. No deploy debt.
REM The default RWKV_DECAY_SHAPE path was verified BIT-IDENTICAL to the historical schedule
REM over all 2,734 decay steps before this was queued, because a chain's later phases import
REM whatever is on disk THEN and iter 53 was mid-flight.
REM
REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not a
REM safe undo, because line endings shift the byte offset cmd.exe resumes from).
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935


set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5

set TAG=iter57_decayshape
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter57_decayshape
set SRCREL=scratchpad/iter45_kddecay
set SRC=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter45_kddecay
set LOG=%DIR%\iter57.log
set STAMP=%RANDOM%%RANDOM%
set WSSTEPS=10935
set RWKV_GRAD_STATS=%DIR%\grad_stats.json
set RWKV_ID_FEATURES=
set RWKV_MAX_STEPS=

echo ===== ITER 57 (KD alpha_decay 0.5 to 0.9) START %DATE% %TIME% ===== >> "%LOG%"

REM ================= PHASE 0: the scripted-eval guard (iter 48's lesson) =================
"C:\Program Files\Git\bin\bash.exe" scratchpad/parity3/smoke_scripted_eval.sh scratchpad/iter45_kddecay/i45_eval.toml > "%DIR%\smoke_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER57 SCRIPTED_EVAL_SMOKE_FAILED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_45 >> "%LOG%"
  endlocal & exit /b 45
)
echo ITER57 SMOKE_OK %TIME% >> "%LOG%"

REM ====== PHASE A: decay from the champion's WS-final, LINEAR LR decay shape ======
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
REM KD alpha stays at the CHAMPION's 0.5 -- iter 52 is the run that moves it, and
REM moving both at once would make neither attributable.
set RWKV_KD_ALPHA=0.5
REM ---- THE LEVER: 1-sin(pi x/2) (mass 0.3634) becomes 1-x (mass 0.5000, 1.376x) ----
set RWKV_DECAY_SHAPE=linear
.venv\Scripts\python.exe scratchpad/write_decay_setup.py %SRCREL% i45_ws i57_d %DIR%\i57_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER57 DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_22 >> "%LOG%"
  endlocal & exit /b 22
)
findstr /C:"i45_ws_%WSSTEPS%" "%DIR%\dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ITER57 WRONGCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_32 >> "%LOG%"
  endlocal & exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\i57_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER57 DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_23 >> "%LOG%"
  endlocal & exit /b 23
)
REM The experiment's own guards: KD must be ON and at the RIGHT alpha. Without these the run
REM silently reduces to iter 45 and would be recorded as a null.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ITER57 NOKD_DECAY %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_35 >> "%LOG%"
  endlocal & exit /b 35
)
findstr /C:"alpha FIXED at 0.5" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ITER57 WRONGALPHA_DECAY %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_36 >> "%LOG%"
  endlocal & exit /b 36
)
if not exist "%SRC%\i57_d_%WSSTEPS%.pth" (
  echo ITER57 NOCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_31 >> "%LOG%"
  endlocal & exit /b 31
)
echo ITER57 DECAY_OK KD ON alpha 0.9 %TIME% >> "%LOG%"

REM ================= PHASE B: rectified VAL-half eval =================
.venv\Scripts\python.exe scratchpad/write_eval_toml.py %SRCREL% i57_d %DIR%\i57_eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER57 TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_24 >> "%LOG%"
  endlocal & exit /b 24
)
set RWKV_MUON_BATCHED=
set RWKV_NO_JIT=
set RWKV_QAT_COMPILE=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_DECAY_SHAPE=
set RWKV_GRAD_STATS=
set RWKV_EVAL_PAVA=1
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\i57_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo ITER57 EVAL attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\i57_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo ITER57 EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 >> "%LOG%"
  endlocal & exit /b 25
)
echo ITER57 EVAL_OK %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
