@echo off
REM ===========================================================================================
REM ITER 53: PUT THE LoRA PROJECTIONS ON MUON (RWKV_MUON_INCLUDE_LORA=1).
REM Family: optimizer / regularization. Second of the 10 algorithmic iterations Andrew asked
REM for on 2026-08-17.
REM
REM THE MECHANISM, and it is a PREDICTION rather than a hunch. The 2026-08-16 matched-pair
REM measurement (iter 29 vs iter 26, only the three RWKV_MUON_* vars differ) showed Muon's
REM TRAIN-loss advantage decays to zero over a run -- on ahead it inverts -- while its
REM HELD-OUT advantage holds at +0.0019 in both modes. So at our budget Muon is a
REM REGULARIZER, not a faster optimizer. The grouping rule in get_optimizer excludes any
REM param whose name contains lora, so 27,520 params in 94 tensors have never received that
REM regularization -- and being deliberately low-rank (shapes like 4x80 and 80x2) they are the
REM most anisotropic matrices in the model, i.e. exactly where the mechanism predicts the
REM largest effect.
REM
REM ** THE COUNTER-HYPOTHESIS IS PRE-REGISTERED: flattening the update of a deliberately
REM low-rank factorization may destroy what the factorization is for. A null here is
REM informative either way, and a REGRESSION is the outcome that would most sharply bound the
REM regularizer reading.
REM
REM SINGLE VARIABLE. The moved params get their OWN group at wd=0.0, which is what they
REM already had -- dropping them into decay_params would have changed the optimizer AND the
REM weight decay at once. The LR is not separable and that is not a defect: a Muon group runs
REM at RWKV_MUON_LR on a norm-normalised update, which has no comparable scale to AdamW's
REM PEAK_LR. Verified inert with the flag off: same 5 groups, same partition, LoRAs still on
REM AdamW (scratchpad/iter53_muonlora/smoke_muon_lora.py).
REM
REM FULL WS + decay, unlike iter 52: an optimizer change acts from step 1, so warm-starting
REM from the champion's WS-final would measure something else.
REM
REM GATE: PLAIN basis vs iter 45 == 0.297697 ahead / 0.265375 imm on the VAL half, both-modes
REM rule. Params UNCHANGED at 558,212 -- regrouping moves no weights, and nothing ships to
REM Rust (the optimizer does not exist at inference).
REM
REM Do NOT edit this file while it runs (iters 43 and 46 died that way; git checkout is not a
REM safe undo, because line endings shift the byte offset cmd.exe resumes from).
REM No angle brackets or arrows in REM lines -- cmd parses redirection before REM.
REM ===========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter53_muonlora
set LOG=%DIR%\iter53.log
set STAMP=%RANDOM%%RANDOM%
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935
REM BUDGET: 0 = full budget
set MAXSTEPS=0
echo ===== ITER 53 (Muon on the LoRA matrices) START %DATE% %TIME% ===== >> "%LOG%"
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
REM ---- THE LEVER: the LoRA projections join the Muon groups (own group, wd stays 0.0) ----
set RWKV_MUON_INCLUDE_LORA=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_GRAD_STATS=%DIR%\grad_stats.json
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.9
if not "%MAXSTEPS%"=="0" set RWKV_MAX_STEPS=%MAXSTEPS%
if not "%MAXSTEPS%"=="0" set RWKV_BENCH_WARMUP=100000

echo === WS %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/iter53_muonlora/i53_ws.toml > "%DIR%\ws_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WSFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 21
)
findstr /C:"[interleave] round-robin layer schedule ON" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOILV %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
findstr /C:"placement = front-loaded" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGPLACEMENT %DATE% %TIME% >> "%LOG%"
  exit /b 33
)

REM The lever is a PARAM-GROUP change, which fails SILENTLY: a run whose grouping did not
REM change looks perfect and measures the champion. This banner substring only prints when
REM the LoRA group actually exists in the optimizer.
findstr /C:"LoRA in a wd=0 group" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo ITER53 NO_LORA_GROUP %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_37 >> "%LOG%"
  exit /b 37
)
echo WS OK %TIME% >> "%LOG%"

REM ---- THE LEVER: KD is NOT cleared. Only the alpha changes for the decay phase. ----
set RWKV_KD_ALPHA=0.5
set RWKV_GRAD_STATS=
set RWKV_MAX_STEPS=

echo === DECAY SETUP %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/iter53_muonlora i53_ws i53_d scratchpad/iter53_muonlora/i53_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/iter53_muonlora/i53_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
REM THE experiment's own guard: KD must actually have been ON during decay. Without this the run
REM silently reduces to the champion and would be recorded as a null.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOKD_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 35
)
findstr /C:"alpha FIXED at 0.5" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGALPHA_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 36
)
echo DECAY OK (KD ON, alpha 0.5) %TIME% >> "%LOG%"

echo === EVAL TOML rect %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/iter53_muonlora i53_d scratchpad/iter53_muonlora/i53_eval.toml RWKV-iter53_muonlora RWKV-P-iter53_muonlora 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
set RWKV_MUON_BATCHED=
set RWKV_NO_JIT=
set RWKV_QAT_COMPILE=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_EVAL_PAVA=1
echo === EVAL 5001-7500 RECTIFIED attempt 1 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/iter53_muonlora/i53_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo EVAL rect attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config scratchpad/iter53_muonlora/i53_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo EVAL rect OK %TIME% >> "%LOG%"
endlocal

echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
exit /b 0
