"""Generate the lorawd runner from the features-lineage BASELINE's runner + WS toml.

    python scratchpad/lorawd/mk_lorawd.py gen4base      (default; control = gen4base, id4 dbs)
    python scratchpad/lorawd/mk_lorawd.py realcyc       (if realcyc promotes: control = realcyc, id5 dbs)

One variable: `set RWKV_MUON_LORA_WD=0.05`. Everything else is the baseline's recipe verbatim, so
the comparison is single-variable against whichever baseline the features phase settles on. The
switch is one command because a called .cmd is not open until the call -- the armed waiter can be
left alone and this regenerated any time before it fires.

Guards in BOTH directions (the mk_fixc_arm lesson): no baseline token survives outside provenance
comments, AND every line that mentioned the baseline identity was visited (counted, not assumed).
"""
import os
import re
import sys

base = sys.argv[1] if len(sys.argv) > 1 else "gen4base"
cfg = {
    "gen4base": dict(src_dir="gen4_base", src_tag="gen4base", src_prefix="g4b", params="565252"),
    "realcyc": dict(src_dir="realcyc", src_tag="realcyc", src_prefix="rcy", params="563652"),
}[base]
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(REPO)
src_cmd = open(f"scratchpad/{cfg['src_dir']}/run_{cfg['src_tag']}.cmd", newline="").read()
src_ws = open(f"scratchpad/{cfg['src_dir']}/ws.toml", newline="").read()
assert "\r\n" not in src_cmd[:300] and "\r\n" not in src_ws[:300]
# realcyc's runner uses its own prefix; discover it rather than assume
m = re.search(r"%DIR%\\(\w+)_ws_%STEPS%\.pth", src_cmd)
assert m, "could not find the WS ckpt prefix in the source runner"
cfg["src_prefix"] = m.group(1)
TAG, PREFIX, DIRN = "lorawd", "lwd", "lorawd"

visited = 0
out = []
for line in src_cmd.split("\n"):
    orig = line
    if line.startswith("REM ") and ("PHASE 2" in line or "restart" in line):
        continue
    line = line.replace(f"\\scratchpad\\{cfg['src_dir']}", f"\\scratchpad\\{DIRN}")
    line = line.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}")
    line = line.replace(f"set TAG={cfg['src_tag']}", f"set TAG={TAG}")
    line = line.replace(f"{cfg['src_tag']}.log", f"{TAG}.log")
    line = line.replace(f"{cfg['src_prefix']}_ws", f"{PREFIX}_ws").replace(f"{cfg['src_prefix']}_d", f"{PREFIX}_d")
    line = line.replace(f"===== {cfg['src_tag']} START", f"===== {TAG} START").replace("===== REALCYC START", f"===== {TAG} START")
    if line != orig:
        visited += 1
    out.append(line)
s = "\n".join(out)
# the lever, placed right after the arm block; and a WS-log guard that the optimizer really got it
anchor = "REM ---- what distinguishes this arm"
assert s.count(anchor) == 1
s = s.replace(anchor,
    "REM ---- THE LEVER (lorawd): decoupled weight decay 0.05 on the LoRA Muon group ONLY ----\n"
    "REM ADOPTED from Moonlight (arXiv 2502.16982): Muon without wd lets norms grow unboundedly; iter 53\n"
    "REM measured +62 pct LoRA norm growth here at wd 0. Dose from the 2026-08-18 time-constant screen.\n"
    "set RWKV_MUON_LORA_WD=0.05\n\n" + anchor, 1)
guard_anchor = 'echo %TAG% WS_OK %TIME% >> "%LOG%"'
assert s.count(guard_anchor) == 1
s = s.replace(guard_anchor,
    'REM The optimizer must have CONSUMED the flag: the banner prints the LoRA group wd it was built with.\n'
    'findstr /C:"LoRA in a wd=0.05 group" "%DIR%\\ws_%STAMP%.log" >nul\n'
    'if not %ERRORLEVEL%==0 (\n'
    '  echo %TAG% LORA_WD_NOT_CONSUMED %DATE% %TIME% >> "%LOG%"\n'
    '  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"\n'
    '  exit /b 44\n'
    ')\n' + guard_anchor, 1)
# header provenance
s = s.replace("@echo off\n", f"@echo off\nREM lorawd -- generated by scratchpad/lorawd/mk_lorawd.py from the {base} runner. DO NOT HAND-EDIT.\n", 1)
# 2026-09-03: user 6701 exceeds the WDDM ceiling on the gen-4/5 dbs; every eval in this lineage excludes it.
if " --exclude 6701 " not in s:
    s = s.replace(" --shards 1 --solo-threshold 0 --fetch-per-shard 2", " --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2", 1)
assert s.count(" --exclude 6701 ") == 1
# both-direction guards
body = "\n".join(l for l in s.split("\n") if not l.startswith("REM"))
for tok in (cfg["src_tag"], f"{cfg['src_prefix']}_", f"scratchpad/{cfg['src_dir']}", f"\\{cfg['src_dir']}\\"):
    assert tok not in body, f"stale token survived outside REM: {tok!r}"
n_mentions = sum(1 for l in src_cmd.split("\n") if not l.startswith("REM") and (cfg["src_tag"] in l or cfg["src_prefix"] + "_" in l or cfg["src_dir"] in l))
assert visited >= n_mentions, (visited, n_mentions)
assert s.count("set RWKV_MUON_LORA_WD=0.05") == 1 and s.count("DONE_EXIT_0") == 1
assert f"Trainable parameters: {cfg['params']}" in s
assert "set RWKV_KD_MIX=\n" in s and "set RWKV_KD_ALPHA=\n" in s
ws = src_ws.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}").replace(f'"{cfg["src_prefix"]}_ws"', f'"{PREFIX}_ws"')
assert f'SAVE_MODEL_PREFIX = "{PREFIX}_ws"' in ws and f'SAVE_MODEL_FOLDER = "scratchpad/{DIRN}"' in ws
ws = ws.replace(ws.split("\n")[0], f"# lorawd WS phase -- {base}'s recipe + RWKV_MUON_LORA_WD=0.05 (set in the runner env, not here).", 1)
os.makedirs(f"scratchpad/{DIRN}", exist_ok=True)
open(f"scratchpad/{DIRN}/run_{TAG}.cmd", "w", newline="\n").write(s)
open(f"scratchpad/{DIRN}/ws.toml", "w", newline="\n").write(ws)
print(f"wrote run_{TAG}.cmd + ws.toml from {base}: visited {visited} lines (>= {n_mentions} mentions); guard params {cfg['params']}")
