@echo off
REM lorawd -- generated by scratchpad/lorawd/mk_lorawd.py from the gen4base runner. DO NOT HAND-EDIT.
REM ======================================================================================
REM gen4base -- the KD-off features recipe (featB's) re-based on the GEN-4 dbs (Bug C fixed, e2s-selected
REM equalize set). Cloned from run_featB.cmd; header + START banner corrected 2026-09-02 after the run
REM
REM KD IS OFF IN BOTH ARMS, and not by preference: the teacher's features2card in_dim is
REM 92 while the gen-2 DBs feed 114, so it cannot forward-pass them. Comparing a KD-off
REM features run against the KD-ON champion would confound the features with KD removal,
REM worth ~0.0019 per iters 32/35/39/45.
REM
REM NEITHER ARM IS COMPARABLE TO iter 53. B minus A is the number that means something.
REM
REM Do NOT edit while running: cmd.exe re-reads a batch file from a saved byte offset.
REM ======================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\lorawd
set LOG=%DIR%\lorawd.log
set STAMP=%RANDOM%%RANDOM%
set TAG=lorawd
set STEPS=10935

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_MUON_INCLUDE_LORA=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1

REM ---- THE LEVER (lorawd): decoupled weight decay 0.05 on the LoRA Muon group ONLY ----
REM ADOPTED from Moonlight (arXiv 2502.16982): Muon without wd lets norms grow unboundedly; iter 53
REM measured +62 pct LoRA norm growth here at wd 0. Dose from the 2026-08-18 time-constant screen.
set RWKV_MUON_LORA_WD=0.05

REM ---- what distinguishes this arm ----
set RWKV_ID_FEATURES=1
set RWKV_ZERO_FEATURES=
REM db overrides consumed by write_decay_setup.py / write_eval_toml.py, which used to
REM hardcode the 92-dim paths -- the trap the idfeat diagnostic caught.
set RWKV_VAL_DB=F:/rwkv_lmdb/test_db_5k_id4
set RWKV_EVAL_DB=F:/rwkv_lmdb/test_db_5k_id4
set RWKV_LABEL_FILTER_DB=F:/rwkv_lmdb/label_filter_db_id_e2s
REM KD explicitly CLEARED, never merely unset, so an inherited value cannot turn the
REM control into a treatment -- the false-green shape that bit the rgate smoke.
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=

if not exist "%DIR%" mkdir "%DIR%"
echo ===== lorawd START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE A: WS, 1 epoch ----
if exist "%DIR%\ws_%STAMP%.log" del /q "%DIR%\ws_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/lorawd/ws.toml > "%DIR%\ws_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% WS_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_21 %DATE% %TIME% >> "%LOG%"
  exit /b 21
)
REM Gate on the artifact AT THE EXPECTED STEP: exit 0 is not evidence, and an
REM interrupted run leaves a checkpoint at the step it died on.
if not exist "%DIR%\lwd_ws_%STEPS%.pth" (
  echo %TAG% WS_SHORT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_27 %DATE% %TIME% >> "%LOG%"
  exit /b 27
)
REM The arm must have used the input width it claims. This is the one check that
REM catches RWKV_ID_FEATURES failing to reach the workers.
findstr /C:"Trainable parameters: 565252" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% WRONG_PARAM_COUNT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_33 %DATE% %TIME% >> "%LOG%"
  exit /b 33
)
REM The optimizer must have CONSUMED the flag: the banner prints the LoRA group wd it was built with.
findstr /C:"LoRA in a wd=0.05 group" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% LORA_WD_NOT_CONSUMED %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"
  exit /b 44
)
echo %TAG% WS_OK %TIME% >> "%LOG%"

REM ---- PHASE B: decay, ratio 1.0 ----
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/lorawd lwd_ws lwd_d %DIR%\decay.toml F:/rwkv_lmdb/train_db_5k_h1_id4 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% DSETUP_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_22 %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
findstr /C:"lwd_ws_%STEPS%" "%DIR%\dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% WRONGCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_32 %DATE% %TIME% >> "%LOG%"
  exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% DECAY_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_23 %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
REM KD must be ABSENT here -- the opposite of every recent runner's guard.
findstr /C:"[kd-mix] KD ON" "%DIR%\decay_%STAMP%.log" >nul
if %ERRORLEVEL%==0 (
  echo %TAG% KD_LEAKED_IN %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_43 %DATE% %TIME% >> "%LOG%"
  exit /b 43
)
if not exist "%DIR%\lwd_d_%STEPS%.pth" (
  echo %TAG% DECAY_SHORT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_28 %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
echo %TAG% DECAY_OK %TIME% >> "%LOG%"

REM ---- PHASE C: rectified VAL-half eval, users 5001-7500 ----
set RWKV_EVAL_PAVA=1
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/lorawd lwd_d %DIR%\eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% ETOML_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_24 %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
REM The eval toml must point at THIS arm's db, or the arm silently scores on the
REM other arm's feature width. This is trap #2 made into a guard.
findstr /C:"F:/rwkv_lmdb/test_db_5k_id4" "%DIR%\eval.toml" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% EVAL_DB_MISMATCH %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_34 %DATE% %TIME% >> "%LOG%"
  exit /b 34
)
if exist "result\RWKV-%TAG%.jsonl" del /q "result\RWKV-%TAG%.jsonl"
if exist "result\RWKV-P-%TAG%.jsonl" del /q "result\RWKV-P-%TAG%.jsonl"
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% EVAL_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo %TAG% EVAL_OK %TIME% >> "%LOG%"

REM Terminal marker BEFORE endlocal: endlocal restores the pre-setlocal environment,
REM so %LOG% would expand to empty and the marker would go to "".
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0