"""Generate the ordcut runner from the features-lineage reference's runner + WS toml.
    python scratchpad/ordcut/mk_ordcut.py realcyc      (default; control = realcyc, gen-5 SSD dbs)
    python scratchpad/ordcut/mk_ordcut.py durdrop      (if durdrop promotes: control = durdrop)
One variable: `set RWKV_ORD_LAMBDA=0.25` (ordinal ONE-cut supervision of the curve logit from the
next review's rating, on successful ahead rows with t >= 1 d; 2 train-only params, so the param
guard becomes reference + 2). Same shape and both-direction guards as mk_durdrop.py.
"""
import os
import re
import sys
base = sys.argv[1] if len(sys.argv) > 1 else "realcyc"
cfg = {
    "realcyc": dict(src_dir="realcyc", src_tag="realcyc", params=563652),
    "durdrop": dict(src_dir="durdrop", src_tag="durdrop", params=563652),
}[base]
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(REPO)
src_cmd = open(f"scratchpad/{cfg['src_dir']}/run_{cfg['src_tag']}.cmd", newline="").read()
src_ws = open(f"scratchpad/{cfg['src_dir']}/ws.toml", newline="").read()
assert "\r\n" not in src_cmd[:300] and "\r\n" not in src_ws[:300]
m = re.search(r"%DIR%\\(\w+)_ws_%STEPS%\.pth", src_cmd)
assert m, "could not find the WS ckpt prefix in the source runner"
cfg["src_prefix"] = m.group(1)
TAG, PREFIX, DIRN, LAM = "ordcut", "oc", "ordcut", "0.25"
NEW_PARAMS = cfg["params"] + 2
visited = 0
out = []
for line in src_cmd.split("\n"):
    orig = line
    if line.startswith("REM ") and ("PHASE 2" in line or "restart" in line):
        continue
    if line.startswith("REM ") and "generated by scratchpad/" in line:
        continue  # the source's own provenance header; ours is added below
    line = line.replace(f"\\scratchpad\\{cfg['src_dir']}", f"\\scratchpad\\{DIRN}")
    line = line.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}")
    line = line.replace(f"set TAG={cfg['src_tag']}", f"set TAG={TAG}")
    line = line.replace(f"{cfg['src_tag']}.log", f"{TAG}.log")
    line = line.replace(f"{cfg['src_prefix']}_ws", f"{PREFIX}_ws").replace(f"{cfg['src_prefix']}_d", f"{PREFIX}_d")
    line = line.replace(f"===== {cfg['src_tag']} START", f"===== {TAG} START").replace("===== REALCYC START", f"===== {TAG} START")
    line = line.replace(f"Trainable parameters: {cfg['params']}", f"Trainable parameters: {NEW_PARAMS}")
    if line != orig:
        visited += 1
    out.append(line)
s = "\n".join(out)
anchor = "set RWKV_KD_ALPHA=\n"
assert s.count(anchor) == 1
s = s.replace(anchor, anchor +
    "REM ---- THE LEVER (ordcut, ADOPTED: CORAL / Frank-Hall ordinal cutpoints, ONE cut): BCE on the\n"
    "REM curve logit shifted by a learnable cut a + c*log1p(t/1d), target (next rating >= Good), on\n"
    "REM successful ahead rows with t >= 1 d. 2 train-only params. Screen 2026-09-04: Hard share is\n"
    "REM monotone in the model's own R (Spearman -1.000); Easy is U-shaped, hence one cut not two.\n"
    f"set RWKV_ORD_LAMBDA={LAM}\n", 1)
guard_anchor = 'echo %TAG% WS_OK %TIME% >> "%LOG%"'
assert s.count(guard_anchor) == 1
s = s.replace(guard_anchor,
    'REM The model must have BUILT the lever: the [ord] banner prints the lambda it was constructed with.\n'
    f'findstr /C:"[ord] ordinal one-cut supervision on the curve logit ON: lambda={LAM}" "%DIR%\\ws_%STAMP%.log" >nul\n'
    'if not %ERRORLEVEL%==0 (\n'
    '  echo %TAG% ORD_NOT_BUILT %DATE% %TIME% >> "%LOG%"\n'
    '  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"\n'
    '  exit /b 44\n'
    ')\n' + guard_anchor, 1)
s = s.replace("@echo off\n", f"@echo off\nREM ordcut -- generated by scratchpad/ordcut/mk_ordcut.py from the {base} runner. DO NOT HAND-EDIT.\n", 1)
if " --exclude 6701 " not in s:
    s = s.replace(" --shards 1 --solo-threshold 0 --fetch-per-shard 2", " --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2", 1)
assert s.count(" --exclude 6701 ") == 1
body = "\n".join(l for l in s.split("\n") if not l.startswith("REM"))
for tok in (cfg["src_tag"], f"{cfg['src_prefix']}_", f"scratchpad/{cfg['src_dir']}", f"\\{cfg['src_dir']}\\"):
    assert tok not in body, f"stale token survived outside REM: {tok!r}"
n_mentions = sum(1 for l in src_cmd.split("\n") if not l.startswith("REM") and (cfg["src_tag"] in l or cfg["src_prefix"] + "_" in l or cfg["src_dir"] in l))
assert visited >= n_mentions, (visited, n_mentions)
assert s.count(f"set RWKV_ORD_LAMBDA={LAM}") == 1 and s.count("DONE_EXIT_0") == 1
assert f"Trainable parameters: {NEW_PARAMS}" in s and f"Trainable parameters: {cfg['params']}" not in s
# the control's own lever must NOT leak into this arm unless the control is durdrop itself
if base != "durdrop":
    assert "set RWKV_DUR_DROP=" not in s, "durdrop's lever leaked into ordcut"
assert "set RWKV_KD_MIX=\n" in s and "set RWKV_RESUME_SKIP_GROUPS" not in s
ws = src_ws.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}").replace(f'"{cfg["src_prefix"]}_ws"', f'"{PREFIX}_ws"')
assert f'SAVE_MODEL_PREFIX = "{PREFIX}_ws"' in ws and f'SAVE_MODEL_FOLDER = "scratchpad/{DIRN}"' in ws
ws = ws.replace(ws.split("\n")[0], f"# ordcut WS phase -- {base}'s recipe + RWKV_ORD_LAMBDA={LAM} (set in the runner env, not here).", 1)
os.makedirs(f"scratchpad/{DIRN}", exist_ok=True)
open(f"scratchpad/{DIRN}/run_{TAG}.cmd", "w", newline="\n").write(s)
open(f"scratchpad/{DIRN}/ws.toml", "w", newline="\n").write(ws)
print(f"wrote run_{TAG}.cmd + ws.toml from {base}: visited {visited} lines (>= {n_mentions} mentions); guard params {NEW_PARAMS}")
