@echo off
REM =====================================================================================
REM DIAGNOSTIC RUN `base` -- EPOCHS 0.05, 20-user eval. ~25 min.
REM Generated by scratchpad/bughunt/mk_diag.py. DO NOT HAND-EDIT; regenerate.
REM
REM THIS RUN'S LOGLOSS IS MEANINGLESS and must never be recorded as a result. The
REM purpose is to EXECUTE the path -- reading code did not catch any of the failures
REM of 2026-08-17/18, and one cheap end-to-end run would have caught every one.
REM
REM Do NOT edit this file while it runs: cmd.exe re-reads a batch file from a saved
REM byte offset after every command returns (iters 43 and 46 died that way).
REM =====================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\bughunt\diag_base
set LOG=%DIR%\diag_base.log
set STAMP=%RANDOM%%RANDOM%
set TAG=diag_base
set STEPS=546
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k

set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_MUON_INCLUDE_LORA=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1

if not exist "%DIR%" mkdir "%DIR%"
echo ===== DIAG base START %DATE% %TIME% ===== > "%LOG%"

REM ---- PHASE A: WS, 0.05 epochs ----
set RWKV_KD_MIX=%DUMP%:10935
set RWKV_KD_ALPHA=0.9
if exist "%DIR%\ws_%STAMP%.log" del /q "%DIR%\ws_%STAMP%.log"
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config scratchpad/bughunt/diag_base/ws.toml > "%DIR%\ws_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DIAG WS_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_21 %DATE% %TIME% >> "%LOG%"
  exit /b 21
)
REM Gate on the ARTIFACT AT THE EXPECTED STEP. Neither the exit code nor the mere
REM existence of a .pth is evidence: train_rwkv has exited 0 after a fatal error, and
REM an interrupted run leaves a checkpoint at the step it died on.
if not exist "%DIR%\base_ws_%STEPS%.pth" (
  echo DIAG WS_SHORT no base_ws_%STEPS%.pth %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_27 %DATE% %TIME% >> "%LOG%"
  exit /b 27
)
REM The validation path must actually have run -- VALIDATE_EVERY under the step count
REM is the whole reason it can.
findstr /C:"val" "%DIR%\ws_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DIAG NOVALIDATION %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_29 %DATE% %TIME% >> "%LOG%"
  exit /b 29
)
echo DIAG WS_OK %TIME% >> "%LOG%"

REM ---- PHASE B: decay, 0.05 epochs ----
REM alpha 0.5 in decay (iter 45); 0.9 is the WS value (iter 39). Setting this is what
REM iter 54 phase 2a omitted, and it decayed 3.3 h at the wrong value.
set RWKV_KD_ALPHA=0.5
if exist "%DIR%\decay_%STAMP%.log" del /q "%DIR%\decay_%STAMP%.log"
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/bughunt/diag_base base_ws base_d %DIR%\decay.toml train_db_5k_h1 1 5000 0.05 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DIAG DSETUP_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_22 %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
REM The decay must start from the step the WS phase actually reached.
findstr /C:"base_ws_%STEPS%" "%DIR%\dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DIAG WRONGCKPT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_32 %DATE% %TIME% >> "%LOG%"
  exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DIAG DECAY_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_23 %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
REM Guards derived from the value set above, not typed independently: a guard that
REM names a different number than its env is how two runs went wrong in one day.
findstr /C:"alpha FIXED at 0.5" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DIAG WRONGALPHA %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_36 %DATE% %TIME% >> "%LOG%"
  exit /b 36
)
if not exist "%DIR%\base_d_%STEPS%.pth" (
  echo DIAG DECAY_SHORT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_28 %DATE% %TIME% >> "%LOG%"
  exit /b 28
)
echo DIAG DECAY_OK alpha 0.5 %TIME% >> "%LOG%"

REM ---- PHASE C: 20-user rectified eval ----
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_EVAL_PAVA=1
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/bughunt/diag_base base_d %DIR%\eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 5020 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DIAG ETOML_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_24 %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
REM A stale result jsonl would be RESUMED from, not overwritten -- eval_sharded skips
REM users already present, so a rerun would silently mix two models' users.
if exist "result\RWKV-%TAG%.jsonl" del /q "result\RWKV-%TAG%.jsonl"
if exist "result\RWKV-P-%TAG%.jsonl" del /q "result\RWKV-P-%TAG%.jsonl"
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DIAG EVAL_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
if not exist "result\RWKV-P-%TAG%.jsonl" (
  echo DIAG NORESULT %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_26 %DATE% %TIME% >> "%LOG%"
  exit /b 26
)
echo DIAG EVAL_OK %TIME% >> "%LOG%"

REM The terminal marker goes BEFORE endlocal. endlocal restores the pre-setlocal
REM environment, so %LOG% would expand to EMPTY and the marker would be written to
REM "" -- which stranded a four-job chain for 45 min on 2026-08-18.
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0