@echo off
REM ===========================================================================================
REM ITER 46 PHASE 2 (recovery): DECAY + EVAL from the surviving WS-final.
REM
REM WHY THIS EXISTS. run_iter46.cmd's WS phase COMPLETED (i46_ws_10935.pth, 03:05) but the chain
REM died `DONE_EXIT_WSFAIL_3` at 03:06. Cause, and it was self-inflicted: I edited the RUNNING
REM runner, caught it, and "reverted" with `git checkout --` -- which restored the committed
REM CONTENT but not the launched BYTES. The file was written LF (python newline='\n') at launch
REM and git restored it CRLF, adding 222 bytes. cmd.exe resumes a batch file from a saved BYTE
REM OFFSET, so every offset past the edit was wrong; it re-executed a mangled fragment, which
REM re-opened the SAME ws log path with `>` and truncated the training log to 44 bytes.
REM
REM ⚠ THE LESSON, which is sharper than the old one: reverting a running .cmd is NOT safe unless
REM the bytes are restored EXACTLY. `git checkout` normalizes line endings and is therefore the
REM WRONG tool. I even saw the md5 mismatch and dismissed it as "just line endings" -- it was just
REM line endings, and that was precisely the failure. Never touch a running runner; if it has
REM already been touched, restore from a BYTE-EXACT copy, not from git.
REM
REM WHAT SURVIVED: the WS checkpoint (all 10,935 steps). Banners were verified LIVE at launch
REM (selfkd beta 0.7 with the teacher detached, interleave front-loaded, KD alpha 0.9 checksum OK,
REM compile + batched Muon), so the phase is trustworthy even though its log is gone.
REM WHAT WAS LOST: the WS log -- so no per-step trace for a future champion promotion, and no
REM post-hoc banner audit. Low practical cost: the trace's only consumer is the vprune reference
REM for HP tuning, which is closed.
REM
REM This phase is byte-for-byte the decay+eval half of run_iter46.cmd with KDDECAY=1 inlined.
REM ⚠ DO NOT EDIT THIS FILE WHILE IT RUNS. Not even to add a comment. Not even reverting one.
REM  ALSO: write_decay_setup/write_eval_toml EMBED their <folder> arg into the generated TOML,
REM  so it must be a RELATIVE forward-slash path. A Windows absolute path makes tomli read the
REM  backslash-U of C:\Users as a unicode escape and die 'Invalid hex value'. Cost one 3-second
REM  false start -- and then the patch script that fixed it hit the SAME escape. 
REM ===========================================================================================
cd /d C:\Users\Andrew\rwkv-anki-autoresearch
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\iter46_selfkd
set LOG=%DIR%\iter46b.log
set STAMP=%RANDOM%%RANDOM%
set DUMP=C:\rwkv_kd_dump\t128_seedpair_65k
set WSSTEPS=10935
set BETA=0.7

echo ===== ITER 46 PHASE 2 (decay+eval, beta=%BETA%, kddecay=1) START %DATE% %TIME% ===== > "%LOG%"

setlocal
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_MUON=1
set RWKV_MUON_LR=0.0025
set RWKV_MUON_MOMENTUM=0.95
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_WEIGHT_DECAY=0.01
set RWKV_WEIGHT_DECAY_HEAD=0.01
set RWKV_CLIP=0.25
set RWKV_ADAMW_BETA2=0.999
set RWKV_DROPOUT_SCALE=0.5
set RWKV_MUON_BATCHED=1
set RWKV_NO_JIT=1
set RWKV_QAT_COMPILE=1
set RWKV_SELFKD_BETA=%BETA%
REM iter-45 base: KD survives into decay at alpha 0.5
set RWKV_KD_MIX=%DUMP%:%WSSTEPS%
set RWKV_KD_ALPHA=0.5

echo === DECAY SETUP %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_decay_setup.py scratchpad/iter46_selfkd i46_ws i46_d %DIR%\i46_decay.toml train_db_5k_h1 1 5000 1.0 1e-3 65536 > "%DIR%\dsetup_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DSETUPFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 22
)
findstr /C:"i46_ws_%WSSTEPS%" "%DIR%\dsetup_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGCKPT %DATE% %TIME% >> "%LOG%"
  exit /b 32
)
.venv\Scripts\python.exe -u -m rwkv.train_rwkv --config %DIR%\i46_decay.toml > "%DIR%\decay_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_DECAYFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 23
)
findstr /C:"[selfkd] privileged self-distillation ON" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOSELFKD_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 39
)
findstr /C:"hard-share = %BETA% *" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGBETA_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 38
)
findstr /C:"alpha FIXED at 0.5" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_NOBASEKD_DECAY %DATE% %TIME% >> "%LOG%"
  exit /b 40
)
findstr /C:"placement = front-loaded" "%DIR%\decay_%STAMP%.log" >nul
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_WRONGPLACEMENT %DATE% %TIME% >> "%LOG%"
  exit /b 33
)
if not exist "%DIR%\i46_d_%WSSTEPS%.pth" (
  echo DONE_EXIT_NOCKPT %DATE% %TIME% >> "%LOG%"
  exit /b 31
)
echo DECAY OK (selfkd 0.7 + base KD 0.5) %TIME% >> "%LOG%"

echo === EVAL TOML rect %TIME% === >> "%LOG%"
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/iter46_selfkd i46_d %DIR%\i46_eval.toml RWKV-iter46_selfkd RWKV-P-iter46_selfkd 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_TOMLFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
set RWKV_MUON_BATCHED=
set RWKV_NO_JIT=
set RWKV_QAT_COMPILE=
set RWKV_KD_MIX=
set RWKV_KD_ALPHA=
set RWKV_SELFKD_BETA=
set RWKV_EVAL_PAVA=1
echo === EVAL 5001-7500 RECTIFIED attempt 1 %TIME% === >> "%LOG%"
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\i46_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval1_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo EVAL rect attempt 1 failed - retrying from banked users %TIME% >> "%LOG%"
  .venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\i46_eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval2_%STAMP%.log" 2>&1
)
if not %ERRORLEVEL%==0 (
  echo DONE_EXIT_EVALFAIL_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo EVAL rect OK %TIME% >> "%LOG%"
endlocal

echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
