"""Generate scratchpad/lfqat/run_fit_catalogs_lf.cmd -- the PQ-catalog refit on w10lf's WS-final.

WHY. The leak-free QAT arms decay from w10lf_ws_109350, so their start catalogs must be fitted on THAT
model's states. A stale catalog passes every shape assert (the q72u and gen-5 incidents), and a
catalog does not even survive a budget change on the same architecture (ws10's refit, 2026-09-10:
0.39 -> 0.76 on the realcyc-fitted WKV catalog). Same procedure as scratchpad/w10qat/mk_fit_catalogs.py
(weights to safetensors in seconds, a Rust corpus dump driven by the model-independent
reference_realcyc traces, then the two fits), re-pointed at w10lf.

THE STATES ARE LEAK-INDEPENDENT. The corpus is the card/note state after each REAL review of the
trace users; query and probe rows (the only rows the clock fix changes) never update state. So the
existing traces are the right inputs for a leak-free model.

FREE MEASUREMENT ON THE WAY PAST. Phase 4 scores ws10's refit catalogs AND arm 2's LEARNED catalogs
on w10lf's states: does a catalog fitted on a leaked model transfer to a leak-free one at the same
budget? (Reconstruction cannot rank two WORKING catalogs; it can say whether one went stale.)

Usage: python scratchpad/w10lf/mk_lf_fit_catalogs.py [wkv_bits] [shift_m] [shift_bits]
       defaults 10 2 12 = the deploy split (b10 WKV, m2b12 shift). Phase D may move it.
"""
import io
import os
import sys

B = chr(92)
os.chdir(r"C:\Users\Andrew\rwkv-anki-autoresearch")
WB = int(sys.argv[1]) if len(sys.argv) > 1 else 10
SM = int(sys.argv[2]) if len(sys.argv) > 2 else 2
SB = int(sys.argv[3]) if len(sys.argv) > 3 else 12
WKV_OUT = "reference/pq_cb_wkv_w10lf_b%d.txt" % WB
SHIFT_OUT = "reference/pq_cb_shift_w10lf_m%db%d.txt" % (SM, SB)

src = io.open("scratchpad/w10qat/mk_fit_catalogs.py", encoding="utf-8").read()
ENV_START = src.index("ENV = [")
ENV_END = src.index("]\n", ENV_START) + 2
ns = {"B": B}
exec(src[ENV_START:ENV_END], ns)
ENV = ns["ENV"]
for want in ("set RWKV_CHAMP_CKPT=scratchpad/ws10/w10_ws_109350.pth", "set RWKV_REF_DIR=scratchpad/w10qat/cb"):
    assert want in ENV, want
ENV = [e.replace("scratchpad/ws10/w10_ws_109350.pth", "scratchpad/w10lf/w10lf_ws_109350.pth")
        .replace("scratchpad/w10qat/cb", "scratchpad/lfqat/cb") for e in ENV]

R = "C:" + B + "Users" + B + "Andrew" + B + "rwkv-anki-autoresearch"
L = ["@echo off",
     "REM Refit the PQ catalogs on w10lf's LEAK-FREE WS-final. Generated by",
     "REM scratchpad/w10lf/mk_lf_fit_catalogs.py %d %d %d; read that file for why." % (WB, SM, SB),
     "setlocal",
     "cd /d " + R,
     "set DIR=" + R + B + "scratchpad" + B + "lfqat",
     "set LOG=%DIR%" + B + "fitcb.log",
     "set PY=.venv" + B + "Scripts" + B + "python.exe",
     "set BIN=rust" + B + "rwkv-infer" + B + "target" + B + "release" + B + "rwkv-infer.exe",
     'if not exist "%DIR%" mkdir "%DIR%"']
L += ENV
L += ['echo ===== w10lf CATALOG REFIT START %DATE% %TIME% ===== > "%LOG%"',
      "",
      "REM ---- PHASE 0: the WS-final must exist; a refit on anything else fits the wrong model.",
      'if not exist "scratchpad' + B + 'w10lf' + B + 'w10lf_ws_109350.pth" (',
      '  echo missing w10lf_ws_109350.pth %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_61 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 61",
      ")",
      "",
      "REM ---- PHASE 1: weights to safetensors (seconds)",
      '"%PY%" -u scratchpad/w10qat/export_weights_only.py >> "%LOG%" 2>&1',
      "if not %ERRORLEVEL%==0 (",
      '  echo weights export FAILED %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_62 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 62",
      ")",
      "",
      "REM ---- PHASE 2: the corpus, from the Rust engine driven by the existing gen-5 traces",
      "set RWKV_TRACE_DIR=reference_realcyc",
      "set RWKV_WEIGHTS=scratchpad/lfqat/cb/rwkv_ref_558.safetensors",
      'if not exist "%DIR%' + B + 'corpus" mkdir "%DIR%' + B + 'corpus"']
for u in (107, 136, 156):
    for s in ("card", "note"):
        base = '"%DIR%' + B + 'corpus' + B
        L += ['%BIN% --dump-corpus ' + str(u) + ' ' + s + ' 1 > ' + base +
              'wkv_' + str(u) + '_' + s + '.txt" 2>> "%LOG%"',
              '%BIN% --dump-shift-corpus ' + str(u) + ' ' + s + ' 1 > ' + base +
              'shift_' + str(u) + '_' + s + '.txt" 2>> "%LOG%"']
L += ["",
      "REM ---- PHASE 3: fit both catalogs",
      '"%PY%" scratchpad/pq_train_juv.py ' + WKV_OUT + ' '
      '"%DIR%' + B + 'corpus' + B + 'wkv_*_*.txt" --k 16 --h 5 --bits ' + str(WB) + ' >> "%LOG%" 2>&1',
      "if not %ERRORLEVEL%==0 (",
      '  echo WKV fit FAILED %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_63 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 63",
      ")",
      '"%PY%" scratchpad/pq_train_shift.py ' + SHIFT_OUT + ' '
      '"%DIR%' + B + 'corpus' + B + 'shift_*_*.txt" --c 80 --m ' + str(SM) + ' --bits ' + str(SB) +
      ' --minibatch 1 >> "%LOG%" 2>&1',
      "if not %ERRORLEVEL%==0 (",
      '  echo shift fit FAILED %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_64 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 64",
      ")",
      "",
      "REM ---- PHASE 4 (report only): do ws10's refit and arm 2's LEARNED catalogs transfer to a",
      "REM leak-free model at the same budget?",
      "echo === ws10 refit WKV catalog on w10lf states === >> \"%LOG%\"",
      "set WKV_CB=reference/pq_cb_wkv_ws10_b10.txt",
      '"%PY%" scratchpad/qat_tax/wkv_cb_staleness.py "%DIR%' + B + 'corpus' + B + 'wkv_*_*.txt" '
      '--holdout-user 156 >> "%LOG%" 2>&1',
      "echo === arm 2 LEARNED WKV catalog on w10lf states === >> \"%LOG%\"",
      "set WKV_CB=scratchpad/ws10/w10q_d_wkvcb_21870.txt",
      '"%PY%" scratchpad/qat_tax/wkv_cb_staleness.py "%DIR%' + B + 'corpus' + B + 'wkv_*_*.txt" '
      '--holdout-user 156 >> "%LOG%" 2>&1',
      "echo === ws10 refit shift catalog on w10lf states === >> \"%LOG%\"",
      '"%PY%" scratchpad/qat_gen5/shift_cb_staleness.py reference/pq_cb_shift_ws10_m2b12.txt '
      '"%DIR%' + B + 'corpus' + B + 'shift_*_*.txt" --holdout-user 156 >> "%LOG%" 2>&1',
      "",
      'if not exist "' + WKV_OUT.replace("/", B) + '" (',
      '  echo WKV catalog was not written %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_65 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 65",
      ")",
      'if not exist "' + SHIFT_OUT.replace("/", B) + '" (',
      '  echo shift catalog was not written %DATE% %TIME% >> "%LOG%"',
      '  echo DONE_EXIT_66 %DATE% %TIME% >> "%LOG%"',
      "  exit /b 66",
      ")",
      'echo CATALOGS OK ' + WKV_OUT + ' ' + SHIFT_OUT + ' %DATE% %TIME% >> "%LOG%"',
      'echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"',
      "endlocal & exit /b 0",
      ""]
out = "\n".join(L)
code = "\n".join(l for l in out.split("\n") if not l.strip().upper().startswith("REM"))
for tok in ("scratchpad/ws10/w10_ws", "scratchpad/w10qat/cb", "w10qat" + B + "corpus"):
    assert tok not in code, tok
assert "set RWKV_CHAMP_CKPT=scratchpad/w10lf/w10lf_ws_109350.pth" in code
assert out.index("echo DONE_EXIT_0 ") < out.rindex("endlocal")
os.makedirs("scratchpad/lfqat", exist_ok=True)
io.open("scratchpad/lfqat/run_fit_catalogs_lf.cmd", "w", encoding="ascii", newline="\r\n").write(out)
print("wrote scratchpad/lfqat/run_fit_catalogs_lf.cmd  ->", WKV_OUT, SHIFT_OUT)
