"""Generate the LEAK-FREE 10-epoch run -- WS from scratch, then arm 1's decay and eval -- and its
dry run. Andrew 2026-09-10: "I think we should do a leak-free run anyway. Nothing that cheats
should make it into the final version that will be shipped."

THE RUN. ws10's WS (109,350 steps, same env, same toml but the save folder/prefix) -> arm 1's 2-epoch
decay (21,870 steps) -> arm 1's rectified VAL-half eval, with RWKV_CLOCK_AT_PREV_ANSWER=<T> in ALL
THREE phases (rwkv/clock_fix.py). So no weight of this model ever trained on a clock column that
carried the current review's excess, and (w10lf minus w10plain) is what the leak was worth once
training can adapt from step 0. It is the base the shipped model is built on.

One env difference from ws10, stated so nobody finds it later: ws10 ran WITHOUT OMP_NUM_THREADS=7
(it was sliced away when its env was copied; every fetch worker then ran torch on 32 cores, found
2026-09-09). Arm 1's decay and every later branch set it, and so does this run, WS included. It
changes CPU thread counts in the fetch workers, not what they compute or what the GPU does.

Built from the two runners it must match, and asserted in both directions: every RWKV_ variable of
ws10's and of arm 1's env block appears here with the same value, the only extra one is the lever;
every substitution fires; no identity of either source survives outside REM lines; exit codes are
unique; the terminal marker precedes endlocal; ws.toml differs from ws10's only where it must.

Writes: scratchpad/w10lf/{ws.toml,run_w10lf.cmd} and scratchpad/w10lfdry/{ws.toml,run_w10lfdry.cmd}
(dry = 0.05 epochs in both phases, WS validation every 250 steps so the WS validation path and a
resume checkpoint are exercised, 20 eval users).
Usage: python scratchpad/w10lf/mk_w10lf.py [T_seconds]      (default 1800)
"""
import io
import os
import re
import sys

os.chdir(r"C:\Users\Andrew\rwkv-anki-autoresearch")
T = sys.argv[1] if len(sys.argv) > 1 else "1800"
assert float(T) > 0, T
WS_SRC = "scratchpad/ws10/run_ws10.cmd"
TOML_SRC = "scratchpad/ws10/ws.toml"
ARM1_SRC = "scratchpad/w10plain/run_w10plain.cmd"
NL = "\n"
DRY_STEPS = int(0.05 * 10935)          # train_rwkv: total_steps = int(EPOCHS * len(groups))


def rd(p):
    return io.open(p, encoding="utf-8", newline="").read().replace("\r\n", NL)


def code_of(s):
    return NL.join(l for l in s.split(NL) if not l.strip().upper().startswith("REM"))


def env_block(s):
    """RWKV_* / OMP_* / PYTHON* assignments before the first python call, first value wins."""
    head = code_of(s).split(".venv\\Scripts")[0]
    out = {}
    for m in re.finditer(r"^set ((?:RWKV_|OMP_|PYTHON)\w*)=(.*)$", head, re.M):
        out.setdefault(m.group(1), m.group(2).rstrip())
    return out


def sub(text, pat, rep, count=None):
    new, n = re.subn(pat, rep, text)
    if n == 0 or (count is not None and n != count):
        sys.exit(f"REFUSING: substitution fired {n}x (want {count or '>=1'}): {pat}")
    return new


HEADER = r"""@echo off
REM w10lf -- THE LEAK-FREE 10-EPOCH RUN. Generated by scratchpad/w10lf/mk_w10lf.py from ws10's WS
REM runner (phase A) and arm 1's runner (phases B, C). Andrew 2026-09-10: "Nothing that cheats
REM should make it into the final version that will be shipped."
REM
REM THE LEVER, in all three phases: RWKV_CLOCK_AT_PREV_ANSWER=%T% (rwkv/clock_fix.py). The query
REM row (imm) and the PAVA probe rows (rectified ahead) predict at SHOW time, and their clock
REM columns carried the current review's capped-duration excess; they move to the previous answer
REM when the gap is in-session, a shift past UTC midnight takes the previous day's calendar
REM columns, and the ahead label time loses the target review's in-session gap. Params unchanged.
REM
REM Controls: ws10 for the WS phase (same env plus OMP_NUM_THREADS=7, see mk_w10lf.py), arm 1
REM (w10plain) for the decay and the eval. PREREG: scratchpad/w10lf/PREREG.md.
REM
REM RESUME: the WS phase loops like ws10's, so a crash costs at most 1000 steps. The decay
REM checkpoints every 2000 steps but does NOT auto-resume; a crash there needs a hand resume.
"""

LEVER = ("\nREM ---- THE LEVER: the query-row clock-leak fix, in WS, decay, validation and eval ----\n"
         "set RWKV_CLOCK_AT_PREV_ANSWER=%s\n" % T)


def guard(logname, code_on, code_ran, what):
    return (
        "REM The fix must have REACHED the fetch workers and RUN there: the ON banner prints at import\n"
        "REM in every process, the chunk-count line only from apply_to_sample.\n"
        'findstr /C:"ON: T=%s s" "%%DIR%%\\%s" >nul\n'
        "if not %%ERRORLEVEL%%==0 (\n"
        '  echo %%TAG%% CLOCK_FIX_NOT_ON_%s %%DATE%% %%TIME%% >> "%%LOG%%"\n'
        '  echo DONE_EXIT_%d %%DATE%% %%TIME%% >> "%%LOG%%"\n'
        "  exit /b %d\n"
        ")\n"
        'findstr /C:"s chunks 1 query rows" "%%DIR%%\\%s" >nul\n'
        "if not %%ERRORLEVEL%%==0 (\n"
        '  echo %%TAG%% CLOCK_FIX_NEVER_RAN_%s %%DATE%% %%TIME%% >> "%%LOG%%"\n'
        '  echo DONE_EXIT_%d %%DATE%% %%TIME%% >> "%%LOG%%"\n'
        "  exit /b %d\n"
        ")\n" % (T, logname, what, code_on, code_on, logname, what, code_ran, code_ran))


EVAL_POSTCHECK = (
    "REM Non-fatal post-check: the eval's shard log must carry the ON banner too (a guard that could\n"
    "REM destroy a finished eval on a banner mismatch is worse than what it guards).\n"
    'findstr /C:"ON: T=%s s" scratchpad\\eval_shards\\shard_s0.log >nul 2>&1\n'
    "if not %%ERRORLEVEL%%==0 (\n"
    '  echo %%TAG%% EVAL_SHARD_LOG_HAS_NO_CLOCK_FIX_BANNER %%DATE%% %%TIME%% >> "%%LOG%%"\n'
    '  echo clock-fix banner missing from the eval shard log > "%%DIR%%\\EVAL_BANNER_MISSING.txt"\n'
    ")\n"
    "copy /y scratchpad\\eval_shards\\shard_s0.log \"%%DIR%%\\eval_shard_%%STAMP%%.log\" >nul 2>&1\n" % T)


def phase_a(ws):
    """ws10's WS loop, from `set ATTEMPT=0` to its WS_OK line, renamed to this run."""
    a = ws.index("set ATTEMPT=0")
    ok = 'echo %TAG% WS_OK after %ATTEMPT% attempt(s) %DATE% %TIME% >> "%LOG%"\n'
    b = ws.index(ok) + len(ok)
    s = ws[a:b]
    s = sub(s, r"w10_ws_%STEPS%\.pth", "w10lf_ws_%WSSTEPS%.pth", 1)
    s = sub(s, r"w10_ws_1000\.pth", "w10lf_ws_1000.pth", 1)
    s = sub(s, r"make_resume\.py %DIR% w10_ws scratchpad/ws10/ws\.toml scratchpad/ws10/ws_resume\.toml",
            "make_resume.py %DIR% w10lf_ws scratchpad/w10lf/ws.toml scratchpad/w10lf/ws_resume.toml", 1)
    s = sub(s, r"set CFG=scratchpad/ws10/ws_resume\.toml", "set CFG=scratchpad/w10lf/ws_resume.toml", 1)
    s = s.replace(ok, guard("ws_%STAMP%.log", 58, 59, "WS") + ok, 1)
    s += ("REM The decay is a fresh start from the WS-final: the WS resume flag must not reach it.\n"
          "set RWKV_RESUME_SKIP_GROUPS=\n\n")
    return "REM ---- PHASE A: the 10-epoch WS, from scratch, WITH the fix ----\n" + s


def build():
    ws, arm1, toml = rd(WS_SRC), rd(ARM1_SRC), rd(TOML_SRC)
    body = arm1[arm1.index("setlocal"):]
    for pat, rep in [
        (r"set DIR=C:\\Users\\Andrew\\rwkv-anki-autoresearch\\scratchpad\\w10plain",
         r"set DIR=C:\\Users\\Andrew\\rwkv-anki-autoresearch\\scratchpad\\w10lf"),
        (r"set LOG=%DIR%\\w10plain\.log", r"set LOG=%DIR%\\w10lf.log"),
        (r"set TAG=w10plain", r"set TAG=w10lf"),
        (r"scratchpad/write_decay_setup\.py scratchpad/ws10 w10_ws w10p_d",
         r"scratchpad/write_decay_setup.py scratchpad/w10lf w10lf_ws w10lf_d"),
        (r'findstr /C:"w10_ws_%WSSTEPS%"', r'findstr /C:"w10lf_ws_%WSSTEPS%"'),
        (r"scratchpad\\ws10\\w10p_d_%STEPS%\.pth", r"scratchpad\\w10lf\\w10lf_d_%STEPS%.pth"),
        (r"scratchpad/write_eval_toml\.py scratchpad/w10plain w10p_d",
         r"scratchpad/write_eval_toml.py scratchpad/w10lf w10lf_d"),
        (r"echo ===== w10plain START", r"echo ===== w10lf START"),
    ]:
        body = sub(body, pat, rep, 1)
    for anchor, add in [
        ("set RWKV_KD_ALPHA=\n", LEVER),
        ("set WSSTEPS=109350\n", "set CFG=scratchpad/w10lf/ws.toml\n"),
    ]:
        if body.count(anchor) != 1:
            sys.exit(f"REFUSING: anchor not unique: {anchor!r}")
        body = body.replace(anchor, anchor + add)
    a = "REM ---- PHASE B: the 2-EPOCH decay from the shared 10-epoch WS checkpoint ----"
    if body.count(a) != 1:
        sys.exit("REFUSING: the phase-B anchor is not unique")
    body = body.replace(a, phase_a(ws) + "REM ---- PHASE B: the 2-EPOCH decay from THIS run's leak-free WS-final ----")
    a = "REM KD must be ABSENT here"
    if body.count(a) != 1:
        sys.exit("REFUSING: the KD-absent anchor is not unique")
    body = body.replace(a, guard("decay_%STAMP%.log", 56, 57, "DECAY") + a)
    a = 'echo %TAG% EVAL_OK %TIME% >> "%LOG%"\n'
    if body.count(a) != 1:
        sys.exit("REFUSING: the EVAL_OK anchor is not unique")
    body = body.replace(a, a + EVAL_POSTCHECK)
    out = HEADER.replace("%T%", T) + body

    wtoml = toml[toml.index("TRAIN_USERS_START"):]
    wtoml = ("# w10lf -- ws10's WS toml, save folder and prefix changed, nothing else (mk_w10lf.py).\n"
             "# Leak-free: the runner sets RWKV_CLOCK_AT_PREV_ANSWER. See scratchpad/w10lf/PREREG.md.\n"
             + wtoml)
    wtoml = sub(wtoml, r'SAVE_MODEL_FOLDER = "scratchpad/ws10"', 'SAVE_MODEL_FOLDER = "scratchpad/w10lf"', 1)
    wtoml = sub(wtoml, r'SAVE_MODEL_PREFIX = "w10_ws"', 'SAVE_MODEL_PREFIX = "w10lf_ws"', 1)
    return out, wtoml, ws, arm1, toml


def dry_of(out, wtoml):
    d = out.replace("w10lf", "w10lfdry")
    d = sub(d, r"set WSSTEPS=109350", "set WSSTEPS=%d" % DRY_STEPS, 1)
    d = sub(d, r"set STEPS=21870", "set STEPS=%d" % DRY_STEPS, 1)
    d = sub(d, r"(1 5000 )2\.0( 1e-3)", r"\g<1>0.05\g<2>", 1)
    d = sub(d, r"(write_eval_toml\.py.+?)5001 7500(\s*>)", r"\g<1>5001 5020\g<2>", 1)
    d = sub(d, r"w10lfdry_ws_1000\.pth", "w10lfdry_ws_250.pth", 1)
    d = d.replace("REM w10lfdry -- THE LEAK-FREE 10-EPOCH RUN.",
                  "REM w10lfdry -- DRY RUN (0.05 + 0.05 epochs, 20 users) of THE LEAK-FREE 10-EPOCH RUN.", 1)
    t = wtoml.replace("w10lf", "w10lfdry")
    # prose pointers stay on the real run's files
    d = d.replace("scratchpad/w10lfdry/mk_w10lfdry.py", "scratchpad/w10lf/mk_w10lf.py").replace("mk_w10lfdry.py", "mk_w10lf.py").replace("scratchpad/w10lfdry/PREREG.md", "scratchpad/w10lf/PREREG.md")
    t = t.replace("mk_w10lfdry.py", "mk_w10lf.py").replace("scratchpad/w10lfdry/PREREG.md", "scratchpad/w10lf/PREREG.md")
    t = sub(t, r"(?m)^EPOCHS = 10$", "EPOCHS = 0.05", 1)
    t = sub(t, r"(?m)^VALIDATE_EVERY = 1000$", "VALIDATE_EVERY = 250", 1)
    return d, t


def kv(toml):
    return dict(re.findall(r"(?m)^(\w+)\s*=\s*(.+?)\s*$", toml))


def check(out, wtoml, ws, arm1, toml, dry):
    code = code_of(out)
    tag = "w10lfdry" if dry else "w10lf"
    for tok in ("w10plain", "w10p_d", "w10_ws", "scratchpad/ws10", "scratchpad\\ws10"):
        bad = [l for l in code.split(NL) if tok in l]
        if bad:
            sys.exit(f"REFUSING ({tag}): '{tok}' survives on a non-REM line:\n  " + "\n  ".join(bad[:3]))
    if dry and re.search(r"w10lf(?!dry)", code):
        sys.exit("REFUSING: the dry runner still names the real run")
    e, e_ws, e_a1 = env_block(out), env_block(ws), env_block(arm1)
    for name, src in (("ws10", e_ws), ("arm 1", e_a1)):
        diff = {k: (v, e.get(k)) for k, v in src.items() if e.get(k) != v}
        if diff:
            sys.exit(f"REFUSING ({tag}): env differs from {name}: {diff}")
    extra = set(e) - set(e_ws) - set(e_a1)
    if extra != {"RWKV_CLOCK_AT_PREV_ANSWER"}:
        sys.exit(f"REFUSING ({tag}): unexpected extra env {sorted(extra)}")
    if e["RWKV_CLOCK_AT_PREV_ANSWER"] != T:
        sys.exit("REFUSING: the lever has the wrong value")
    if "set RWKV_CLOCK_AT_PREV_ANSWER=\n" in code:
        sys.exit("REFUSING: the lever is cleared somewhere")
    if code.index("set RWKV_CLOCK_AT_PREV_ANSWER=") > code.index("rwkv.train_rwkv"):
        sys.exit("REFUSING: the lever is set after training starts")
    if code.index("set RWKV_RESUME_SKIP_GROUPS=\n") > code.index("write_decay_setup.py"):
        sys.exit("REFUSING: the resume flag is not cleared before the decay")
    codes = re.findall(r"echo DONE_EXIT_(\d+) ", out)
    if len(codes) != len(set(codes)):
        sys.exit(f"REFUSING: duplicate exit codes {sorted(int(c) for c in codes)}")
    if out.index("echo DONE_EXIT_0 ") > out.rindex("endlocal"):
        sys.exit("REFUSING: the terminal marker follows endlocal")
    k0, k1 = kv(toml), kv(wtoml)
    changed = {k for k in set(k0) | set(k1) if k0.get(k) != k1.get(k)}
    want = {"SAVE_MODEL_FOLDER", "SAVE_MODEL_PREFIX"} | ({"EPOCHS", "VALIDATE_EVERY"} if dry else set())
    if changed != want:
        sys.exit(f"REFUSING ({tag}): ws.toml differs from ws10's in {sorted(changed)}, want {sorted(want)}")
    return sorted(int(c) for c in codes)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    io.open(path, "w", encoding="ascii", newline="\r\n").write(text)


def main():
    out, wtoml, ws, arm1, toml = build()
    dout, dtoml = dry_of(out, wtoml)
    c1 = check(out, wtoml, ws, arm1, toml, False)
    check(dout, dtoml, ws, arm1, toml, True)
    write("scratchpad/w10lf/run_w10lf.cmd", out)
    write("scratchpad/w10lf/ws.toml", wtoml)
    write("scratchpad/w10lfdry/run_w10lfdry.cmd", dout)
    write("scratchpad/w10lfdry/ws.toml", dtoml)
    print(f"wrote scratchpad/w10lf/run_w10lf.cmd + ws.toml and the dry pair; T = {T} s")
    print(f"  exit codes {c1}; WS 109350 + decay 21870 steps (dry: {DRY_STEPS} + {DRY_STEPS}, 20 users)")


if __name__ == "__main__":
    main()
