"""Generate scratchpad/lfd3/wait_lf_then_decaylen.cmd: the LEAK-FREE decay-length pair behind w10lf.

WHY (2026-09-11). Phase L said the clock leak is MATERIAL, so the decay-length pair runs on w10lf's
leak-free WS instead of ws10's, and it runs FIRST after w10lf: the length it picks is the length the
leak-free QAT arms then use, so they need not be re-run. Runners: mk_lf_branch.py (lfd3, lfd1 and
their dry twins); control = w10lf.

GATE 0 -- the w10lf waiter's log (w10lf/wait_lf2.log) must carry a terminal marker (anchored):
  DONE_EXIT_150         arm 2's eval failed upstream, the GPU is kept for its resume -> REFUSE 160
  DONE_EXIT_151 .. 156  w10lf never ran (its dry run or its regeneration refused)   -> REFUSE 161
  DONE_EXIT_0           w10lf ran; now require ITS OWN success line in w10lf.log and both of its
                        final checkpoints (WS-final and decay-final) on disk, else    -> REFUSE 162
A refusal leaves the GPU for a human: without a finished w10lf this pair has no base.
GATE 1 -- all four branch runners must PASS preflight now (w10lf's checkpoints exist)   else 163.
Then both dry runs (0.05 epochs, 20 users; 164..169 on failure), then lfd3 (~12 h + eval), then lfd1.

STOP THIS WAITER'S cmd FIRST, then its children.
Usage: python scratchpad/w10lf/mk_wait_lf_decaylen.py
"""
import io
import os

B = chr(92)
R = "C:" + B + "Users" + B + "Andrew" + B + "rwkv-anki-autoresearch"
OUT = "scratchpad/lfd3/wait_lf_then_decaylen.cmd"

DRY = r"""
call %R%{B}scratchpad{B}{T}dry{B}run_{T}dry.cmd
findstr /B /C:"DONE_EXIT_0 " "%R%{B}scratchpad{B}{T}dry{B}{T}dry.log" >nul 2>&1
if errorlevel 1 (
  echo {T} dry run ended WITHOUT success -- not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_{C1} %DATE% %TIME% >> "%WLOG%"
  exit /b {C1}
)
findstr /C:"Traceback" /C:"Exception caught" "%R%{B}scratchpad{B}{T}dry{B}decay_*.log" >nul 2>&1
if not errorlevel 1 (
  echo {T} dry decay swallowed an exception -- a HOLLOW run, not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_{C2} %DATE% %TIME% >> "%WLOG%"
  exit /b {C2}
)
if not exist "%R%{B}result{B}RWKV-P-{T}dry.jsonl" (
  echo {T} dry eval produced no result file %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_{C3} %DATE% %TIME% >> "%WLOG%"
  exit /b {C3}
)
"""

T = r"""@echo off
REM Leak-free decay-length pair behind w10lf: dry lfd3, dry lfd1, then lfd3, then lfd1.
REM Generated by scratchpad/w10lf/mk_wait_lf_decaylen.py -- read its docstring for the gate logic.
REM Displace it by stopping THIS waiter's cmd FIRST, then its children, while it loops in gate 0.
setlocal
cd /d {R}
set R={R}
set WLOG={R}{B}scratchpad{B}lfd3{B}wait_lfdecay.log
set PREV={R}{B}scratchpad{B}w10lf{B}wait_lf2.log
echo ===== leak-free decay-length waiter armed on the w10lf waiter %DATE% %TIME% ===== >> "%WLOG%"

:waitprev
if not exist "%PREV%" goto sleepprev
findstr /B /C:"DONE_EXIT_" "%PREV%" >nul 2>&1
if errorlevel 1 goto sleepprev
goto gotprev
:sleepprev
ping -n 61 127.0.0.1 >nul
goto waitprev

:gotprev
findstr /B /C:"DONE_EXIT_150 " "%PREV%" >nul 2>&1
if not errorlevel 1 (
  echo arm 2 eval FAILED upstream per the w10lf waiter -- the GPU is kept for its resume %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_160 %DATE% %TIME% >> "%WLOG%"
  exit /b 160
)
findstr /B /C:"DONE_EXIT_0 " "%PREV%" >nul 2>&1
if errorlevel 1 (
  echo w10lf never ran -- its waiter refused; this pair has no base, a human must look %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_161 %DATE% %TIME% >> "%WLOG%"
  exit /b 161
)
findstr /B /C:"DONE_EXIT_0 " "%R%{B}scratchpad{B}w10lf{B}w10lf.log" >nul 2>&1
if errorlevel 1 goto nobase
if not exist "%R%{B}scratchpad{B}w10lf{B}w10lf_ws_109350.pth" goto nobase
if not exist "%R%{B}scratchpad{B}w10lf{B}w10lf_d_21870.pth" goto nobase
goto preflight
:nobase
echo w10lf did not finish cleanly -- no success line or a final checkpoint missing; a human must look %DATE% %TIME% >> "%WLOG%"
echo DONE_EXIT_162 %DATE% %TIME% >> "%WLOG%"
exit /b 162

:preflight
.venv\Scripts\python.exe scratchpad/preflight_runner.py scratchpad/lfd3/run_lfd3.cmd scratchpad/lfd1/run_lfd1.cmd scratchpad/lfd3dry/run_lfd3dry.cmd scratchpad/lfd1dry/run_lfd1dry.cmd >> "%WLOG%" 2>&1
if errorlevel 1 (
  echo preflight FAILED on the decay-length runners -- not launching %DATE% %TIME% >> "%WLOG%"
  echo DONE_EXIT_163 %DATE% %TIME% >> "%WLOG%"
  exit /b 163
)
echo w10lf done and preflight clean -- 120 s for its workers, then the two dry runs %DATE% %TIME% >> "%WLOG%"
ping -n 121 127.0.0.1 >nul
{DRY_LFD3}{DRY_LFD1}
echo both dry runs clean -- launching lfd3 %DATE% %TIME% >> "%WLOG%"
call %R%{B}scratchpad{B}lfd3{B}run_lfd3.cmd
echo run_lfd3.cmd returned %ERRORLEVEL% -- launching lfd1 %DATE% %TIME% >> "%WLOG%"
call %R%{B}scratchpad{B}lfd1{B}run_lfd1.cmd
echo run_lfd1.cmd returned %ERRORLEVEL% %DATE% %TIME% >> "%WLOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%WLOG%"
endlocal & exit /b 0
"""

os.chdir(R)
d3 = DRY.replace("{T}", "lfd3").replace("{C1}", "164").replace("{C2}", "165").replace("{C3}", "166")
d1 = DRY.replace("{T}", "lfd1").replace("{C1}", "167").replace("{C2}", "168").replace("{C3}", "169")
out = T.replace("{DRY_LFD3}", d3).replace("{DRY_LFD1}", d1).replace("{R}", R).replace("{B}", B)
assert "{" not in out and "}" not in out
codes = [l.split()[1] for l in out.splitlines() if l.strip().startswith("echo DONE_EXIT_")]
assert len(codes) == len(set(codes)), codes
assert out.index("echo DONE_EXIT_0 ") < out.rindex("endlocal")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
io.open(OUT, "w", encoding="ascii", newline="\r\n").write(out)
raw = open(OUT, "rb").read()
print(f"wrote {OUT}: {raw.count(b'\n')} lines, {raw.count(b'\r\n')} CRLF, exit codes {codes}")
