@echo off
REM =========================================================================================
REM Score the UNCHANGED iter-53 champion against the id-FIXED published eval db. RESUME run.
REM
REM This is the champion's TRUE DEPLOY ACCURACY. Eval has always grouped rows by the ids stored
REM in the test db, which int32 saturated; DEPLOY keys states on the RAW full-precision id. On
REM the published test db user 5010 had note n_unique == 1 across ALL 171,933 scored rows. So
REM 0.297523 / 0.265191 was measured on a grouping Anki does not use.
REM
REM TWO CHANGES FROM THE FIRST VERSION, both from the same mistake.
REM
REM 1. IT WAITS FOR featB TO FINISH, not for the eval db. The first version waited on the
REM    eval-db build, and I assumed the train build queued after it would take 2.5 h. It took
REM    50 min. So this eval and featA2 landed on the GPU together at 11,991 of 12,282 MiB and
REM    featA2 managed 2 steps in 48 minutes -- the WDDM paging deadlock CLAUDE.md records as
REM    costing 2.7 h once before. Never gate a job on a GUESS about another job's duration;
REM    gate it on that job's terminal marker.
REM
REM 2. IT DOES NOT DELETE THE RESULT JSONLS. eval_sharded SKIPS users already present, so a
REM    relaunch only re-risks the remainder. 455 users were banked before the kill and deleting
REM    them would throw away ~30 min of GPU for nothing. CLAUDE.md states this rule outright.
REM
REM Nothing is retrained. Same checkpoint, same users 5001-7500, same label filter, same fetch
REM settings as featA's eval -- only the db and the output names differ.
REM
REM Do NOT edit this file while it runs. No angle brackets or arrows in REM lines.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\champ_deploy
set LOG=%DIR%\champ_deploy_resume.log
set STAMP=%RANDOM%%RANDOM%
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7

set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_EVAL_PAVA=1
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0

echo ===== CHAMP_DEPLOY_RESUME START %DATE% %TIME% ===== > "%LOG%"

:wait
findstr /B /C:"DONE_EXIT_" "%DIR%\..\features_ab\featB\featB.log" >nul 2>&1
if %ERRORLEVEL%==0 goto go
timeout /t 120 /nobreak >nul
goto wait

:go
echo featB finished, GPU is free %DATE% %TIME% >> "%LOG%"
.venv\Scripts\python.exe scratchpad/features_rebuild/check_db.py F:/rwkv_lmdb/test_db_5k_fix 2000 24 >> "%LOG%" 2>&1
if not %ERRORLEVEL%==0 (
  echo CHAMP_DEPLOY_RESUME DB_BAD %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_14 %DATE% %TIME% >> "%LOG%"
  exit /b 14
)

del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval_resume_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo CHAMP_DEPLOY_RESUME EVAL_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo CHAMP_DEPLOY_RESUME EVAL_OK %TIME% >> "%LOG%"
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
