"""Generate the durdrop runner from the features-lineage reference's runner + WS toml.
    python scratchpad/durdrop/mk_durdrop.py realcyc      (default; control = realcyc, gen-5 SSD dbs)
One variable: `set RWKV_DUR_DROP=0.25` (train-only Bernoulli zeroing of the scaled_duration input
column, the deploy contract's zeroed current duration taught at full loss weight on ~25% of real rows).
Everything else is the reference's recipe verbatim. Same shape as scratchpad/lorawd/mk_lorawd.py:
guards in BOTH directions (no reference token survives outside REM; every mentioning line visited),
plus a WS-log guard that the model really built the lever ([dur-drop] banner) and the unchanged
param count (a train-only input mask adds no parameters: 563,652 must survive).
"""
import os
import re
import sys
base = sys.argv[1] if len(sys.argv) > 1 else "realcyc"
cfg = {
    "realcyc": dict(src_dir="realcyc", src_tag="realcyc", src_prefix="rc", params="563652"),
}[base]
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(REPO)
src_cmd = open(f"scratchpad/{cfg['src_dir']}/run_{cfg['src_tag']}.cmd", newline="").read()
src_ws = open(f"scratchpad/{cfg['src_dir']}/ws.toml", newline="").read()
assert "\r\n" not in src_cmd[:300] and "\r\n" not in src_ws[:300]
m = re.search(r"%DIR%\\(\w+)_ws_%STEPS%\.pth", src_cmd)
assert m, "could not find the WS ckpt prefix in the source runner"
cfg["src_prefix"] = m.group(1)
TAG, PREFIX, DIRN, P = "durdrop", "dd", "durdrop", "0.25"
visited = 0
out = []
for line in src_cmd.split("\n"):
    orig = line
    if line.startswith("REM ") and ("PHASE 2" in line or "restart" in line):
        continue
    line = line.replace(f"\\scratchpad\\{cfg['src_dir']}", f"\\scratchpad\\{DIRN}")
    line = line.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}")
    line = line.replace(f"set TAG={cfg['src_tag']}", f"set TAG={TAG}")
    line = line.replace(f"{cfg['src_tag']}.log", f"{TAG}.log")
    line = line.replace(f"{cfg['src_prefix']}_ws", f"{PREFIX}_ws").replace(f"{cfg['src_prefix']}_d", f"{PREFIX}_d")
    line = line.replace(f"===== {cfg['src_tag']} START", f"===== {TAG} START").replace("===== REALCYC START", f"===== {TAG} START")
    if line != orig:
        visited += 1
    out.append(line)
s = "\n".join(out)
# the lever: right after RWKV_KD_ALPHA= (the last env line of the reference block)
anchor = "set RWKV_KD_ALPHA=\n"
assert s.count(anchor) == 1
s = s.replace(anchor, anchor +
    "REM ---- THE LEVER (durdrop, INVENTED -- iter 33's prescribed clean retry): train-only Bernoulli\n"
    "REM zeroing of input dim 8 (scaled_duration) with p=0.25. Screen 2026-09-04: zeroing the current\n"
    "REM duration costs +0.001388 ahead on realcyc (10 train users). Eval/deploy untouched.\n"
    f"set RWKV_DUR_DROP={P}\n", 1)
# WS-log guard: the model must have BUILT the lever (banner), and the param count is unchanged
guard_anchor = 'echo %TAG% WS_OK %TIME% >> "%LOG%"'
assert s.count(guard_anchor) == 1
s = s.replace(guard_anchor,
    'REM The model must have BUILT the lever: the [dur-drop] banner prints the p it was constructed with.\n'
    f'findstr /C:"[dur-drop] TRAIN-ONLY Bernoulli zeroing of input dim 8 (scaled_duration) with p={P}" "%DIR%\\ws_%STAMP%.log" >nul\n'
    'if not %ERRORLEVEL%==0 (\n'
    '  echo %TAG% DUR_DROP_NOT_BUILT %DATE% %TIME% >> "%LOG%"\n'
    '  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"\n'
    '  exit /b 44\n'
    ')\n' + guard_anchor, 1)
s = s.replace("@echo off\n", f"@echo off\nREM durdrop -- generated by scratchpad/durdrop/mk_durdrop.py from the {base} runner. DO NOT HAND-EDIT.\n", 1)
if " --exclude 6701 " not in s:
    s = s.replace(" --shards 1 --solo-threshold 0 --fetch-per-shard 2", " --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2", 1)
assert s.count(" --exclude 6701 ") == 1
body = "\n".join(l for l in s.split("\n") if not l.startswith("REM"))
for tok in (cfg["src_tag"], f"{cfg['src_prefix']}_", f"scratchpad/{cfg['src_dir']}", f"\\{cfg['src_dir']}\\"):
    assert tok not in body, f"stale token survived outside REM: {tok!r}"
n_mentions = sum(1 for l in src_cmd.split("\n") if not l.startswith("REM") and (cfg["src_tag"] in l or cfg["src_prefix"] + "_" in l or cfg["src_dir"] in l))
assert visited >= n_mentions, (visited, n_mentions)
assert s.count(f"set RWKV_DUR_DROP={P}") == 1 and s.count("DONE_EXIT_0") == 1
assert f"Trainable parameters: {cfg['params']}" in s, "the param guard must survive: the lever adds no params"
assert "set RWKV_KD_MIX=\n" in s
assert "set RWKV_RESUME_SKIP_GROUPS" not in s, "cloned a resume runner by mistake"
ws = src_ws.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}").replace(f'"{cfg["src_prefix"]}_ws"', f'"{PREFIX}_ws"')
assert f'SAVE_MODEL_PREFIX = "{PREFIX}_ws"' in ws and f'SAVE_MODEL_FOLDER = "scratchpad/{DIRN}"' in ws
ws = ws.replace(ws.split("\n")[0], f"# durdrop WS phase -- {base}'s recipe + RWKV_DUR_DROP={P} (set in the runner env, not here).", 1)
os.makedirs(f"scratchpad/{DIRN}", exist_ok=True)
open(f"scratchpad/{DIRN}/run_{TAG}.cmd", "w", newline="\n").write(s)
open(f"scratchpad/{DIRN}/ws.toml", "w", newline="\n").write(ws)
print(f"wrote run_{TAG}.cmd + ws.toml from {base}: visited {visited} lines (>= {n_mentions} mentions); guard params {cfg['params']}")
