"""Generate the hord runner (multi-horizon button-order hinge on the probes) from the reference's runner.
    python scratchpad/hord/mk_hord.py realcyc            (control = realcyc's recipe)
    python scratchpad/hord/mk_hord.py realcyc --sam      (if sam promotes: the reference recipe now carries
                                                         SAM in its DECAY, so hord's decay carries it too
                                                         and the control is sam's own numbers)
One variable on top of the base recipe: `set RWKV_PAVA_HORIZON_LAMBDA=0.05` (factors 0.125,8 default).
No new parameters (563,652 must survive). With --sam the SAM env is set AFTER the WS phase and BEFORE
the decay setup, exactly where sam's own decay-only runner applies it. Both-direction guards as in
mk_ordcut.py, plus a decay-log guard for the SAM banners when --sam is on.
"""
import os
import re
import sys
args = [a for a in sys.argv[1:] if not a.startswith("--")]
base = args[0] if args else "realcyc"
WITH_SAM = "--sam" in sys.argv
cfg = {"realcyc": dict(src_dir="realcyc", src_tag="realcyc", params="563652")}[base]
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(REPO)
src_cmd = open(f"scratchpad/{cfg['src_dir']}/run_{cfg['src_tag']}.cmd", newline="").read()
src_ws = open(f"scratchpad/{cfg['src_dir']}/ws.toml", newline="").read()
assert "\r\n" not in src_cmd[:300] and "\r\n" not in src_ws[:300]
m = re.search(r"%DIR%\\(\w+)_ws_%STEPS%\.pth", src_cmd)
assert m
cfg["src_prefix"] = m.group(1)
TAG, PREFIX, DIRN, LAM = "hord", "hd", "hord", "0.05"
visited = 0
out = []
for line in src_cmd.split("\n"):
    orig = line
    if line.startswith("REM ") and ("PHASE 2" in line or "restart" in line or "generated by scratchpad/" in line):
        continue
    line = line.replace(f"\\scratchpad\\{cfg['src_dir']}", f"\\scratchpad\\{DIRN}")
    line = line.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}")
    line = line.replace(f"set TAG={cfg['src_tag']}", f"set TAG={TAG}")
    line = line.replace(f"{cfg['src_tag']}.log", f"{TAG}.log")
    line = line.replace(f"{cfg['src_prefix']}_ws", f"{PREFIX}_ws").replace(f"{cfg['src_prefix']}_d", f"{PREFIX}_d")
    line = line.replace(f"===== {cfg['src_tag']} START", f"===== {TAG} START").replace("===== REALCYC START", f"===== {TAG} START")
    if line != orig:
        visited += 1
    out.append(line)
s = "\n".join(out)
anchor = "set RWKV_KD_ALPHA=\n"
assert s.count(anchor) == 1
s = s.replace(anchor, anchor +
    "REM ---- THE LEVER (hord, INVENTED): hinge on adjacent-button ORDER of the 4 probe curves at t x {1/8, 8},\n"
    "REM probe rows only, curve head only (RWKV_PAVA_HORIZON_LAMBDA). Screen 2026-09-04: raw button curves\n"
    "REM cross on 30-49 pct of rows across horizons. No new params. Curve-side gate.\n"
    f"set RWKV_PAVA_HORIZON_LAMBDA={LAM}\n", 1)
guard_anchor = 'echo %TAG% WS_OK %TIME% >> "%LOG%"'
assert s.count(guard_anchor) == 1
s = s.replace(guard_anchor,
    'REM The model must have BUILT the lever: the [pava-horizon] banner prints the lambda it was constructed with.\n'
    f'findstr /C:"[pava-horizon] button-order hinge at t x [0.125, 8.0] ON: lambda={LAM}" "%DIR%\\ws_%STAMP%.log" >nul\n'
    'if not %ERRORLEVEL%==0 (\n'
    '  echo %TAG% HORD_NOT_BUILT %DATE% %TIME% >> "%LOG%"\n'
    '  echo DONE_EXIT_44 %DATE% %TIME% >> "%LOG%"\n'
    '  exit /b 44\n'
    ')\n' + guard_anchor, 1)
if WITH_SAM:
    b = "REM ---- PHASE B: decay, ratio 1.0 ----\n"
    assert s.count(b) == 1
    s = s.replace(b, "REM the reference recipe carries SAM in its DECAY (sam promoted): apply it here, after WS\n"
                     "set RWKV_SAM_RHO=0.05\nset RWKV_SAM_EVERY=1\n" + b, 1)
    g = 'echo %TAG% DECAY_OK %TIME% >> "%LOG%"'
    assert s.count(g) == 1
    s = s.replace(g,
        'findstr /C:"[sam] first pass: weights restored bit-exactly" "%DIR%\\decay_%STAMP%.log" >nul\n'
        'if not %ERRORLEVEL%==0 (\n'
        '  echo %TAG% SAM_NEVER_RAN %DATE% %TIME% >> "%LOG%"\n'
        '  echo DONE_EXIT_45 %DATE% %TIME% >> "%LOG%"\n'
        '  exit /b 45\n'
        ')\n' + g, 1)
s = s.replace("@echo off\n", f"@echo off\nREM hord -- generated by scratchpad/hord/mk_hord.py from the {base} runner{' WITH SAM in the decay' if WITH_SAM else ''}. DO NOT HAND-EDIT.\n", 1)
if " --exclude 6701 " not in s:
    s = s.replace(" --shards 1 --solo-threshold 0 --fetch-per-shard 2", " --shards 1 --solo-threshold 0 --exclude 6701 --fetch-per-shard 2", 1)
assert s.count(" --exclude 6701 ") == 1
body = "\n".join(l for l in s.split("\n") if not l.startswith("REM"))
for tok in (cfg["src_tag"], f"{cfg['src_prefix']}_", f"scratchpad/{cfg['src_dir']}", f"\\{cfg['src_dir']}\\"):
    assert tok not in body, f"stale token survived outside REM: {tok!r}"
n_mentions = sum(1 for l in src_cmd.split("\n") if not l.startswith("REM") and (cfg["src_tag"] in l or cfg["src_prefix"] + "_" in l or cfg["src_dir"] in l))
assert visited >= n_mentions, (visited, n_mentions)
assert s.count(f"set RWKV_PAVA_HORIZON_LAMBDA={LAM}") == 1 and s.count("DONE_EXIT_0") == 1
assert f"Trainable parameters: {cfg['params']}" in s, "the lever adds no params; the guard must survive"
assert "set RWKV_DUR_DROP=" not in s and "set RWKV_ORD_LAMBDA=" not in s and "set RWKV_RESUME_SKIP_GROUPS" not in s
assert (s.count("set RWKV_SAM_RHO=0.05") == 1) == WITH_SAM
if WITH_SAM:
    # SAM must be set AFTER the WS training line and BEFORE the decay setup
    # the CALL sites, not the header REM that mentions the script names
    assert s.index("rwkv.train_rwkv --config scratchpad/hord/ws.toml") < s.index("set RWKV_SAM_RHO=0.05") < s.index("scratchpad/write_decay_setup.py scratchpad/hord")
ws = src_ws.replace(f"scratchpad/{cfg['src_dir']}", f"scratchpad/{DIRN}").replace(f'"{cfg["src_prefix"]}_ws"', f'"{PREFIX}_ws"')
assert f'SAVE_MODEL_PREFIX = "{PREFIX}_ws"' in ws and f'SAVE_MODEL_FOLDER = "scratchpad/{DIRN}"' in ws
ws = ws.replace(ws.split("\n")[0], f"# hord WS phase -- {base}'s recipe + RWKV_PAVA_HORIZON_LAMBDA={LAM} (set in the runner env, not here).", 1)
os.makedirs(f"scratchpad/{DIRN}", exist_ok=True)
open(f"scratchpad/{DIRN}/run_{TAG}.cmd", "w", newline="\n").write(s)
open(f"scratchpad/{DIRN}/ws.toml", "w", newline="\n").write(ws)
open(f"scratchpad/{DIRN}/CONTROL.txt", "w").write(f"base={base}\nwith_sam={WITH_SAM}\ncontrol={'sam' if WITH_SAM else base}\n")
print(f"wrote run_{TAG}.cmd + ws.toml from {base}{' with SAM in the decay' if WITH_SAM else ''}: visited {visited} lines (>= {n_mentions}); guard params {cfg['params']}")
