"""Generate the two-arm FEATURES experiment: do the 23 real-timestamp inputs actually help?

THE QUESTION. The rebuild finished 2026-08-20 and cost ~4 h; nothing yet says the new inputs are
worth anything. This is the experiment that answers it, and it is the "large impact" work Andrew
asked for (2026-08-19: "focus on major changes that are likely to have a large impact on loss").

WHY BOTH ARMS MUST BE KD-OFF, and this is NOT a stylistic choice. The KD teacher
(`pretrain/RWKV_trained_on_101_4999.pth`) has `features2card` **in_dim = 92**. The rebuilt DBs feed
**114**. The teacher cannot forward-pass the new data AT ALL, so the dump cannot be regenerated --
KD is structurally unavailable on the new inputs until a teacher is trained on them.

The champion (iter 53) is KD-ON. Comparing a KD-off features run against it would therefore confound
the new features with the removal of KD, which iters 32/35/39/45 measured at **~0.0019** -- larger
than almost every effect this project chases. So:

    ARM A   champion recipe, KD OFF, OLD 92-dim DBs    <- the control
    ARM B   champion recipe, KD OFF, NEW 114-dim DBs   <- the treatment
    B - A   =  the value of the new input features, cleanly isolated

⚠ A is NOT redundant with iter 53 and cannot be skipped. It is the only thing that separates
"features helped" from "KD removal hurt".

⚠ NEITHER ARM IS COMPARABLE TO iter 53. This opens a new generation: within it everything is KD-off
until a new teacher exists. Do not gate these against the champion's 0.297523/0.265191.

COST at the plain (no-KD) rate of ~1.253 steps/s: WS 10,935 + decay 10,935 steps = ~4.85 h, plus a
~2.9 h eval = ~7.75 h per arm, ~15.5 h total.

THE DB PATHS ARE PASSED THROUGH THE ENV, using the override added to write_decay_setup.py and
write_eval_toml.py on 2026-08-20. Those generators previously HARDCODED the 92-dim DBs, so arm B
would have trained on 114-dim data and then decayed and evaluated on 92-dim data -- silently, since
nothing checks that a toml's db matches the run's feature width. The idfeat diagnostic found that
before it could cost a re-base.

Usage: .venv/Scripts/python.exe scratchpad/features_ab/mk_features_ab.py
"""
import io
import sys
import os
import re

REPO = r"C:\Users\Andrew\rwkv-anki-autoresearch"

# The iter-53 champion recipe, minus KD. Identical in both arms -- the ONLY differences are the
# db paths and RWKV_ID_FEATURES, which is what makes B-A attributable to the features.
ENV = [
    ("PYTHONUNBUFFERED", "1"), ("PYTHONPATH", REPO), ("OMP_NUM_THREADS", "7"),
    ("RWKV_DETERMINISTIC", "1"), ("RWKV_AUGMENT_SEED", "4321"),
    ("RWKV_EMPTY_CACHE_EVERY", "1"), ("RWKV_EMPTY_CACHE_WINDOW", "0"),
    ("RWKV_ARCH_MODULE", "scratchpad/track2_a18/architecture_d80_lora4_cnd.py"),
    ("RWKV_INTERLEAVE", "1"), ("RWKV_GRU_HEAD", "3"), ("RWKV_PAVA_LAMBDA", "0.2"),
    ("RWKV_PROBE_DENSITY", "0.08"), ("RWKV_PROBE_DUR", "0.0"),
    ("RWKV_MUON", "1"), ("RWKV_MUON_LR", "0.0025"), ("RWKV_MUON_MOMENTUM", "0.95"),
    ("RWKV_MUON_INCLUDE_LORA", "1"),
    ("RWKV_NO_AHEAD_RESIDUAL", "1"), ("RWKV_STRIP_L0_VLORA", "1"),
    ("RWKV_STATE_CLAMP_TAU", "300"), ("RWKV_STATE_CLAMP_WINDOW", "32768"),
    ("RWKV_STRIP_CMIX", "user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,"
                        "preset_id:2,deck_id:1,deck_id:2,card_id:1"),
    ("RWKV_WEIGHT_DECAY", "0.01"), ("RWKV_WEIGHT_DECAY_HEAD", "0.01"),
    ("RWKV_CLIP", "0.25"), ("RWKV_ADAMW_BETA2", "0.999"), ("RWKV_DROPOUT_SCALE", "0.5"),
    ("RWKV_MUON_BATCHED", "1"), ("RWKV_NO_JIT", "1"), ("RWKV_QAT_COMPILE", "1"),
]

ARMS = {
    "featA": dict(
        train_db="train_db_5k_h1",
        val_db="F:/rwkv_lmdb/test_db_5k",
        eval_db="F:/rwkv_lmdb/test_db_5k",
        lf_db="label_filter_db",
        idf="",                       # OFF -> 92-dim
        zero="22",                    # the card-state mask the old DBs still need
        why="CONTROL: champion recipe with KD OFF on the OLD 92-dim DBs.",
    ),
    "featB": dict(
        train_db="F:/rwkv_lmdb/train_db_5k_h1_id2",
        val_db="F:/rwkv_lmdb/test_db_5k_id2",
        eval_db="F:/rwkv_lmdb/test_db_5k_id2",
        lf_db="F:/rwkv_lmdb/label_filter_db_id",
        idf="1",                      # ON -> 114-dim
        zero="",                      # the rebuild DROPPED the card-state column at source
        why="TREATMENT: same recipe on the GEN-2 114-dim DBs, 23 real-timestamp features.",
    ),
}

WS_TOML = '''# {arm} WS phase -- {why}
# Generated by scratchpad/features_ab/mk_features_ab.py. KD is OFF in BOTH arms: the teacher's
# features2card in_dim is 92 and the gen-2 DBs feed 114, so it cannot forward-pass them at all.
TRAIN_USERS_START = 1
TRAIN_USERS_END = 5000
VALIDATE_USERS_START = 5001
VALIDATE_USERS_END = 5010

TRAIN_DATASET_LMDB_PATH = "{train_db}"
TRAIN_DATASET_LMDB_SIZE = 400_000_000_000
VALIDATE_DATASET_LMDB_PATH = "{val_db}"
VALIDATE_DATASET_LMDB_SIZE = 250_000_000_000
LABEL_FILTER_LMDB_PATH = "{lf_db}"
LABEL_FILTER_LMDB_SIZE = 40_000_000_000

NUM_FETCH_PROCESSES = 2
MAX_TRAIN_GLOBAL_LEN = 65536

TRAIN_MODE = "WS"
STEP_OFFSET = 1
WARMUP_STEPS = 400
EPOCHS = 1
VALIDATE_EVERY = 1000
PEAK_LR = 1e-3

LOAD_MODEL = false
SAVE_MODEL_FOLDER = "scratchpad/features_ab/{arm}"
SAVE_MODEL_PREFIX = "{arm}_ws"
DEVICE = "cuda"
DTYPE = "bfloat16"

USE_WANDB = false
WANDB_PROJECT_NAME = "rwkv"
WANDB_RESUME = false
WANDB_RESUME_ID = ""
'''


def rem(t):
    for b, g in (("<", "("), (">", ")"), ("&", "and"), ("|", "/"), ("^", "")):
        t = t.replace(b, g)
    return "REM " + t


def build(arm, cfg):
    d = "%s\\scratchpad\\features_ab\\%s" % (REPO, arm)
    L = ["@echo off", "REM " + "=" * 86,
         rem("%s -- %s" % (arm.upper(), cfg["why"])),
         rem("Generated by mk_features_ab.py. DO NOT HAND-EDIT; regenerate."),
         "REM",
         rem("KD IS OFF IN BOTH ARMS, and not by preference: the teacher's features2card in_dim is"),
         rem("92 while the gen-2 DBs feed 114, so it cannot forward-pass them. Comparing a KD-off"),
         rem("features run against the KD-ON champion would confound the features with KD removal,"),
         rem("worth ~0.0019 per iters 32/35/39/45."),
         "REM",
         rem("NEITHER ARM IS COMPARABLE TO iter 53. B minus A is the number that means something."),
         "REM",
         rem("Do NOT edit while running: cmd.exe re-reads a batch file from a saved byte offset."),
         "REM " + "=" * 86,
         "setlocal", "cd /d " + REPO, "",
         "set DIR=" + d,
         "set LOG=%DIR%\\" + arm + ".log",
         "set STAMP=%RANDOM%%RANDOM%",
         "set TAG=" + arm,
         "set STEPS=10935", ""]
    for k, v in ENV:
        L.append("set %s=%s" % (k, v))
    L += ["", rem("---- what distinguishes this arm ----"),
          "set RWKV_ID_FEATURES=" + cfg["idf"],
          "set RWKV_ZERO_FEATURES=" + cfg["zero"],
          rem("db overrides consumed by write_decay_setup.py / write_eval_toml.py, which used to"),
          rem("hardcode the 92-dim paths -- the trap the idfeat diagnostic caught."),
          "set RWKV_VAL_DB=" + cfg["val_db"],
          "set RWKV_EVAL_DB=" + cfg["eval_db"],
          "set RWKV_LABEL_FILTER_DB=" + cfg["lf_db"],
          rem("KD explicitly CLEARED, never merely unset, so an inherited value cannot turn the"),
          rem("control into a treatment -- the false-green shape that bit the rgate smoke."),
          "set RWKV_KD_MIX=", "set RWKV_KD_ALPHA=", "",
          'if not exist "%DIR%" mkdir "%DIR%"',
          'echo ===== ' + arm.upper() + ' START %DATE% %TIME% ===== > "%LOG%"']

    # phase A: WS
    L += ["", rem("---- PHASE A: WS, 1 epoch ----"),
          'if exist "%DIR%\\ws_%STAMP%.log" del /q "%DIR%\\ws_%STAMP%.log"',
          '.venv\\Scripts\\python.exe -u -m rwkv.train_rwkv --config scratchpad/features_ab/%s/ws.toml > "%%DIR%%\\ws_%%STAMP%%.log" 2>&1' % arm,
          "if not %ERRORLEVEL%==0 (",
          '  echo %TAG% WS_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_21 %DATE% %TIME% >> "%LOG%"', "  exit /b 21", ")",
          rem("Gate on the artifact AT THE EXPECTED STEP: exit 0 is not evidence, and an"),
          rem("interrupted run leaves a checkpoint at the step it died on."),
          'if not exist "%DIR%\\' + arm + '_ws_%STEPS%.pth" (',
          '  echo %TAG% WS_SHORT %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_27 %DATE% %TIME% >> "%LOG%"', "  exit /b 27", ")",
          rem("The arm must have used the input width it claims. This is the one check that"),
          rem("catches RWKV_ID_FEATURES failing to reach the workers."),
          'findstr /C:"Trainable parameters: %s" "%%DIR%%\\ws_%%STAMP%%.log" >nul' % cfg["params"],
          "if not %ERRORLEVEL%==0 (",
          '  echo %TAG% WRONG_PARAM_COUNT %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_33 %DATE% %TIME% >> "%LOG%"', "  exit /b 33", ")",
          'echo %TAG% WS_OK %TIME% >> "%LOG%"']

    # phase B: decay
    L += ["", rem("---- PHASE B: decay, ratio 1.0 ----"),
          '.venv\\Scripts\\python.exe scratchpad/write_decay_setup.py scratchpad/features_ab/%s %s_ws %s_d %%DIR%%\\decay.toml %s 1 5000 1.0 1e-3 65536 > "%%DIR%%\\dsetup_%%STAMP%%.log" 2>&1' % (arm, arm, arm, cfg["train_db"]),
          "if not %ERRORLEVEL%==0 (",
          '  echo %TAG% DSETUP_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_22 %DATE% %TIME% >> "%LOG%"', "  exit /b 22", ")",
          'findstr /C:"' + arm + '_ws_%STEPS%" "%DIR%\\dsetup_%STAMP%.log" >nul',
          "if not %ERRORLEVEL%==0 (",
          '  echo %TAG% WRONGCKPT %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_32 %DATE% %TIME% >> "%LOG%"', "  exit /b 32", ")",
          '.venv\\Scripts\\python.exe -u -m rwkv.train_rwkv --config %DIR%\\decay.toml > "%DIR%\\decay_%STAMP%.log" 2>&1',
          "if not %ERRORLEVEL%==0 (",
          '  echo %TAG% DECAY_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_23 %DATE% %TIME% >> "%LOG%"', "  exit /b 23", ")",
          rem("KD must be ABSENT here -- the opposite of every recent runner's guard."),
          'findstr /C:"[kd-mix] KD ON" "%DIR%\\decay_%STAMP%.log" >nul',
          "if %ERRORLEVEL%==0 (",
          '  echo %TAG% KD_LEAKED_IN %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_43 %DATE% %TIME% >> "%LOG%"', "  exit /b 43", ")",
          'if not exist "%DIR%\\' + arm + '_d_%STEPS%.pth" (',
          '  echo %TAG% DECAY_SHORT %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_28 %DATE% %TIME% >> "%LOG%"', "  exit /b 28", ")",
          'echo %TAG% DECAY_OK %TIME% >> "%LOG%"']

    # phase C: eval
    L += ["", rem("---- PHASE C: rectified VAL-half eval, users 5001-7500 ----"),
          "set RWKV_EVAL_PAVA=1",
          '.venv\\Scripts\\python.exe scratchpad/write_eval_toml.py scratchpad/features_ab/%s %s_d %%DIR%%\\eval.toml RWKV-%%TAG%% RWKV-P-%%TAG%% 5001 7500 > "%%DIR%%\\etoml_%%STAMP%%.log" 2>&1' % (arm, arm),
          "if not %ERRORLEVEL%==0 (",
          '  echo %TAG% ETOML_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_24 %DATE% %TIME% >> "%LOG%"', "  exit /b 24", ")",
          rem("The eval toml must point at THIS arm's db, or the arm silently scores on the"),
          rem("other arm's feature width. This is trap #2 made into a guard."),
          'findstr /C:"%s" "%%DIR%%\\eval.toml" >nul' % cfg["eval_db"].replace("/", "/"),
          "if not %ERRORLEVEL%==0 (",
          '  echo %TAG% EVAL_DB_MISMATCH %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_34 %DATE% %TIME% >> "%LOG%"', "  exit /b 34", ")",
          'if exist "result\\RWKV-%TAG%.jsonl" del /q "result\\RWKV-%TAG%.jsonl"',
          'if exist "result\\RWKV-P-%TAG%.jsonl" del /q "result\\RWKV-P-%TAG%.jsonl"',
          'del /q scratchpad\\eval_shards\\shard_*.log 2>nul',
          '.venv\\Scripts\\python.exe -u optimization/eval_sharded.py --config %DIR%\\eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\\eval_%STAMP%.log" 2>&1',
          "if not %ERRORLEVEL%==0 (",
          '  echo %TAG% EVAL_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"',
          '  echo DONE_EXIT_25 %DATE% %TIME% >> "%LOG%"', "  exit /b 25", ")",
          'echo %TAG% EVAL_OK %TIME% >> "%LOG%"', "",
          rem("Terminal marker BEFORE endlocal: endlocal restores the pre-setlocal environment,"),
          rem("so %LOG% would expand to empty and the marker would go to \"\"."),
          'echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"',
          "endlocal & exit /b 0"]
    return L


def validate(text):
    problems, lines = [], text.replace("\r\n", "\n").split("\n")
    if not re.search(r"^cd /d ", text, re.M):
        problems.append("no cd /d")
    setpos, usepos = {}, {}
    for n, l in enumerate(lines):
        m = re.match(r"\s*set\s+([A-Za-z_][A-Za-z0-9_]*)=", l)
        if m and m.group(1).upper() not in setpos:
            setpos[m.group(1).upper()] = n
        if l.strip().upper().startswith("REM"):
            continue
        for v in re.findall(r"%([A-Za-z_][A-Za-z0-9_]*)%", l):
            usepos.setdefault(v.upper(), n)
    for v, un in usepos.items():
        if v in {"DATE", "TIME", "ERRORLEVEL", "RANDOM", "CD"}:
            continue
        if v not in setpos:
            problems.append("%%%s%% used at %d, never set" % (v, un + 1))
        elif setpos[v] > un:
            problems.append("%%%s%% used at %d before set at %d" % (v, un + 1, setpos[v] + 1))
    el = [n for n, l in enumerate(lines) if l.strip().lower() == "endlocal"]
    de = [n for n, l in enumerate(lines) if l.strip().startswith("echo DONE_EXIT_")]
    if el and de and min(el) < max(de):
        problems.append("endlocal precedes a DONE_EXIT_ echo")
    if text.count("DONE_EXIT_0") != 1:
        problems.append("expected exactly one DONE_EXIT_0")
    for l in lines:
        if l.strip().upper().startswith("REM"):
            bad = [c for c in "<>&|^" if c in l]
            if bad:
                problems.append("redirection char %s in REM: %s" % (bad, l[:50]))
    return problems


if __name__ == "__main__":
    # Param counts differ ONLY by the input FC: 92 -> 114 dims x the 320-wide FC = +7,040.
    # 564,612 was the 112-dim figure; generation 2 adds scaled_sibling_gap and
    # card_predates_first_review, i.e. 2 more dims = +640. Baked into a runner guard so an arm
    # that silently ran at the wrong width cannot be mistaken for a result.
    ARMS["featA"]["params"] = "558212"
    ARMS["featB"]["params"] = "565252"

    # ⚠ ARM FILTER, added 2026-08-20. This script rewrites BOTH runners, and featA's was RUNNING
    # when generation 2 was prepared. cmd.exe re-reads a batch file from a saved BYTE OFFSET
    # every time a command returns, so rewriting a live runner makes it resume mid-garbage --
    # the documented trap that cost iters 43 and 46. Pass an arm name to regenerate only that
    # arm; with no argument it still writes both, which is correct only when neither is running.
    only = sys.argv[1:] or None
    if only:
        missing = [a for a in only if a not in ARMS]
        assert not missing, "unknown arm(s): %s" % missing
        for a in list(ARMS):
            if a not in only:
                del ARMS[a]
        print("ARM FILTER: writing only %s" % ", ".join(only))

    for arm, cfg in ARMS.items():
        d = os.path.join("scratchpad", "features_ab", arm)
        os.makedirs(d, exist_ok=True)
        io.open(os.path.join(d, "ws.toml"), "w", encoding="ascii", newline="\n").write(
            WS_TOML.format(arm=arm, **{k: v for k, v in cfg.items() if k != "params"}))
        text = "\n".join(build(arm, cfg)).replace("\n", "\r\n")
        probs = validate(text)
        if probs:
            print("REFUSING to write %s:" % arm)
            for p in probs:
                print("   ! " + p)
            raise SystemExit(1)
        out = os.path.join(d, "run_%s.cmd" % arm)
        io.open(out, "w", encoding="ascii", newline="").write(text)
        print("wrote %s (%d bytes), params guard %s, id_features=%r"
              % (out, len(text), cfg["params"], cfg["idf"]))
