@echo off
REM =========================================================================================
REM featA2 PHASE C ONLY -- the rectified VAL-half eval. Andrew paused the loop after decay on
REM 2026-08-21 to free the PC for the FSRS-7 benchmark, so featA2 has its WS and decay
REM checkpoints but never generated eval.toml.
REM
REM Re-launching run_featA2.cmd would redo 8 h of training. This is that runner's PHASE C,
REM sliced out byte-for-byte so the env is identical -- the same pattern as
REM scratchpad/qat_tax/run_i45kd_evalresume.cmd.
REM
REM Guards, all inherited from the full runner plus one added for the slice:
REM   * the decay checkpoint must EXIST before anything runs (a slice cannot assume the phase
REM     it depends on actually completed);
REM   * eval.toml must name test_db_5k_fix, or the arm silently scores on the wrong feature
REM     width;
REM   * no training or decay call may appear in this file.
REM
REM Do NOT edit this file while it runs. No angle brackets or arrows in REM lines.
REM =========================================================================================
setlocal
cd /d C:\Users\Andrew\rwkv-anki-autoresearch

set TAG=featA2
set DIR=C:\Users\Andrew\rwkv-anki-autoresearch\scratchpad\features_ab\featA2
set LOG=%DIR%\featA2_evalonly.log
set STAMP=%RANDOM%%RANDOM%
set PYTHONUNBUFFERED=1
set PYTHONPATH=C:\Users\Andrew\rwkv-anki-autoresearch
set OMP_NUM_THREADS=7

set RWKV_ARCH_MODULE=scratchpad/track2_a18/architecture_d80_lora4_cnd.py
set RWKV_INTERLEAVE=1
set RWKV_GRU_HEAD=3
set RWKV_PAVA_LAMBDA=0.2
set RWKV_NO_AHEAD_RESIDUAL=1
set RWKV_STRIP_L0_VLORA=1
set RWKV_ZERO_FEATURES=22
set RWKV_ID_FEATURES=
set RWKV_STRIP_CMIX=user_id:0,user_id:1,user_id:2,preset_id:0,preset_id:1,preset_id:2,deck_id:1,deck_id:2,card_id:1
set RWKV_STATE_CLAMP_TAU=300
set RWKV_STATE_CLAMP_WINDOW=32768
set RWKV_PROBE_DENSITY=0.08
set RWKV_PROBE_DUR=0.0
set RWKV_DETERMINISTIC=1
set RWKV_AUGMENT_SEED=4321
set RWKV_EMPTY_CACHE_EVERY=1
set RWKV_EMPTY_CACHE_WINDOW=0
set RWKV_VAL_DB=F:/rwkv_lmdb/test_db_5k_fix
set RWKV_EVAL_DB=F:/rwkv_lmdb/test_db_5k_fix
set RWKV_LABEL_FILTER_DB=label_filter_db

echo ===== FEATA2 EVAL-ONLY START %DATE% %TIME% ===== > "%LOG%"

REM ---- the phase this slice DEPENDS on must have produced its artifact ----
if not exist "%DIR%\featA2_d_10935.pth" (
  echo %TAG% DECAY_CKPT_MISSING %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_31 %DATE% %TIME% >> "%LOG%"
  exit /b 31
)
echo %TAG% DECAY_CKPT_PRESENT %TIME% >> "%LOG%"

set RWKV_EVAL_PAVA=1
.venv\Scripts\python.exe scratchpad/write_eval_toml.py scratchpad/features_ab/featA2 featA2_d %DIR%\eval.toml RWKV-%TAG% RWKV-P-%TAG% 5001 7500 > "%DIR%\etoml_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% ETOML_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_24 %DATE% %TIME% >> "%LOG%"
  exit /b 24
)
findstr /C:"F:/rwkv_lmdb/test_db_5k_fix" "%DIR%\eval.toml" >nul
if not %ERRORLEVEL%==0 (
  echo %TAG% EVAL_DB_MISMATCH %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_34 %DATE% %TIME% >> "%LOG%"
  exit /b 34
)
if exist "result\RWKV-%TAG%.jsonl" del /q "result\RWKV-%TAG%.jsonl"
if exist "result\RWKV-P-%TAG%.jsonl" del /q "result\RWKV-P-%TAG%.jsonl"
del /q scratchpad\eval_shards\shard_*.log 2>nul
.venv\Scripts\python.exe -u optimization/eval_sharded.py --config %DIR%\eval.toml --shards 1 --solo-threshold 0 --fetch-per-shard 2 --threads-per-shard 7 > "%DIR%\eval_%STAMP%.log" 2>&1
if not %ERRORLEVEL%==0 (
  echo %TAG% EVAL_FAILED_%ERRORLEVEL% %DATE% %TIME% >> "%LOG%"
  echo DONE_EXIT_25 %DATE% %TIME% >> "%LOG%"
  exit /b 25
)
echo %TAG% EVAL_OK %TIME% >> "%LOG%"

REM Terminal marker BEFORE endlocal: endlocal restores the pre-setlocal environment, so %LOG%
REM would expand to empty and the marker would go to "".
echo DONE_EXIT_0 %DATE% %TIME% >> "%LOG%"
endlocal & exit /b 0
